PERKS = [
    'PERK_AWARENESS',
    'PERK_BONUS_HTH_ATTACKS',
    'PERK_BONUS_HTH_DAMAGE',
    'PERK_BONUS_MOVE',
    'PERK_BONUS_RANGED_DAMAGE',
    'PERK_BONUS_RATE_OF_FIRE',
    'PERK_EARLIER_SEQUENCE',
    'PERK_FASTER_HEALING',
    'PERK_MORE_CRITICALS',
    'PERK_NIGHT_VISION',
    'PERK_PRESENCE',
    'PERK_RAD_RESISTANCE',
    'PERK_TOUGHNESS',
    'PERK_STRONG_BACK',
    'PERK_SHARPSHOOTER',
    'PERK_SILENT_RUNNING',
    'PERK_SURVIVALIST',
    'PERK_MASTER_TRADER',
    'PERK_EDUCATED',
    'PERK_HEALER',
    'PERK_FORTUNE_FINDER',
    'PERK_BETTER_CRITICALS',
    'PERK_EMPATHY',
    'PERK_SLAYER',
    'PERK_SNIPER',
    'PERK_SILENT_DEATH',
    'PERK_ACTION_BOY',
    'PERK_MENTAL_BLOCK',
    'PERK_LIFEGIVER',
    'PERK_DODGER',
    'PERK_SNAKEATER',
    'PERK_MR_FIXIT',
    'PERK_MEDIC',
    'PERK_MASTER_THIEF',
    'PERK_SPEAKER',
    'PERK_HEAVE_HO',
    'PERK_FRIENDLY_FOE',
    'PERK_PICKPOCKET',
    'PERK_GHOST',
    'PERK_CULT_OF_PERSONALITY',
    'PERK_SCROUNGER',
    'PERK_EXPLORER',
    'PERK_FLOWER_CHILD',
    'PERK_PATHFINDER',
    'PERK_ANIMAL_FRIEND',
    'PERK_SCOUT',
    'PERK_MYSTERIOUS_STRANGER',
    'PERK_RANGER',
    'PERK_QUICK_POCKETS',
    'PERK_SMOOTH_TALKER',
    'PERK_SWIFT_LEARNER',
    'PERK_TAG',
    'PERK_MUTATE',
    'PERK_NUKA_COLA_ADDICTION',
    'PERK_BUFFOUT_ADDICTION',
    'PERK_MENTATS_ADDICTION',
    'PERK_PSYCHO_ADDICTION',
    'PERK_RADAWAY_ADDICTION',
    'PERK_WEAPON_LONG_RANGE',
    'PERK_WEAPON_ACCURATE',
    'PERK_WEAPON_PENETRATE',
    'PERK_WEAPON_KNOCKBACK',
    'PERK_POWERED_ARMOR',
    'PERK_COMBAT_ARMOR',
    'PERK_WEAPON_SCOPE_RANGE',
    'PERK_WEAPON_FAST_RELOAD',
    'PERK_WEAPON_NIGHT_SIGHT',
    'PERK_WEAPON_FLAMEBOY',
    'PERK_ARMOR_ADVANCED_I',
    'PERK_ARMOR_ADVANCED_II',
    'PERK_JET_ADDICTION',
    'PERK_TRAGIC_ADDICTION',
    'PERK_ARMOR_CHARISMA',
    'PERK_GECKO_SKINNING',
    'PERK_DERMAL_IMPACT_ARMOR',
    'PERK_DERMAL_IMPACT_ASSAULT_ENHANCEMENT',
    'PERK_PHOENIX_ARMOR_IMPLANTS',
    'PERK_PHOENIX_ASSAULT_ENHANCEMENT',
    'PERK_VAULT_CITY_INOCULATIONS',
    'PERK_ADRENALINE_RUSH',
    'PERK_CAUTIOUS_NATURE',
    'PERK_COMPREHENSION',
    'PERK_DEMOLITION_EXPERT',
    'PERK_GAMBLER',
    'PERK_GAIN_STRENGTH',
    'PERK_GAIN_PERCEPTION',
    'PERK_GAIN_ENDURANCE',
    'PERK_GAIN_CHARISMA',
    'PERK_GAIN_INTELLIGENCE',
    'PERK_GAIN_AGILITY',
    'PERK_GAIN_LUCK',
    'PERK_HARMLESS',
    'PERK_HERE_AND_NOW',
    'PERK_HTH_EVADE',
    'PERK_KAMA_SUTRA_MASTER',
    'PERK_KARMA_BEACON',
    'PERK_LIGHT_STEP',
    'PERK_LIVING_ANATOMY',
    'PERK_MAGNETIC_PERSONALITY',
    'PERK_NEGOTIATOR',
    'PERK_PACK_RAT',
    'PERK_PYROMANIAC',
    'PERK_QUICK_RECOVERY',
    'PERK_SALESMAN',
    'PERK_STONEWALL',
    'PERK_THIEF',
    'PERK_WEAPON_HANDLING',
    'PERK_VAULT_CITY_TRAINING',
    'PERK_ALCOHOL_RAISED_HIT_POINTS',
    'PERK_ALCOHOL_RAISED_HIT_POINTS_II',
    'PERK_ALCOHOL_LOWERED_HIT_POINTS',
    'PERK_ALCOHOL_LOWERED_HIT_POINTS_II',
    'PERK_AUTODOC_RAISED_HIT_POINTS',
    'PERK_AUTODOC_RAISED_HIT_POINTS_II',
    'PERK_AUTODOC_LOWERED_HIT_POINTS',
    'PERK_AUTODOC_LOWERED_HIT_POINTS_II',
    'PERK_EXPERT_EXCREMENT_EXPEDITOR',
    'PERK_WEAPON_ENHANCED_KNOCKOUT',
    'PERK_JINXED',
    'NONE'
]

ITEM_TYPE_ARMOR = 0
ITEM_TYPE_CONTAINER = 1
ITEM_TYPE_DRUG = 2
ITEM_TYPE_WEAPON = 3
ITEM_TYPE_AMMO = 4
ITEM_TYPE_MISC = 5
ITEM_TYPE_KEY = 6

ITEM_TYPES = [
    'ITEM_TYPE_ARMOR',
    'ITEM_TYPE_CONTAINER',
    'ITEM_TYPE_DRUG',
    'ITEM_TYPE_WEAPON',
    'ITEM_TYPE_AMMO',
    'ITEM_TYPE_MISC',
    'ITEM_TYPE_KEY'
]

DAMAGE_TYPES = [
    'DAMAGE_TYPE_NORMAL',
    'DAMAGE_TYPE_LASER',
    'DAMAGE_TYPE_FIRE',
    'DAMAGE_TYPE_PLASMA',
    'DAMAGE_TYPE_ELECTRICAL',
    'DAMAGE_TYPE_EMP',
    'DAMAGE_TYPE_EXPLOSION'
]

DAMAGE_TYPE_KEYS = [
    'normal',
    'laser',
    'fire',
    'plasma',
    'electrical',
    'emp',
    'explosion'
]

STATS = [
    'STAT_STRENGTH',
    'STAT_PERCEPTION',
    'STAT_ENDURANCE',
    'STAT_CHARISMA',
    'STAT_INTELLIGENCE',
    'STAT_AGILITY',
    'STAT_LUCK',
    'STAT_MAXIMUM_HIT_POINTS',
    'STAT_MAXIMUM_ACTION_POINTS',
    'STAT_ARMOR_CLASS',
    'STAT_UNARMED_DAMAGE',
    'STAT_MELEE_DAMAGE',
    'STAT_CARRY_WEIGHT',
    'STAT_SEQUENCE',
    'STAT_HEALING_RATE',
    'STAT_CRITICAL_CHANCE',
    'STAT_BETTER_CRITICALS',
    'STAT_DAMAGE_THRESHOLD',
    'STAT_DAMAGE_THRESHOLD_LASER',
    'STAT_DAMAGE_THRESHOLD_FIRE',
    'STAT_DAMAGE_THRESHOLD_PLASMA',
    'STAT_DAMAGE_THRESHOLD_ELECTRICAL',
    'STAT_DAMAGE_THRESHOLD_EMP',
    'STAT_DAMAGE_THRESHOLD_EXPLOSION',
    'STAT_DAMAGE_RESISTANCE',
    'STAT_DAMAGE_RESISTANCE_LASER',
    'STAT_DAMAGE_RESISTANCE_FIRE',
    'STAT_DAMAGE_RESISTANCE_PLASMA',
    'STAT_DAMAGE_RESISTANCE_ELECTRICAL',
    'STAT_DAMAGE_RESISTANCE_EMP',
    'STAT_DAMAGE_RESISTANCE_EXPLOSION',
    'STAT_RADIATION_RESISTANCE',
    'STAT_POISON_RESISTANCE',
    'STAT_AGE',
    'STAT_GENDER',
    'STAT_CURRENT_HIT_POINTS',
    'STAT_CURRENT_POISON_LEVEL',
    'STAT_CURRENT_RADIATION_LEVEL'
]

def parse_msg_file(file_path: str) -> dict:
    result = {}
    with open(file_path, 'r') as f:
        lines = f.readlines()
        for line in lines:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.split('}{')
            message_id = int(parts[0].strip('{'))
            text = parts[2].strip('}')
            result[message_id] = text
    return result

def read_calibers(protoMsg) -> list:
    i = 300
    result = []
    while i in protoMsg and protoMsg[i] != "":
        result.append(protoMsg[i])
        i += 1
    return result