/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

//#define EXTRA_HEADER                "../headers/newreno.h"

#define WATCHER_OBJ                 Shack_Shelf_Watcher
//#define ENTER_LOCK_CONDITION        (map_first_run)
//#define LOCKPICK_SKILL_PENALTY      HARD_LOCK_PENALTY
#define DO_CHECK_TAMPER_CONDITION   ( global_var( GVAR_VAULT_CITIZEN ) != CITIZEN_CAPTAIN_GUARD )

#include "../generic/zilocker.ssl"
