/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

//#define EXTRA_HEADER                "../headers/newreno.h"

#define WATCHER_OBJ                 Lynette_Ptr
//#define ENTER_LOCK_CONDITION        (map_first_run)
//#define LOCKPICK_SKILL_PENALTY      EASY_LOCK_PENALTY
//#define DO_CHECK_TAMPER_CONDITION   (dude_is_made_man == false)

#include "../generic/zilocker.ssl"
