variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable tmp_gen_rep;
variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant := 2;
variable Karma_Perception;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;

procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure Node998;
procedure Node999;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node033;
procedure Node034;
procedure Node035;
procedure Node036;
procedure Node037;
procedure Node038;
procedure Node039;
procedure Node040;
procedure Node041;
procedure Node042;
procedure Node043;
procedure Node044;
procedure Node045;
procedure Node046;
procedure Node047;
procedure Node048;
procedure Node049;
procedure Node050;
procedure Node051;
procedure Node052;
procedure Node053;
procedure Node054;
procedure Node002a;
procedure Node003a;
procedure Node004a;
procedure Node005a;
procedure Node007a;
procedure Node010a;
procedure Node010b;
procedure Node012a;
procedure Node034a;
procedure Node035a;
procedure Node037a;
procedure Node050a;
procedure Node051a;
procedure Node052a;
procedure Node053a;

import variable Doc_Johnson_Ptr;

variable Only_Once;
variable From_50;
variable From_51;
variable From_52;
variable From_53;

#define _LEARN_CRAFT_DRJOHNSON
#include "learn_craft.h"

procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777718) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777718)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777719) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777719)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777720) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777720)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
end

procedure critter_p_proc
begin
    if ((global_var(492) == 1) and obj_can_see_obj(self_obj, dude_obj)) then begin
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
    if ((local_var(5) == 2) and obj_can_see_obj(self_obj, dude_obj)) then begin
        set_local_var(5, 1);
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
    end
end

procedure talk_p_proc
begin
    Evil_Critter := 0;
    Slavery_Tolerant := 2;
    Karma_Perception := 10;
    set_global_var(37, 0);
    set_global_var(38, 0);
    set_global_var(39, 0);
    set_global_var(40, 0);
    set_global_var(41, 0);
    set_global_var(42, 0);
    set_global_var(43, 0);
    set_global_var(44, 0);
    set_global_var(45, 0);
    tmp_gen_rep := global_var(0);
    if (has_trait(0, dude_obj, 95)) then begin
        tmp_gen_rep := global_var(0) * 2;
    end
    if (tmp_gen_rep >= 1000) then begin
        set_global_var(37, 1);
    end
    else begin
        if (tmp_gen_rep >= 750) then begin
            set_global_var(38, 1);
        end
        else begin
            if (tmp_gen_rep >= 500) then begin
                set_global_var(39, 1);
            end
            else begin
                if (tmp_gen_rep >= 250) then begin
                    set_global_var(40, 1);
                end
                else begin
                    if (tmp_gen_rep > -250) then begin
                        set_global_var(41, 1);
                    end
                    else begin
                        if (tmp_gen_rep > -500) then begin
                            set_global_var(42, 1);
                        end
                        else begin
                            if (tmp_gen_rep > -750) then begin
                                set_global_var(43, 1);
                            end
                            else begin
                                if (tmp_gen_rep > -1000) then begin
                                    set_global_var(44, 1);
                                end
                                else begin
                                    set_global_var(45, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    if (local_var(2) == 0) then begin
        set_local_var(2, 1);
        set_local_var(3, (get_critter_stat(dude_obj, 3) - get_critter_stat(self_obj, 3)) * 5);
        debug_msg("Base Reaction == " + local_var(3));
    end
    Static_Reaction := 0;
    set_local_var(0, 0);
    debug_msg("Start Reaction == " + local_var(0));
    if (reaction_bonus_karma >= 0) then begin
        reaction_bonus_karma := reaction_bonus_karma / 1000;
    end
    else begin
        reaction_bonus_karma := -1 * (-1 * reaction_bonus_karma / 1000);
    end
    if (global_var(56) >= 0) then begin
        reaction_bonus_town_rep := global_var(56) / 2;
    end
    else begin
        reaction_bonus_town_rep := -1 * (-1 * global_var(56) / 2);
    end
    if (has_trait(2, dude_obj, 13)) then begin
        if (get_critter_stat(dude_obj, 34) == get_critter_stat(self_obj, 34)) then begin
            Static_Reaction := Static_Reaction + -20;
        end
        else begin
            Static_Reaction := Static_Reaction + 20;
        end
        debug_msg("Sex Appeal Bonus == " + Static_Reaction);
    end
    else begin
        debug_msg("Sex Appeal Bonus == 0");
    end
    if (Evil_Critter == 1) then begin
        if (reaction_bonus_karma >= 0) then begin
            Static_Reaction := Static_Reaction - reaction_bonus_karma;
        end
        else begin
            Static_Reaction := Static_Reaction + reaction_bonus_karma;
        end
        debug_msg("Karma Reaction Bonus == " + Static_Reaction);
        if (reaction_bonus_town_rep >= 0) then begin
            Static_Reaction := Static_Reaction - reaction_bonus_town_rep;
        end
        else begin
            Static_Reaction := Static_Reaction + reaction_bonus_town_rep;
        end
        debug_msg("Town Rep Bonus == " + Static_Reaction);
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        tmp_gen_rep := global_var(0);
        if (has_trait(0, dude_obj, 95)) then begin
            tmp_gen_rep := global_var(0) * 2;
        end
        if (tmp_gen_rep >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (tmp_gen_rep >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (tmp_gen_rep >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (tmp_gen_rep >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (tmp_gen_rep > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (tmp_gen_rep > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (tmp_gen_rep > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (tmp_gen_rep > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (global_var(37) == 1) then begin
            Static_Reaction := Static_Reaction - 20;
        end
        else begin
            if (global_var(38) == 1) then begin
                Static_Reaction := Static_Reaction - 15;
            end
            else begin
                if (global_var(39) == 1) then begin
                    Static_Reaction := Static_Reaction - 10;
                end
                else begin
                    if (global_var(40) == 1) then begin
                        Static_Reaction := Static_Reaction - 5;
                    end
                    else begin
                        if (global_var(41) == 1) then begin
                            Static_Reaction := Static_Reaction - 0;
                        end
                        else begin
                            if (global_var(42) == 1) then begin
                                Static_Reaction := Static_Reaction + -5;
                            end
                            else begin
                                if (global_var(43) == 1) then begin
                                    Static_Reaction := Static_Reaction + -10;
                                end
                                else begin
                                    if (global_var(44) == 1) then begin
                                        Static_Reaction := Static_Reaction + -15;
                                    end
                                    else begin
                                        Static_Reaction := Static_Reaction + -20;
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        debug_msg("Bad Person Reaction Bonus == " + Static_Reaction);
    end
    else begin
        Static_Reaction := Static_Reaction + reaction_bonus_karma;
        debug_msg("Karma Reaction Bonus == " + Static_Reaction);
        Static_Reaction := Static_Reaction + reaction_bonus_town_rep;
        debug_msg("Town Rep Bonus == " + Static_Reaction);
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        tmp_gen_rep := global_var(0);
        if (has_trait(0, dude_obj, 95)) then begin
            tmp_gen_rep := global_var(0) * 2;
        end
        if (tmp_gen_rep >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (tmp_gen_rep >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (tmp_gen_rep >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (tmp_gen_rep >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (tmp_gen_rep > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (tmp_gen_rep > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (tmp_gen_rep > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (tmp_gen_rep > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (global_var(37) == 1) then begin
            Static_Reaction := Static_Reaction + 20;
        end
        else begin
            if (global_var(38) == 1) then begin
                Static_Reaction := Static_Reaction + 15;
            end
            else begin
                if (global_var(39) == 1) then begin
                    Static_Reaction := Static_Reaction + 10;
                end
                else begin
                    if (global_var(40) == 1) then begin
                        Static_Reaction := Static_Reaction + 5;
                    end
                    else begin
                        if (global_var(41) == 1) then begin
                            Static_Reaction := Static_Reaction + 0;
                        end
                        else begin
                            if (global_var(42) == 1) then begin
                                Static_Reaction := Static_Reaction + -5;
                            end
                            else begin
                                if (global_var(43) == 1) then begin
                                    Static_Reaction := Static_Reaction + -10;
                                end
                                else begin
                                    if (global_var(44) == 1) then begin
                                        Static_Reaction := Static_Reaction + -15;
                                    end
                                    else begin
                                        Static_Reaction := Static_Reaction + -20;
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        debug_msg("Good Person Reaction Bonus == " + Static_Reaction);
    end
    if (Slavery_Tolerant == 0) then begin
        if (global_var(11) == 1) then begin
            Static_Reaction := Static_Reaction + (2 * -25);
        end
    end
    else begin
        if (Slavery_Tolerant == 1) then begin
            if (global_var(11) == 1) then begin
                Static_Reaction := Static_Reaction + -25;
            end
        end
        else begin
            if (Slavery_Tolerant == 3) then begin
                if (global_var(11) == 1) then begin
                    Static_Reaction := Static_Reaction - -25;
                end
            end
        end
    end
    debug_msg("Slaver + Aligned Reaction == " + Static_Reaction);
    Static_Reaction := Static_Reaction + (10 * has_trait(0, dude_obj, 10));
    debug_msg("Presence Reaction == " + Static_Reaction);
    if (global_var(1) >= 2) then begin
        Static_Reaction := Static_Reaction + -30;
    end
    debug_msg("Childkiller Reaction == " + Static_Reaction);
    if (has_trait(0, dude_obj, 39)) then begin
        if (Evil_Critter == 1) then begin
            if (Static_Reaction > 0) then begin
                Static_Reaction := Static_Reaction * -1;
            end
        end
        else begin
            if (Static_Reaction < 0) then begin
                Static_Reaction := Static_Reaction * -1;
            end
        end
    end
    set_local_var(0, local_var(3) + Static_Reaction);
    debug_msg("Initial Reaction == " + local_var(0));
    if (get_critter_stat(dude_obj, 4) < 4) then begin
        call Node001;
    end
    else begin
        if (get_poison(dude_obj) or (get_critter_stat(dude_obj, 35) < get_critter_stat(dude_obj, 7)) or get_poison(dude_obj) or get_critter_stat(dude_obj, 37)) then begin
            start_gdialog(808, self_obj, 4, -1, -1);
            gsay_start;
            call Node002;
            gsay_end;
            end_dialogue;
        end
        else begin
            How_Many_Party_Members_Are_Injured := 0;
            if (party_member_obj(16777278) != 0) then begin
                if (get_critter_stat(party_member_obj(16777278), 35) < get_critter_stat(party_member_obj(16777278), 7)) then begin
                    How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
                end
            end
            if (party_member_obj(16777376) != 0) then begin
                if (get_critter_stat(party_member_obj(16777376), 35) < get_critter_stat(party_member_obj(16777376), 7)) then begin
                    How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
                end
            end
            if (party_member_obj(16777377) != 0) then begin
                if (get_critter_stat(party_member_obj(16777377), 35) < get_critter_stat(party_member_obj(16777377), 7)) then begin
                    How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
                end
            end
            if (party_member_obj(16777305) != 0) then begin
                if (get_critter_stat(party_member_obj(16777305), 35) < get_critter_stat(party_member_obj(16777305), 7)) then begin
                    How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
                end
            end
            if (party_member_obj(16777313) != 0) then begin
                if (get_critter_stat(party_member_obj(16777313), 35) < get_critter_stat(party_member_obj(16777313), 7)) then begin
                    How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
                end
            end
            if (party_member_obj(16777323) != 0) then begin
                if (get_critter_stat(party_member_obj(16777323), 35) < get_critter_stat(party_member_obj(16777323), 7)) then begin
                    How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
                end
            end
            if (party_member_obj(16777352) != 0) then begin
                if (get_critter_stat(party_member_obj(16777352), 35) < get_critter_stat(party_member_obj(16777352), 7)) then begin
                    How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
                end
            end
            if (party_member_obj(16777378) != 0) then begin
                if (get_critter_stat(party_member_obj(16777378), 35) < get_critter_stat(party_member_obj(16777378), 7)) then begin
                    How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
                end
            end
            if (party_member_obj(16777368) != 0) then begin
                if (get_critter_stat(party_member_obj(16777368), 35) < get_critter_stat(party_member_obj(16777368), 7)) then begin
                    How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
                end
            end
            if (party_member_obj(16777379) != 0) then begin
                if (get_critter_stat(party_member_obj(16777379), 35) < get_critter_stat(party_member_obj(16777379), 7)) then begin
                    How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
                end
            end
            if (party_member_obj(16777380) != 0) then begin
                if (get_critter_stat(party_member_obj(16777380), 35) < get_critter_stat(party_member_obj(16777380), 7)) then begin
                    How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
                end
            end
            if (party_member_obj(16777381) != 0) then begin
                if (get_critter_stat(party_member_obj(16777381), 35) < get_critter_stat(party_member_obj(16777381), 7)) then begin
                    How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
                end
            end
            if (party_member_obj(16777295) != 0) then begin
                if (get_critter_stat(party_member_obj(16777295), 35) < get_critter_stat(party_member_obj(16777295), 7)) then begin
                    How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
                end
            end
            if (party_member_obj(16777407) != 0) then begin
                if (get_critter_stat(party_member_obj(16777407), 35) < get_critter_stat(party_member_obj(16777407), 7)) then begin
                    How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
                end
            end
            if (party_member_obj(16777718) != 0) then begin
                if (get_critter_stat(party_member_obj(16777718), 35) < get_critter_stat(party_member_obj(16777718), 7)) then begin
                    How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
                end
            end
            if (party_member_obj(16777719) != 0) then begin
                if (get_critter_stat(party_member_obj(16777719), 35) < get_critter_stat(party_member_obj(16777719), 7)) then begin
                    How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
                end
            end
            if (party_member_obj(16777720) != 0) then begin
                if (get_critter_stat(party_member_obj(16777720), 35) < get_critter_stat(party_member_obj(16777720), 7)) then begin
                    How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
                end
            end
            if (How_Many_Party_Members_Are_Injured > 0) then begin
                start_gdialog(808, self_obj, 4, -1, -1);
                gsay_start;
                call Node002;
                gsay_end;
                end_dialogue;
            end
            else begin
                start_gdialog(808, self_obj, 4, -1, -1);
                gsay_start;
                call Node017;
                gsay_end;
                end_dialogue;
            end
        end
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(5, global_var(5) + 1);
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        if (metarule(51, self_obj) == 2) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(2, 0);
                set_global_var(1, global_var(1) + 1);
                set_global_var(0, global_var(0) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(37, 0);
                set_global_var(38, 0);
                set_global_var(39, 0);
                set_global_var(40, 0);
                set_global_var(41, 0);
                set_global_var(42, 0);
                set_global_var(43, 0);
                set_global_var(44, 0);
                set_global_var(45, 0);
                tmp_gen_rep := global_var(0);
                if (has_trait(0, dude_obj, 95)) then begin
                    tmp_gen_rep := global_var(0) * 2;
                end
                if (tmp_gen_rep >= 1000) then begin
                    set_global_var(37, 1);
                end
                else begin
                    if (tmp_gen_rep >= 750) then begin
                        set_global_var(38, 1);
                    end
                    else begin
                        if (tmp_gen_rep >= 500) then begin
                            set_global_var(39, 1);
                        end
                        else begin
                            if (tmp_gen_rep >= 250) then begin
                                set_global_var(40, 1);
                            end
                            else begin
                                if (tmp_gen_rep > -250) then begin
                                    set_global_var(41, 1);
                                end
                                else begin
                                    if (tmp_gen_rep > -500) then begin
                                        set_global_var(42, 1);
                                    end
                                    else begin
                                        if (tmp_gen_rep > -750) then begin
                                            set_global_var(43, 1);
                                        end
                                        else begin
                                            if (tmp_gen_rep > -1000) then begin
                                                set_global_var(44, 1);
                                            end
                                            else begin
                                                set_global_var(45, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                set_global_var(56, global_var(56) + -8);
                debug_msg("Added " + -8 + " to Town Rep");
            end
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        set_global_var(0, global_var(0) + -10);
        debug_msg("Player gains " + -10 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        tmp_gen_rep := global_var(0);
        if (has_trait(0, dude_obj, 95)) then begin
            tmp_gen_rep := global_var(0) * 2;
        end
        if (tmp_gen_rep >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (tmp_gen_rep >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (tmp_gen_rep >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (tmp_gen_rep >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (tmp_gen_rep > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (tmp_gen_rep > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (tmp_gen_rep > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (tmp_gen_rep > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(56, global_var(56) + -5);
        debug_msg("Added " + -5 + " to Town Rep");
    end
    set_global_var(492, 1);
    set_global_var(437, 1);
    Doc_Johnson_Ptr := 0;
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(7) == 0) then begin
        set_local_var(7, local_var(7) + 1);
        display_msg(message_str(808, 100));
    end
    else begin
        display_msg(message_str(808, 101));
    end
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(808, 102));
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(6, 1);
    end
end

procedure map_enter_p_proc
begin
    Only_Once := 0;
    critter_add_trait(self_obj, 1, 6, 152);
    critter_add_trait(self_obj, 1, 5, 19);
    Doc_Johnson_Ptr := self_obj;
    if ((game_time < 0) and (local_var(16) == 0)) then begin
        set_local_var(15, game_time - 1);
        set_local_var(16, 1);
    end
    if (local_var(15) < game_time) then begin
        debug_msg("Should have restocked");
        restock_amt := random(4, 5);
        if (obj_is_carrying_obj_pid(self_obj, 40) < restock_amt) then begin
            if (100 >= random(1, 100)) then begin
                if (obj_is_carrying_obj_pid(self_obj, 40) < restock_amt) then begin
                    restock_obj := create_object_sid(40, 0, 0, -1);
                    add_mult_objs_to_inven(self_obj, restock_obj, restock_amt - obj_is_carrying_obj_pid(self_obj, 40));
                end
                else begin
                    if (obj_is_carrying_obj_pid(self_obj, 40) > restock_amt) then begin
                        removed_qty := obj_is_carrying_obj_pid(self_obj, 40);
                        if ((obj_is_carrying_obj_pid(self_obj, 40) - restock_amt) < removed_qty) then begin
                            removed_qty := obj_is_carrying_obj_pid(self_obj, 40) - restock_amt;
                        end
                        if (removed_qty > 0) then begin
                            restock_obj := obj_carrying_pid_obj(self_obj, 40);
                            if (obj_type(self_obj) == 1) then begin
                                restock_obj := obj_carrying_pid_obj(self_obj, 40);
                                if (critter_inven_obj(self_obj, 0) == restock_obj) then begin
                                    if (obj_item_subtype(critter_inven_obj(self_obj, 0)) == 0) then begin
                                        restock_obj := critter_inven_obj(self_obj, 0);
                                        debug_msg("armour pid == " + obj_pid(restock_obj));
                                        rm_obj_from_inven(self_obj, restock_obj);
                                        add_obj_to_inven(self_obj, restock_obj);
                                    end
                                end
                                else begin
                                    if ((critter_inven_obj(self_obj, 2) == restock_obj) or (critter_inven_obj(self_obj, 1) == restock_obj)) then begin
                                        metarule(43, self_obj);
                                    end
                                end
                            end
                            restock_amt := rm_mult_objs_from_inven(self_obj, restock_obj, removed_qty);
                            destroy_object(restock_obj);
                        end
                        restock_obj := 0;
                        restock_amt := 0;
                    end
                    else begin
                        restock_obj := 0;
                    end
                end
            end
        end
        else begin
            if (obj_is_carrying_obj_pid(self_obj, 40) < restock_amt) then begin
                restock_obj := create_object_sid(40, 0, 0, -1);
                add_mult_objs_to_inven(self_obj, restock_obj, restock_amt - obj_is_carrying_obj_pid(self_obj, 40));
            end
            else begin
                if (obj_is_carrying_obj_pid(self_obj, 40) > restock_amt) then begin
                    removed_qty := obj_is_carrying_obj_pid(self_obj, 40);
                    if ((obj_is_carrying_obj_pid(self_obj, 40) - restock_amt) < removed_qty) then begin
                        removed_qty := obj_is_carrying_obj_pid(self_obj, 40) - restock_amt;
                    end
                    if (removed_qty > 0) then begin
                        restock_obj := obj_carrying_pid_obj(self_obj, 40);
                        if (obj_type(self_obj) == 1) then begin
                            restock_obj := obj_carrying_pid_obj(self_obj, 40);
                            if (critter_inven_obj(self_obj, 0) == restock_obj) then begin
                                if (obj_item_subtype(critter_inven_obj(self_obj, 0)) == 0) then begin
                                    restock_obj := critter_inven_obj(self_obj, 0);
                                    debug_msg("armour pid == " + obj_pid(restock_obj));
                                    rm_obj_from_inven(self_obj, restock_obj);
                                    add_obj_to_inven(self_obj, restock_obj);
                                end
                            end
                            else begin
                                if ((critter_inven_obj(self_obj, 2) == restock_obj) or (critter_inven_obj(self_obj, 1) == restock_obj)) then begin
                                    metarule(43, self_obj);
                                end
                            end
                        end
                        restock_amt := rm_mult_objs_from_inven(self_obj, restock_obj, removed_qty);
                        destroy_object(restock_obj);
                    end
                    restock_obj := 0;
                    restock_amt := 0;
                end
                else begin
                    restock_obj := 0;
                end
            end
        end
        restock_amt := random(1, 1);
        if (obj_is_carrying_obj_pid(self_obj, 49) < restock_amt) then begin
            if (80 >= random(1, 100)) then begin
                if (obj_is_carrying_obj_pid(self_obj, 49) < restock_amt) then begin
                    restock_obj := create_object_sid(49, 0, 0, -1);
                    add_mult_objs_to_inven(self_obj, restock_obj, restock_amt - obj_is_carrying_obj_pid(self_obj, 49));
                end
                else begin
                    if (obj_is_carrying_obj_pid(self_obj, 49) > restock_amt) then begin
                        removed_qty := obj_is_carrying_obj_pid(self_obj, 49);
                        if ((obj_is_carrying_obj_pid(self_obj, 49) - restock_amt) < removed_qty) then begin
                            removed_qty := obj_is_carrying_obj_pid(self_obj, 49) - restock_amt;
                        end
                        if (removed_qty > 0) then begin
                            restock_obj := obj_carrying_pid_obj(self_obj, 49);
                            if (obj_type(self_obj) == 1) then begin
                                restock_obj := obj_carrying_pid_obj(self_obj, 49);
                                if (critter_inven_obj(self_obj, 0) == restock_obj) then begin
                                    if (obj_item_subtype(critter_inven_obj(self_obj, 0)) == 0) then begin
                                        restock_obj := critter_inven_obj(self_obj, 0);
                                        debug_msg("armour pid == " + obj_pid(restock_obj));
                                        rm_obj_from_inven(self_obj, restock_obj);
                                        add_obj_to_inven(self_obj, restock_obj);
                                    end
                                end
                                else begin
                                    if ((critter_inven_obj(self_obj, 2) == restock_obj) or (critter_inven_obj(self_obj, 1) == restock_obj)) then begin
                                        metarule(43, self_obj);
                                    end
                                end
                            end
                            restock_amt := rm_mult_objs_from_inven(self_obj, restock_obj, removed_qty);
                            destroy_object(restock_obj);
                        end
                        restock_obj := 0;
                        restock_amt := 0;
                    end
                    else begin
                        restock_obj := 0;
                    end
                end
            end
        end
        else begin
            if (obj_is_carrying_obj_pid(self_obj, 49) < restock_amt) then begin
                restock_obj := create_object_sid(49, 0, 0, -1);
                add_mult_objs_to_inven(self_obj, restock_obj, restock_amt - obj_is_carrying_obj_pid(self_obj, 49));
            end
            else begin
                if (obj_is_carrying_obj_pid(self_obj, 49) > restock_amt) then begin
                    removed_qty := obj_is_carrying_obj_pid(self_obj, 49);
                    if ((obj_is_carrying_obj_pid(self_obj, 49) - restock_amt) < removed_qty) then begin
                        removed_qty := obj_is_carrying_obj_pid(self_obj, 49) - restock_amt;
                    end
                    if (removed_qty > 0) then begin
                        restock_obj := obj_carrying_pid_obj(self_obj, 49);
                        if (obj_type(self_obj) == 1) then begin
                            restock_obj := obj_carrying_pid_obj(self_obj, 49);
                            if (critter_inven_obj(self_obj, 0) == restock_obj) then begin
                                if (obj_item_subtype(critter_inven_obj(self_obj, 0)) == 0) then begin
                                    restock_obj := critter_inven_obj(self_obj, 0);
                                    debug_msg("armour pid == " + obj_pid(restock_obj));
                                    rm_obj_from_inven(self_obj, restock_obj);
                                    add_obj_to_inven(self_obj, restock_obj);
                                end
                            end
                            else begin
                                if ((critter_inven_obj(self_obj, 2) == restock_obj) or (critter_inven_obj(self_obj, 1) == restock_obj)) then begin
                                    metarule(43, self_obj);
                                end
                            end
                        end
                        restock_amt := rm_mult_objs_from_inven(self_obj, restock_obj, removed_qty);
                        destroy_object(restock_obj);
                    end
                    restock_obj := 0;
                    restock_amt := 0;
                end
                else begin
                    restock_obj := 0;
                end
            end
        end
        restock_amt := random(123, 200);
        if (obj_is_carrying_obj_pid(self_obj, 41) < restock_amt) then begin
            if (50 >= random(1, 100)) then begin
                if (obj_is_carrying_obj_pid(self_obj, 41) < restock_amt) then begin
                    restock_obj := create_object_sid(41, 0, 0, -1);
                    add_mult_objs_to_inven(self_obj, restock_obj, restock_amt - obj_is_carrying_obj_pid(self_obj, 41));
                end
                else begin
                    if (obj_is_carrying_obj_pid(self_obj, 41) > restock_amt) then begin
                        removed_qty := obj_is_carrying_obj_pid(self_obj, 41);
                        if ((obj_is_carrying_obj_pid(self_obj, 41) - restock_amt) < removed_qty) then begin
                            removed_qty := obj_is_carrying_obj_pid(self_obj, 41) - restock_amt;
                        end
                        if (removed_qty > 0) then begin
                            restock_obj := obj_carrying_pid_obj(self_obj, 41);
                            if (obj_type(self_obj) == 1) then begin
                                restock_obj := obj_carrying_pid_obj(self_obj, 41);
                                if (critter_inven_obj(self_obj, 0) == restock_obj) then begin
                                    if (obj_item_subtype(critter_inven_obj(self_obj, 0)) == 0) then begin
                                        restock_obj := critter_inven_obj(self_obj, 0);
                                        debug_msg("armour pid == " + obj_pid(restock_obj));
                                        rm_obj_from_inven(self_obj, restock_obj);
                                        add_obj_to_inven(self_obj, restock_obj);
                                    end
                                end
                                else begin
                                    if ((critter_inven_obj(self_obj, 2) == restock_obj) or (critter_inven_obj(self_obj, 1) == restock_obj)) then begin
                                        metarule(43, self_obj);
                                    end
                                end
                            end
                            restock_amt := rm_mult_objs_from_inven(self_obj, restock_obj, removed_qty);
                            destroy_object(restock_obj);
                        end
                        restock_obj := 0;
                        restock_amt := 0;
                    end
                    else begin
                        restock_obj := 0;
                    end
                end
            end
        end
        else begin
            if (obj_is_carrying_obj_pid(self_obj, 41) < restock_amt) then begin
                restock_obj := create_object_sid(41, 0, 0, -1);
                add_mult_objs_to_inven(self_obj, restock_obj, restock_amt - obj_is_carrying_obj_pid(self_obj, 41));
            end
            else begin
                if (obj_is_carrying_obj_pid(self_obj, 41) > restock_amt) then begin
                    removed_qty := obj_is_carrying_obj_pid(self_obj, 41);
                    if ((obj_is_carrying_obj_pid(self_obj, 41) - restock_amt) < removed_qty) then begin
                        removed_qty := obj_is_carrying_obj_pid(self_obj, 41) - restock_amt;
                    end
                    if (removed_qty > 0) then begin
                        restock_obj := obj_carrying_pid_obj(self_obj, 41);
                        if (obj_type(self_obj) == 1) then begin
                            restock_obj := obj_carrying_pid_obj(self_obj, 41);
                            if (critter_inven_obj(self_obj, 0) == restock_obj) then begin
                                if (obj_item_subtype(critter_inven_obj(self_obj, 0)) == 0) then begin
                                    restock_obj := critter_inven_obj(self_obj, 0);
                                    debug_msg("armour pid == " + obj_pid(restock_obj));
                                    rm_obj_from_inven(self_obj, restock_obj);
                                    add_obj_to_inven(self_obj, restock_obj);
                                end
                            end
                            else begin
                                if ((critter_inven_obj(self_obj, 2) == restock_obj) or (critter_inven_obj(self_obj, 1) == restock_obj)) then begin
                                    metarule(43, self_obj);
                                end
                            end
                        end
                        restock_amt := rm_mult_objs_from_inven(self_obj, restock_obj, removed_qty);
                        destroy_object(restock_obj);
                    end
                    restock_obj := 0;
                    restock_amt := 0;
                end
                else begin
                    restock_obj := 0;
                end
            end
        end
        set_local_var(15, (random(2, 6) * (24 * (60 * (60 * 10)))) + game_time);
    end
    debug_msg("local_var(LVAR_Gave_Antidote) == " + local_var(14));
    if (((game_time - local_var(14)) > (24 * (60 * (60 * 10)))) and (local_var(14) != 0)) then begin
        set_global_var(333, 4);
        debug_msg("Redding is Cured");
    end
end

procedure Node998
begin
    set_local_var(5, 2);
end

procedure Node999
begin
end

procedure Node001
begin
    float_msg(self_obj, message_str(808, random(103, 110)), 8);
end

procedure Node002
begin
    if (local_var(8) == 0) then begin
        set_local_var(8, local_var(8) + 1);
        How_Many_Party_Members_Are_Injured := 0;
        if (party_member_obj(16777278) != 0) then begin
            if (get_critter_stat(party_member_obj(16777278), 35) < get_critter_stat(party_member_obj(16777278), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777376) != 0) then begin
            if (get_critter_stat(party_member_obj(16777376), 35) < get_critter_stat(party_member_obj(16777376), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777377) != 0) then begin
            if (get_critter_stat(party_member_obj(16777377), 35) < get_critter_stat(party_member_obj(16777377), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777305) != 0) then begin
            if (get_critter_stat(party_member_obj(16777305), 35) < get_critter_stat(party_member_obj(16777305), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777313) != 0) then begin
            if (get_critter_stat(party_member_obj(16777313), 35) < get_critter_stat(party_member_obj(16777313), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777323) != 0) then begin
            if (get_critter_stat(party_member_obj(16777323), 35) < get_critter_stat(party_member_obj(16777323), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777352) != 0) then begin
            if (get_critter_stat(party_member_obj(16777352), 35) < get_critter_stat(party_member_obj(16777352), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777378) != 0) then begin
            if (get_critter_stat(party_member_obj(16777378), 35) < get_critter_stat(party_member_obj(16777378), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777368) != 0) then begin
            if (get_critter_stat(party_member_obj(16777368), 35) < get_critter_stat(party_member_obj(16777368), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777379) != 0) then begin
            if (get_critter_stat(party_member_obj(16777379), 35) < get_critter_stat(party_member_obj(16777379), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777380) != 0) then begin
            if (get_critter_stat(party_member_obj(16777380), 35) < get_critter_stat(party_member_obj(16777380), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777381) != 0) then begin
            if (get_critter_stat(party_member_obj(16777381), 35) < get_critter_stat(party_member_obj(16777381), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777295) != 0) then begin
            if (get_critter_stat(party_member_obj(16777295), 35) < get_critter_stat(party_member_obj(16777295), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777407) != 0) then begin
            if (get_critter_stat(party_member_obj(16777407), 35) < get_critter_stat(party_member_obj(16777407), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777718) != 0) then begin
            if (get_critter_stat(party_member_obj(16777718), 35) < get_critter_stat(party_member_obj(16777718), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777719) != 0) then begin
            if (get_critter_stat(party_member_obj(16777719), 35) < get_critter_stat(party_member_obj(16777719), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777720) != 0) then begin
            if (get_critter_stat(party_member_obj(16777720), 35) < get_critter_stat(party_member_obj(16777720), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (How_Many_Party_Members_Are_Injured > 0) then begin
            gsay_reply(808, 114);
        end
        else begin
            gsay_reply(808, 111);
        end
    end
    else begin
        How_Many_Party_Members_Are_Injured := 0;
        if (party_member_obj(16777278) != 0) then begin
            if (get_critter_stat(party_member_obj(16777278), 35) < get_critter_stat(party_member_obj(16777278), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777376) != 0) then begin
            if (get_critter_stat(party_member_obj(16777376), 35) < get_critter_stat(party_member_obj(16777376), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777377) != 0) then begin
            if (get_critter_stat(party_member_obj(16777377), 35) < get_critter_stat(party_member_obj(16777377), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777305) != 0) then begin
            if (get_critter_stat(party_member_obj(16777305), 35) < get_critter_stat(party_member_obj(16777305), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777313) != 0) then begin
            if (get_critter_stat(party_member_obj(16777313), 35) < get_critter_stat(party_member_obj(16777313), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777323) != 0) then begin
            if (get_critter_stat(party_member_obj(16777323), 35) < get_critter_stat(party_member_obj(16777323), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777352) != 0) then begin
            if (get_critter_stat(party_member_obj(16777352), 35) < get_critter_stat(party_member_obj(16777352), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777378) != 0) then begin
            if (get_critter_stat(party_member_obj(16777378), 35) < get_critter_stat(party_member_obj(16777378), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777368) != 0) then begin
            if (get_critter_stat(party_member_obj(16777368), 35) < get_critter_stat(party_member_obj(16777368), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777379) != 0) then begin
            if (get_critter_stat(party_member_obj(16777379), 35) < get_critter_stat(party_member_obj(16777379), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777380) != 0) then begin
            if (get_critter_stat(party_member_obj(16777380), 35) < get_critter_stat(party_member_obj(16777380), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777381) != 0) then begin
            if (get_critter_stat(party_member_obj(16777381), 35) < get_critter_stat(party_member_obj(16777381), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777295) != 0) then begin
            if (get_critter_stat(party_member_obj(16777295), 35) < get_critter_stat(party_member_obj(16777295), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777407) != 0) then begin
            if (get_critter_stat(party_member_obj(16777407), 35) < get_critter_stat(party_member_obj(16777407), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777718) != 0) then begin
            if (get_critter_stat(party_member_obj(16777718), 35) < get_critter_stat(party_member_obj(16777718), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777719) != 0) then begin
            if (get_critter_stat(party_member_obj(16777719), 35) < get_critter_stat(party_member_obj(16777719), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (party_member_obj(16777720) != 0) then begin
            if (get_critter_stat(party_member_obj(16777720), 35) < get_critter_stat(party_member_obj(16777720), 7)) then begin
                How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
            end
        end
        if (How_Many_Party_Members_Are_Injured > 0) then begin
            gsay_reply(808, 118);
        end
        else begin
            gsay_reply(808, 117);
        end
    end
    giq_option(4, 808, 119, Node002a, 50);
    giq_option(4, 808, 120, Node012, 50);
    giq_option(4, 808, 121, Node010, 50);
    giq_option(4, 808, 122, Node999, 50);
end

procedure Node003
begin
    if (get_critter_stat(dude_obj, 35) < get_critter_stat(dude_obj, 7)) then begin
        gsay_reply(808, 123);
    end
    else begin
        gsay_reply(808, 124);
    end
    if (item_caps_total(dude_obj) > 49) then begin
        giq_option(4, 808, 125, Node003a, 50);
    end
    else begin
        giq_option(4, 808, 126, Node015, 50);
    end
    giq_option(4, 808, 127, Node999, 50);
end

procedure Node004
begin
    gsay_reply(808, 128);
    if (item_caps_total(dude_obj) > 99) then begin
        giq_option(4, 808, 129, Node004a, 50);
    end
    else begin
        giq_option(4, 808, 130, Node015, 50);
    end
    giq_option(4, 808, 131, Node999, 50);
end

procedure Node005
begin
    gsay_reply(808, 132);
    if (item_caps_total(dude_obj) > 99) then begin
        giq_option(4, 808, 134, Node005a, 50);
    end
    else begin
        giq_option(4, 808, 135, Node015, 50);
    end
    giq_option(4, 808, 136, Node999, 50);
end

procedure Node006
begin
end

procedure Node007
begin
    gsay_reply(808, 141);
    giq_option(4, 808, 142, Node007a, 50);
    giq_option(4, 808, 143, Node999, 50);
end

procedure Node008
begin
    if (local_var(13) == 0) then begin
        set_local_var(13, local_var(13) + 1);
        gsay_reply(808, 144);
        giq_option(4, 808, 146, Node004a, 50);
        giq_option(4, 808, 147, Node999, 49);
    end
    else begin
        gsay_reply(808, 145);
        giq_option(4, 808, 148, Node010, 50);
        giq_option(4, 808, 149, Node999, 50);
    end
end

procedure Node009
begin
    gsay_reply(808, 150);
    giq_option(4, 808, 151, Node011, 50);
    giq_option(4, 808, 152, Node010, 50);
    giq_option(4, 808, 153, Node999, 50);
end

procedure Node010
begin
    if (local_var(9) == 0) then begin
        set_local_var(9, local_var(9) + 1);
        gsay_reply(808, 154);
    end
    else begin
        gsay_reply(808, 155);
    end
    if (obj_is_carrying_obj_pid(dude_obj, 260) and (local_var(14) == 0)) then begin
        giq_option(4, 808, 156, Node020, 50);
    end
    if ((global_var(84) == 2) or (global_var(84) == 1) and (metarule(17, 4) == 2)) then begin
        giq_option(4, 808, 157, Node010a, 50);
    end
    How_Many_Party_Members_Are_Injured := 0;
    if (party_member_obj(16777278) != 0) then begin
        if (get_critter_stat(party_member_obj(16777278), 35) < get_critter_stat(party_member_obj(16777278), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (get_critter_stat(party_member_obj(16777376), 35) < get_critter_stat(party_member_obj(16777376), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (get_critter_stat(party_member_obj(16777377), 35) < get_critter_stat(party_member_obj(16777377), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (get_critter_stat(party_member_obj(16777305), 35) < get_critter_stat(party_member_obj(16777305), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (get_critter_stat(party_member_obj(16777313), 35) < get_critter_stat(party_member_obj(16777313), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (get_critter_stat(party_member_obj(16777323), 35) < get_critter_stat(party_member_obj(16777323), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (get_critter_stat(party_member_obj(16777352), 35) < get_critter_stat(party_member_obj(16777352), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (get_critter_stat(party_member_obj(16777378), 35) < get_critter_stat(party_member_obj(16777378), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (get_critter_stat(party_member_obj(16777368), 35) < get_critter_stat(party_member_obj(16777368), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (get_critter_stat(party_member_obj(16777379), 35) < get_critter_stat(party_member_obj(16777379), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (get_critter_stat(party_member_obj(16777380), 35) < get_critter_stat(party_member_obj(16777380), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (get_critter_stat(party_member_obj(16777381), 35) < get_critter_stat(party_member_obj(16777381), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (get_critter_stat(party_member_obj(16777295), 35) < get_critter_stat(party_member_obj(16777295), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (get_critter_stat(party_member_obj(16777407), 35) < get_critter_stat(party_member_obj(16777407), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777718) != 0) then begin
        if (get_critter_stat(party_member_obj(16777718), 35) < get_critter_stat(party_member_obj(16777718), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777719) != 0) then begin
        if (get_critter_stat(party_member_obj(16777719), 35) < get_critter_stat(party_member_obj(16777719), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777720) != 0) then begin
        if (get_critter_stat(party_member_obj(16777720), 35) < get_critter_stat(party_member_obj(16777720), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if ((How_Many_Party_Members_Are_Injured > 0) or (get_critter_stat(dude_obj, 35) < get_critter_stat(dude_obj, 7))) then begin
        giq_option(4, 808, 158, Node002, 50);
    end
    giq_option(4, 808, 159, Node010b, 50);
    giq_option(4, 808, 160, Node042, 50);
    giq_option(4, 808, 161, Node012, 50);
    if (get_sfall_global_int(SGVAR_CRAFT_FIRST_AID) == 0) then begin
      NOption(501, NodeCraft1, 004);
    end else begin
      NOption(502, NodeCraft10, 004);
    end
    giq_option(4, 808, 162, Node999, 50);
end

procedure Node011
begin
    gsay_reply(808, 163);
    giq_option(4, 808, 164, Node999, 50);
end

procedure Node012
begin
    gsay_reply(808, 165);
    giq_option(4, 808, 166, Node012a, 50);
    giq_option(4, 808, 167, Node010, 50);
    giq_option(4, 808, 168, Node999, 50);
end

procedure Node013
begin
    if (local_var(10) == 0) then begin
        set_local_var(10, local_var(10) + 1);
        gsay_reply(808, 169);
    end
    else begin
        gsay_reply(808, 170);
    end
    giq_option(4, 808, 171, Node012a, 50);
    giq_option(4, 808, 172, Node010, 50);
    giq_option(4, 808, 173, Node999, 50);
end

procedure Node014
begin
    gsay_reply(808, 174);
    giq_option(4, 808, 175, Node010, 50);
    giq_option(4, 808, 176, Node999, 50);
end

procedure Node015
begin
    gsay_reply(808, 177);
    giq_option(4, 808, 178, Node010, 50);
    giq_option(4, 808, 179, Node999, 50);
end

procedure Node016
begin
    set_global_var(84, 2);
    if (global_var(333) == 0) then begin
        gsay_reply(808, 180);
    end
    else begin
        if (global_var(333) == 1) then begin
            gsay_reply(808, 181);
        end
        else begin
            gsay_reply(808, 182);
        end
    end
    giq_option(4, 808, 183, Node022, 50);
    giq_option(4, 808, 184, Node023, 50);
    giq_option(4, 808, 185, Node010, 50);
    giq_option(4, 808, 186, Node999, 50);
end

procedure Node017
begin
    if (local_var(11) == 0) then begin
        set_local_var(11, local_var(11) + 1);
        gsay_reply(808, 187);
    end
    else begin
        gsay_reply(808, 188);
    end
    giq_option(4, 808, 189, Node010, 50);
    giq_option(4, 808, 190, Node012, 50);
    if (global_var(384) == 1) then begin
        giq_option(4, 808, 191, Node044, 50);
    end
    giq_option(4, 808, 192, Node999, 50);
end

procedure Node018
begin
    gsay_reply(808, 193);
    giq_option(4, 808, 194, Node010, 49);
    giq_option(6, 808, 195, Node024, 49);
    giq_option(4, 808, 196, Node999, 49);
end

procedure Node019
begin
    gsay_reply(808, 197);
    giq_option(4, 808, 198, Node010, 49);
    giq_option(6, 808, 199, Node024, 49);
    giq_option(4, 808, 200, Node022, 50);
    giq_option(4, 808, 201, Node999, 49);
end

procedure Node020
begin
    gsay_reply(808, 202);
    giq_option(4, 808, 203, Node032, 50);
    giq_option(4, 808, 204, Node010, 50);
end

procedure Node021
begin
    gsay_reply(808, 205);
    if (metarule(17, 4) == 2) then begin
        giq_option(4, 808, 206, Node039, 49);
    end
    giq_option(4, 808, 207, Node040, 50);
    giq_option(4, 808, 208, Node010, 50);
end

procedure Node022
begin
    gsay_reply(808, 209);
    giq_option(4, 808, 210, Node010, 50);
    giq_option(6, 808, 211, Node025, 50);
    giq_option(4, 808, 212, Node999, 50);
end

procedure Node023
begin
    gsay_reply(808, 213);
    giq_option(6, 808, 214, Node030, 51);
    giq_option(6, 808, 215, Node030, 51);
    giq_option(4, 808, 216, Node010, 50);
    giq_option(4, 808, 217, Node012, 50);
end

procedure Node024
begin
    gsay_reply(808, 218);
    giq_option(4, 808, 219, Node010, 50);
    giq_option(4, 808, 220, Node999, 50);
end

procedure Node025
begin
    gsay_reply(808, 221);
    giq_option(4, 808, 222, Node026, 50);
end

procedure Node026
begin
    gsay_reply(808, 223);
    giq_option(4, 808, 224, Node027, 50);
end

procedure Node027
begin
    gsay_reply(808, 225);
    if (metarule(17, 4) == 2) then begin
        giq_option(4, 808, 226, Node029, 51);
    end
    giq_option(4, 808, 227, Node028, 50);
end

procedure Node028
begin
    gsay_reply(808, 228);
    giq_option(4, 808, 229, Node010, 50);
    giq_option(4, 808, 230, Node999, 50);
end

procedure Node029
begin
    gsay_reply(808, 231);
    giq_option(4, 808, 232, Node028, 50);
    giq_option(4, 808, 233, Node999, 50);
end

procedure Node030
begin
    gsay_reply(808, 234);
    giq_option(4, 808, 235, Node010, 49);
    giq_option(6, 808, 236, Node031, 51);
    giq_option(4, 808, 237, Node999, 50);
end

procedure Node031
begin
    gsay_reply(808, 238);
    giq_option(4, 808, 239, Node010, 50);
    giq_option(4, 808, 240, Node999, 50);
end

procedure Node032
begin
    gsay_reply(808, 241);
    giq_option(4, 808, 242, Node033, 50);
    giq_option(4, 808, 243, Node034, 49);
end

procedure Node033
begin
    gsay_reply(808, 244);
    giq_option(4, 808, 245, Node034, 49);
end

procedure Node034
begin
    gsay_reply(808, 246);
    giq_option(4, 808, 247, Node034a, 49);
    giq_option(4, 808, 248, Node035, 50);
    giq_option(4, 808, 249, Node999, 50);
end

procedure Node035
begin
    gsay_reply(808, 250);
    giq_option(4, 808, 251, Node037, 51);
    giq_option(4, 808, 252, Node035a, 49);
end

procedure Node036
begin
    gsay_reply(808, 253);
    giq_option(4, 808, 254, Node024, 50);
    giq_option(4, 808, 255, Node010, 49);
    giq_option(4, 808, 256, Node999, 49);
end

procedure Node037
begin
    gsay_reply(808, 257);
    giq_option(4, 808, 258, Node037a, 49);
    giq_option(4, 808, 259, Node038, 51);
end

procedure Node038
begin
    gsay_reply(808, 260);
    giq_option(4, 808, 261, Node037a, 49);
    giq_option(4, 808, 262, Node999, 51);
end

procedure Node039
begin
    gsay_reply(808, 263);
    giq_option(4, 808, 264, Node041, 49);
    giq_option(4, 808, 265, Node043, 51);
end

procedure Node040
begin
    gsay_reply(808, 266);
    giq_option(4, 808, 267, Node041, 49);
    giq_option(4, 808, 268, Node010, 50);
end

procedure Node041
begin
    gsay_reply(808, 269);
    giq_option(4, 808, 270, Node010, 49);
    giq_option(4, 808, 271, Node999, 51);
end

procedure Node042
begin
    gsay_reply(808, 272);
    giq_option(4, 808, 273, Node010, 50);
    giq_option(4, 808, 274, Node999, 51);
end

procedure Node043
begin
    gsay_reply(808, 275);
    giq_option(4, 808, 276, Node041, 49);
end

procedure Node044
begin
    gsay_reply(808, 277);
    giq_option(4, 808, 278, Node045, 50);
end

procedure Node045
begin
    gsay_reply(808, 279);
    giq_option(4, 808, 280, Node046, 50);
end

procedure Node046
begin
    gsay_reply(808, 281);
    giq_option(4, 808, 282, Node047, 50);
end

procedure Node047
begin
    gsay_reply(808, 283);
    giq_option(4, 808, 284, Node048, 50);
end

procedure Node048
begin
    if (local_var(12) == 0) then begin
        set_local_var(12, local_var(12) + 1);
        gsay_reply(808, 285);
    end
    else begin
        gsay_reply(808, 286);
    end
    giq_option(4, 808, 287, Node017, 50);
    giq_option(4, 808, 288, Node049, 50);
    giq_option(4, 808, 289, Node999, 50);
end

procedure Node049
begin
    gsay_reply(808, 290);
    if (not(has_trait(0, dude_obj, 74)) and not(has_trait(0, dude_obj, 75))) then begin
        giq_option(4, 808, 291, Node050, 50);
    end
    if (not(has_trait(0, dude_obj, 76)) and not(has_trait(0, dude_obj, 77))) then begin
        giq_option(4, 808, 292, Node052, 50);
    end
    if (not(has_trait(0, dude_obj, 75))) then begin
        giq_option(4, 808, 293, Node051, 50);
    end
    if (not(has_trait(0, dude_obj, 77))) then begin
        giq_option(4, 808, 294, Node053, 50);
    end
    giq_option(4, 808, 295, Node017, 50);
    giq_option(4, 808, 296, Node999, 50);
end

procedure Node050
begin
    gsay_reply(808, 297);
    if ((item_caps_total(dude_obj) >= 5000) and (obj_carrying_pid_obj(dude_obj, 17) or obj_carrying_pid_obj(dude_obj, 381) or obj_carrying_pid_obj(dude_obj, 239))) then begin
        giq_option(4, 808, 298, Node050a, 50);
    end
    giq_option(4, 808, 299, Node049, 50);
    if (item_caps_total(dude_obj) < 5000) then begin
        giq_option(4, 808, 300, Node999, 50);
    end
    if (not(obj_carrying_pid_obj(dude_obj, 17) or obj_carrying_pid_obj(dude_obj, 381) or obj_carrying_pid_obj(dude_obj, 239))) then begin
        giq_option(4, 808, 301, Node999, 50);
    end
    giq_option(4, 808, 302, Node999, 50);
end

procedure Node051
begin
    if (not(has_trait(0, dude_obj, 74))) then begin
        gsay_reply(808, 303);
    end
    else begin
        gsay_reply(808, 304);
        if ((item_caps_total(dude_obj) >= 30000) and (obj_carrying_pid_obj(dude_obj, 17) or obj_carrying_pid_obj(dude_obj, 381) or obj_carrying_pid_obj(dude_obj, 239))) then begin
            giq_option(4, 808, 305, Node051a, 50);
        end
        giq_option(4, 808, 306, Node049, 50);
        if (item_caps_total(dude_obj) < 30000) then begin
            giq_option(4, 808, 307, Node999, 50);
        end
        if (not(obj_carrying_pid_obj(dude_obj, 17) or obj_carrying_pid_obj(dude_obj, 381) or obj_carrying_pid_obj(dude_obj, 239))) then begin
            giq_option(4, 808, 308, Node999, 50);
        end
    end
    giq_option(4, 808, 309, Node999, 50);
end

procedure Node052
begin
    gsay_reply(808, 310);
    if ((item_caps_total(dude_obj) >= 8000) and (obj_carrying_pid_obj(dude_obj, 17) or obj_carrying_pid_obj(dude_obj, 381) or obj_carrying_pid_obj(dude_obj, 239))) then begin
        giq_option(4, 808, 311, Node052a, 50);
    end
    giq_option(4, 808, 312, Node049, 50);
    if (item_caps_total(dude_obj) < 8000) then begin
        giq_option(4, 808, 313, Node999, 50);
    end
    if (not(obj_carrying_pid_obj(dude_obj, 17) or obj_carrying_pid_obj(dude_obj, 381) or obj_carrying_pid_obj(dude_obj, 239))) then begin
        giq_option(4, 808, 314, Node999, 50);
    end
    giq_option(4, 808, 315, Node999, 50);
end

procedure Node053
begin
    if (not(has_trait(0, dude_obj, 76))) then begin
        gsay_reply(808, 316);
    end
    else begin
        gsay_reply(808, 317);
        if ((item_caps_total(dude_obj) >= 30000) and (obj_carrying_pid_obj(dude_obj, 17) or obj_carrying_pid_obj(dude_obj, 381) or obj_carrying_pid_obj(dude_obj, 239))) then begin
            giq_option(4, 808, 318, Node053a, 50);
        end
        giq_option(4, 808, 319, Node049, 50);
        if (item_caps_total(dude_obj) < 30000) then begin
            giq_option(4, 808, 320, Node999, 50);
        end
        if (not(obj_carrying_pid_obj(dude_obj, 17) or obj_carrying_pid_obj(dude_obj, 381) or obj_carrying_pid_obj(dude_obj, 239))) then begin
            giq_option(4, 808, 321, Node999, 50);
        end
    end
    giq_option(4, 808, 322, Node999, 50);
end

procedure Node054
begin
    if (From_50) then begin
        gsay_reply(808, 323);
    end
    else begin
        if (From_51) then begin
            gsay_reply(808, 324);
        end
        else begin
            if (From_52) then begin
                gsay_reply(808, 325);
            end
            else begin
                gsay_reply(808, 326);
            end
        end
    end
    giq_option(4, 808, 327, Node017, 50);
    giq_option(4, 808, 328, Node999, 50);
end

procedure Node002a
begin
    How_Many_Party_Members_Are_Injured := 0;
    if (party_member_obj(16777278) != 0) then begin
        if (get_critter_stat(party_member_obj(16777278), 35) < get_critter_stat(party_member_obj(16777278), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (get_critter_stat(party_member_obj(16777376), 35) < get_critter_stat(party_member_obj(16777376), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (get_critter_stat(party_member_obj(16777377), 35) < get_critter_stat(party_member_obj(16777377), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (get_critter_stat(party_member_obj(16777305), 35) < get_critter_stat(party_member_obj(16777305), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (get_critter_stat(party_member_obj(16777313), 35) < get_critter_stat(party_member_obj(16777313), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (get_critter_stat(party_member_obj(16777323), 35) < get_critter_stat(party_member_obj(16777323), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (get_critter_stat(party_member_obj(16777352), 35) < get_critter_stat(party_member_obj(16777352), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (get_critter_stat(party_member_obj(16777378), 35) < get_critter_stat(party_member_obj(16777378), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (get_critter_stat(party_member_obj(16777368), 35) < get_critter_stat(party_member_obj(16777368), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (get_critter_stat(party_member_obj(16777379), 35) < get_critter_stat(party_member_obj(16777379), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (get_critter_stat(party_member_obj(16777380), 35) < get_critter_stat(party_member_obj(16777380), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (get_critter_stat(party_member_obj(16777381), 35) < get_critter_stat(party_member_obj(16777381), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (get_critter_stat(party_member_obj(16777295), 35) < get_critter_stat(party_member_obj(16777295), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (get_critter_stat(party_member_obj(16777407), 35) < get_critter_stat(party_member_obj(16777407), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777718) != 0) then begin
        if (get_critter_stat(party_member_obj(16777718), 35) < get_critter_stat(party_member_obj(16777718), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777719) != 0) then begin
        if (get_critter_stat(party_member_obj(16777719), 35) < get_critter_stat(party_member_obj(16777719), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (party_member_obj(16777720) != 0) then begin
        if (get_critter_stat(party_member_obj(16777720), 35) < get_critter_stat(party_member_obj(16777720), 7)) then begin
            How_Many_Party_Members_Are_Injured := How_Many_Party_Members_Are_Injured + 1;
        end
    end
    if (How_Many_Party_Members_Are_Injured > 0) then begin
        if (How_Many_Party_Members_Armed == 1) then begin
            call Node003;
        end
        else begin
            call Node004;
        end
    end
    else begin
        if (get_critter_stat(dude_obj, 35) < get_critter_stat(dude_obj, 7)) then begin
            call Node003;
        end
        else begin
            call Node005;
        end
    end
end

procedure Node003a
begin
    item_caps_adjust(dude_obj, -50);
    item_caps_adjust(self_obj, 30);
    game_time_advance(60 * (60 * 10));
    gfade_out(600);
    gfade_in(600);
    if (get_critter_stat(dude_obj, 35) < get_critter_stat(dude_obj, 7)) then begin
        critter_heal(dude_obj, get_critter_stat(dude_obj, 7) - get_critter_stat(dude_obj, 35));
    end
    else begin
        if (party_member_obj(16777278) != 0) then begin
            if (get_critter_stat(party_member_obj(16777278), 35) < get_critter_stat(party_member_obj(16777278), 7)) then begin
                critter_heal(party_member_obj(16777278), get_critter_stat(party_member_obj(16777278), 7) - get_critter_stat(party_member_obj(16777278), 35));
            end
        end
        else begin
            if (party_member_obj(16777376) != 0) then begin
                if (get_critter_stat(party_member_obj(16777376), 35) < get_critter_stat(party_member_obj(16777376), 7)) then begin
                    critter_heal(party_member_obj(16777376), get_critter_stat(party_member_obj(16777376), 7) - get_critter_stat(party_member_obj(16777376), 35));
                end
            end
            else begin
                if (party_member_obj(16777377) != 0) then begin
                    if (get_critter_stat(party_member_obj(16777377), 35) < get_critter_stat(party_member_obj(16777377), 7)) then begin
                        critter_heal(party_member_obj(16777377), get_critter_stat(party_member_obj(16777377), 7) - get_critter_stat(party_member_obj(16777377), 35));
                    end
                end
                else begin
                    if (party_member_obj(16777305) != 0) then begin
                        if (get_critter_stat(party_member_obj(16777305), 35) < get_critter_stat(party_member_obj(16777305), 7)) then begin
                            critter_heal(party_member_obj(16777305), get_critter_stat(party_member_obj(16777305), 7) - get_critter_stat(party_member_obj(16777305), 35));
                        end
                    end
                    else begin
                        if (party_member_obj(16777313) != 0) then begin
                            if (get_critter_stat(party_member_obj(16777313), 35) < get_critter_stat(party_member_obj(16777313), 7)) then begin
                                critter_heal(party_member_obj(16777313), get_critter_stat(party_member_obj(16777313), 7) - get_critter_stat(party_member_obj(16777313), 35));
                            end
                        end
                        else begin
                            if (party_member_obj(16777323) != 0) then begin
                                if (get_critter_stat(party_member_obj(16777323), 35) < get_critter_stat(party_member_obj(16777323), 7)) then begin
                                    critter_heal(party_member_obj(16777323), get_critter_stat(party_member_obj(16777323), 7) - get_critter_stat(party_member_obj(16777323), 35));
                                end
                            end
                            else begin
                                if (party_member_obj(16777352) != 0) then begin
                                    if (get_critter_stat(party_member_obj(16777352), 35) < get_critter_stat(party_member_obj(16777352), 7)) then begin
                                        critter_heal(party_member_obj(16777352), get_critter_stat(party_member_obj(16777352), 7) - get_critter_stat(party_member_obj(16777352), 35));
                                    end
                                end
                                else begin
                                    if (party_member_obj(16777378) != 0) then begin
                                        if (get_critter_stat(party_member_obj(16777378), 35) < get_critter_stat(party_member_obj(16777378), 7)) then begin
                                            critter_heal(party_member_obj(16777378), get_critter_stat(party_member_obj(16777378), 7) - get_critter_stat(party_member_obj(16777378), 35));
                                        end
                                    end
                                    else begin
                                        if (party_member_obj(16777368) != 0) then begin
                                            if (get_critter_stat(party_member_obj(16777368), 35) < get_critter_stat(party_member_obj(16777368), 7)) then begin
                                                critter_heal(party_member_obj(16777368), get_critter_stat(party_member_obj(16777368), 7) - get_critter_stat(party_member_obj(16777368), 35));
                                            end
                                        end
                                        else begin
                                            if (party_member_obj(16777379) != 0) then begin
                                                if (get_critter_stat(party_member_obj(16777379), 35) < get_critter_stat(party_member_obj(16777379), 7)) then begin
                                                    critter_heal(party_member_obj(16777379), get_critter_stat(party_member_obj(16777379), 7) - get_critter_stat(party_member_obj(16777379), 35));
                                                end
                                            end
                                            else begin
                                                if (party_member_obj(16777380) != 0) then begin
                                                    if (get_critter_stat(party_member_obj(16777380), 35) < get_critter_stat(party_member_obj(16777380), 7)) then begin
                                                        critter_heal(party_member_obj(16777380), get_critter_stat(party_member_obj(16777380), 7) - get_critter_stat(party_member_obj(16777380), 35));
                                                    end
                                                end
                                                else begin
                                                    if (party_member_obj(16777381) != 0) then begin
                                                        if (get_critter_stat(party_member_obj(16777381), 35) < get_critter_stat(party_member_obj(16777381), 7)) then begin
                                                            critter_heal(party_member_obj(16777381), get_critter_stat(party_member_obj(16777381), 7) - get_critter_stat(party_member_obj(16777381), 35));
                                                        end
                                                    end
                                                    else begin
                                                        if (party_member_obj(16777295) != 0) then begin
                                                            if (get_critter_stat(party_member_obj(16777295), 35) < get_critter_stat(party_member_obj(16777295), 7)) then begin
                                                                critter_heal(party_member_obj(16777295), get_critter_stat(party_member_obj(16777295), 7) - get_critter_stat(party_member_obj(16777295), 35));
                                                            end
                                                        end
                                                        else begin
                                                            if (party_member_obj(16777407) != 0) then begin
                                                                if (get_critter_stat(party_member_obj(16777407), 35) < get_critter_stat(party_member_obj(16777407), 7)) then begin
                                                                    critter_heal(party_member_obj(16777407), get_critter_stat(party_member_obj(16777407), 7) - get_critter_stat(party_member_obj(16777407), 35));
                                                                end
                                                            end
                                                            else begin
                                                                if (party_member_obj(16777558) != 0) then begin
                                                                    if (get_critter_stat(party_member_obj(16777558), 35) < get_critter_stat(party_member_obj(16777558), 7)) then begin
                                                                        critter_heal(party_member_obj(16777558), get_critter_stat(party_member_obj(16777558), 7) - get_critter_stat(party_member_obj(16777558), 35));
                                                                    end
                                                                end
                                                                else begin
                                                                    if (party_member_obj(16777687) != 0) then begin
                                                                        if (get_critter_stat(party_member_obj(16777687), 35) < get_critter_stat(party_member_obj(16777687), 7)) then begin
                                                                            critter_heal(party_member_obj(16777687), get_critter_stat(party_member_obj(16777687), 7) - get_critter_stat(party_member_obj(16777687), 35));
                                                                        end
                                                                    end
                                                                    else begin
                                                                        if (party_member_obj(16777718) != 0) then begin
                                                                            if (get_critter_stat(party_member_obj(16777718), 35) < get_critter_stat(party_member_obj(16777718), 7)) then begin
                                                                                critter_heal(party_member_obj(16777718), get_critter_stat(party_member_obj(16777718), 7) - get_critter_stat(party_member_obj(16777718), 35));
                                                                            end
                                                                        end
                                                                        else begin
                                                                            if (party_member_obj(16777719) != 0) then begin
                                                                                if (get_critter_stat(party_member_obj(16777719), 35) < get_critter_stat(party_member_obj(16777719), 7)) then begin
                                                                                    critter_heal(party_member_obj(16777719), get_critter_stat(party_member_obj(16777719), 7) - get_critter_stat(party_member_obj(16777719), 35));
                                                                                end
                                                                            end
                                                                            else begin
                                                                                if (party_member_obj(16777720) != 0) then begin
                                                                                    if (get_critter_stat(party_member_obj(16777720), 35) < get_critter_stat(party_member_obj(16777720), 7)) then begin
                                                                                        critter_heal(party_member_obj(16777720), get_critter_stat(party_member_obj(16777720), 7) - get_critter_stat(party_member_obj(16777720), 35));
                                                                                    end
                                                                                end
                                                                            end
                                                                        end
                                                                    end
                                                                end
                                                            end
                                                        end
                                                    end
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    call Node014;
end

procedure Node004a
begin
    item_caps_adjust(dude_obj, -100);
    item_caps_adjust(self_obj, 60);
    game_time_advance(60 * (60 * 10));
    gfade_out(600);
    gfade_in(600);
    if (get_critter_stat(dude_obj, 35) < get_critter_stat(dude_obj, 7)) then begin
        critter_heal(dude_obj, get_critter_stat(dude_obj, 7) - get_critter_stat(dude_obj, 35));
    end
    if (party_member_obj(16777278) != 0) then begin
        if (get_critter_stat(party_member_obj(16777278), 35) < get_critter_stat(party_member_obj(16777278), 7)) then begin
            critter_heal(party_member_obj(16777278), get_critter_stat(party_member_obj(16777278), 7) - get_critter_stat(party_member_obj(16777278), 35));
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (get_critter_stat(party_member_obj(16777376), 35) < get_critter_stat(party_member_obj(16777376), 7)) then begin
            critter_heal(party_member_obj(16777376), get_critter_stat(party_member_obj(16777376), 7) - get_critter_stat(party_member_obj(16777376), 35));
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (get_critter_stat(party_member_obj(16777377), 35) < get_critter_stat(party_member_obj(16777377), 7)) then begin
            critter_heal(party_member_obj(16777377), get_critter_stat(party_member_obj(16777377), 7) - get_critter_stat(party_member_obj(16777377), 35));
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (get_critter_stat(party_member_obj(16777305), 35) < get_critter_stat(party_member_obj(16777305), 7)) then begin
            critter_heal(party_member_obj(16777305), get_critter_stat(party_member_obj(16777305), 7) - get_critter_stat(party_member_obj(16777305), 35));
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (get_critter_stat(party_member_obj(16777313), 35) < get_critter_stat(party_member_obj(16777313), 7)) then begin
            critter_heal(party_member_obj(16777313), get_critter_stat(party_member_obj(16777313), 7) - get_critter_stat(party_member_obj(16777313), 35));
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (get_critter_stat(party_member_obj(16777323), 35) < get_critter_stat(party_member_obj(16777323), 7)) then begin
            critter_heal(party_member_obj(16777323), get_critter_stat(party_member_obj(16777323), 7) - get_critter_stat(party_member_obj(16777323), 35));
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (get_critter_stat(party_member_obj(16777352), 35) < get_critter_stat(party_member_obj(16777352), 7)) then begin
            critter_heal(party_member_obj(16777352), get_critter_stat(party_member_obj(16777352), 7) - get_critter_stat(party_member_obj(16777352), 35));
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (get_critter_stat(party_member_obj(16777378), 35) < get_critter_stat(party_member_obj(16777378), 7)) then begin
            critter_heal(party_member_obj(16777378), get_critter_stat(party_member_obj(16777378), 7) - get_critter_stat(party_member_obj(16777378), 35));
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (get_critter_stat(party_member_obj(16777368), 35) < get_critter_stat(party_member_obj(16777368), 7)) then begin
            critter_heal(party_member_obj(16777368), get_critter_stat(party_member_obj(16777368), 7) - get_critter_stat(party_member_obj(16777368), 35));
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (get_critter_stat(party_member_obj(16777379), 35) < get_critter_stat(party_member_obj(16777379), 7)) then begin
            critter_heal(party_member_obj(16777379), get_critter_stat(party_member_obj(16777379), 7) - get_critter_stat(party_member_obj(16777379), 35));
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (get_critter_stat(party_member_obj(16777380), 35) < get_critter_stat(party_member_obj(16777380), 7)) then begin
            critter_heal(party_member_obj(16777380), get_critter_stat(party_member_obj(16777380), 7) - get_critter_stat(party_member_obj(16777380), 35));
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (get_critter_stat(party_member_obj(16777381), 35) < get_critter_stat(party_member_obj(16777381), 7)) then begin
            critter_heal(party_member_obj(16777381), get_critter_stat(party_member_obj(16777381), 7) - get_critter_stat(party_member_obj(16777381), 35));
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (get_critter_stat(party_member_obj(16777295), 35) < get_critter_stat(party_member_obj(16777295), 7)) then begin
            critter_heal(party_member_obj(16777295), get_critter_stat(party_member_obj(16777295), 7) - get_critter_stat(party_member_obj(16777295), 35));
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (get_critter_stat(party_member_obj(16777407), 35) < get_critter_stat(party_member_obj(16777407), 7)) then begin
            critter_heal(party_member_obj(16777407), get_critter_stat(party_member_obj(16777407), 7) - get_critter_stat(party_member_obj(16777407), 35));
        end
    end
    else begin
        if (party_member_obj(16777558) != 0) then begin
            if (get_critter_stat(party_member_obj(16777558), 35) < get_critter_stat(party_member_obj(16777558), 7)) then begin
                critter_heal(party_member_obj(16777558), get_critter_stat(party_member_obj(16777558), 7) - get_critter_stat(party_member_obj(16777558), 35));
            end
        end
        else begin
            if (party_member_obj(16777687) != 0) then begin
                if (get_critter_stat(party_member_obj(16777687), 35) < get_critter_stat(party_member_obj(16777687), 7)) then begin
                    critter_heal(party_member_obj(16777687), get_critter_stat(party_member_obj(16777687), 7) - get_critter_stat(party_member_obj(16777687), 35));
                end
            end
            else begin
                if (party_member_obj(16777718) != 0) then begin
                    if (get_critter_stat(party_member_obj(16777718), 35) < get_critter_stat(party_member_obj(16777718), 7)) then begin
                        critter_heal(party_member_obj(16777718), get_critter_stat(party_member_obj(16777718), 7) - get_critter_stat(party_member_obj(16777718), 35));
                    end
                end
                else begin
                    if (party_member_obj(16777719) != 0) then begin
                        if (get_critter_stat(party_member_obj(16777719), 35) < get_critter_stat(party_member_obj(16777719), 7)) then begin
                            critter_heal(party_member_obj(16777719), get_critter_stat(party_member_obj(16777719), 7) - get_critter_stat(party_member_obj(16777719), 35));
                        end
                    end
                    else begin
                        if (party_member_obj(16777720) != 0) then begin
                            if (get_critter_stat(party_member_obj(16777720), 35) < get_critter_stat(party_member_obj(16777720), 7)) then begin
                                critter_heal(party_member_obj(16777720), get_critter_stat(party_member_obj(16777720), 7) - get_critter_stat(party_member_obj(16777720), 35));
                            end
                        end
                    end
                end
            end
        end
    end
    call Node014;
end

procedure Node005a
begin
    item_caps_adjust(dude_obj, -100);
    item_caps_adjust(self_obj, 60);
    if (get_poison(dude_obj)) then begin
        poison(dude_obj, -get_poison(dude_obj));
    end
    if (get_critter_stat(dude_obj, 37)) then begin
        radiation_dec(dude_obj, get_critter_stat(dude_obj, 37));
    end
    gfade_out(600);
    gfade_in(600);
    game_time_advance(60 * (60 * 10));
    call Node014;
end

procedure Node007a
begin
    if (is_success(roll_vs_skill(dude_obj, 14, -20))) then begin
        call Node008;
    end
    else begin
        call Node009;
    end
end

procedure Node010a
begin
    set_global_var(84, 2);
    call Node021;
end

procedure Node010b
begin
    if (global_var(333) == 3) then begin
        call Node018;
    end
    else begin
        if (global_var(333) == 4) then begin
            call Node019;
        end
        else begin
            call Node016;
        end
    end
end

procedure Node012a
begin
    gdialog_mod_barter(0);
    call Node013;
end

procedure Node034a
begin
    variable LVar0 := 0;
    display_msg(message_str(808, 329));
    set_local_var(14, game_time);
    if (not((map_var(0) == 7) or (map_var(0) == 8) or (map_var(0) == 9))) then begin
        set_map_var(0, 8);
    end
    give_exp_points(2500);
    display_msg(message_str(14, 100) + 2500 + message_str(14, 101));
    LVar0 := obj_carrying_pid_obj(dude_obj, 260);
    rm_obj_from_inven(dude_obj, LVar0);
    destroy_object(LVar0);
    set_global_var(84, 3);
    set_global_var(333, 3);
    set_global_var(0, global_var(0) + 25);
    debug_msg("Player gains " + 25 + " Karma Points.");
    set_global_var(37, 0);
    set_global_var(38, 0);
    set_global_var(39, 0);
    set_global_var(40, 0);
    set_global_var(41, 0);
    set_global_var(42, 0);
    set_global_var(43, 0);
    set_global_var(44, 0);
    set_global_var(45, 0);
    tmp_gen_rep := global_var(0);
    if (has_trait(0, dude_obj, 95)) then begin
        tmp_gen_rep := global_var(0) * 2;
    end
    if (tmp_gen_rep >= 1000) then begin
        set_global_var(37, 1);
    end
    else begin
        if (tmp_gen_rep >= 750) then begin
            set_global_var(38, 1);
        end
        else begin
            if (tmp_gen_rep >= 500) then begin
                set_global_var(39, 1);
            end
            else begin
                if (tmp_gen_rep >= 250) then begin
                    set_global_var(40, 1);
                end
                else begin
                    if (tmp_gen_rep > -250) then begin
                        set_global_var(41, 1);
                    end
                    else begin
                        if (tmp_gen_rep > -500) then begin
                            set_global_var(42, 1);
                        end
                        else begin
                            if (tmp_gen_rep > -750) then begin
                                set_global_var(43, 1);
                            end
                            else begin
                                if (tmp_gen_rep > -1000) then begin
                                    set_global_var(44, 1);
                                end
                                else begin
                                    set_global_var(45, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    call Node036;
end

procedure Node035a
begin
    variable LVar0 := 0;
    display_msg(message_str(808, 329));
    set_local_var(14, game_time);
    if (not((map_var(0) == 7) or (map_var(0) == 8) or (map_var(0) == 9))) then begin
        set_map_var(0, 8);
    end
    give_exp_points(2500);
    display_msg(message_str(14, 100) + 2500 + message_str(14, 101));
    LVar0 := obj_carrying_pid_obj(dude_obj, 260);
    rm_obj_from_inven(dude_obj, LVar0);
    set_global_var(84, 3);
    set_global_var(333, 3);
    set_global_var(0, global_var(0) + 15);
    debug_msg("Player gains " + 15 + " Karma Points.");
    set_global_var(37, 0);
    set_global_var(38, 0);
    set_global_var(39, 0);
    set_global_var(40, 0);
    set_global_var(41, 0);
    set_global_var(42, 0);
    set_global_var(43, 0);
    set_global_var(44, 0);
    set_global_var(45, 0);
    tmp_gen_rep := global_var(0);
    if (has_trait(0, dude_obj, 95)) then begin
        tmp_gen_rep := global_var(0) * 2;
    end
    if (tmp_gen_rep >= 1000) then begin
        set_global_var(37, 1);
    end
    else begin
        if (tmp_gen_rep >= 750) then begin
            set_global_var(38, 1);
        end
        else begin
            if (tmp_gen_rep >= 500) then begin
                set_global_var(39, 1);
            end
            else begin
                if (tmp_gen_rep >= 250) then begin
                    set_global_var(40, 1);
                end
                else begin
                    if (tmp_gen_rep > -250) then begin
                        set_global_var(41, 1);
                    end
                    else begin
                        if (tmp_gen_rep > -500) then begin
                            set_global_var(42, 1);
                        end
                        else begin
                            if (tmp_gen_rep > -750) then begin
                                set_global_var(43, 1);
                            end
                            else begin
                                if (tmp_gen_rep > -1000) then begin
                                    set_global_var(44, 1);
                                end
                                else begin
                                    set_global_var(45, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    call Node036;
end

procedure Node037a
begin
    variable LVar0 := 0;
    display_msg(message_str(808, 329));
    set_local_var(14, game_time);
    if (not((map_var(0) == 7) or (map_var(0) == 8) or (map_var(0) == 9))) then begin
        set_map_var(0, 8);
    end
    give_exp_points(2500);
    display_msg(message_str(14, 100) + 2500 + message_str(14, 101));
    LVar0 := obj_carrying_pid_obj(dude_obj, 260);
    rm_obj_from_inven(dude_obj, LVar0);
    set_global_var(84, 3);
    set_global_var(333, 3);
    item_caps_adjust(self_obj, -2000);
    item_caps_adjust(dude_obj, 2000);
    call Node036;
end

procedure Node050a
begin
    variable LVar0 := 0;
    if ((item_caps_total(dude_obj) >= 5000) and (obj_carrying_pid_obj(dude_obj, 17) or obj_carrying_pid_obj(dude_obj, 381) or obj_carrying_pid_obj(dude_obj, 239))) then begin
        item_caps_adjust(dude_obj, -5000);
        if (obj_carrying_pid_obj(dude_obj, 17)) then begin
            LVar0 := obj_carrying_pid_obj(dude_obj, 17);
        end
        else begin
            if (obj_carrying_pid_obj(dude_obj, 381)) then begin
                LVar0 := obj_carrying_pid_obj(dude_obj, 381);
            end
            else begin
                if (obj_carrying_pid_obj(dude_obj, 239)) then begin
                    LVar0 := obj_carrying_pid_obj(dude_obj, 239);
                end
            end
        end
        rm_obj_from_inven(dude_obj, LVar0);
        destroy_object(LVar0);
        critter_add_trait(dude_obj, 0, 74, 1);
        game_time_advance(2 * (24 * (60 * (60 * 10))));
        gfade_out(600);
        gfade_in(600);
        From_50 := 1;
        From_51 := 0;
        From_52 := 0;
        From_53 := 0;
        call Node054;
    end
    else begin
        gsay_reply(808, 297);
        if (item_caps_total(dude_obj) < 5000) then begin
            giq_option(4, 808, 300, Node999, 50);
        end
        if (not(obj_carrying_pid_obj(dude_obj, 17) or obj_carrying_pid_obj(dude_obj, 381) or obj_carrying_pid_obj(dude_obj, 239))) then begin
            giq_option(4, 808, 301, Node999, 50);
        end
    end
end

procedure Node051a
begin
    variable LVar0 := 0;
    if ((item_caps_total(dude_obj) >= 30000) and (obj_carrying_pid_obj(dude_obj, 17) or obj_carrying_pid_obj(dude_obj, 381) or obj_carrying_pid_obj(dude_obj, 239))) then begin
        item_caps_adjust(dude_obj, -30000);
        if (obj_carrying_pid_obj(dude_obj, 17)) then begin
            LVar0 := obj_carrying_pid_obj(dude_obj, 17);
        end
        else begin
            if (obj_carrying_pid_obj(dude_obj, 381)) then begin
                LVar0 := obj_carrying_pid_obj(dude_obj, 381);
            end
            else begin
                if (obj_carrying_pid_obj(dude_obj, 239)) then begin
                    LVar0 := obj_carrying_pid_obj(dude_obj, 239);
                end
            end
        end
        rm_obj_from_inven(dude_obj, LVar0);
        destroy_object(LVar0);
        critter_rm_trait(dude_obj, 0, 74, 1);
        critter_add_trait(dude_obj, 0, 75, 1);
        game_time_advance(5 * (24 * (60 * (60 * 10))));
        gfade_out(600);
        gfade_in(600);
        From_50 := 0;
        From_51 := 1;
        From_52 := 0;
        From_53 := 0;
        call Node054;
    end
    else begin
        gsay_reply(808, 304);
        if (item_caps_total(dude_obj) < 30000) then begin
            giq_option(4, 808, 307, Node999, 50);
        end
        if (not(obj_carrying_pid_obj(dude_obj, 17) or obj_carrying_pid_obj(dude_obj, 381) or obj_carrying_pid_obj(dude_obj, 239))) then begin
            giq_option(4, 808, 308, Node999, 50);
        end
    end
end

procedure Node052a
begin
    variable LVar0 := 0;
    if ((item_caps_total(dude_obj) >= 8000) and (obj_carrying_pid_obj(dude_obj, 17) or obj_carrying_pid_obj(dude_obj, 381) or obj_carrying_pid_obj(dude_obj, 239))) then begin
        item_caps_adjust(dude_obj, -8000);
        if (obj_carrying_pid_obj(dude_obj, 17)) then begin
            LVar0 := obj_carrying_pid_obj(dude_obj, 17);
        end
        else begin
            if (obj_carrying_pid_obj(dude_obj, 381)) then begin
                LVar0 := obj_carrying_pid_obj(dude_obj, 381);
            end
            else begin
                if (obj_carrying_pid_obj(dude_obj, 239)) then begin
                    LVar0 := obj_carrying_pid_obj(dude_obj, 239);
                end
            end
        end
        rm_obj_from_inven(dude_obj, LVar0);
        destroy_object(LVar0);
        critter_add_trait(dude_obj, 0, 76, 1);
        game_time_advance(3 * (24 * (60 * (60 * 10))));
        gfade_out(600);
        gfade_in(600);
        From_50 := 0;
        From_51 := 0;
        From_52 := 1;
        From_53 := 0;
        call Node054;
    end
    else begin
        gsay_reply(808, 310);
        if (item_caps_total(dude_obj) < 8000) then begin
            giq_option(4, 808, 313, Node999, 50);
        end
        if (not(obj_carrying_pid_obj(dude_obj, 17) or obj_carrying_pid_obj(dude_obj, 381) or obj_carrying_pid_obj(dude_obj, 239))) then begin
            giq_option(4, 808, 314, Node999, 50);
        end
    end
end

procedure Node053a
begin
    variable LVar0 := 0;
    if ((item_caps_total(dude_obj) >= 48000) and (obj_carrying_pid_obj(dude_obj, 17) or obj_carrying_pid_obj(dude_obj, 381) or obj_carrying_pid_obj(dude_obj, 239))) then begin
        item_caps_adjust(dude_obj, -48000);
        if (obj_carrying_pid_obj(dude_obj, 17)) then begin
            LVar0 := obj_carrying_pid_obj(dude_obj, 17);
        end
        else begin
            if (obj_carrying_pid_obj(dude_obj, 381)) then begin
                LVar0 := obj_carrying_pid_obj(dude_obj, 381);
            end
            else begin
                if (obj_carrying_pid_obj(dude_obj, 239)) then begin
                    LVar0 := obj_carrying_pid_obj(dude_obj, 239);
                end
            end
        end
        rm_obj_from_inven(dude_obj, LVar0);
        destroy_object(LVar0);
        critter_rm_trait(dude_obj, 0, 76, 1);
        critter_add_trait(dude_obj, 0, 77, 1);
        game_time_advance(6 * (24 * (60 * (60 * 10))));
        gfade_out(600);
        gfade_in(600);
        From_50 := 0;
        From_51 := 0;
        From_52 := 0;
        From_53 := 1;
        call Node054;
    end
    else begin
        gsay_reply(808, 317);
        if (item_caps_total(dude_obj) < 48000) then begin
            giq_option(4, 808, 320, Node999, 50);
        end
        if (not(obj_carrying_pid_obj(dude_obj, 17) or obj_carrying_pid_obj(dude_obj, 381) or obj_carrying_pid_obj(dude_obj, 239))) then begin
            giq_option(4, 808, 321, Node999, 50);
        end
    end
end

