#ifndef GAME_RPU_H
#define GAME_RPU_H

procedure critical_items_list_rpu begin
   return [
      PID_ACCOUNT_BOOK,
      PID_ANNA_GOLD_LOCKET,
      PID_BECKY_BOOK,
      PID_BISHOPS_HOLODISK,
      PID_BLUE_PASS_KEY,
      //PID_CAR_FUEL_CELL,
      PID_CAR_FUEL_CELL_CONTROLLER,
      PID_CAR_FUEL_INJECTION,
      PID_CELL_DOOR_KEY,
      PID_COMPUTER_VOICE_MODULE,
      PID_CORNELIUS_GOLD_WATCH,
      PID_DAY_PASS,
      PID_DR_HENRY_PAPERS,
      //PID_ECON_HOLODISK,
      PID_ENLIGHTENED_ONE_LETTER,
      PID_EXCAVATOR_CHIP,
      PID_FAKE_CITIZENSHIP,
      PID_GECK,
      PID_GECKO_DATA_DISK,
      PID_GOLD_LOCKET,
      PID_HY_MAG_PART,
      PID_K9_MOTIVATOR,
      PID_LYNETTE_HOLO,
      PID_MOORE_BAD_BRIEFCASE,
      PID_MOORE_GOOD_BRIEFCASE,
      PID_NAV_COMPUTER_PARTS,
      PID_PLASMA_TRANSFORMER,
      PID_PRES_ACCESS_KEY,
      PID_PRESIDENTIAL_PASS,
      PID_RAMIREZ_BOX_CLOSED,
      PID_RAMIREZ_BOX_OPEN,
      PID_REACTOR_DATA_DISK,
      PID_RED_PASS_KEY,
      PID_RED_REACTOR_KEYCARD,
      PID_SMITTY_MEAL,
      PID_SPY_HOLO,
      PID_TANKER_FOB,
      PID_TRAPPER_TOWN_KEY,
      PID_V15_COMPUTER_PART,
      PID_VAULT_13_SHACK_KEY,
      PID_VERTIBIRD_PLANS,
      PID_VIC_RADIO,
      PID_VIC_WATER_FLASK,
      PID_WESTIN_HOLO,
      PID_YELLOW_PASS_KEY,
      PID_YELLOW_REACTOR_KEYCARD
   ];
end

#define MERCHANT_CRITICAL_ITEMS        critical_items_list_rpu


#endif
