#ifndef H_TALKING_HEADS_COMPAT
#define H_TALKING_HEADS_COMPAT

//Additional Head Defines from Talking Heads Mod, Black_Electric & Goat_Boy//
#define HEAD_LARAD          (15)
#define HEAD_DAVIN          (16)
#define HEAD_JOEYD          (17)
#define HEAD_DOGMT          (18)
#define HEAD_SLVTR          (19)
#define HEAD_ABSHP          (20)
#define HEAD_LBSHP          (21)
#define HEAD_LJMRD          (22)
#define HEAD_RBCCA          (23)
#define HEAD_MASON          (24)
#define HEAD_GRUTH          (25)
#define HEAD_MIRIA          (26)
#define HEAD_JOMOD          (27)
#define HEAD_VEGER          (28)
#define HEAD_JULES          (29)
#define HEAD_VCVAL          (30)
#define HEAD_MCCLR          (31)
#define HEAD_SALVA          (32)
#define HEAD_JENNY          (33)
#define HEAD_METZG          (34)
#define HEAD_ELISE          (35)
#define HEAD_BGJES          (36)
#define HEAD_BISHP          (37)
#define HEAD_WRITE          (38)
#define HEAD_MARIN          (39)
#define HEAD_ASCOR          (40)
#define HEAD_SKERI          (41)
#define HEAD_CHRSY          (42)
#define HEAD_AHS9H          (43)
#define HEAD_KENSF          (44)
#define HEAD_ARDIN          (45)
#define HEAD_TYPHN          (46)
#define HEAD_FRANC          (47)
#define HEAD_KLINT          (48)
#define HEAD_KITTY          (49)
#define HEAD_WEST           (50)
#define HEAD_SMILW          (51)
#define HEAD_SMILEY         (52)
#define HEAD_DARIO          (53)
#define HEAD_ROSE           (54)
#define HEAD_MOM            (55)
#define HEAD_GORIS          (56)
#define HEAD_VIC            (57)
#define HEAD_TYLER          (58)
#define HEAD_KIT            (59)
#define HEAD_LENNY          (60)
#define HEAD_DEX            (61)
#define HEAD_PHL            (62)
#define HEAD_CAT            (63)
#define HEAD_TROY           (64)
#define HEAD_RDOG           (65)
#define HEAD_DOGR           (66)
#define HEAD_HENRY          (67)
#define HEAD_SKY            (68)
#define HEAD_ABOTT          (69)
#define HEAD_CNR            (70)
#define HEAD_SCH            (71)
#define HEAD_BADGE          (72)
#define HEAD_SUZE           (73)
#define HEAD_BIRD           (74)
#define HEAD_MAIDA          (75)
#define HEAD_MARGE          (76)
#define HEAD_CHIEF          (77)
#define HEAD_FANNI          (78)
#define HEAD_FANNC          (79)
#define HEAD_DAN            (80)
#define HEAD_DOCJ           (81)
#define HEAD_LOU            (82)
#define HEAD_OBAD           (83)
#define HEAD_TULLY          (84)
#define HEAD_MARJ           (85)
#define HEAD_STARK          (86)
#define HEAD_STUL           (87)
#define HEAD_CAP            (88)
#define HEAD_LOPAN          (89)
#define HEAD_DRAGO          (90)
#define HEAD_AHS7           (91)
#define HEAD_VAJ            (92)
#define HEAD_WONG           (93)
#define HEAD_MAT            (94)
#define HEAD_LAO            (95)
#define HEAD_SLIM           (96)
#define HEAD_CHAD           (97)
#define HEAD_CHA2           (98)
#define HEAD_STEVE          (99)
#define HEAD_TORR           (100)
#define HEAD_SKEET          (101)
#define HEAD_WOOZ           (102)
#define HEAD_FEST           (103)
#define HEAD_GORD           (104)
#define HEAD_DALIA          (105)
#define HEAD_DAL13          (106)
#define HEAD_MERK           (107)
#define HEAD_EO             (108)
#define HEAD_CMDR           (109)
#define HEAD_QM             (110)
#define HEAD_QM2            (111)
#define HEAD_GRANI          (112)
#define HEAD_CAM            (113)
#define HEAD_ANNA           (114)
#define HEAD_PLANT          (115)
#define HEAD_MYNOC          (116)
#define HEAD_SHELA          (117)
#define HEAD_FRANK          (118)
#define HEAD_BARK           (119)
#define HEAD_GREG           (120)
#define HEAD_WALL           (121)
#define HEAD_LYDIA          (122)
#define HEAD_KAGA           (123)
#define HEAD_KEITH          (124)
#define HEAD_CHIP           (125)
#define HEAD_CW             (126)
#define HEAD_EW             (127)
#define HEAD_RB15           (128)
#define HEAD_ZEKE           (129)
#define HEAD_NIKKI          (130)
#define HEAD_ZOMAK          (131)
#define HEAD_SULLJ          (132)
#define HEAD_SULLA          (133)
#define HEAD_SULMA          (134)
#define HEAD_SULCA          (135)
#define HEAD_SULRO          (136)
#define HEAD_SULPA          (137)
#define HEAD_SULAP          (138)
#define HEAD_CASLJ          (139)
#define HEAD_CASMA          (140)
#define HEAD_CASCA          (141)
#define HEAD_CASRO          (142)
#define HEAD_CASPA          (143)
#define HEAD_CASAP          (144)
#define HEAD_MYRCA          (145)
#define HEAD_MYRRO          (146)
#define HEAD_MYRPA          (147)
#define HEAD_MYRAP          (148)
#define HEAD_CASUN          (149)
#define HEAD_BRAIN          (150)
#define HEAD_SMIT           (151)
#define HEAD_CURL           (152)
#define HEAD_JACOB          (153)
#define HEAD_ZAIUS          (154)
#define HEAD_DON            (155)
#define HEAD_DUM            (156)
#define HEAD_JIMMY          (157)
#define HEAD_SHAM           (158)
#define HEAD_KROM           (159)
#define HEAD_RENE           (160)
#define HEAD_KUR            (161)
#define HEAD_VORT           (162)
#define HEAD_SALLY          (163)
#define HEAD_GRISH          (164)
#define HEAD_BEN            (165)
#define HEAD_CORN           (166)
#define HEAD_FAR            (167)
#define HEAD_BAL            (168)
#define HEAD_LAD            (169)
#define HEAD_JONNY          (170)
#define HEAD_BMATT          (171)
#define HEAD_PET            (172)
#define HEAD_MERCH          (173)
#define HEAD_PAUL           (174)
#define HEAD_ANNVV          (175)
#define HEAD_HHARY          (176)
#define HEAD_QUIN           (177)
#define HEAD_RAUL           (178)
#define HEAD_XARN           (179)
#define HEAD_CHRIS          (180)
#define HEAD_MOORE          (181)
#define HEAD_IANOJ          (182)
#define HEAD_BUCK           (183)
#define HEAD_FLICK          (184)
#define HEAD_JONES          (185)
#define HEAD_TUBBY          (186)
#define HEAD_AMA            (187)
#define HEAD_ARIEL          (188)
#define HEAD_ANDR           (189)
#define HEAD_FUNG           (190)
#define HEAD_JUB            (191)
#define HEAD_HOL            (192)
#define HEAD_JOSEP          (193)
#define HEAD_MOR            (194)
#define HEAD_CERI           (195)
#define HEAD_RHEA           (196)
//#define HEAD_JONES          (197)
#define HEAD_HANGM          (198)
#define HEAD_BADG           (199)
#define HEAD_ELD            (200)
#define HEAD_TRAY           (201)
#define HEAD_ARTH           (202)
#define HEAD_BRIGE          (203)


variable talking_head_available;

#define talking_head_art_fid(headId)   (0x80A0000 bwor (headId bwand 0xFFF))
#define talking_head_exists(headId)    art_exists(talking_head_art_fid(headId))
#define start_gdialog_check_talking_head(reactLvl, headId, bgId) \
   if (talking_head_exists(headId)) then begin \
      talking_head_available := true; \
      start_gdialog(NAME, self_obj, reactLvl, headId, bgId); \
   end else \
      start_gdialog(NAME, self_obj, reactLvl, -1, -1)

#define Reply_THAT(talkingHeadReply, normalReply)      Reply(talkingHeadReply if talking_head_available else normalReply)

// #define debug_talking_head_art(headId)    display_msg(sprintf("Art: %x", talking_head_art_fid(headId))+", exist:"+art_exists(talking_head_art_fid(headId)));

#define start_dialog_at_node_check_talking_head(x, headId, bgId)  \
      if (in_dialog == false) then begin           \
         in_dialog := true;                        \
         start_gdialog_check_talking_head(4, headId, bgId); \
         gSay_Start;                               \
            call x;                                \
         gSay_End;                                 \
         end_dialogue;                             \
         in_dialog := false;                       \
      end else call x

#define check_forced_dialog_check_talking_head(headId, bgId)  \
      if (forced_node != 0) then begin          \
         ndebug("calling forced dialog: "+forced_node); \
         start_dialog_at_node_check_talking_head(forced_node, headId, bgId);     \
         forced_node := 0;                      \
      end

#endif // H_TALKING_HEADS_COMPAT
