# combat messages
# stealth
{100}{}{You caught %s off guard with unexpected attack.}

# boomerang
{120}{}{You manage to catch a %s on return.}

# destroy weapon - male
{200}{}{%s damaged his %s beyond repair.}
{201}{}{%s lost his %s in the heat of battle.}
{202}{}{%s shattered his %s to pieces while defending.}

# destroy weapon - female
{210}{}{%s damaged her %s beyond repair.}
{211}{}{%s lost her %s in the heat of battle.}
{212}{}{%s shattered her %s to pieces while defending.}


# first aid
{300}{}{ Restores %d-%d HP.}
{301}{}{ Restores %d HP.}
