# section categories (up to 12 can be defined and used)
{41}{}{Food}
{42}{}{First Aid}
{43}{}{Drugs}
{44}{}{Explosive}
{45}{}{Ammo}
{46}{}{Traps}
{47}{}{Armor}
{48}{}{Electronics}
{49}{}{Blades}
{50}{}{Weapons}
{51}{}{Misc}

# craft learning messages (used in scripts of teachers)
{81}{}{You have learned to make explosives.}
{82}{}{You have learned to make a crude armor from leather.}
{83}{}{You have learned to make first-aid drugs.}
{84}{}{You have optained recipes for several advanced drugs.}
{85}{}{You have obtained a schematics for some electronic devices.}
{86}{}{You have learned ways to make new types of ammo.}
{87}{}{You have learned to sharpen blades with a flint.}
{88}{}{You have obtained several food recipes.}
{89}{}{You think you can assemble a tool kit yourself.}
{90}{}{You have an idea of how to use those claws...}

# craft UI
{100}{}{[OK]}
{101}{}{[Quit]}
{102}{}{[Back]}
{103}{}{Make}
{104}{}{Dismantle}
{105}{}{[Next]}
{106}{}{[Prev]}
{107}{}{[No schematics]}
{108}{}{Make all}
{109}{}{Dismantle all}
{110}{}{ (}
{111}{}{ unit(s))}
{112}{}{[Categories]}
{120}{}{DONE}
{121}{}{Fix-Boy is not available in combat!}

{150}{}{ or }

{200}{}{Choose item to make.}
{201}{}{Item(s) crafted.}
{202}{}{Item(s) dismantled.}
{210}{}{Choose item category.}

{300}{}{[Tools]}
{301}{}{[Skills]}
{302}{}{[Components]}
{303}{}{No}
{304}{}{[Time]}
{305}{}{Hours: }
{306}{}{Minutes: }
{307}{}{%d h %d m}

{400}{}{Created: %s (%d). }
{401}{}{Dismantled: %s (%d). }
{402}{}{%d h %d m passed.}
{403}{}{ unit(s)). }
{404}{}{ h. }
{405}{}{ m. passed.}

{420}{}{You gain %d experience points for creating a new item.}
{430}{}{You have learned to make: %s.}
{431}{}{You already knew how to make: %s.}
