{100}{}{Leather Armor}
{101}{}{Your basic all leather apparel. Finely crafted from tanned brahmin hide.}
{200}{}{Metal Armor}
{201}{}{Polished metal plates, crudely forming a suit of armor.}
{300}{}{Power Armor}
{301}{}{A self-contained suit of advanced technology armor. Powered by a micro-fusion reactor, with enough fuel to last a hundred years.}
{400}{}{Knife}
{401}{}{A sharp-bladed cutting and stabbing weapon. Min ST: 2.}
{500}{}{Club}
{501}{}{A military or police baton. Heavy wood. Min ST: 3.}
{600}{}{Sledgehammer}
{601}{}{A large hammer with big handle. Very popular with the muscular crowd. Min ST: 6.}
{700}{}{Spear}
{701}{}{A razor tipped polearm. The shaft is wooden, and the tip is worked steel. Min ST: 4.}
{800}{}{10mm Pistol}
{801}{}{A Colt 6520 10mm autoloading pistol. Each pull of the trigger will automatically reload the firearm until the cylinder is empty. Single shot only, using the powerful 10mm round. Min ST: 3.}
{900}{}{10mm SMG}
{901}{}{H&K MP9 Submachinegun (10mm variant). A medium-sized SMG, capable of single shot and burst mode. Min ST: 4.}
{1000}{}{Hunting Rifle}
{1001}{}{A Colt Rangemaster semi-automatic rifle, in .223 caliber. Single-shot only. Min ST: 5.}
{1100}{}{Flamer}
{1101}{}{A Flambe 450 model flamethrower, varmiter variation. Fires a short spray of extremely hot, flammable liquid. Requires specialized fuel to work properly. Min ST: 6.}
{1200}{}{Minigun}
{1201}{}{A Rockwell CZ53 Personal Minigun. A multi-barreled chaingun firing 5mm ammunition at over 60,000 RPM. Min ST: 7.}
{1300}{}{Rocket Launcher}
{1301}{}{A Rockwell BigBazooka rocket launcher. With the deluxe 3 lb. trigger. Fires AP or Explosive Rockets. Min ST: 6.}
{1400}{}{Explosive Rocket}
{1401}{}{A rocket with a large explosive warhead.}
{1500}{}{Plasma Rifle}
{1501}{}{A Winchester Model P94 Plasma Rifle. An industrial-grade energy weapon, firing superheated bolts of plasma down a superconducting barrel. Powered by Micro Fusion Cells. Min ST: 6.}
{1600}{}{Laser Pistol}
{1601}{}{A Wattz 1000 Laser Pistol. Civilian model, so the wattage is lower than military or police versions. Uses small energy cells. Min ST: 3.}
{1700}{}{Combat Armor}
{1701}{}{High tech armor, made out of advanced defensive polymers.}
{1800}{}{Desert Eagle .44}
{1801}{}{An ancient Desert Eagle pistol, in .44 magnum. Interest in late 20th century films made this one of the most popular handguns of all times. Min ST: 4.}
{1900}{}{Rock}
{1901}{}{It's a rock. The Granite-Inc. model is an upgraded version. Min ST: 1.}
{2000}{}{Crowbar}
{2001}{}{A very solid and heavy piece of metal, specially designed to exert leverage. Or pound heads. Min ST: 5.}
{2100}{}{Brass Knuckles}
{2101}{}{Hardened knuckle grip that is actually made out of steel. They protect your hand, and do more damage, in unarmed combat. Min ST: 1.}
{2200}{}{14mm Pistol}
{2201}{}{A Sig-Sauer 14mm Auto Pistol. Large, single shot handgun. Excellent craftsmanship. Large caliber provides very high penetration. Min ST: 4.}
{2300}{}{Assault Rifle}
{2301}{}{An AK-112 5mm Assault Rifle. An old military model, out of use around the time of the war. Can fire single-shot or burst, using the high velocity 5mm rounds. Min ST: 5.}
{2400}{}{Plasma Pistol}
{2401}{}{Glock 86 Plasma Pistol. Designed by the Gaston Glock AI. Shoots a small bolt of superheated plasma. Powered by a small energy cell. Min ST: 4.}
{2500}{}{Grenade (Frag)}
{2501}{}{A generic fragmentation grenade. Contains a small amount of high explosives, the container itself forming most of the damaging fragments. Explodes on contact. Min ST: 3.}
{2600}{}{Grenade (Plasma)}
{2601}{}{A magnetically sealed plasma delivery unit, with detonating explosives. Creates a blast of superheated plasma on contact. Min ST: 4.}
{2700}{}{Grenade (Pulse)}
{2701}{}{An electromagnetic pulse grenade, generating an intense magnetic field on detonation. Doesn't affect biological creatures. Contact fuze. Min ST: 4.}
{2800}{}{Gatling Laser}
{2801}{}{An H&K L30 Gatling Laser. Designed specifically for military use, these were in the prototype stage at the beginning of the War. Multiple barrels allow longer firing before overheating. Powered by Micro Fusion Cells. Min ST: 6.}
{2900}{}{10mm JHP}
{2901}{}{Ammunition. Caliber: 10mm, jacketed hollow-points}
{3000}{}{10mm AP}
{3001}{}{Ammunition. Caliber: 10mm, armor piercing.}
{3100}{}{.44 Magnum JHP}
{3101}{}{A brick of ammunition, .44 magnum caliber, hollow-points.}
{3200}{}{Flamethrower Fuel}
{3201}{}{A cylinder containing an extremely flammable liquid fuel for flamethrowers.}
{3300}{}{14mm AP}
{3301}{}{Large caliber ammunition. 14mm armor piercing.}
{3400}{}{.223 FMJ}
{3401}{}{A case of ammunition, .223 caliber, Full Metal Jacket.}
{3500}{}{5mm JHP}
{3501}{}{A brick of small, lightweight ammunition. Caliber: 5mm, jacketed hollow-point.}
{3600}{}{5mm AP}
{3601}{}{A brick of small caliber ammunition. 5mm armor piercing.}
{3700}{}{Rocket AP}
{3701}{}{A rocket shell, with a smaller explosive, but designed to pierce armor plating.}
{3800}{}{Small Energy Cell}
{3801}{}{A small, self-contained energy storage unit.}
{3900}{}{Micro Fusion Cell}
{3901}{}{A medium sized energy production unit. Self-contained fusion plant.}
{4000}{}{Stimpak}
{4001}{}{A healing drug. When injected, the drug provides immediate healing of minor wounds.}
{4100}{}{Money}
{4101}{}{Legal tender for the world of the wastes.}
{4200}{}{Fridge}
{4201}{}{A refrigerator. Out of coolant.}
{4300}{}{Ice Chest}
{4301}{}{On old-style ice chest. The hinges are in good working condition.}
{4400}{}{Ice Chest}
{4401}{}{On old-style ice chest. The hinges are in good working condition.}
{4500}{}{Throwing Knife}
{4501}{}{A knife, balanced specifically for throwing. Made of titanium, and laser sharpened. Min ST: 3.}
{4600}{}{Bag}
{4601}{}{An average sized bag. Made from weaved brahmin hairs.}
{4700}{}{First Aid Kit}
{4701}{}{A small kit containing basic medical equipment. Bandages, wraps, antiseptic spray, and more.}
{4800}{}{RadAway}
{4801}{}{A chemical solution that bonds with radiation particles and passes them through your system. Takes time to work.}
{4900}{}{Antidote}
{4901}{}{A bottle containing a home-brewed antidote for poison. A milky liquid with floating pieces of radscorpion flesh.}
{5000}{}{Reserved Item}
{5001}{}{This is a reserved item. DO NOT USE.}
{5100}{}{Dynamite}
{5101}{}{A high explosive, consisting of nitroglycerin mixed with the absorbent substance kieselguhr. Includes a timer.}
{5200}{}{Geiger Counter}
{5201}{}{A Wattz Electronics C-Radz model Geiger Counter. Detects the presence and strength of radiation fields.}
{5300}{}{Mentats}
{5301}{}{A pillbox of mind-altering drugs. Increases memory related functions, and speeds other mental processes. Highly addictive.}
{5400}{}{Stealth Boy}
{5401}{}{A RobCo Stealth Boy 3001 personal stealth device. Generates a modulating field that transmits the reflected light from one side of an object to the other.}
{5500}{}{Water Chip}
{5501}{}{This is a Vault-Tec water chip. They are typically packaged in groups of five to a box.}
{5600}{}{Dog Tags}
{5601}{}{A set of military dog tags. The name Dickinson and the word Enclave are barely readable.}
{5700}{}{Bug}
{5701}{}{A miniature microphone and transmitting device.}
{5800}{}{Tape}
{5801}{}{A Wattz Electronics Holodisc tape. This particular tape looks to be into very poor condition.}
{5900}{}{Motion Sensor}
{5901}{}{A Wattz Electronics C-U model motion sensor. Detects the movement of biological material over a distance of meters using a tuned radar device. Having one in your inventory will also help you avoid outdoor encounters (+20% Outdoorsman skill).}
{6000}{}{Bookcase}
{6001}{}{A wooden bookcase.}
{6100}{}{Bookcase}
{6101}{}{A wooden bookcase.}
{6200}{}{Bookcase}
{6201}{}{A wooden bookcase.}
{6300}{}{Bookcase}
{6301}{}{A wooden bookcase.}
{6400}{}{Bookcase}
{6401}{}{A wooden bookcase.}
{6500}{}{Bookcase}
{6501}{}{A wooden bookcase.}
{6600}{}{Desk}
{6601}{}{A wooden desk.}
{6700}{}{Desk}
{6701}{}{A wooden desk.}
{6800}{}{Dresser}
{6801}{}{A wooden dresser.}
{6900}{}{Dresser}
{6901}{}{A wooden dresser.}
{7000}{}{Dresser}
{7001}{}{A wooden dresser.}
{7100}{}{Fruit}
{7101}{}{A strange piece of fruit. No preservatives and no additional food coloring added.}
{7200}{}{Briefcase}
{7201}{}{A briefcase, with a Made-in-the-USA label. Leather. Good condition, but the combination lock is broken.}
{7300}{}{Big Book of Science}
{7301}{}{A set of books, containing information about different scientific fields.}
{7400}{}{Leather Jacket}
{7401}{}{A black, heavy leather jacket.}
{7500}{}{Tool}
{7501}{}{A tool set, containing various useful tools, including pliers.}
{7600}{}{Deans Electronics}
{7601}{}{A study book on the field of electronics. A note on the cover says that it is for the "budding young electrician in everyone!"}
{7700}{}{Electronic Lockpick}
{7701}{}{A Wattz Electronics Micromanipulator FingerStuff electronic lockpick. For defeating electronic locks and security devices.}
{7800}{}{Fuzzy Painting}
{7801}{}{An image of a singer. Obviously, very old. The image has a felt coating that is still in good condition.}
{7900}{}{Flare}
{7901}{}{A flare. Creates light for a short period of time. The paper is a little worn, but otherwise it is in good condition. Twist the top to activate it.}
{8000}{}{First Aid Book}
{8001}{}{A study book on the concepts and practical use of first aid skills.}
{8100}{}{Iguana-on-a-stick}
{8101}{}{A cooked iguana, roasted in its own skin.}
{8200}{}{Key}
{8201}{}{A key. A key will open a particular lock.}
{8300}{}{Key Ring}
{8301}{}{Multiple keys.}
{8400}{}{Lockpicks}
{8401}{}{A set of locksmith tools. Includes all the necessary picks and tension wrenches to open conventional pin and tumbler locks.}
{8500}{}{Plastic Explosives}
{8501}{}{A chunk of Cordex, a military brand of plastic explosives. Highly stable, very destructive. Includes a timer.}
{8600}{}{Scout Handbook}
{8601}{}{A book on the methods and ideals of Scouting. Very practical information regarding outdoor life.}
{8700}{}{Buffout}
{8701}{}{Highly advanced steroids. While in effect, they increase strength and reflexes. Very addictive.}
{8800}{}{Watch}
{8801}{}{An expensive watch. Not really working, but it still looks nice.}
{8900}{}{Motor}
{8901}{}{A 40-hp electric motor.}
{9000}{}{Back Pack}
{9001}{}{A basic backpack, with optional carrying straps.}
{9100}{}{Doctor's Bag}
{9101}{}{This brown bag contains instruments and drugs used by doctors in the application of their trade.}
{9200}{}{Scorpion Tail}
{9201}{}{The severed tail of a radscorpion.}
{9300}{}{Bag}
{9301}{}{An average sized bag. Made from weaved Brahmin hairs.}
{9400}{}{Shotgun}
{9401}{}{A Winchester Widowmaker double-barreled 12-gauge shotgun. Short barrel, with mahogany grip. Min ST: 4.}
{9500}{}{12 ga. Buckshot}
{9501}{}{Shotgun ammunition, #00 buckshot. This particular ammo is marked: "12-gauge shells, not for use by children under the age of 3."}
{9600}{}{Red Pass Key}
{9601}{}{An electronic security key, color coded red.}
{9700}{}{Blue Pass Key}
{9701}{}{An electronic security key, color coded blue.}
{9800}{}{Junk}
{9801}{}{A pile of junk parts. A little bit of everything.}
{9900}{}{Gold Locket}
{9901}{}{A valuable gold locket.}
{10000}{}{Radio}
{10001}{}{A model 2043B Radio Communicator, from the fine people at Wattz Electronics. Dependable, rugged, and camouflaged. With the optional RS-121 interface.}
{10100}{}{Lighter}
{10101}{}{A silver butane lighter, in good condition.}
{10200}{}{Guns and Bullets}
{10201}{}{A gun rag. A magazine devoted to the practical use of firearms, and the occasional biased review.}
{10300}{}{Iguana-on-a-stick}
{10301}{}{Some charred meat and vegetables on a cooking stick.}
{10400}{}{Tape Recorder}
{10401}{}{A Wattz Electronics Play-It-For-Me tape recorder. Plays and records the standard 30 minute high density Record-It-Once tapes.}
{10500}{}{Key}
{10501}{}{A special key of some sort.}
{10600}{}{Nuka-Cola}
{10601}{}{A bottle of Nuka-Cola, the flavored softdrink of the post-nuclear world. Warm and flat.}
{10700}{}{Bones}
{10701}{}{A collection of strange bones.}
{10800}{}{Bones}
{10801}{}{A collection of strange bones.}
{10900}{}{Rad-X}
{10901}{}{Anti-radiation drugs to be taken before exposure. No known side effects.}
{11000}{}{Psycho}
{11001}{}{An unique delivery system filled with strange and unknown chemicals of probably military origin. It is supposed to increase the combat potential of a soldier.}
{11100}{}{.44 magnum FMJ}
{11101}{}{A brick of ammunition, .44 magnum caliber, full metal jacket.}
{11200}{}{Urn}
{11201}{}{A beautiful golden urn, with the name "Harriet" inscribed on the front and ashes inside.}
{11300}{}{Robes}
{11301}{}{Worn-looking robes.}
{11400}{}{Tangler's Hand}
{11401}{}{A cybernetic manipulator, in the shape and form of a hand. Damaged due to the sloppy nature of the removal process.}
{11500}{}{Super Sledge}
{11501}{}{A Super Sledgehammer, manufactured by the Brotherhood of Steel, using the finest weapons technology available. Includes a kinetic energy storage device, to increase knockback. Min ST: 5.}
{11600}{}{Ripper}
{11601}{}{A Ripper(tm) vibroblade. Powered by a small energy cell, the chainblade rips and tears into it's target. Min ST: 4.}
{11700}{}{Flower}
{11701}{}{A beautiful flower.}
{11800}{}{Laser Rifle}
{11801}{}{A Wattz 2000 Laser Rifle. Uses micro fusion cells for more powerful lasers, and an extended barrel for additional range. Min ST: 5.}
{11900}{}{Necklace}
{11901}{}{An expensive looking necklace, made from silver, gold and pressed diamonds.}
{12000}{}{Alien Blaster}
{12001}{}{A strange gun of obviously alien origin. Looks like it can support small energy cells, however. Min ST: 2.}
{12100}{}{9mm ball}
{12101}{}{A collection of ancient 9x19mm rounds. Heavy grease to preserve them from the environment. Standard bullets.}
{12200}{}{9mm Mauser}
{12201}{}{A Mauser M/96, in 9x19mm Parabellum. In excellent condition. Extremely accurate. Min ST: 3.}
{12300}{}{Psychic Nullifier}
{12301}{}{A strange device, constructed from an odd technology.}
{12400}{}{Beer}
{12401}{}{Some type of home brewed beer.}
{12500}{}{Booze}
{12501}{}{An ancient liquor, from the pre-War era.}
{12600}{}{Water Flask}
{12601}{}{A container for the holding and preservation of water or other liquids.}
{12700}{}{Rope}
{12701}{}{A strong, thick line. About 45 feet in length.}
{12800}{}{Footlocker}
{12801}{}{Your basic footlocker. Holds stuff, sits at foot of bed, can be locked.}
{12900}{}{Footlocker}
{12901}{}{Your basic footlocker. Holds stuff, sits at foot of bed, can be locked.}
{13000}{}{Footlocker}
{13001}{}{Your basic footlocker. Holds stuff, sits at foot of bed, can be locked.}
{13100}{}{Footlocker}
{13101}{}{Your basic footlocker. Holds stuff, sits at foot of bed, can be locked.}
{13200}{}{Locker}
{13201}{}{A storage container.}
{13300}{}{Locker}
{13301}{}{A storage container.}
{13400}{}{Locker}
{13401}{}{A storage container.}
{13500}{}{Locker}
{13501}{}{A storage container.}
{13600}{}{Locker}
{13601}{}{A storage container.}
{13700}{}{Locker}
{13701}{}{A storage container.}
{13800}{}{Locker}
{13801}{}{A storage container.}
{13900}{}{Locker}
{13901}{}{A storage container.}
{14000}{}{Access Card}
{14001}{}{A security access card. Still in working condition.}
{14100}{}{COC Badge}
{14101}{}{A badge in the shape of the Children of the Cathedral symbol. On one side you notice bumps and indentations, almost reminding you of a key.}
{14200}{}{COC Badge}
{14201}{}{A badge in the shape of the Children of the Cathedral symbol. On one side you notice bumps and indentations, almost reminding you of a key.}
{14300}{}{Sniper Rifle}
{14301}{}{A DKS-501 Sniper Rifle. Excellent long range projectile weapon. Chambered for powerful 7.62 caliber. Min ST: 5.}
{14400}{}{Super Stimpak}
{14401}{}{An advanced healing chem. Very powerful. Superstims will cause a small amount of damage after a period of time due to the powerful nature of the chemicals used.}
{14500}{}{Bookshelf}
{14501}{}{A wooden bookshelf.}
{14600}{}{Bookshelf}
{14601}{}{A wooden bookshelf.}
{14700}{}{Bookshelf}
{14701}{}{A wooden bookshelf.}
{14800}{}{Bookshelf}
{14801}{}{A wooden bookshelf.}
{14900}{}{Bookshelf}
{14901}{}{A wooden bookshelf.}
{15000}{}{Bookshelf}
{15001}{}{A wooden bookshelf.}
{15100}{}{Shelves}
{15101}{}{A set of wooden shelves.}
{15200}{}{Shelves}
{15201}{}{A set of wooden shelves.}
{15300}{}{Shelves}
{15301}{}{A set of wooden shelves.}
{15400}{}{Shelves}
{15401}{}{A set of wooden shelves.}
{15500}{}{Shelves}
{15501}{}{A set of wooden shelves.}
{15600}{}{Shelves}
{15601}{}{A set of wooden shelves.}
{15700}{}{Workbench}
{15701}{}{A workbench. Yep, your standard old, run of the mill, workbench. Looks nice sitting there, too.}
{15800}{}{Tool Board}
{15801}{}{This board holds a variety of tools above the popular workbench.}
{15900}{}{Molotov Cocktail}
{15901}{}{A home-made flammable grenade. Min ST: 3.}
{16000}{}{Cattle Prod}
{16001}{}{A Farmer's Best Friend model cattle prod from Wattz Electronics. Uses small energy cells for power. Min ST: 4.}
{16100}{}{Red Ryder BB Gun}
{16101}{}{A Red Ryder BB gun. The classic. Min ST: 3.}
{16200}{}{Red Ryder LE BB Gun}
{16201}{}{A limited edition version of the Red Ryder BB gun. A true classic. Min ST: 3.}
{16300}{}{BB's}
{16301}{}{A package of BB's from before the war. In excellent condition. Stainless steel.}
{16400}{}{Brotherhood Tape}
{16401}{}{A holodisc from regarding the Brotherhood of Steel.}
{16500}{}{Iguana Stand}
{16501}{}{The home of Bob's Iguana Bits. What's not to love about fresh-roasted iguana?}
{16600}{}{Table}
{16601}{}{A generic table. Holds stuff off the ground.}
{16700}{}{Table}
{16701}{}{A generic table. Holds stuff off the ground.}
{16800}{}{Stuff}
{16801}{}{These are miscellaneous items, also known as "stuff".}
{16900}{}{Stuff}
{16901}{}{These are miscellaneous items, also known as "stuff".}
{17000}{}{Stuff}
{17001}{}{These are miscellaneous items, also known as "stuff".}
{17100}{}{Stuff}
{17101}{}{These are miscellaneous items, also known as "stuff".}
{17200}{}{Stuff}
{17201}{}{These are miscellaneous items, also known as "stuff".}
{17300}{}{Stuff}
{17301}{}{These are miscellaneous items, also known as "stuff".}
{17400}{}{Stuff}
{17401}{}{These are miscellaneous items, also known as "stuff".}
{17500}{}{Stuff}
{17501}{}{These are miscellaneous items, also known as "stuff".}
{17600}{}{Stuff}
{17601}{}{These are miscellaneous items, also known as "stuff".}
{17700}{}{Stuff}
{17701}{}{These are miscellaneous items, also known as "stuff".}
{17800}{}{Stuff}
{17801}{}{These are miscellaneous items, also known as "stuff".}
{17900}{}{Stuff}
{17901}{}{These are miscellaneous items, also known as "stuff".}
{18000}{}{Crate}
{18001}{}{A wooden crate filled with generic stuff.}
{18100}{}{Desk}
{18101}{}{A generic desk. Seen one desk, you've seen them all.}
{18200}{}{Desk}
{18201}{}{A generic desk.}
{18300}{}{Desk}
{18301}{}{A generic desk.}
{18400}{}{Desk}
{18401}{}{A generic desk.}
{18500}{}{Desk}
{18501}{}{A generic desk.}
{18600}{}{Desk}
{18601}{}{A generic desk.}
{18700}{}{Desk}
{18701}{}{A generic desk.}
{18800}{}{Locker}
{18801}{}{A locker.}
{18900}{}{Locker}
{18901}{}{A locker.}
{19000}{}{FEV Disk}
{19001}{}{A holotape containing medical information. Can be used to enter information into your Pip-Boy.}
{19100}{}{Security Disk}
{19101}{}{A holotape with the writing "Security Log" on the label. You can use it to transfer the data it contains to your Pip-Boy.}
{19200}{}{Alpha Experiment Disk}
{19201}{}{The label on this holotape reads: "Alpha Experiment Log"}
{19300}{}{Delta Experiment Disk}
{19301}{}{The label on this holotape reads: "Delta Experiment Log"}
{19400}{}{Vree's Experiment Disk}
{19401}{}{This holotape has been updated with medical evidence from Vree of the BoS. It can be used to transfer the data to your Pip-Boy.}
{19500}{}{Brotherhood Honor Code}
{19501}{}{A holotape, with a rough symbol of the Brotherhood of Steel inscribed on it. Use the tape to transfer the data to your Pip-Boy.}
{19600}{}{Mutant Transmissions}
{19601}{}{This holotape looks like it was set to record audio data from a radio. Use the tape to transfer the information to your Pip-Boy.}
{19700}{}{Box}
{19800}{}{Box}
{19900}{}{Box}
{20000}{}{Box}
{20100}{}{Box}
{20200}{}{Box}
{20300}{}{Box}
{20400}{}{Box}
{20500}{}{Flare}
{20501}{}{A flare. Creates light for a short period of time. The paper is a little worn, but otherwise it is in good condition. It is lit.}
{20600}{}{Dynamite}
{20601}{}{A high explosive, consisting of nitroglycerin mixed with the absorbent substance kieselguhr. Includes a timer, which is ticking.}
{20700}{}{Geiger Counter}
{20701}{}{A Wattz Electronics C-Radz model Geiger Counter. Detects the presence and strength of radiation fields. It is on.}
{20800}{}{Motion Sensor}
{20801}{}{A Wattz Electronics C-U model motion sensor. Detects the movement of biological material over a distance of meters using a tuned radar device. It is on.}
{20900}{}{Plastic Explosives}
{20901}{}{A chunk of Cordex, a military brand of plastic explosives. Highly stable, very destructive. Includes a timer, which is ticking.}
{21000}{}{Stealth Boy}
{21001}{}{A RobCo Stealth Boy 3001 personal stealth device. Generates a modulating field that transmits the reflected light from one side of an object to the other.}
{21100}{}{Bones}
{21101}{}{You see Ed. Ed's dead.}
{21200}{}{Tandi}
{21201}{}{You are bartering for Tandi's release.}
{21300}{}{Remains of Gizmo}
{21301}{}{Gizmo, former crime boss of Junktown, is dead. And pretty stinky, too.}
{21400}{}{Desk}
{21401}{}{A desk. After further observation, you decide that it is still a desk.}
{21500}{}{Brotherhood History}
{21501}{}{A holotape containing information relating to the Brotherhood of Steel. Can be used to enter information into your Pip-Boy 2000.}
{21600}{}{Maxson's History}
{21700}{}{Maxson's Journal}
{21800}{}{Light Healing}
{21801}{}{Barter for this option if you want light healing.}
{21900}{}{Medium Healing}
{21901}{}{Barter for this option if you want medium healing.}
{22000}{}{Heavy Healing}
{22001}{}{Barter for this option if you want lots of care and heavy healing.}
{22100}{}{Security Card}
{22101}{}{A keycard with a security level encoded within it's very simple electronics.}
{22200}{}{Field Switch}
{22201}{}{An electronic transmission device, with a very simple, and large, toggle button. It looks like it was recently made and designed for very large hands.}
{22300}{}{Yellow Pass Key}
{22301}{}{An electronic security key, color coded yellow.}
{22400}{}{Small Statuette}
{22401}{}{You think this might be a carving of the "Pip-Boy" but you can't be sure.}
{22500}{}{Cat's Paw Magazine}
{22501}{}{An issue of Cat's Paw magazine.}
{22600}{}{Box Of Noodles}
{22601}{}{You have no idea what "Instant Spaghetti" means.}
{22700}{}{Small Dusty Box Of Some Sort}
{22701}{}{A television dinner. You're not sure, but it's definitely not edible. You're not quite sure if it ever was.}
{22800}{}{Technical Manual}
{22801}{}{A technical repair manual on the T-51b Power Armor.}
{22900}{}{Small Piece Of Machinery}
{22901}{}{Some mechanical component for a machine. If a machine is missing one of these, then it's a safe bet it isn't working properly.}
{23000}{}{Vault Records}
{23001}{}{A compendium of events and important recordings from a Vault computer system. Possibly damaged.}
{23100}{}{Military Base Security Code}
{23101}{}{}
{23200}{}{Hardened Power Armor}
{23201}{}{A suit of T-51b Power Armor. The hardening process has improved the defensive capability of this high-tech armor system.}
{23300}{}{Turbo Plasma Rifle}
{23301}{}{A modified Winchester P94 plasma rifle. The plasma bolt chamber has been hotwired to accelerate the bolt formation process. Min ST: 6.}
{23400}{}{Spiked Knuckles}
{23401}{}{An improved version of the classic Brass Knuckles. The Spiked Knuckles do more damage, tearing into the flesh of your opponent in unarmed combat. Min ST: 1.}
{23500}{}{Power Fist}
{23501}{}{A "Big Frigger" Power Fist from BeatCo. Considered by many to be the ultimate weapon to use in unarmed combat. Others are just scared. Powered by small energy cells. Min ST: 1.}
{23600}{}{Combat Knife}
{23601}{}{A high-quality combat knife, the Stallona is from SharpWit, Inc. The edge of this blade is guaranteed sharp for over a decade of use! Min ST: 2.}
{23700}{}{Chemistry Journals}
{23701}{}{A random pile of literature regarding the field of Chemistry. The papers on Molecular Chemistry are particularly interesting.}
{23800}{}{Regulator Transmission}
{23801}{}{A holotape recording of an audio transmission.}
{23900}{}{Brotherhood Armor}
{23901}{}{A superior version of Combat Armor. The Brotherhood of Steel have made many improvements over the standard version.}
{24000}{}{Tesla Armor}
{24001}{}{This shining armor provides superior protection against energy attacks. The three Tesla Attraction Coil Rods disperse a large percentage of directed energy attacks. Superb protection against laser weapons.}
{24100}{}{.223 Pistol}
{24101}{}{A .223 rifle modified and cut down to a pistol. This is a one-of-a-kind firearm, obviously made with love and skill. Min ST: 5.}
{24200}{}{Combat Shotgun}
{24201}{}{A Winchester City-Killer 12-gauge combat shotgun, bullpup variant. In excellent condition, it has the optional DesertWarfare environmental sealant modification for extra reliability. Min ST: 5.}
{24300}{}{Pot}
{24301}{}{A finely crafted clay pot.}
{24400}{}{Pot}
{24401}{}{A finely crafted clay pot.}
{24500}{}{Chest}
{24501}{}{A wooden chest.}
{24600}{}{Shelf}
{24601}{}{A wood shelf with miscellaneous items.}
{24700}{}{Shelf}
{24701}{}{A wood shelf with miscellaneous items.}
{24800}{}{Pot}
{24801}{}{A finely crafted clay pot.}
{24900}{}{Pot}
{24901}{}{A finely crafted clay pot.}
{25000}{}{Bones}
{25001}{}{A pile of human bones.}
{25100}{}{Anna's Bones}
{25101}{}{These bones seem unsettled.}
{25200}{}{Anna's Gold Locket}
{25201}{}{This well-worn golden locket opens to reveal a charming picture.}
{25300}{}{Fuel Cell Controller}
{25301}{}{This chip controls the flow of power into a car's electric engines. Many drivers quickly burnt out this chip through frequent rapid acceleration. Still a valuable part to have-- if you only had a car to install it in.}
{25400}{}{Fuel Cell Regulator}
{25401}{}{Some car-owners installed this regulator, which doubles your car's mileage between charges, but most drivers didn't care how much juice their cars consumed, after all, power's cheap and plentiful so why worry?}
{25500}{}{Day Pass}
{25501}{}{This slightly crumpled piece of paper grants you access to all areas of Vault City, except the Vault itself, during daylight hours only.}
{25600}{}{False Citizenship Papers}
{25601}{}{This is a set of false Citizenship Papers. They look authentic enough, but you doubt they could pass a serious inspection.}
{25700}{}{Cornelius' Gold Watch}
{25701}{}{This is an ancient time-piece known as a pocket watch. Time ran out for this keepsake, many long years ago.}
{25800}{}{Hydroelectric Part}
{25801}{}{This is a Hydroelectric Magnetosphere Regulator.}
{25900}{}{Jet}
{25901}{}{Jet is a powerful methamphetamine that stimulates the central nervous system. The initial euphoric rush rarely lasts more than a few minutes, but during that time, the user is filled with a rush of energy & strength.}
{26000}{}{Jet Antidote}
{26001}{}{This antidote cures the Jet addiction.}
{26100}{}{Jonny's BB Gun}
{26101}{}{A Red Ryder BB gun with the name 'Jonny' scratched on the stock. Min ST: 3.}
{26200}{}{Rubber Boots}
{26201}{}{An old pair of sturdy rubber work boots. They look durable enough to keep out sludge, at least for a while.}
{26300}{}{Slag Message}
{26301}{}{This is a message from the leader of the Slags to the townspeople of Modoc.}
{26400}{}{Smith's Cool Item}
{26401}{}{LONG DESCRIPTION HERE.}
{26500}{}{Combat Leather Jacket}
{26501}{}{This heavily padded leather jacket is unusual in that it has two sleeves. You'll definitely make a fashion statement whenever, and wherever, you rumble.}
{26600}{}{Vic's Radio}
{26601}{}{This hand-held radio doesn't work but it looks as though it's still in pretty good condition. Some of its parts could probably be salvaged for use in other radios.}
{26700}{}{Vic's Water Flask}
{26701}{}{This relic of the Vault was probably used to contain some sacred sacrament. The Holy number 13 is emblazoned on the side of this precious link to your people's past, and hopeful future.}
{26800}{}{H&K CAWS}
{26801}{}{The CAWS, short for Close Assault Weapons System, shotgun is a useful tool for close-range combat. The bullpup layout gives the weapon a short, easily handleable, length while still retaining enough barrel length for its high velocity shells. Min ST: 6.}
{26900}{}{Robot Parts}
{26901}{}{A pile of damaged robot parts.}
{27000}{}{Robo Rocket Launcher}
{27001}{}{Only used by rocket equipped robots.}
{27100}{}{Broc Flower}
{27101}{}{The plentiful flower that forms the base for the powder of healing.}
{27200}{}{Xander Root}
{27201}{}{The rare root that gives healing properties to the powder of healing.}
{27300}{}{Healing Powder}
{27301}{}{A very powerful healing magic- though it will bring the feeling of sleep to your head.}
{27400}{}{Robo Rocket Ammo}
{27401}{}{Only used by rocket equipped robots.}
{27500}{}{Trophy of Recognition}
{27501}{}{A solid gold trophy with the inscription "To: Dave, From: DC's, For: Being a Special Person."}
{27600}{}{Gecko Pelt}
{27601}{}{This is the dried and cured hide of a Gecko.}
{27700}{}{Golden Gecko Pelt}
{27701}{}{This is the dried and cured hide of a Golden Gecko.}
{27800}{}{Flint}
{27801}{}{A stone used to sharpen weapons.}
{27900}{}{Neural Interface}
{27901}{}{It appears to be a set of electrodes built into a head unit with a standard computer interface plug. It's broken, however.}
{28000}{}{Sharpened Spear}
{28001}{}{A razor tipped polearm. The shaft is wooden, and the tip is sharpened steel. Min ST: 4.}
{28100}{}{Dixon's Eye}
{28101}{}{A small jar containing a human eye suspended in some kind of liquid. The label says Corporal Dixon.}
{28200}{}{Clifton's Eye}
{28201}{}{A small jar containing a human eye suspended in some kind of liquid. The label says General Clifton.}
{28300}{}{Tommy Gun}
{28301}{}{This Thompson M1928 submachine gun is a sinister looking weapon; every time you hold it, you have an urge to put on a fedora hat and crack your knuckles. The Thompson is well-fed by a large 50 round drum magazine. Min ST: 6.}
{28400}{}{Meat Jerky}
{28401}{}{These smoked and dried chunks of beast-flesh remain chewy-licious and even somewhat nutritious for years, and years, and years....}
{28500}{}{Radscorpion Limbs}
{28501}{}{These Radscorpion pincers are hollowed out and have a strap with a broken buckle at the end.}
{28600}{}{Firewood}
{28601}{}{A pile of firewood and kindling.}
{28700}{}{Scoped Hunting Rifle}
{28701}{}{Nothing's better than seeing that surprised look on your target's face. The Loophole x20 Scope on this hunting rifle makes it easier than ever before. Accurate from first shot to last, no matter what kind of game you're gunning for. Min ST: 5.}
{28800}{}{Car Fuel Cell}
{28801}{}{A car fuel cell.}
{28900}{}{Shovel}
{28901}{}{This is a shovel for digging ditches and stuff.}
{29000}{}{Robo Melee Weapon 1}
{29001}{}{For Floating Eye Robot. Does Electrical Damage.}
{29100}{}{Robo Melee Weapon 2}
{29101}{}{For Floating Eye Robot. Does Electrical damage.}
{29200}{}{Boxing Gloves}
{29201}{}{A pair of boxing gloves that smell faintly of sweat. They look like they have seen a lot of use: many old blood stains still remain.}
{29300}{}{Plated Boxing Gloves}
{29301}{}{Someone has "accidentally" slipped metal plates into these boxing gloves. It could technically be considered cheating, but you prefer to think of it as an increased opportunity to dispense bone-crunching damage.}
{29400}{}{Vault 13 Holodisk}
{29401}{}{A holodisk which supposedly has the location of Vault 13.}
{29500}{}{Cheezy Poofs}
{29501}{}{A box of cheese flavored puffs. They are extremely good.}
{29600}{}{H&K P90c}
{29601}{}{The Heckler & Koch P90c was just coming into use at the time of the war. The weapon's bullpup layout, and compact design, make it easy to control. The durable P90c is prized for its reliability, and high firepower in a ruggedly-compact package. Min ST: 4.}
{29700}{}{Metal Pole}
{29701}{}{It's a long metal pole. What did you expect?}
{29800}{}{Trapper Town Key}
{29801}{}{A standard key.}
{29900}{}{Pipe Rifle}
{29901}{}{This is a hand-made single shot rifle. Min ST: 5.}
{30000}{}{Zip Gun}
{30001}{}{A handmade single shot pistol. Min ST: 4.}
{30100}{}{Clipboard}
{30101}{}{This is a clipboard with the coolant report.}
{30200}{}{Gecko Holodisk}
{30201}{}{The label on this holotape reads: "Gecko Economic Data." It's difficult to interpret most of the technical charts, tables, and formulae here, but the majority of the information seems to highlight the advantages of a Vault City -- Gecko alliance.}
{30300}{}{Reactor Holodisk}
{30301}{}{The label on this holotape reads: "Gecko Reactor Performance Data." This disk contains a string of numbers that mean nothing to you. There sure is a lot of information here and it must be important to someone, somehow.}
{30400}{}{Deck of "Tragic" Cards}
{30401}{}{This is a deck of cards for a collectible card game. Looks like it could be an expensive hobby if you got hooked.}
{30500}{}{Yellow Reactor Keycard}
{30501}{}{An electronic security key, color coded yellow.}
{30600}{}{Red Reactor Keycard}
{30601}{}{An electronic security key, color coded red.}
{30700}{}{Plasma Transformer}
{30701}{}{This is a Three-step Plasma Transformer.}
{30800}{}{Super Tool Kit}
{30801}{}{An impressive tool set made by "Snap-Off".}
{30900}{}{Talisman}
{30901}{}{A talisman which is worn by followers of The Brain.}
{31000}{}{Gamma Gulp Beer}
{31001}{}{A bottle of Gamma Gulp beer. It glows in the dark!}
{31100}{}{Roentgen Rum}
{31101}{}{A bottle of Roentgen rum. It glows in the dark!}
{31200}{}{Part Requisition Form}
{31201}{}{This is a Part Requisition Request form.}
{31300}{}{.44 Magnum Revolver}
{31301}{}{Being that this is the most powerful handgun in the world, and can blow your head clean-off, you've got to ask yourself one question. Do I feel lucky? Well, do ya punk?. Min ST: 5.}
{31400}{}{Condom (Blue Package)}
{31401}{}{This is a Jimmy Hats brand condom, a very reliable brand. This one is ribbed for her pleasure.}
{31500}{}{Condom (Green package)}
{31501}{}{This is a Jimmy Hats brand condom, a very reliable brand. This one contains phosphorous green dye #2 and is slathered in spermicidal lubricant for added protection.}
{31600}{}{Condom (Red Package)}
{31601}{}{This is a Jimmy Hats brand condom, a very reliable brand. This one contains phosphorous red dye #5 and has a yummy cinnamon bun flavor... or so you heard.}
{31700}{}{Cosmetics Case}
{31701}{}{This is a genuine Mary May brand cosmetics case.}
{31800}{}{Empty Hypodermic}
{31801}{}{This is an empty hypodermic.}
{31900}{}{Switchblade}
{31901}{}{The blade of this small knife is held by a spring. When a button on the handle is pressed, the blade shoots out with a satisfying "Sssssshk" sound. Min ST: 1.}
{32000}{}{Sharpened Pole}
{32001}{}{A wood pole sharpened at one end. Min ST: 4.}
{32100}{}{Cybernetic Brain}
{32101}{}{A human brain that has been enhanced by the addition of electronic and robotic attachments.}
{32200}{}{Human Brain}
{32201}{}{A typical human brain. Normally they are found in human skulls. Yuck.}
{32300}{}{Chimpanzee Brain}
{32301}{}{A monkey brain. It's soft and squishy.}
{32400}{}{Abnormal Brain}
{32401}{}{Quite possibly a human brain. The color doesn't seem quite right and the left hemisphere of the brain has caved in on itself.}
{32500}{}{Dice}
{32501}{}{A standard pair of gambling dice. It'd be cool to get a fuzzy pair for your car.}
{32600}{}{Loaded Dice}
{32601}{}{A pair of loaded dice. Don't be flashing these around the casino.}
{32700}{}{Easter Egg}
{32701}{}{This is a hard boiled chicken egg painted with colored dyes.}
{32800}{}{Magic 8-Ball}
{32801}{}{This black sphere is some strange precognitive device... a small window on the top seems to be able to predict the future! Pre-war humanity must have been geniuses to invent such a wonder!}
{32900}{}{Mutagenic Serum}
{32901}{}{A strange organic concoction that could possibly reverse the Mutation Factor in humans.}
{33000}{}{Crashed Verti-Bird}
{33001}{}{This is wreckage from a verti-bird. Looks like it crashed here months ago.}
{33100}{}{Cat's Paw Issue #5}
{33101}{}{This is the hard to find Issue 5 of Cat's Paw magazine. The pictures aside, this issue has a wonderful article on energy weapons.}
{33200}{}{M3A1 "Grease Gun" SMG}
{33201}{}{This submachine gun filled National Guard arsenals after the Army replaced it with newer weapons. However, the "Grease Gun" was simple and cheap to manufacture so there are still quite a few still in use. Min ST: 4.}
{33300}{}{Heart Pills}
{33301}{}{These pills are used by people with heart problems.}
{33400}{}{Poison}
{33401}{}{A hypodermic needle full of powerful poison.}
{33500}{}{Moore's Briefcase}
{33501}{}{Thomas Moore asked you to take this brahmin hide briefcase to the Bishop family in New Reno. It is securely locked, and you can't seem to open it.}
{33600}{}{Moore's Briefcase}
{33601}{}{Thomas Moore asked you to take this brahmin hide briefcase to the Bishop family in New Reno. It is securely locked, and you can't seem to open it.}
{33700}{}{Lynette Holodisk}
{33701}{}{This is the holodisk you got from Lynette.}
{33800}{}{Westin Holodisk}
{33801}{}{This is the holodisk you got from Westin.}
{33900}{}{NCR Spy Holodisk}
{33901}{}{This holodisk contains reports of NCR caravan schedules and security information. It's addressed to Darion and signed "F". With this info, it's easy to see how the raiders have avoided capture.}
{34000}{}{Doctor's Papers}
{34001}{}{A set of very detailed plans for a Cybernetic Canine Guard Unit. With this and the right facilities, a person just might be able to build a robo-dog.}
{34100}{}{Presidential Pass}
{34101}{}{The bearer of this document is Security Clearance A-Prime as authorized by the authority of the President of the New California Republic. It's signed by President Tandi.}
{34200}{}{Ranger Pin}
{34201}{}{This pin says you're an official New California Ranger. Look -- it's got a code wheel and everything!}
{34300}{}{Ranger's Map}
{34301}{}{A map of the surrounding area -- it won't help you much -- but there are code names on it for the Ranger safe houses in the north.}
{34400}{}{Gravesite}
{34500}{}{Gravesite}
{34600}{}{Gravesite}
{34700}{}{Gravesite}
{34701}{}{}
{34800}{}{Advanced Power Armor}
{34801}{}{This powered armor is composed of lightweight metal alloys, reinforced with ceramic castings at key points. The motion-assist servo-motors appear to be high quality models as well. The user is vulnerable to EMP attacks.}
{34900}{}{Adv. Power Armor MKII}
{34901}{}{This powered armor appears to be composed of entirely of lightweight ceramic composites rather than the usual combination of metal and ceramic plates. It seems as though it should give even more protection than the standard Advanced Power Armor.}
{35000}{}{Bozar AMR}
{35001}{}{Anti-materiel rifle. The ultimate refinement of the sniper's art. Although, somewhat finicky and prone to jamming if not kept scrupulously clean, the big weapon's accuracy more than makes up for its extra maintenance requirements. Min ST: 7.}
{35100}{}{FN FAL}
{35101}{}{This rifle has been more widely used by armed forces than any other rifle in history. It's a reliable assault weapon for any terrain or tactical situation. Min ST: 5.}
{35200}{}{H&K G11}
{35201}{}{This gun revolutionized assault weapon design. The weapon fires a caseless cartridge consisting of a block of propellant with a bullet buried inside. The resultant weight and space savings allow this weapon to have a very high magazine capacity. Min ST: 5.}
{35300}{}{XL70E3}
{35301}{}{This was an experimental weapon at the time of the war. Manufactured, primarily, from high-strength polymers, the weapon is almost indestructible. It's light, fast firing, accurate, and can be broken down without the use of any tools. Min ST: 5.}
{35400}{}{Pancor Jackhammer}
{35401}{}{The Jackhammer, despite its name, is an easy to control shotgun, even when fired on full automatic. The popular bullpup design, which places the magazine behind the trigger, makes the weapon well balanced & easy to control. Min ST: 5.}
{35500}{}{Light Support Weapon}
{35501}{}{This squad-level support weapon has a bullpup design. The bullpup design makes it difficult to use while lying down. Because of this it was remanded to National Guard units. It, however, earned a reputation as a reliable weapon that packs a lot of punch for its size. Min ST: 6.}
{35600}{}{Computer Voice Module}
{35601}{}{A circuit board with several unidentifiable parts, a microphone, and an inscription that reads "Vault-Tec Voice Recognition Module."}
{35700}{}{.45 Caliber}
{35701}{}{Ammunition. .45 Caliber.}
{35800}{}{2mm EC}
{35801}{}{Ammunition.}
{35900}{}{4.7mm Caseless}
{35901}{}{Ammunition. Caliber: 4.7mm, caseless.}
{36000}{}{9mm AP}
{36001}{}{A collection of ancient 9x19mm rounds. Heavy grease to preserve them from the environment. Armor piercing bullets.}
{36100}{}{HN Needler Cartridge}
{36101}{}{Ammunition. This cartridge appears to be ammo for the HN Needler Pistol. Each 'bullet' is a small hypodermic designed to inject a target with its contents upon impact.}
{36200}{}{HN AP Needler Cartridge}
{36201}{}{Ammunition. This cartridge appears to be armor-piercing ammo for the HN Needler Pistol. The hypodermic tips are made of a strange alloy and are incredibly sharp.}
{36300}{}{7.62mm FMJ}
{36301}{}{Ammunition. Caliber: 7.62mm, full metal jacket.}
{36400}{}{Robot Motivator}
{36401}{}{This is the drive mechanism for a robot.}
{36500}{}{Plant Spike}
{36501}{}{An organic seed-spike that the carnivorous plants spit at potential food or seed carriers.}
{36600}{}{G.E.C.K.}
{36601}{}{The Garden of Eden Creation Kit. This unit is standard equipment for all Vault-Tec vaults. A GECK is the resource for rebuilding civilization after the bomb. Just add water and stir.}
{36700}{}{Ammo Crate}
{36800}{}{Ammo Crate}
{36900}{}{Ammo Crate}
{37000}{}{Ammo Crate}
{37100}{}{Claw}
{37101}{}{Claw}
{37200}{}{Claw}
{37201}{}{Claw}
{37300}{}{Vault 15 Keycard}
{37301}{}{An electronic security key, color coded red.}
{37400}{}{Gravesite}
{37500}{}{Gravesite}
{37600}{}{Gravesite}
{37700}{}{Vault 15 Computer Parts}
{37701}{}{Miscellaneous computer parts with various functions. A computer geek's dream.}
{37800}{}{Cookie}
{37801}{}{A chocolate chip cookie. Yum!}
{37900}{}{Leather Armor Mark II}
{37901}{}{An enhanced version of the basic leather armor with extra layers of protection. Finely crafted from tanned brahmin hide.}
{38000}{}{Metal Armor Mark II}
{38001}{}{Polished metal plates, finely crafted into a suit of armor.}
{38100}{}{Combat Armor Mark II}
{38101}{}{High tech armor, made out of advanced defensive polymers.}
{38200}{}{Flamethrower Fuel MKII}
{38201}{}{This flamethrower fuel uses an advanced super-burn mix.}
{38300}{}{Shiv}
{38301}{}{This home-made knife is as dangerous as it is easily concealed. Its presence can't be detected by others. Min ST: 1.}
{38400}{}{Wrench}
{38401}{}{A typical wrench used by mechanics. Min ST: 3.}
{38500}{}{Sawed-Off Shotgun}
{38501}{}{Someone took the time to chop the last few inches off the barrel and stock of this shotgun. Now, the wide spread of this hand-cannon's short-barreled shots makes it perfect for short-range crowd control. Min ST: 4.}
{38600}{}{Louisville Slugger}
{38601}{}{This all-American, hardwood, baseball bat will knock anything right out of the park. Min ST: 4.}
{38700}{}{M60}
{38701}{}{This relatively light machine gun was prized by militaries around the world for its high rate of fire. This reliable, battlefield-proven design, was used on vehicles and for squad level fire-support. Min ST: 7.}
{38800}{}{Needler Pistol}
{38801}{}{You suspect this Bringham needler pistol was once used for scientific field studies. It uses small hard-plastic hypodermic darts as ammo. Min ST: 3.}
{38900}{}{Avenger Minigun}
{38901}{}{Rockwell designed the Avenger as the replacement for their aging CZ53 Personal Minigun. The Avenger's design improvements include improved, gel-fin, cooling and chromium plated barrel-bores. This gives it a greater range and lethality. Min ST: 7.}
{39000}{}{Solar Scorcher}
{39001}{}{Without the sun's rays to charge this weapon's capacitors this gun can't light a match. However, in full daylight, the experimental photo-electric cells that power the Scorcher allow it to turn almost anything into a crispy critter. Min ST: 3.}
{39100}{}{H&K G11E}
{39101}{}{This gun revolutionized squad level support weapon design. The gun fires a caseless cartridge consisting of a block of propellant with a bullet buried inside. The resultant weight and space savings allow it to have a very high magazine capacity. Min ST: 6.}
{39200}{}{M72 Gauss Rifle}
{39201}{}{The M72 rifle is of German design. It uses an electromagnetic field to propel rounds at tremendous speed... and pierce almost any obstacle. Its range, accuracy and stopping power is almost unparalleled. Min ST: 6.}
{39300}{}{Phazer}
{39301}{}{This mysterious high tech weapon appears to have some sort of energy generator inside. If it wasn't damaged, this gun could be the ultimate weapon against any enemy. The backup energy module consists of replaceable small energy cell. Min ST: 3.}
{39400}{}{PPK12 Gauss Pistol}
{39401}{}{Praised for its range and stopping power, the PPK12 Gauss Pistol is of German design. The pistol uses an electromagnetic field to propel rounds at tremendous speed and punch through almost any armor. Min ST: 4.}
{39500}{}{Vindicator Minigun}
{39501}{}{The German Rheinmetal AG company created the ultimate minigun. The Vindicator throws over 90,000 caseless shells per minute down its six carbon-polymer barrels. As the pinnacle of Teutonic engineering skill, it is the ultimate hand-held weapon. Min ST: 7.}
{39600}{}{YK32 Pulse Pistol}
{39601}{}{The YK32 is an electrical pulse weapon that was developed by the Yuma Flats Energy Consortium. Though powerful, the YK32 was never considered a practical weapon due to its inefficient energy usage and bulky design. Min ST: 3.}
{39700}{}{YK42B Pulse Rifle}
{39701}{}{The YK42B is an electrical pulse weapon that was developed by the Yuma Flats Energy Consortium. It is considered a far superior weapon to the YK32 pistol, having a greater charge capacity and range. Min ST: 3.}
{39800}{}{.44 Magnum (Speed Load)}
{39801}{}{A .44 Magnum Revolver with a speed loader. Min ST: 5.}
{39900}{}{Super Cattle Prod}
{39901}{}{A Farmer's Best Friend model cattle prod from Wattz Electronics. This model has been upgraded to increase the electrical discharge. Min ST: 4.}
{40000}{}{Improved Flamer}
{40001}{}{A Flambe 450 model flamethrower, varmiter variation. Fires a spray of extremely hot, flammable liquid. This model has been modified to fire a hotter mixture which causes greater combustibility at range. Min ST: 6.}
{40100}{}{Laser Rifle (Ext. Cap.)}
{40101}{}{This Wattz 2000 laser rifle has had its recharging system upgraded and a special recycling chip installed that reduces the drain on the micro fusion cell by 50%. Min ST: 5.}
{40200}{}{Magneto-Laser Pistol}
{40201}{}{This Wattz 1000 laser pistol has been upgraded with a magnetic field targeting system that tightens the laser emission, giving this pistol extra penetrating power. Min ST: 3.}
{40300}{}{FN FAL (Night Sight)}
{40301}{}{This rifle has been more widely used by armed forces than any other rifle in history. It's a reliable assault weapon for any terrain or tactical situation. This weapon has been equipped with a night sight for greater night accuracy. Min ST: 5.}
{40400}{}{Desert Eagle (Exp. Mag.)}
{40401}{}{An ancient Desert Eagle pistol, in .44 magnum. Interest in late 20th century films made this one of the most popular handguns of all times. This one has been equipped with an expanded magazine for longer fun and games! Min ST: 4.}
{40500}{}{Assault Rifle (Exp. Mag.)}
{40501}{}{This Assault Rifle has an extended, military sized, ammunition clip. The expanded magazine capacity makes it more fun than ever to Spray-and-Pray. Min ST: 5.}
{40600}{}{Plasma Pistol (Ext. Cap.)}
{40601}{}{This Glock 86 Plasma Pistol has had its magnetic housing chamber realigned to reduce the drain on its energy cell. Its efficiency has doubled, allowing it to fire more shots before the battery is expended. Min ST: 4.}
{40700}{}{Mega Power Fist}
{40701}{}{A "Big Frigger" Power Fist from BeatCo. Considered by many to be the ultimate weapon to use in unarmed combat. This one has upgraded power servos for increased strength. Powered by small energy cells. Min ST: 1.}
{40800}{}{Field Medic First Aid Kit}
{40801}{}{A small kit containing basic emergency medical equipment. Bandages, wraps, antiseptic spray, and more.}
{40900}{}{Paramedics Bag}
{40901}{}{This bag contains instruments and drugs used by paramedics in the field. The tools contained are specifically designed for high trauma and emergency cases.}
{41000}{}{Expanded Lockpick Set}
{41001}{}{A set of locksmith tools. Includes all the necessary picks and tension wrenches to open conventional pin and tumbler locks. This set also includes some special tools for more difficult mechanical locking mechanisms.}
{41100}{}{Electronic Lockpick MKII}
{41101}{}{This is the second generation Wattz Electronics Micromanipulator FingerStuff electronic lockpick. For defeating electronic locks and security devices. This Mark II version includes updated software and interface tools.}
{41200}{}{Oil Can}
{41201}{}{You see a can of Armor-Go. A space-age, polymer, lubricant for powered armor.}
{41300}{}{Stables ID Badge}
{41301}{}{This is a temporary ID badge. It has a red stripe through it, which seems to indicate that you are a "Stables Researcher."}
{41400}{}{Vault 15 Shack Key}
{41401}{}{A standard key.}
{41500}{}{Spectacles}
{41501}{}{A set of spectacles for eye correction.}
{41600}{}{Empty Jet Canister}
{41601}{}{This empty Jet canister was found in Richard Wright's room. It still has traces of Jet inside.}
{41700}{}{Oxygen Tank}
{41701}{}{This is the oxygen tank for Salvatore's breathing apparatus.}
{41800}{}{Poison Tank}
{41801}{}{This tank looks suspiciously like an oxygen tank, but there is a small skull and crossbones symbol etched in the bottom. If you hadn't examined it closely, you wouldn't have seen the symbol.}
{41900}{}{Mine Parts}
{41901}{}{You see a bundle of parts that are clearly labeled "GX-9 Air Purifier". Using your incredible deductive skills, you decide that they are probably parts for a broken air purifier.}
{42000}{}{Morningstar Mine Scrip}
{42001}{}{This is a small chit probably used to pay Morningstar Mine Workers.}
{42100}{}{Holy Hand Grenade}
{42101}{}{A Holy relic of godly might.}
{42200}{}{Excavator Chip}
{42201}{}{This chip appears to be for some sort of large industrial machine. Beneath the dirt and dust, it appears to be in surprisingly good shape.}
{42300}{}{Gold Nugget}
{42301}{}{A nugget of gold.}
{42400}{}{Monument Chunk}
{42401}{}{This is a piece of the disgruntled stone monument you found out in the desert. Although many of your village would no doubt regard it as a sacred relic, somehow you suspect that you have been cheated.}
{42500}{}{Stone Head}
{42501}{}{A huge stone monument.}
{42600}{}{Uranium Ore}
{42601}{}{A chunk of Uranium Ore, unrefined.}
{42700}{}{Flame Breath}
{42800}{}{Medical Supplies}
{42801}{}{A box of assorted medical supplies. Nothing I can make use of though.}
{42900}{}{Gold Tooth}
{42901}{}{This gold tooth used to belong to someone else, but they won't be needing it anymore.}
{43000}{}{Howitzer Shell}
{43001}{}{A 75mm Howitzer shell. The casing has mostly corroded away, but you can make out these letters. EXP. 9-25-98.}
{43100}{}{Ramirez Box, Closed}
{43101}{}{This is the box you received from Big Jesus Mordino to give to Ramirez at the Stables.}
{43200}{}{Ramirez Box, Open}
{43201}{}{This is the box you received from Big Jesus Mordino to give to Ramirez at the Stables. It is open, and you have removed the Jet that was inside.}
{43300}{}{Mirrored Shades}
{43301}{}{This is a pair of fashionable and deadly-looking mirrored shades. Just having them in your inventory makes you feel cool.}
{43400}{}{Wagon}
{43401}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{43500}{}{Wagon}
{43501}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{43600}{}{Deck of Cards}
{43601}{}{A standard set of playing cards.}
{43700}{}{Pack of Marked Cards}
{43701}{}{Every card in this set is a red queen. Must make for some boring games.}
{43800}{}{Temple Key}
{43801}{}{A key for the Arroyo Temple door.}
{43900}{}{Pocket Lint}
{43901}{}{Some fuzz you found in a pocket.}
{44000}{}{Biomed Gel}
{44001}{}{A jar of Bio Gel used in the biomedical field.}
{44100}{}{Blondie's Dog Tags}
{44101}{}{These dog tags have the owner's name scratched off and the name "Blondie" scrawled on the back. Beneath the name is the number "11."}
{44200}{}{Angel-Eyes' Dog Tags}
{44201}{}{These dog tags list the owner as "Angel-Eyes." Beneath the name is the number "16."}
{44300}{}{Tuco's Dog Tags}
{44301}{}{These foul-smelling dog tags list the owner as "Tuco Benedicto Pacifico Juan Maria Ramirez," followed by the number "27."}
{44400}{}{Raiders Map}
{44401}{}{This is a crumpled map of pre-war Northern California. Reno and the surrounding caravan trails are outlined in red, and there is a red "X" far to the east of Reno with "Raiders" scrawled beneath it.}
{44500}{}{Sheriff's Badge}
{44501}{}{A Badge worn by the Sheriff of a town.}
{44600}{}{Vertibird Plans}
{44601}{}{A set of plans for building Vertibirds.}
{44700}{}{Bishop's Holodisk}
{44701}{}{This holodisk contains incriminating information on Bishop's secret deal with NCR. Apparently, Bishop hired mercenaries to attack Vault City in the hopes that Vault City would turn to NCR for military aid. This holodisk is audio only and has no text data. Vault City might be interested in this.}
{44800}{}{Account Book}
{44801}{}{This account book lists a series of monthly payments made to the mercenary band from the Bishop Family in New Reno. The payments depend heavily on how much "pressure" the mercenaries put on Vault City. Vault City might be interested in this.}
{44900}{}{Unused}
{44901}{}{Unused}
{45000}{}{Torn Paper 1}
{45001}{}{You see a piece of paper with writing on it. It looks like it's part of a code of some sort. Unfortunately, the code is incomplete. If only you could find all three pieces. You can make out the following: 1. Physics Password KSLJ, 2. Chemistry Password TIU, 3. Biology Password INTL}
{45100}{}{Torn Paper 2}
{45101}{}{You see a piece of paper with writing on it. It looks like it's part of a code of some sort. Unfortunately, the code is incomplete. If only you could find all three pieces. You can make out the following: KJ: Ken-Lee-9, ASPO- Lo-S, VR- Dnky-Pnch-}
{45200}{}{Torn Paper 3}
{45201}{}{You see a piece of paper with writing on it. It looks like it's part of a code of some sort. Unfortunately, the code is incomplete. If only you could find all three pieces. You can make out the following: 7313, hi-S12908, 98790}
{45300}{}{Password Paper}
{45301}{}{This is three pieces of a single page that, when assembled, reveal three passwords. The text reads: 1. Physics Password KSLJKJ: Ken-Lee-97313, 2. Chemistry Password TIUASPO- Lo-Shi-S12908, 3. Biology Password INTLVR- Dnky-Pnch-98790}
{45400}{}{Explosive Switch}
{45401}{}{This toggle switch is the final component of an explosive device.}
{45500}{}{Car Trunk}
{45501}{}{The trunk is a great place to store your stuff.}
{45600}{}{Cell Door Key}
{45601}{}{This key fits the Cell Door in Broken Hills.}
{45700}{}{Hubologist Field Report}
{45701}{}{A field office report for the membership drive in the True Faith.}
{45800}{}{M.B. Holodisk 5}
{45801}{}{The label reads: Message to CHQ- Confidential.}
{45900}{}{M.B. Holodisk 1}
{45901}{}{The label reads: Radio transmission log checkpoint 1.}
{46000}{}{M.B. Holodisk 2}
{46001}{}{The label reads: Radio transmission log checkpoint 2.}
{46100}{}{M.B. Holodisk 3}
{46101}{}{The label reads: Radio transmission log checkpoint 3.}
{46200}{}{M.B. Holodisk 4}
{46201}{}{The label reads: Radio transmission log research team.}
{46300}{}{Evacuation Holodisk}
{46301}{}{The label reads: Base evacuation notice.}
{46400}{}{Experiment Holodisk}
{46401}{}{The label reads: Research log.}
{46500}{}{Medical Holodisk}
{46501}{}{The label reads: Medical log.}
{46600}{}{Password Paper}
{46601}{}{A sheet of folded paper with the word "TCHAIKOVSKY" written on it.}
{46700}{}{Jesse's Container}
{46701}{}{}
{46800}{}{Smitty's Meal}
{46801}{}{It's some kind of salad and a sandwich made out of what you think is Brahmin meat covered in a thick dark yellow sauce. There is also a strange pickled green vegetable on the side.}
{46900}{}{Rot Gut}
{46901}{}{A very strong liquor or cleaning fluid, you decide.}
{47000}{}{Ball Gag}
{47001}{}{A questionable sexual device. If you need to ask, you don't want to know.}
{47100}{}{"The Lavender Flower"}
{47101}{}{It appears to be some kind of romance novel written by Dorothy Rixon. The cover has a woman laying on a bed surrounded by a hundred flowers.}
{47200}{}{Hubologist Holodisk}
{47201}{}{This holodisk is labeled "Hubology: The Truth Behind the Lies". It looks like it works with your Pip-Boy.}
{47300}{}{Mutated Toe}
{47301}{}{You see your sixth toe. It is a small mutated part of yourself. For some reason, you feel a terrible sense of loss as you look at the tiny amputated toe.}
{47400}{}{Daisies}
{47401}{}{A flower pot of daisies. Aren't they nice?}
{47500}{}{Unused}
{47501}{}{Unused}
{47600}{}{Enlightened One's Letter}
{47601}{}{A report addressed to AHS-9 in San Francisco. It's really dry reading- tables of oppressive adjustments, expense reports, and other twaddle not worth wasting your time on.}
{47700}{}{Broadcast Holodisk}
{47701}{}{The label reads: "Galaxy News Network."}
{47800}{}{Sierra Mission Holodisk}
{47801}{}{The label reads: "Mission Statement."}
{47900}{}{NavCom Parts}
{47901}{}{These are computer parts that look like they slot into the interior of a machine. The fact that they say "Poseidon Oil" and "Navigation Computer" on them lead you to believe they fit into a Poseidon Oil Navigation Computer.}
{48000}{}{Bonus +1 Agility}
{48100}{}{Bonus +1 Intelligence}
{48200}{}{Bonus +1 Strength}
{48300}{}{Fallout 2 Hintbook}
{48301}{}{Well, THIS would have been good to have at the beginning of the goddamn game.}
{48400}{}{Player's Ear}
{48401}{}{This is your ear. The Masticator bit it off during the fight and spit it on your unconscious body. If you are reading this, it probably means you will be reloading soon. Of course, it is possible this item has some special value.}
{48500}{}{Masticator's Ear}
{48501}{}{This is the Masticator's ear. You bit it off after pummeling him senseless. Congratulations on beating him. He's one of the toughest NPC's in the game, especially when you don't have any weapons or armor.}
{48600}{}{Refined Uranium Ore}
{48601}{}{A chunk of Uranium Ore. This ore seems to have been processed somehow. It seems heavier.}
{48700}{}{Note from Francis}
{48701}{}{"Zaius, Marcus isn't doing anything about that mutant-hater Jacob and his damned conspirators. First they disable the air purifier... and then what? I found their secret meeting tunnels. I figure a body or two down there could implicate Jacob. If you want in, let me know. And burn the damn note this time!" -Signed, Francis.}
{48800}{}{K-9 Motivator}
{48801}{}{This is the drive mechanism for a K-9 series robot.}
{48900}{}{Special Boxer Weapon}
{49000}{}{NCR History Holodisk}
{49001}{}{The label reads: "History of NCR."}
{49100}{}{Mr. Nixon Doll}
{49101}{}{You see a small doll with a big red nose. For some reason, you don't trust this seemingly-innocent child's toy.}
{49200}{}{Tanker Fob}
{49201}{}{An encoded passkey that provides access to high security areas.}
{49300}{}{Teachings Holodisk}
{49301}{}{The label reads: "Hubologist Teachings."}
{49400}{}{Kokoweef Mine Scrip}
{49401}{}{This is a small chit probably used to pay Kokoweef Mine Workers.}
{49500}{}{Presidential Access Key}
{49501}{}{This access key has what looks like the presidential seal on it. It appears as though it's used to gain Presidential level access to computers.}
{49600}{}{Boxing Gloves}
{49601}{}{A pair of boxing gloves that smell faintly of sweat. They look like they have seen a lot of use: many old blood stains still remain.}
{49700}{}{Plated Boxing Gloves}
{49701}{}{Someone has "accidentally" slipped metal plates into these boxing gloves. It could technically be considered cheating, but you prefer to think of it as an increased opportunity to dispense bone-crunching damage.}
{49800}{}{Dual Plasma Cannon}
{49801}{}{Only use for Gun Turret critter.}
{49900}{}{Pip-Boy Lingual Enhancer}
{49901}{}{This Pip-Boy lingual enhancer consists of a storage holodisk, a microfilament cord, headgear, and an optical sensor that is placed over the user's right eye. When used, an optical flash transmits an entire dictionary into the user's memory, permanently improving the user's speech skills.}
{50000}{}{FN FAL HPFA}
{50001}{}{This rifle has been more widely used by armed forces than any other rifle in history. It's a reliable assault weapon for any terrain or tactical situation. The HPFA modification has extended magazine and higher rate of fire. Min ST: 5.}
{50100}{}{Wall Safe}
{50200}{}{Floor Safe}
{50300}{}{Blue Memory Module}
{50301}{}{A read only computer memory module containing medical information. This module details charisma enhancements.}
{50400}{}{Green Memory Module}
{50401}{}{A read only computer memory module containing medical information. This module details perception enhancements.}
{50500}{}{Red Memory Module}
{50501}{}{A read only computer memory module containing medical information. This module details strength enhancements.}
{50600}{}{Yellow Memory Module}
{50601}{}{A read only computer memory module containing medical information. This module details intelligence enhancements.}
{50700}{}{Decomposing Body}
{50701}{}{This is a partially decomposed body of a humanoid creature.}
{50800}{}{Rubber Doll}
{50801}{}{An inflatable rubber sex doll. This model is called "Tandi".}
{50900}{}{Damaged Rubber Doll}
{50901}{}{This inflatable rubber sex doll has a torn seam. It's obviously been well used.}
{51000}{}{Pool Table}
{51100}{}{Pool Table}
{51101}{}{}
{51200}{}{Pool Table}
{51300}{}{Pool Table}
{51400}{}{Pool Table}
{51500}{}{Pool Table}
{51600}{}{Pip-Boy Medical Enhancer}
{51601}{}{This Pip-Boy medical enhancer consists of a storage holodisk, microfilament cord, headgear, and an optical sensor that is placed over the user's left eye. When used, an optical flash transmits a dictionary of physician skills and know-how into the user's memory, permanently improving the user's doctor skill.}
{51700}{}{"Little Jesus"}
{51701}{}{This wicked looking blade once belonged to Lil' Jesus Mordino. It has numerous nicks and cuts along its surface, but its edge is razor sharp. On its handle is carved "Little Jesus."}
{51800}{}{Dual Minigun}
{51801}{}{Only use for Auto-Cannon critter.}
{51900}{}{Bottle Caps}
{51901}{}{These are worthless bottle caps. You've heard that at one time they were used as money, though you suspect its only a story.}
{52000}{}{Heavy Dual Minigun}
{52001}{}{Only use for Auto-Cannon Critter.}
{52100}{}{Poor Box}
{52101}{}{A small box used to collect money for the poor.}
{52200}{}{Wakizashi Blade}
{52201}{}{A short finely crafted knife. The tip seems to be designed to pierce armor.}
{52300}{}{Survey Map}
{52301}{}{It looks like a geological survey map of the Bay area.}
{52400}{}{Bridgekeeper's Robes}
{52401}{}{This smelly, filthy garment must be made out of some special fabric in order to have withstood the foulness of the bridgekeeper's body. Oddly enough, it has plasma burns and scorch marks all over it, as if these weapons were used against it... to no effect. You have NO idea why it's purple.}
{52500}{}{Hypo}
{52501}{}{A medical injection instrument of some kind. It looks very high tech. You don't know what it's filled with but it appears to have only one dose left.}
{52600}{}{Dead Redshirt}
{52601}{}{This guy has a weird red uniform you have never seen. It looks like he died from dehydration.}
{52700}{}{Dead Redshirt}
{52701}{}{This guy has a weird red uniform you have never seen. It looks like he died from dehydration.}
{52800}{}{Dead Redshirt}
{52801}{}{This guy has a weird red uniform you have never seen. It looks like he died from dehydration.}
{52900}{}{Mining Machine}
{53000}{}{End Boss Knife}
{53100}{}{End Boss Plasma Gun}
{53200}{}{Sam Pritchard's Map}
{53201}{}{This crudely-drawn map shows the area surrounding New Reno. It looks like there's some sort of military base to the north.}
{53300}{}{Fire Gecko Pelt}
{53301}{}{This is the dried and cured hide of a fire gecko.}
{53400}{}{Bucket}
{53401}{}{A medium sized bucket used to haul water from a well.}
{53500}{}{Scaly Fish}
{53501}{}{A scaly looking fish. If cooked, it would probably make a tasty meal.}
{53600}{}{Fish}
{53601}{}{A raw looking fish. If cooked, it would probably make a tasty meal.}
{53700}{}{Ode to the Flame Deluge}
{53701}{}{A novel set after a devastating nuclear war. The book excerpt describes how a violent backlash against the culture of advanced knowledge and technology that had led to the development of nuclear weapons took place shortly after this war. Anyone of learning, and eventually anyone who could even read, was likely to be killed.}
{53800}{}{Text Book}
{53801}{}{An old text book from before the Great War. It is quite technical and doesn't appear to contain any useful information.}
{53900}{}{Medical Book}
{53901}{}{A study book on the field of medicine and biology.}
{54000}{}{Operations Manual}
{54001}{}{The operations manual to the KV-75; a portable, tactical cryptographic device. Also used by non-tactical users for high-level communications in the local wideband telephone networks and wideband satellite terminals.}
{54100}{}{Chinese Army: Special Ops Manual}
{54101}{}{You can't understand a thing from the text, but the illustrations are quite informative.}
{54200}{}{Bottle of wine}
{54201}{}{A fresh bottle of Abbey's finest wine.}
{54300}{}{Diary}
{54301}{}{It appears to be a diary which belonged to a young girl. The writing on the inside cover says: "Property of Anna" Most of the pages are either torn or faded, but one is still readable. "Day 271: Today my mother gave me a gold locket. It is the most beautiful thing I have ever owned. I will never part with it."}
{54400}{}{Botany Holodisk}
{54401}{}{This information disk categorizes the various plant life that grew before the Great War.}
{54500}{}{Expired G.E.C.K.}
{54501}{}{The Garden of Eden Creation Kit. This unit is standard equipment for all Vault-Tec vaults. A GECK is the resource for rebuilding civilization after the bomb. Just add water and stir. This one is well beyond is expiration date. What a waste!}
{54600}{}{Old Coin}
{54601}{}{A very old coin. You are not sure whose face is on it, but it looks like it could be rare and worth a lot of money.}
{54700}{}{A watch}
{54701}{}{An antique watch. This brand stopped being manufactured long before the Great War.}
{54800}{}{Pack of Cigarettes}
{54801}{}{A pack of 'Commies'. On the back it says: 'Smoke a Commie to do your bit for democracy and feel better'. Lower down there's a health warning: 'As your doctor, I recommend Commies for fresher breath and a winning smile'. It looks like there's about 10 in a pack.}
{54900}{}{Gas Mask}
{54901}{}{The Protective Mask: Your mask is your first line of defense against biological agents. Take care of it.}
{55000}{}{Toaster}
{55001}{}{A silver toaster sitting on a desk.}
{55100}{}{Syringe}
{55101}{}{A pre war implement for administrating drugs. It is full of an unknown substance.}
{55200}{}{Dog Food}
{55201}{}{Several cans of dog food.}
{55300}{}{Bug Spray}
{55301}{}{A spray can full of a substance that kills all known bugs.}
{55400}{}{Environmental Armor}
{55401}{}{Armor best worn against biological attacks.}
{55500}{}{EPA Pamphlet}
{55501}{}{A leaflet given out at the beginning of tours.}
{55600}{}{Drugs}
{55601}{}{Some sort of drugs preserved from before the war.}
{55700}{}{Security Rooms Key Card}
{55701}{}{A key card to unlock the security rooms.}
{55800}{}{Test tube rack}
{55801}{}{A rack for holding chemical test tubes.}
{55900}{}{Keys}
{55901}{}{Keys to allow access to the storage shed on the surface.}
{56000}{}{Random Chemicals}
{56001}{}{DANGER! Unknown chemicals. Use with caution.}
{56100}{}{Corn Seeds}
{56101}{}{Packets of seeds, used to grow plants. These are labeled as genetically modified corn seeds immune to both disease and insect infestation.}
{56200}{}{Plant Spray}
{56201}{}{A spray can full of a substance that kills various types of plants.}
{56300}{}{Trigger activated dynamite}
{56301}{}{Unlike normal dynamite which is set by a timer, this dynamite is activated by a trigger.}
{56400}{}{Trigger switch}
{56401}{}{Trigger for dynamite.}
{56500}{}{Paper}
{56501}{}{Paper with a passcode scribbled on it.}
{56600}{}{Experimental Seeds}
{56601}{}{Packet of experimental seeds. Result of germination is unknown.}
{56700}{}{A drill}
{56701}{}{An electric powered drill.}
{56800}{}{Trigger activated dynamite}
{56801}{}{Unlike normal dynamite which is set by a timer, this dynamite is activated by a trigger. This one is armed and ready to be triggered.}
{56900}{}{Pop Rocks}
{56901}{}{An unopened bag of a tasty carbonated candy made of sugar, lactose (more sugar), corn syrup (even more sugar), and flavoring. It is rumored that when mixed with drinks like Nuka Cola one's stomach would explode.}
{57000}{}{Bottle of Shampoo}
{57001}{}{A premium bottle of shampoo. Unlike other leading brands, this shampoo comes in an unusual flexi-plastic bottle. It was specially designed this way, so when the bottle was squeezed, the right amount of shampoo was poured out - no more, no less. Just a flip of the cap, and you're on your way.}
{57100}{}{K-9 Kevlar}
{57101}{}{A dusty old set of sturdy kevlar plates set into black nylon sleeves. You think it must be sized for a dwarf, until you notice a tag on the inside which reads: Canine Kevlar. Large. A DoggieBuddy product. Made in Taiwan.}
{57200}{}{Human Ear}
{57201}{}{A woman's ear. Gross! Only a mentally unstable person would ever remove a human ear.}
{57300}{}{ERSI canister}
{57301}{}{A canister of Environmental Rejection Syndrome Inhibitors. Applied to specimens exiting from an extended period of hibernation.}
{57400}{}{Lightsaber}
{57401}{}{An ancient weapon from a more civilized age. Not as clumsy or as random as a blaster. It was given to you by Obi-Wan-Killap. Min ST: 2}
{57500}{}{Blaster}
{57501}{}{Hokey religions and ancient weapons are no match for a good blaster at your side, kid. Min ST: 3}
{57600}{}{Lightsaber}
{57601}{}{An ancient weapon from a more civilized age. Not as clumsy or as random as a blaster. It was given to you by Empress Timeslip. Min ST: 2.}
{57700}{}{Air Processing Vent}
{57701}{}{The grill on this vent looks different.}
{57800}{}{Metal Locker}
{57801}{}{A storage container.}
{57900}{}{Metal Locker}
{57901}{}{A storage container.}
{58000}{}{Chinese Code Chart}
{58001}{}{You're not certain, but it appears to be a chart containing various Chinese command codes. Perhaps if you found a place to input these codes, you could learn a thing or two.}
{58100}{}{Dead Tribal}
{58101}{}{This person has died a horrible death on the medical table.}
{58200}{}{Dead Tribal}
{58201}{}{This person has died a horrible death on the medical table.}
{58300}{}{Plant Spike}
{58301}{}{An organic seed-spike that the carnivorous plants spit at potential food or seed carriers. This one is sharper, and harder than usual.}
{58400}{}{Dead Vault Dweller}
{58401}{}{This person has died a horrible death on the medical table.}
{58500}{}{Dead Vault Dweller}
{58501}{}{This person has died a horrible death on the medical table.}
{58600}{}{Dead Tribal}
{58601}{}{This person has died a horrible death on the medical table.}
{58700}{}{Dead Tribal}
{58701}{}{This person has died a horrible death on the medical table.}
{58800}{}{K-9 Kevlar}
{58801}{}{Wearable K-9 Kevlar (FAKE)}
{58900}{}{Mutant Armor}
{58901}{}{Mutant Armor}
{59000}{}{Mutant Armor}
{59001}{}{Wearable Mutant Armor (FAKE)}
{59100}{}{Small Scorpion Tail}
{59101}{}{The severed tail of a small radscorpion.}
{59200}{}{Plant seed}
{59201}{}{A plant seed given to you by Dr. Sheng.}
{59300}{}{Nothing out of the ordinary}
{59301}{}{Nothing out of the ordinary.}
{59400}{}{Nothing out of the ordinary}
{59401}{}{Nothing out of the ordinary.}
{59500}{}{Nothing out of the ordinary}
{59501}{}{Nothing out of the ordinary.}
{59600}{}{Fake Heart Pills}
{59601}{}{These pills would normally be used by people with heart problems, except in this case death would ensue. These pills have been mixed with other chemicals, resulting in a guaranteed heart-exploding experience.}
{61000}{}{.50 BMG}
{61001}{}{Large caliber ammunition 12.7x99 armour piercing. This bullets can penetrate a tank.}
{61100}{}{Throwing Axe}
{61101}{}{Throwing axe. Perfectly balanced and sharpened. Work of a master blacksmith. Min ST: 5.}
{52901}{}{}
{61200}{}{Dragon Skin}
{61201}{}{This strange drug makes user invulnerable to fire. Nasty side effects are reported.}
{61300}{}{Home-made grenade}
{61301}{}{This grenade was made from junk. However it does its job in dismembering people pretty well. Min ST: 3.}
{61400}{}{12 ga. Slugs}
{61401}{}{Shotgun ammunition. Loaded with heavy lead for large game hunting.}
{61500}{}{.223 AP}
{61501}{}{A case of .223 caliber ammunition, armor piercing.}
{61600}{}{Mine-Trap Kit}
{61601}{}{Disassembled floor plate trap. Contains pressing mechanism with a detonator. Can be armed with all kinds of explosives or grenades.}
{61700}{}{Taser}
{61701}{}{Police issue X46 Taser. Non-lethal weapon used to temporarily stop the target. Min ST: 3.}
{61800}{}{Spike Trap}
{61801}{}{This trap consists of a crude triggering mechanism and a number of sharp spikes. It can be used several times before the spikes are worn out.}
{61900}{}{Proximity Mine Kit}
{61901}{}{A mine-trap kit, consisting of a plastic shell and a simple proximity sensor with detonator. Can be armed with all types of explosives or grenades.}
{62000}{}{Hercules}
{62001}{}{This drug increases strength of certain muscle groups, allowing to lift and carry heavy items.}
{62100}{}{Severed Arm}
{62101}{}{An arm brutally cut from the body. There is a tattoo that indecates a gang and a rank of the victim.}
{62200}{}{Death Claw}
{62201}{}{A sharp claw ripped from a powerful creature. Its unique properties make it very valuable among traders and collectors alike.}
{62300}{}{Mole Rat Hide}
{62301}{}{A sturdy piece of mole rat skin. Great material for leather armor.}
{62400}{}{Mutant Tentacle}
{62401}{}{A tentacle, severed from a mutant. It is said to be very useful in a medical field. Only doctors know why...}
{62500}{}{Wanamingo Hand}
{62501}{}{A hand taken from a dead wanamingo. Extraordinary hardness that allows the creature to dig tunnels through solid rock also makes it useful in many ways.}
{62600}{}{Bone Amulet}
{62601}{}{A tribal amulet, carefully carved from bones. Unique image on the amulet indicates the tribe of origin and the name of the warrior who should wear it.}
{62700}{}{Fish Soup}
{62701}{}{Healthy soup made from local fish and some other strange ingredients. They say fish is good for concentration.}
{62800}{}{Meat Stew}
{62801}{}{This healthy stew made with meat, fruits and spices will keep you going throughout the day! Grandmother's recipe.}
{62900}{}{9mm SMG}
{62901}{}{This old pre-war sub-machine gun was primarily used by police forces. It is inferior to other SMGs, but can still be found in the wastes. Caliber: 9x19mm. Min ST: 4.}
{63000}{}{Grenade Launcher}
{63001}{}{40mm M79 grenade launcher. Sawed-off for concealed carry. Needs reload after each shot, but still effective against large groups. Min ST: 4.}
{63100}{}{40mm HE Grenades}
{63101}{}{High-explosive frag grenades. Caliber 40x46 mm. Typically used with M79 grenade launcher.}
{63200}{}{40mm IC Grenades}
{63201}{}{Incendiary grenades. Caliber 40x46 mm. Useful for fast clearing of rooms and other positions.}
{63300}{}{14mm JHP}
{63301}{}{Large caliber ammunition. 14mm jacketed hollow-points.}
{63400}{}{MGL}
{63401}{}{Milkor MGL is a lightweight 40mm six-shot revolver-type grenade launcher. It has enough firepower to quickly create chaos in a wide area. Min ST: 5.}
{63500}{}{Traps and Explosives}
{63501}{}{This book describes ways to set and disarm traps, and how to make explosives without getting blown up in the process.}
{63600}{}{Capital}
{63601}{}{Capital: A Critique of Political Economy. Book describes the process of circulation of capital. You already feel as it starts to circulate towards your pocket.}
{63700}{}{Boomerang}
{63701}{}{Ancient thrown weapon. Min ST: 3.}
{63800}{}{Spiked Sledge}
{63801}{}{Heavy sledgehammer with sharp spikes for additional effect. Min ST: 6.}
{63900}{}{Piston Spear}
{63901}{}{Spear with a pneumatic piston built into the end. It is designed to do more impact damage. Min ST: 5.}
{64000}{}{Deathclaw Gauntlet}
{64001}{}{A sturdy leather gauntlet with three claws attached to it. Extremely sharp. Min ST: 3.}
{64100}{}{12 ga. Dragon Breath}
{64101}{}{These incendiary shells pack a fiery punch that can melt armor and flesh alike.}
{64200}{}{7.62mm AP}
{64201}{}{Ammunition. Caliber: 7.62mm armor piercing.}
{64300}{}{Cowboy Repeater}
{64301}{}{Winchester lever-action rifle, in .44 magnum. Min ST: 4.}
{64400}{}{14mm SMG}
{64401}{}{When you need the most firepower in the smallest package. Caliber: 14mm. Min ST: 6.}
{64500}{}{Bear Trap}
{64501}{}{This trap can hold down a large animal, like a bear. But there are no bears around here...}
