#
# Quest descriptons
#
#    Please leave space between the areas (like 100 or so)
#


#
# Arroyo Quests
#
{100}{}{Kill the evil plants that infest Hakunin's garden.}
{110}{}{Obtain flint to have Mynoc sharpen your spear.}
{120}{}{Rescue Nagor's dog, Smoke, from the wilds.}
{130}{}{Retrieve the GECK for Arroyo.}
{140}{}{Find Vic the Trader.}

#
# Den Quests
#
{200}{}{Free Vic from his debt by getting his radio from his house in Klamath and paying Metzger.}
{201}{}{Find out how Becky can sell her booze for such low prices.}
{202}{}{Sabotage Becky's still.}
{203}{}{Get car part for Smitty.}
{204}{}{Return Anna's locket.}
{205}{}{Collect Rebecca's money from Fred.}
{206}{}{Get Rebecca's book from Derek.}
{207}{}{Deliver a meal to Smitty for Mom.}
{208}{}{Lara wants to know what is being guarded in the church.}
{209}{}{Get permission from Metzger for the gang war.}
{210}{}{Find a weakness in Tyler's gang guarding the church.}
{211}{}{Help Lara attack Tyler's gang.}
{212}{}{Find a way to get the orphans off the streets.}

#
# Klamath Quests
#
{300}{}{Refuel the still.}
{301}{}{Rescue Smiley the Trapper.}
{302}{}{Guard the brahmin.}
{303}{}{Rustle the brahmin.}
{304}{}{Kill the rat god.}
{305}{}{Rescue Torr.}
{306}{}{Figure out who is rustling the brahmin.}

#
# Modoc Quests
#
{400}{}{Something strange is happening at the farm northeast of Modoc. Investigate and report back to Jo.}
{401}{}{Cornelius has lost his gold pocket watch. Find it and return it to him.}
{402}{}{Farrel wants you to find Cornelius's gold pocket watch. Find it and return it to Farrel.}
{403}{}{Jonny is missing. Find him and bring him home to Balthas.}
{404}{}{Jonny's in the Slag caves. Find a way to get Jonny back home to Balthas.}
{405}{}{Farrel has a rodent problem in his garden. Remove the infestation.}
{406}{}{Deliver the Slag's message to Jo in Modoc.}
{407}{}{Jo is suspicious of the Slags. Find out about the dead bodies at the Ghost Farm and find out what happened to Karl.}
{408}{}{Go to the Den and tell Karl it's alright to come back home.}
{409}{}{Guard Grisham's brahmin.}
# phobos2077:
{421}{}{Bring 10 molerat hides to Balthas.}

#
# Vault City Quests
#
{500}{}{Get a plow for Mr. Smith.}
{501}{}{Deliver Moore's briefcase to Mr. Bishop in New Reno.}
{502}{}{Deliver a sample of Jet to Dr. Troy.}
{503}{}{Solve the Gecko powerplant problem.}
{504}{}{Deliver Lynette's holodisk to Westin in NCR.}
{505}{}{Rescue Amanda's husband, Joshua.}
{506}{}{Deliver beer and booze (10 each) to Lydia.}
{507}{}{Deliver pliers (tools) and a wrench to Valerie.}
{508}{}{Scout the eight sectors around Gecko and return to Stark.}
{509}{}{Enter NCR and return to Stark.}
{510}{}{Resolve the problem with the nearby village.}
{511}{}{Get weapons for Connar to be used at the nearby village.}
{512}{}{Put the Village on a trade route.}
# new quest by Lujo/phobos2077
{513}{}{Scout the eight sectors around Broken Hills and return to Stark.}

#
# Gecko Quests
#
{600}{}{Solve the Gecko powerplant problem.}
{601}{}{Repair the powerplant.}
{602}{}{Optimize the powerplant.}
{603}{}{Retrieve the Economy Disk and deliver it to McClure in Vault City.}
{604}{}{Get super repair kit for Skeeter.}
{605}{}{Get 3-step plasma transformer for Skeeter.}
{606}{}{Find Woody the ghoul for Percy. Try the Den.}

#
# Broken Hills Quests
#
{700}{}{Determine whether Chad is skimming money from the caravan runs.}
{701}{}{Fix the mine's air purifier.}
{702}{}{Find the missing people for Marcus.}
{703}{}{Beat Francis at arm wrestling.}
{704}{}{Break Manson and Franc out of prison.}
{705}{}{Blow up the mine's air purifier.}
{706}{}{Divert more electrical power to Eric's home.}

#
# New Reno Quests
#
{800}{}{Recover your stolen car.}
{801}{}{Find out who was responsible for Richard Wright's overdose.}
{802}{}{     Suspect: Jagged Jimmy J}
{803}{}{     Suspect: Jules}
{804}{}{     Suspect: Lil' Jesus Mordino}
{805}{}{     Suspect: Renesco}
{806}{}{Find a way into the Sierra Army Base.}
{807}{}{Track down Pretty Boy Lloyd, recover the stolen money, and make an... example of him.}
{808}{}{Go visit Renesco the Rocketman and collect Mr. Salvatore's tribute of $1000.}
{809}{}{Help guard a secret transaction taking place in the desert.}
{810}{}{Find some endorphin blockers to make a cure for Jet.}
{811}{}{Bust up Wright's still beneath the train station.}
{812}{}{Assassinate Westin in NCR without making it look like a murder.}
{813}{}{Murder Carlson in NCR.}
{814}{}{Deliver ten Cat's Paw magazines to Miss Kitty.}
{815}{}{Deliver a laser pistol to Eldridge.}
{816}{}{Deliver Big Jesus' package to Ramirez at the Stables.}
{817}{}{Collect tribute from the Corsican Brothers.}
{818}{}{Assassinate Boss Salvatore for Big Jesus Mordino.}
{819}{}{Bring a bottle of Abbey's hootch to Father Tully.}

#
# Sierra Army Base Quests
#
{900}{}{}

#
# Vault 15 Quests
# Moved it to 3000 on accedent
{1000}{}{}

#
# New California Republic Quests
#
{1100}{}{Retrieve Parts/Gain Access to Vault 15.}
{1101}{}{"Take care of" Officer Jack for Mira.}
{1102}{}{Complete the brahmin drive.}
{1103}{}{Retrieve the papers from Dr. Henry.}
{1104}{}{Test the mutagenic serum on a super-mutant. Try Broken Hills.}
{1105}{}{Eliminate Mr. Bishop.}
{1106}{}{Deliver Westin's holodisk to Lynette in Vault City.}
{1107}{}{Get the map from the NCR Rangers, for Vortis the slaver.}
{1108}{}{Free the slaves in the slave pen, for the Rangers.}
{1109}{}{Deliver the Hubologist's field report to AHS-9 in San Francisco.}
{1110}{}{Kill the Hubologist for Merk.}
{1111}{}{Stop the brahmin raids.}
{1112}{}{Wipe out the Rangers' safe houses to the north, for Vortis the slaver.}
{1113}{}{Wipe out the Slaver Camp to the north west, for the Rangers.}
# new quests added by phobos2077
{1120}{}{Take down a tribal traveling around Modoc and bring proof to Deputy Karl.}
{1121}{}{Take down a group of villains somewhere east of Broken Hills. Bring proof to Karl.}
{1122}{}{Eliminate an armed gang last seen to the east of San Francisco. Bring proof to Karl.}
{1123}{}{Bring 8 mutant tentacles to Dr. Henry.}

#
# Vault 13 Quests
#
{1200}{}{Fix the Vault 13 computer.}
{1201}{}{Talk to Goris.}

#
# Military Base Quests
#
{1300}{}{}

#
# Redding Quests
#
{1398}{}{Clear out the mine.}
{1399}{}{Find the excavator chip.}
{1400}{}{Take care of the Widow Rooney situation.}
{1401}{}{Break up the bar brawl.}
{1402}{}{Find out who cut the whore.}
{1403}{}{Kill Frog Morton.}
# new quests added by phobos2077
{1411}{}{Eliminate a gang of robbers roaming around town and report to Ascorti.}

#
# San Francisco Quests
#
{1500}{}{The tanker needs fuel.}
{1501}{}{The navigation computer needs the NavComp part to work.}
{1502}{}{You need to use a FOB to access the navigation computer.}
{1503}{}{Kill the Shi Emperor.}
{1504}{}{The Hubologists need plans for a vertibird from Navarro.}
{1505}{}{Steal the vertibird plans from the Shi.}
{1506}{}{The Hubologists need fuel for their spaceship.}
{1507}{}{Kill Badger so the tanker vagrants will embrace the Hub.}
{1508}{}{Kill the AHS-9.}
{1509}{}{The Shi need plans for a vertibird from Navarro.}
{1510}{}{Steal the vertibird plans from the Hubologists.}
{1511}{}{Find Badger's girlfriend in the hold below the ship.}
{1512}{}{The Dragon wants you to take out Lo Pan - hand to hand.}
{1513}{}{Lo Pan wants you to take out the Dragon - hand to hand, if possible.}
{1514}{}{Get Chip's spleen back.}
{1515}{}{Get some hardened power armor from Crockett.}
{1516}{}{Get the vertibird plans for the Brotherhood of Steel.}
{1517}{}{Disable the Shi submarine threatening the tanker.}
{1518}{}{Investigate the whereabouts of Dr. Sheng.}
{1519}{}{Bring Dr. Sheng some plant seeds.}
{1520}{}{Eliminate Dr. Sheng.}
{1521}{}{Deliver the plant seed sample to Dr. Wong.}
{1522}{}{Eliminate Dr. Wong without alerting the Shi.}
{1523}{}{Clear out Dr. Sheng's lab.}

#
# Navarro Quests
#
#1515, ...
{1600}{}{Deal with the deathclaw.}
{1601}{}{Fix K-9.}
{1602}{}{Retrieve the FOB from the base Commander.}

#
# The Enclave Quests
#
{1700}{}{}

#
# The Abbey Quests
#
{1800}{}{Kill the beast beneath the church.}
{1801}{}{Deliver the machine part to Brother Max.}
{1802}{}{Repair the waterpump and report the status to the headmonk.}
{1803}{}{Find out who is digging up the graves.}
{1804}{}{Inform Brother Samuel and Father Tully about the whereabouts of each other.}
{1805}{}{Bring a lighter to Brother Hank.}
{1806}{}{Collect information about Botany for Brother Paul.}
{1807}{}{Format the Abbey's book database.}
{1808}{}{Escort Brother Jason to Gecko.}

#
# Primitive Tribe Quests
#
{1900}{}{Collect some weapons for the Tribe's warriors.}
{1901}{}{Fix the well for Marli and the tribe.}
{1902}{}{Find out what's haunting the tribe's shaman.}
{1903}{}{Find Sulik's missing sister.}
{1904}{}{Find out what happened to the hunting party.}
{1905}{}{Collect firewood for the tribe's fishermen.}
{1906}{}{Reunite Sulik and his sister, Kurisu.}
{1907}{}{Accompany Krom to meet with the trader.}
{1908}{}{Bring some herbs (5 Xander Roots, 3 Broc Flowers) to the Shaman.}

#
# EPA Quests
#
{2000}{}{Fix Hologram 00000.}
{2001}{}{Fix the Voice Computer.}
{2002}{}{Clear out the plant problem.}
{2003}{}{Fix EPA lighting problem.}
{2004}{}{Collect Gecko Pelts for the Doctor.}
{2005}{}{Fix the hologram that speaks with static.}
{2006}{}{Find the tool the Doctor left behind.}
{2007}{}{Test the Solar Scorcher for the Director of Science.}

#
# Ghost Town Quests
#
{2100}{}{}

#
# Car outta Gas Quests
#
{2200}{}{}

#
# Destroyed Arroyo Quests
#
{2300}{}{}

#
# Toxic Caves Quests
#
{2400}{}{}

#
# Den Slave Run Quests
#
{2500}{}{}

#
# Raiders Quests
#
{2600}{}{}

#
# Desert Encounter Quests
#
{2700}{}{}

#
# Mountain Encounter Quests
#
{2800}{}{}

#
# Ruined City Encounter Quests
#
{2900}{}{}

#
# Coast Encounter Quests
#
{3000}{}{}

#
# Golgotha Quests
#
{3100}{}{}


#
# Vault 15 Quests
#
{3200}{}{Rescue Chrissy.}
{3201}{}{Kill Darion.}
{3202}{}{Complete the deal with NCR.}
{3203}{}{Give the Spy Holodisk to the authorities in NCR.}
