procedure inittest begin
   variable var := (24*5);
   var := 1;
   var := 2;
   if (23) then begin
      variable var3 := -5;
      variable var2 := key_pressed(34) + var3;
   end
   var2 := 3;
   return var;
end


procedure elsetest begin
   variable i;
   while (true) do
   if (i < 25) then begin
      i := 10;
   end else begin
      if (i > 60) then continue;
      i := 22;
   end
   i  := 30;
   
   if (1) then i := 1;
   else if (2) then i := 1;
   else if (3) then i := 1;
   
   switch (2142 * 5) begin
      case "123": display_msg("asfaf");
      case 5: return FALSE;
      default:
         i ++;
   end
   
end

procedure proctest(variable wtf := 23) begin
   
end



procedure stuff begin
   variable ar, i, k, v;
   
   call elsetest;
   call inittest;
   
   // break/continue test
   while (i < 555) do begin
      i := 10;
      break;
      i := 20;
   end
   
   while (777) do begin
      i := 60;
      continue;
      i := 120;
   end
   for (i:=0 ; i<45; i++ ) begin
      k := 1;
      break;
      continue;
      i := 34;
   end
  // {"asdasdsa" : 'A', 2: 'B'}
   foreach (k: v in ar) begin
      k := 100 ;
      continue;
      v := 200 ;
   end
   
   foreach (k: v in [1,2,3] while (i < 0)) begin
      k := 100 ;
      if (i == -1) then continue;
      v := 200 ;
      
   end
end

variable trapv;

procedure start begin
   variable a,b,c,d[5],f,trap[25];
   variable k,v,i;
   
   
   a[1] := get_ini_setting("asdasdsa"); // get_array(a, 1)   set_array(a, 1, get_sfall_arg)
   
    
   //a := b[23][525][25];
   a := b[4545].asasd565;
   
   if (cur_map_index != trap[1]) then 
   
   // a[1][2]  - get_array(get_array(a, 1), 2)
   a[1][5].some[5].very.long.combination += 5;     // set_array(get_array(a, 1), 2, get_array(get_array(a, 1), 2) + 5);
                     // tmp := get_array(a, 1); set_array(tmp, 2, get_array(tmp, 2) + 5)
   
   call stuff;
   trap := {};
   trap.id := 3434 % 23;
   trap.key := 232;
   //c[0] := 1;
   b.ccc := a.fwfw + 3434;

   a := {"fdf": 2, 6: -1};
   f := [1,2];
   
   f := (a.fwf == 0);
   
   d := [(1 and 2), -3.14*2,["W", "T", "F"]];
   
   c[0] := f["sfs"];
      
   //a := b.key;   
   for (i:=0; i<5; i++) begin
      a:=1;
      i++;
      if (1) then
         b.ccc++;
      else
         trapv := 0;
   end
end
