#############################################################
#  Message File: ACMynoc.msg                                #
#                                                           #
#       Body Type:  NMPRIM                                  #
#       Combat AI: Berzerker                                #
#       Weapons: Sledgehammer[in hand]                      #
#       HP: 75                                              #
#       Skills to note: 80% Throwing                        #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################

{100}{}{You see the bridge guard.}
{101}{}{You see Mynoc, the bridge guard.}

#############################################################
#  The following lines are for the dialog which the NPC     #
#  says. This will be disorganized because of the Design    #
#  Tool.                                                    #
#############################################################

{150}{}{Before you stands a large warrior of your village,
 holding a spear.}
{151}{}{[TALK]}
{152}{MYNOC1}{Hello, Chosen One. Off to find the GECK?}
{153}{}{Yes.}
{154}{}{Yes. But before I go, I would like to ask you some
 questions.}
{155}{}{Not just yet. I'm going to look around a little
 bit more.}
{156}{MYNOC2}{Well, may the gods watch over you.}
{157}{}{Thank you, goodbye.}
{158}{MYNOC3}{What do you want to know?}
{159}{}{What can you tell me of the men who trade with our
 village?}
{160}{}{What can you tell me about this object I have from
 a vault?}
{161}{}{Nothing, never mind.}
{162}{MYNOC4}{Very well, but don't waste too much time. Without the GECK,
 we're doomed.}
{163}{}{I know, don't worry -- I've got it all under control.}
{164}{}{Why?}
{165}{}{I must be going. Goodbye.}
{166}{MYNOC5}{The traders? They come from Klamath about every two months. There
 won't be another here for a month or more, but Klamath's only a few days
 east of here.}
{167}{}{Thank you. Goodbye.}
{168}{}{What can you tell me about this object I have from
 the sacred vault?}
{169}{MYNOC6}{Looks like a metal water gourd. Maybe the
 vault sent it to us as an omen.}
{170}{}{Can you tell me who brought this item to our village?}
{171}{}{Thank you. I must be going. Goodbye.}
{172}{MYNOC7}{I hope you do.}
{173}{}{Your overconfidence makes all of us suffer! Goodbye!}
{174}{}{Goodbye.}
{175}{MYNOC8}{Why? Look around you -- our village dies. The gardens wither and
 every day children and old ones collapse. You must bring Eden to us before
 it is too late!}
{176}{}{And I will take care of it. Goodbye.}
{177}{}{I am the Chosen One -- I "must" do only as I
 please. Goodbye.}
{178}{MYNOC9}{I don't remember his name, just that he was old and loud -- too
 loud for proper manners -- but he knew many things. He was from Klamath, east
 like I said.}
{179}{}{Thank you, goodbye.}
{180}{MYNOC10}{Are you still here? You must go find the GECK. Staying here
 doesn't help us.}
{181}{}{This bridge is all you need to worry about,
 friend. I can take care of myself.}
{182}{}{I was just heading out. Goodbye, my friend.}
{183}{}{I will speak to you no longer, insubordinate pig!}
{184}{}{I would like to ask you another question.}
{185}{MYNOC11}{That was quick! Have you found the holy Vault 13?}
{186}{}{Yes.}
{187}{}{No, not yet.}
{188}{MYNOC12}{You have? Wonderful! Did you bring back the
 GECK?}
{189}{}{No.}
{190}{}{No. I haven't spoken to the people of the vault yet.}
{191}{}{I don't believe that's any business of yours, my friend.}
{192}{MYNOC13}{No? Chosen One, three old ones have died since you left. You must
 not waste any more time.}
{193}{}{I'll find it, don't worry.}
{194}{}{I'm getting sick of your constant nagging.}
{195}{MYNOC14}{Well, why are you talking to me? Talk to them, and get the GECK.}
{196}{}{I will -- all in good time, my friend.}
{197}{}{I'm getting sick of your constant nagging.}
{198}{MYNOC15}{What news of the GECK, Chosen One?}
{199}{}{I have found the vault!}
{200}{}{I have not been able to find Vault 13.}
{201}{MYNOC16}{Well, look, it's the Chosen One.}
{202}{}{Hello.}
{203}{}{Shut up.}
{204}{}{Can I ask you a question?}
{205}{MYNOC17}{No, I've no time for you.}
{206}{}{Whatever. Good bye.}
{207}{}{Oh well. See you around.}
{208}{}{Go die.}
{209}{MYNOC18}{Greetings, dull one! See bridge? You cross, you be careful.
 Bridge dangerous. You not want to fall. Okay?}
{210}{}{Umm... Hunh?}
{211}{}{Wretch! You have failed the village!}
{212}{}{You betray us. For that you'll die!}
{213}{}{You are a traitor to your own people.}
{214}{}{Why do you do this?}
{215}{}{The Elder was wrong. You are evil.}

{300}{MYNOC19}{My father taught me how to make stronger blades than most. Get me a piece
 of flint and I'll fix your spear, too. You'll need it in the wilderness.}
{301}{}{Where would I get some of this flint?}
{302}{MYNOC20}{They say your Aunt Morlis has been hoarding a piece. She's so
 ill-tempered I don't think anyone's asked her. Of course, the witch will want
 something in return.}
{303}{}{Thanks. Goodbye.}
{304}{MYNOC21}{Did you talk your aunt out of her flint?}
{305}{}{Yes, I have some right here.}
{306}{}{Not yet.}
{307}{MYNOC22}{It's a good piece. Give me your spear.}
{308}{}{Here you go.}
{309}{}{I guess I don't have one.}
{310}{MYNOC23}{Now, you put the pieces like so...}
{311}{MYNOC24}{The Chosen One without a spear? Well, you'll have to take one of
 mine. Now, let's get to work...}
{312}{MYNOC25}{Here is your new spear. Now you know how to sharpen your blades.}
{313}{}{Thank you, my friend -- this will help a lot.}
{314}{}{Yes, but I was wondering about your spear. It looks a little
 different.}


# added in for time limit
{400}{MYNOC26}{Welcome home, Chosen One! Did you find the vault? Have you returned with the GECK?}
{401}{}{Me not find yet.}
{402}{}{No, I haven't found it yet.}
{403}{}{I'm not in the mood for your questions. Goodbye.}
{404}{MYNOC27}{Things are not going well, Chosen One. The drought is getting worse and our crops are
 sure to fail. We are trying to salvage what we can to build up our food reserves.}
{405}{}{Why no trade with other villages?}
{406}{}{Me doing best me can. Me find GECK. Me return.}
{407}{}{Why can't we trade with other villages for the food we need? }
{408}{}{I'm doing my best. When I find the GECK I'll return with it.}
{409}{MYNOC28}{We are a simple people and have little to offer in trade. The few towns that we have
 contacted while you were away have shown no interest in helping us.}
{410}{}{Me see.}
{411}{}{I see.}
{412}{MYNOC29}{You are our only hope, Chosen One. Please do not fail us!}
{413}{MYNOC30}{It is good to see you, Chosen One. How fares your quest?}
{414}{}{Me still look.}
{415}{}{I'm still looking.}
{416}{}{I don't want to talk about it.}
{417}{MYNOC31}{You must hurry. Things are getting worse here at home. Soon there will be little food and
 the Elder speaks of rationing what we have. I fear for the future of Arroyo.}
{418}{MYNOC32}{Chosen One! Please tell me that you have completed your quest. Our village is dying, and so
 are our people. }
{419}{}{No, me still look.}
{420}{}{No, I'm still looking.}
{421}{}{How are things?}
{422}{MYNOC33}{I am sorry, Chosen One, but I am beginning to question my faith in you. The very lives of
 our people are in your hands. Please find the holy Thirteen and return to us with the GECK!}
{423}{MYNOC34}{Our crops fail, the brahmin die, everyone goes hungry now. The cries of the children at night
 allow no one any sleep. We are becoming a desperate people.}
{424}{}{Me continue look.}
{425}{}{I'll do what I can.}
{426}{MYNOC35}{Once again you return to us, Chosen One. Not empty-handed, I hope?}
{427}{}{Me sorry, no find GECK yet.}
{428}{}{I'm sorry, I still haven't found the GECK.}
{429}{}{I've had enough of this.}
{430}{MYNOC36}{People are dying here while you stroll about the lands. Perhaps you should be searching
 elsewhere instead of returning here.}

{500}{}{Have you talked to the Elder yet?}

#############################################################
#  TELL - ME - ABOUTS                                       #
#############################################################
{1000}{}{Elder}
{1001}{}{Founder}
{1002}{}{Vault Dweller}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{Chosen One}
{1007}{}{Shaman}
{1008}{}{Hakunin}
{1009}{}{Healing Powder}
{1010}{}{Bridge}
{1011}{}{Mynoc}

{1100}{}{The Elder is your mother and our leader.}
{1101}{}{Our great ancestor who gave us knowledge.}
{1102}{}{The first to fight and win over chaos.}
{1103}{}{That would be our beautiful village.}
{1104}{}{That's a trading outpost a few days east of here.}
{1105}{}{The Vault is heaven.}
{1106}{}{You are the Chosen One.}
{1107}{}{He heals us with his herbs and magic. He is in the
 northern part of our village.}
{1108}{}{He heals us with his herbs and magic. He is in the
 north part of our village.}
{1109}{}{It is a magic powder which will heal you, but will
 make you sleepy.}
{1110}{}{The Great Bridge exits our village in the south.}
{1111}{}{That would be me.}

#added by killap - expansion
{600}{}{Any final advice for me before I head out into the unknown?}
{601}{MYNOC37}{Certainly. Beware the weapons of the Outsiders. The gecko's bite is nothing compared to the destructive power of their boom-sticks.}
{602}{}{Got it. Anything else?}
{603}{MYNOC38}{Do not give your trust freely. Honor means very little out in the wastes. Stay alert and always question the motives of others.}
{604}{}{Sure thing. Is that all?}
{605}{MYNOC39}{Never forget your roots. The world outside our village is full of shiny toys and luxuries that might make our life here in Arroyo appear simple and plain.
 But remember that the lifestyle of the Outsiders produces wicked men ruled by greed and corruption. Be wary not to become like He-Who-Must-Not-Be-Named.}
{606}{}{I'll never forget my roots. Thanks for the advice, Mynoc.}
{607}{}{He-Who-Must-Not-Be-Named? Uh... who?}
{608}{MYNOC40}{Are you so drunk with the glory of being the Chosen One that you've forgotten about... [Mynoc quickly glances around to be sure no one is listening in, then leans forward and lowers his voice to a whisper.] ... Kaga?}
{609}{}{Oh! Yeah, that guy. I'll make sure I don't end up like him. Thanks.}
{610}{}{Oh, that's who I thought you meant. But, uh, why don't you go ahead and tell me what his deal is again. I really love that story.}
{611}{MYNOC42}{[Mynoc mumbles something under his breath and shakes his head before beginning his tale.] As you should know, he was once the greatest warrior of our tribe. He led many expeditions into the outside world, and it was there where corruption began to poison his mind.}
{612}{MYNOC43}{He became infatuated with the ways of the Outsiders, where power could bring anyone great respect and luxury. He began to view himself as superior to his fellow tribesmen who were content to live a more simple life.}
{613}{}{What a jerk.}
{614}{}{Go on.}
{615}{MYNOC44}{When our tribe fell into these hard times, he deemed himself our people's savior and entered the Temple of Trials to prove himself to be the Chosen One.}
{616}{}{Go on.}
{617}{}{Nevermind, I don't want to hear this story anymore. Bye.}
{618}{MYNOC45}{He made his way through the Temple, quickly reaching the final test: a hand-to-hand battle with a fellow warrior.}
{619}{}{Go on.}
{620}{}{Wait, he blew up that door and everything? Do we have it rebuilt every time someone goes through the temple? Speaking of that, who built the temple in the first place?}
{621}{MYNOC46}{I don't have time to answer all your silly questions. Do you want me to finish the tale, or not?}
{622}{}{Sorry. Please continue.}
{623}{}{Actually, I think I'm ready to go. See you around.}
{624}{MYNOC47}{During the final trial, He-Who-Must-Not-Be-Named unsheathed a hidden blade and used it to kill his opponent. When the Elder confronted him about his dishonorable use of a hidden weapon, he argued that it was not cheating, but rather proved him to be a cunning warrior.}
{625}{MYNOC48}{The Elder did not agree. He-Who-Must-Not-Be-Named was forcibly exiled from our tribe and his name was never to be spoken amongst us again. As he was cast away into the wastes, he swore an oath of vengeance. Vengeance against our tribe, and especially against you.}
{626}{}{Me? What'd I do?}
{627}{}{Thanks for the story, but I'd best be on my way now.}
{628}{MYNOC49}{You are the Chosen One, a title he feels is rightfully his. His pride will not allow you to live.}
{629}{}{I'm not going to worry about it. He's probably dead out in the wastes by now, anyway.}
{630}{}{I'll be on my guard. Hopefully he's dead out in the wastes by now.}
{631}{MYNOC50}{Listen, and understand. He-Who-Must-Not-Be-Named is out there. He can't be bargained with. He can't be reasoned with. He won't feel pity, or remorse, or fear. And he absolutely will not stop, ever, until you are dead.}
{632}{}{You know, I think you might be overdoing it with the melodrama, just a tad. Anyway, thanks for the advice. I'll see you around, Mynoc.}
{633}{}{I'll keep that in mind. Take care, Mynoc.}

{640}{}{Could you tell me anything about this Kaga guy?}
{641}{MYNOC41}{[His eyes go wide and he looks around nervously as if expecting to suddenly be struck by lightning.] Have you lost your senses out in the wastes?! You should know better than to speak the name of the outcast! He is to be referred to only as He-Who-Must-Not-Be-Named.
 Our village suffers enough without inviting the wrath of the Gods upon us. [He raises his eyes nervously to the sky.]}
{642}{}{Sorry about that, Mynoc. But would you mind telling me what Ka... I mean, "He-Who's" deal is again? I really love that story.}
{643}{}{You know, I'd forgotten how stupidly superstitious you people could be. I'll see you around.}

{650}{}{I've faced him before, so I'm sure I can handle him if our paths cross again.}
{651}{}{Actually, he's already dead. I left his corpse out there to rot in the wastes.}
{660}{MYNOC51}{[Mynoc nods grimly.] He may have strayed from the path, but he was once a great and respected warrior. I hope his troubled soul has found peace in the next world.}

{661}{}{Indeed. I'll see you around, Mynoc.}
{662}{}{Whatever. He seemed like an asshole to me. I'll see you around, Mynoc.}


##############################################
#BONUS LINES NEEDED FOR THE TALKING HEADS MOD#
##############################################
