{100}{}{You see a computer terminal.}
{101}{}{You see the library computer terminal.}
{102}{}{You see a standard computer terminal. It appears to be functional and ready for input.}
{103}{}{You access the computer and quickly scan all available files. You find the location of Vault 13
 and copy it to your PIP-Boy.}
{104}{}{You are having difficulty accessing the files.}
{106}{}{Other than the location of Vault 13 and some schematics, the computer contains no useful information.}

# phobos2077: crafting
{200}{}{[Search for more information]}
{201}{}{You also find several schematics for electronic devices. You upload them to your PIP-Boy.}