{100}{}{You see someone in power armor.}
{101}{}{You see the Quartermaster.}
{102}{}{You see someone wearing power armor of an unusual design.
 There is an insignia on the breastplate that you are unfamiliar with.}

{103}{}{Who the hell are you guys... Alert! Intruders on the base!}
{104}{}{What the... I can see why you're here. You obviously want
 to get rid of that antique suit you're wearing.}
{105}{}{Why are you out of uniform, soldier?}
{106}{}{Die!}
{107}{}{Uh, yeah...}
{108}{}{Uh...}
{109}{}{Me new here.}
{110}{}{Me not one you soldiers!}
{111}{}{Uh, well...}
{112}{}{I'm new here.}
{113}{}{I'm not one of your soldiers!}

{114}{}{Uh, what? Can't think of a good excuse? I'm waiting, soldier!}
{115}{}{Me not have uniform yet.}
{116}{}{I don't have a uniform yet.}

{117}{}{You're a bit on the slow side, aren't you? (sigh) Well, that's
 not your fault. I have a brother just like you. Anyway, are you new here?
 I don't recall seeing you before.}
{118}{}{Are you new here? I don't recall seeing you before.}
{119}{}{Yes! Me new here!}
{120}{}{Yes, I'm new here.}

#pbs: changed 121 to give you power armor
{121}{}{Well, you'll get the recruitment standard issue, then.
 Here are your personal suit of Power Armor and a rifle. Don't loose
 any of them!
 So suit up, and take your weapon. You should report to the Drill Sergeant
 afterwards.}
{122}{}{Thanks!}

{123}{}{You're welcome. Now get out of here. I've got work to do and I
 don't want to be disturbed.}

{124}{}{I'm busy right now. Come back later.}

{125}{}{Hello, recruit. I just got a call from your Sergeant. He says
 I'm to suit you up and send you back to him. That right?}
{126}{}{Yes.}

{127}{}{This base is on alert and I don't recognize you. Show me your
 papers, soldier.}
{128}{}{Me not have papers with on me.}
{129}{}{Me no need papers!}
{130}{}{I don't have my papers with me. They're in my footlocker.}
{131}{}{Papers? I've got your papers right here!}

{132}{}{Wrong answer. You're to carry your papers with you at all times
 and you should know that!}
{133}{}{Oops.}