# 0. Look
{100}{}{You see a kindly-looking older woman.}

{150}{}{You see Mom, busily cooking and cleaning.}
{151}{}{You see a robust older woman, with a cheerful smile on her face.}

# 1. Low Intelligence (WtG)
{200}{MOM1}{Hello there, I'm Mom. I haven't seen you around here before.}
{201}{MOM2}{Hello again. What can Mom do for you?}
{202}{}{Me }
{203}{}{Mmmm. Ook? Bye bye Mommy.}

# 2. Low IQ more (1)
{220}{MOM3}{You already half-ate me out of house and home. Why dontcha find someplace else to hang out for a while? You've eaten here enough today.}
{221}{}{Well }
{222}{}{ you sure do look as though you're a mite confused. I hate to see a critter suffer. Want something to eat?}
{223}{}{Me full. Mom food good. Bye Mom.}
{224}{}{Me pay?}
{225}{}{Me go. Bye Mom.}

# 3. Pay? (2)
{240}{MOM5}{Well, OK. Whatcha got? (Mom reaches for your purse)}
{241}{}{Mom? (you hold out your purse)}
{242}{}{No! Me go. Bye Mommy.}

# 4. No, not really (7,9)
{250}{MOM6}{No, not really. I'm sorry. We just have rat-pie, rat-loaf, and spaghetti.}
{251}{MOM7}{What'll it be this time around?}
{252}{}{Uh, could I get something without so much rat in it?}
{253}{}{I guess I'll have the rat-loaf.}
{254}{}{I guess I'll have the rat-pie.}

# 5. Not so much rat in it (4)
{270}{MOM8}{You could have the spaghetti. It doesn't have too much rat in it - just the sauce, that's all.}
{271}{}{Well, OK, I guess I'll have the spaghetti with rat-sauce.}

# 6. Here's your food (4,5)
{280}{MOM9}{I'll get you a nice helping right away. That'll be $10.}
{281}{}{I don't have enough money right now. Let me ask you a question instead.}
{282}{}{$10 for rat? You've got to be crazy. Heck, around the village we charge much more for a nice juicy one. That's a deal.}
{283}{}{Well, OK. Here's your money.}
{284}{}{I think I've changed my mind. Let me ask you a question instead.}
{285}{}{I think I'll come back later. Goodbye.}

# 7.  Thanks Mom (6,20)
{300}{MOM10}{You have quite an appetite there. I love to see a healthy eater. Will that do it for you?}
{301}{}{Not a chance, Mom. I want seconds.}
{302}{}{Sure will. Let me ask you something, Mom.}
{303}{}{That's it for now. Goodbye, Mom.}

# 8. What's there to do here? (13)
{320}{MOM11}{Well, I sure need someone to deliver a meal to Smitty. He's just west of here at the junkyard. Will you do it for me? I'll give you a free meal if you do.}
{321}{}{Sure, I don't mind.}
{322}{}{Let me think about it. In the meantime, let me ask you about something else.}
{323}{}{Uh, sorry, Mom. I can't. Goodbye.}

# 9. Random Food item list (13)
{340}{MOM12}{You're in luck. We're having radscorpion stew.}
{341}{MOM13}{We're having braised pig-rat.}
{342}{MOM14}{We're serving steamed radscorpion tails in drawn butter.}
{343}{MOM15}{Cabbage soup is all I've got right now.}
{344}{MOM16}{Fresh brahmin fries!}
{345}{MOM17}{Pipin' hot gecko pie, comin' up.}
{346}{MOM18}{Flank steak.}
{347}{MOM19}{Well-marbled molerat.}
{348}{MOM20}{Fricasseed floater.}
{349}{MOM21}{Filet mignon.}
{350}{MOM22}{Medallions of grilled gecko.}
{351}{MOM23}{Mantis marsala.}
{352}{MOM24}{Molerat manicotti.}
{353}{MOM25}{Brahmin en brochette.}
{354}{MOM26}{Radscorpion en croute.}
{355}{MOM27}{It's Smeat!}
{356}{MOM28}{Uh, I'm not sure, but it tastes like chicken.}
{357}{MOM29}{Centaur chops, my specialty.}
{358}{MOM30}{It's a surprise.}
{359}{}{I can't give away my secret recipes!}
{360}{}{Really?}

# 10. Low IQ hand food (3)
{375}{MOM31}{Here you go. You look half-starved. (Mom hands you a big steaming plate of delicious smelling food.)}
{376}{}{Tank-u, Mom.}

# 11. Low IQ fed (10)
{385}{MOM32}{There you go. I knew you'd enjoy that.}
{386}{}{Mmm, yum yum. Bye, Mom.}

# 12. Sure I'll deliver it (8)
{395}{MOM33}{Thanks so much. I'd do it myself but there's nobody to watch the place while I'm gone. Here's Smitty's meal. If I didn't have it brought to him I'm sure he'd forget to eat.}
{396}{}{I'll bring it right over to him.}

# 13. Hello (WtG, 6,7,8,15,18)
{405}{MOM34}{I'm so disappointed in you. Poor Smitty had to come get his own meal. Now what do you want?}
{406}{MOM35}{Hello there, my name's Mom and I run this place. Got the best food north of New Reno, too.}
{407}{MOM36}{What did you want to talk to Mom about?}
{417}{MOM37}{Well if it isn't my hero. What can Mom do you for today?}
{408}{}{You're not my mom.}
{409}{}{Have you heard of a Vault or anyone named Vic?}
{410}{}{What's there to do here in town?}
{411}{}{What do you have to eat here?}

# 14. I'm not your mom (13)
{425}{MOM38}{I know that. But everyone calls me that. Heck, I even treat people like they're my kin - long as you obey my rules that is.}
{426}{}{Rules?}

# 15. Rules? (14)
{435}{MOM39}{That's right. No stealing, no cursing, and no fighting - not in my shop you don't. 'Cause if'n you do, out you'll go. I like things peaceful here.}
{436}{}{I see. Let me ask you something else.}
{437}{}{That makes sense. See you later, Mom.}

# 16. Vic or Vault? (13)
{445}{MOM40}{Well now, there's a Vault City a ways east of here and a little north. And Vic, hmm, lemme think.}
{446}{}{I sure hope you know where Vic is. He's a trader.}
{447}{}{Thanks but that's all I need to know. Bye, Mom.}

# 17. Trader Vic (16)
{455}{MOM41}{Trader Vic? Now that rings a bell. Yes, I think he's being held by Metzger for some reason.}
{456}{}{Who's Metzger and where do I find him?}
{457}{}{That's great, Mom. Thanks.}

# 18. Who's Metzger (17)
{465}{MOM42}{Metzger's the head of the local Slaver's Guild. He's got all kinds of people locked up in his place. It's right up the street, just north of here.}
{466}{MOM43}{Metzger used to be the head of the local Slaver's Guild. He had all kinds of people locked up in his place. But I don't know now - I heard he's been killed.}
{467}{}{Thanks for the information. Let me ask you something else, Mom.}
{468}{}{I need to go take care of some business. Thanks, Mom.}

# 19. Smitty's meal in progress (WtG)
{475}{}{Go on and get that meal to Smitty now.}
{476}{}{I won't help you out until you keep your word.}
{477}{}{Hurry up now.}
{478}{}{Go give Smitty his meal. Hurry up.}
{479}{}{Stop your lollygagging and get that meal to Smitty.}

# 20. Reward (WtG)
{485}{MOM44}{That was good work. You must have worked up quite an appetite.
 I have a real treat for you as a reward. A combination plate of the best
 darn food I have here, just for you.}
{486}{}{That sounds great! Let me at it!}
{487}{}{Gee, Mom. I don't think I can eat just now, but thanks anyhow. Goodbye.}

# 21. What do you know about that haunted house? (13)
{500}{MOM45}{Hmm, don't know much about that. Someone's probably just having
 a little fun, that's all.}
{501}{}{Has it always been haunted?}
{502}{}{Does anyone use that house?}
{503}{}{I agree. Bye.}

# 22. Started 2 years back... (21)
{520}{MOM46}{Started about 2 years back. I heard about the moaning and the spirits and all.
 Don't believe it myself.}
{521}{}{Two years, huh? Anybody use the place back then?}
{522}{}{Me neither. Thanks.}

# 23. Anyone used it then? (21-22)
{540}{MOM47}{One of the boys used to sleep there a few years back. Maybe he knows something.}
{541}{}{Who?}
{542}{}{Probably not. Bye.}

# 24. Who? (23)
{560}{MOM48}{He used to come by and try to pawn stuff. Jewelry mostly. I remember
 a little gold locket he kept for himself.}
{561}{}{Do you remember his name?}
{562}{}{Locket? Strange. Who was it?}
{563}{}{Let me ask you something else.}
{564}{}{Thanks, bye.}

# 25. Name? (24)
{580}{MOM49}{Not sure. Think it was Joseph, Joel or something like that. He's almost 19
 now.... A shame, really. I believe he's joined up with some local thugs.}
{581}{}{Thanks. I have another question for you.}
{582}{}{Thanks, bye.}

# 13b. PC Response line added to node 13
{600}{}{What do you know about that haunted house?}

{800}{}{I noticed there seems to be a lot of orphans around town.}
{801}{MOM50}{It's a shame, isn't it? Those poor children living on the streets like that... A lot of them steal to get by -- from
 outsiders mostly -- so if you catch one trying to relieve you of something, please take pity on 'em. I'm not saying it's
 right, but it's a harsh world we live in, and we all do what we have to in order to make it through the day.}
{802}{}{There's gotta be something we can do about this. From what I hear, you seem to be the only person around that
 actually gives a damn about those kids.}
{803}{MOM51}{Why of course I do. Children are our future. They don't *have* to grow up to be jetheads, thugs, and whores like
 most of their deadbeat parents. Why, with an education and some love and care, these kids could grow into the kind of
 decent folk that we so desperately need in this world. I've tried establishing an orphanage for them, but sadly, that
 didn't pan out.}
{804}{}{Maybe it's time to give it another try. I'm not going to be in town for too much longer, but I'll do what I can to help while I'm here.}
{805}{}{That's too bad. Well, nice talking with you. Bye.}
{806}{MOM52}{Yes, perhaps you *could* help. You see, I procured a large building over on the south-west side that, with a little work, would make an excellent
 orphanage. But a bunch of lowlifes are squatting there and refuse to leave unless I pay an absurd fee. Even if I *had* the money, I wouldn't give
 it to them bullies -- they'd just use it to further poison themselves. I'd go to the authorities, but unfortunately, there's no such thing in the Den.
 Perhaps you'd have better luck at convincing them to leave?}
{807}{}{I'm sure I could get them out of there. One way, or another. I'll let you know once they're gone.}
{808}{}{Never was a fan of evicting people. Perhaps someone else is better suited for this.}
{809}{MOM53}{Oh... I see. That's really too bad. Thanks for trying though. Would you like anything before you go?}
{810}{}{Nope. Bye Mom.}

#added by killap - RP 1.3
{811}{}{If I catch one of them little bastards stealing from me, it'll be the last thing they ever do. I don't care what
 their excuse is, a thief is a thief. Bye.}

{820}{}{Good news, Mom. The building's all yours. I ran into a little snag, but those squatters won't be bothering you again.}
{821}{}{The squatters said they'd leave and that they're sorry for causing trouble. They're currently cleaning the place up to try and make it up to you. I was thinking maybe, if they do well enough, you could offer some of them jobs.}
{1821}{}{Good news, Mom. The building's all yours. It took a little convincing, but I got the squatters to agree to pack up and move on.
 I don't think they'll be bothering you again.}
{822}{MOM54}{Oh, that's great news! Thank you so much! I just hope no one was hurt in the process. I'll get in touch with some friends and we'll get
 started right away. If you're still in town a few days from now, you should stop by. Hopefully, we'll have things up and running by then. Oh,
 I'm so excited! Thanks again. Here, this meal's on me.}
{1822}{MOM55}{Oh, that's great news! Thank you so much! I'll get in touch with some friends and we'll get started right away. If you're still in town
 a few days from now, you should stop by. Hopefully, we'll have things up and running by then. Oh, I'm so excited! Thanks again. Here, this meal's on me.}
{823}{MOM56}{Hmm... I suppose everyone deserves a second chance. I'll stop over there with some friends and we'll talk things over with 'em. Thank you so much
 for helping me with this. If you're still in town a few days from now, you should stop by. Hopefully, we'll have things up and running by then. Oh, I'm so
 excited! Thanks again. Here, this meal's on me.}
{824}{}{Thanks Mom. See you around.}
{850}{}{You help establish an orphanage for the children of The Den.}

# crafting - phobos2077
{2001}{}{You must be quite the cook, Mom. Any pointers you could give me?}
{2005}{}{Sure. I can show you how I make a fish soup and something else, too.}
{2006}{}{Sounds great! Show me.}
{2007}{}{I changed my mind.}
{2010}{}{Well, I have a special recipe for fish soup and people seem to like my stew. I could teach you for $400. That's not cheap, but cooking is my livehood, you see.}
{2011}{}{It's a deal.}
{2012}{}{My, that's really expensive. I think I'll leave cooking to you then.}
{2015}{}{Well, I didn't want to chase you away that easily. How about $200?}
{2016}{}{That's better. I'll take it.}
{2020}{}{OK, give me just a moment to find the recipes...}
{2021}{}{... that's how my mother used to cook it. This special ingredient makes it really healthy.}
{2022}{}{They must be feeling the aroma all the way over on the West Side! I think I'll go try to apply your technique, see if I got it down right.}
{2023}{}{Thanks. Can I ask you something else?}


##############################################
#BONUS LINES NEEDED FOR THE TALKING HEADS MOD#
##############################################
{7700}{MOM4}{Well Dear, you sure do look as though you're a mite confused. I hate to see a critter suffer. Want something to eat?}