# 0. Look
{100}{}{You see a greasy old coot.}

{150}{}{You see Smitty the mechanic and junkyard owner.}
{151}{}{You see a greasy old coot with dirty work-clothes on.}

# 1. Get out floats (WtG)
{200}{}{You varmint! Git outta here before I hafta learn ya!}
{201}{}{Git outta my place!}
{202}{}{Git off my land!}
{203}{}{Dang varmint, git outta here.}
{204}{}{Go the hell away from me.}

# 2. Low Intelligence (WtG)
{220}{}{Hey, git off my land.}
{221}{}{You there, dumbass, git outta here.}
{222}{}{Git, go on, git!}
{223}{}{I ain't got time for your type.}
{224}{}{Sorry, I guess I don't speak idjit.}

# 3. Hello (WtG, 4,5,11, 17,20,25)
{240}{SMIT3}{Hello there, young feller. What can old Smitty do ya for?}
{241}{SMIT4}{Hello there, cute-stuff. What can old Smitty do ya for?}
{242}{SMIT1}{Jumpin' jiminy, what can I do for ya now?}
{243}{SMIT2}{Hey there, I really enjoyed my meal from Mom's. Thanks. Now what can old Smitty do for ya?}
{244}{}{I was just wondering what you do here?}
{245}{}{Say, old timer, I have this thingy here that I picked up in Gecko...}
{246}{}{Hey Smitty, I was wondering about that car you had for sale.}
{247}{}{I brought your meal from Mom's.}
{248}{}{Say, old timer, I have this thingy here that I picked up in Klamath...}
{249}{}{I was just looking around a bit. See you later, Smitty.}

# 4. Thing from Gecko (3)
{260}{SMIT5}{Let old Smitty here take a look at it.}
{261}{}{Sure, here it is.}
{262}{}{On second thought, let me ask you about something else.}
{263}{}{Maybe another time. Goodbye, Smitty.}

# 5. Thing from Klamath (3)
{280}{SMIT5}{Let old Smitty here take a look at it.}
{281}{}{Sure, here it is.}
{282}{}{On second thought, let me ask you about something else.}
{283}{}{Maybe another time. Goodbye, Smitty.}

# 6. Use Controller? (4)
{300}{SMIT7}{Well now, that looks to me like it's an old fuel cell controller. Hmm, I bet if I used that with the old Highwayman I could get her purring like a kitten.}
{301}{}{Huh?}

# 7. Use Regulator? (5)
{310}{SMIT8}{Hmm, that looks jist like a fuel cell regulator. If I had a car that ran, it'd sure improve the mileage on it.}
{311}{}{Huh?}

# 8. Meal from Mom's delivered (3,18)
{320}{SMIT10}{That was mighty darn kind of you. Thanks mucho, compadre. Here's a little something for your trouble. It'll come in handy 'round these parts. (He hands you a Stimpack.)}
{321}{}{Thanks, Smitty. No problem. See you around.}
{322}{SMIT9}{Well, uhhh... Thanks, but I already headed over to Mom's and got some eats myself, so I won't be needin' that anymore.}
{323}{}{Oops, I'm not the usual delivery person. He called in sick today. Can I get some experience points anyway?}
{324}{}{OK, sorry about the mix-up. I hope Mom doesn't fire me! I really need this job.}
{325}{}{You know we're not doing the free meal after 24 hours thing anymore, right?}
{326}{}{Well, maybe I'll just eat it myself then.}
{327}{}{Mom's not gonna be too happy with this.}

# 9. Tell about car (6,7)
{330}{SMIT11}{Well, you see, I've got this car, a Chrysalis Motors Highwayman. She's a beaut, too. They used to say "Nothing can stop a Highwayman." Built tough, that's what they were.}
{331}{}{Yeah, so what's that got to do with me?}

# 10. Car-Controller (9)
{340}{SMIT12}{Well, you see, I thought I needed a battery for the thing but all I really need is a fuel cell controller. Them things was always going bad on 'em.}
{341}{}{Well, I've got one of those.}

# 11. I've got one of those (10)
{350}{SMIT13}{That right? Here's the deal. You give me $2,000 and I'll sell you the car. Heck I'll even install the fuel cell controller for you. Should run good as new. I'll even charge it up with some extra micro fusion power cells I got.}
{351}{}{That sounds good to me. Here's the money and the part.}
{352}{}{I don't think I want to do that right now. Let me ask you about something else, Smitty.}
{353}{}{Let me think about it. I'll see you around, Smitty.}

# 12. Here's the car (12)
{370}{SMIT14}{Jist take it easy with her 'til she warms up, now.}
{371}{}{OK, I will. Thanks, Smitty.}

# 13. Car-Regulator (9)
{380}{SMIT15}{Well, a lot an' not so much at the same time.}
{381}{}{Huh?}

# 14. What? (13)
{390}{SMIT16}{What I'm saying is that havin' a regulator is nice but you need to find a fuel cell controller.}
{391}{}{Why's that?}

# 15. Why? (14)
{400}{SMIT17}{'Cause if'n you had a controller, and $2,000, I could fix this here Chrysalis Motors Highwayman that I got here and you could drive around in style.}
{401}{}{Really? Where can I find a fuel cell controller?}

# 16. Where do I find one of those? (15)
{410}{SMIT18}{Now that's a silly question. Don't you think if I knew that then I'd be driving around in the car?}
{411}{}{Wow. I'll have to look for one of those.}

# 17. Look for one (16)
{420}{SMIT19}{Be a good idea. If you find one jist come on back here with it. Oh, and don' forget the $2,000, neither.}
{421}{}{Sounds like a plan, Smitty. Hey, let me ask you about something else.}
{422}{}{I'm going to go look for one right now. Goodbye.}

# 18. Player bought car (WtG)
{430}{SMIT20}{Hey there, how's that car runnin' for ya?}
{431}{}{Pretty good, Smitty, but I found this part for the car and I don't know what to do with it.}
{432}{}{Great, Smitty, just great. Hey, I brought you a meal. Compliments of Mom.}
{433}{}{Real good, Smitty, real good. Thanks. See you around. Goodbye.}

# 19. Have regulator (18)
{450}{SMIT21}{Well now, that's a fuel cell regulator. That'll give you better mileage per energy cell. I could put that in for you, if you had say $750 for my trouble.}
{451}{}{That sounds like a deal, Smitty. Here's the part and the money.}
{452}{}{I'll have to think about it, Smitty. Goodbye for now.}

# 20. What do you do here? (3)
{460}{SMIT22}{Mostly I just keep watch over all this old junk. Only got one thing worth doodly-squat.}
{461}{}{What's that?}
{462}{}{I figured that. Let me ask you something else.}

# 21. What's worth anything? (20)
{470}{SMIT23}{Why, it's none other than this Chrysalis Motors Highwayman. They used ta say that "Nothing can stop a Highwayman." They shore built 'em tough, I'll say that for 'em.}
{471}{}{Wow, does it run?}

# 22. Does it run? (21)
{480}{SMIT24}{If'n it ran, do you think I'd still be in this shithole of a town?}
{481}{}{Uh, yes.}
{482}{}{I guess not.}

# 23. Yes (22)
{490}{SMIT25}{Well, you're probably right. I got kinda settled in here.}
{491}{}{I see.}

# 24. No (22)
{500}{SMIT26}{Well, then again, mebbe' I would too. I got all comfortable here.}
{501}{}{I understand.}

# 25. Got car (23,24 )
{510}{SMIT27}{I wouldn't mind selling the car though. If someone brought me the battery - no strike that, uh, I guess I'd need a fuel cell controller. Yeah, if'n I had one of them, I'd sell the car for $2,000. Even install the controller so it'd run right.}
{511}{}{That sounds interesting. I'll have to come back if I ever find a fuel cell controller. Let me ask you something else right now.}
{512}{}{When I find one, I'll be back. Goodbye, Smitty.}

# 26. Regulator installed  (19)
{520}{SMIT28}{There you go. Better'n new. Take it easy with her now.}
{521}{}{I will. Thanks, Smitty. Goodbye.}

{600}{}{YOU GET THE HELL AWAY FROM MY CAR!}

{650}{SMIT29}{Don't let me catch you sneaking around my car like that again.}
{651}{}{You won't.}
{652}{}{Uggg-K}

# Crafting
{701}{}{Say, you look like a seriously skilled mechanic! You think you could teach me a thing or two?}
{702}{}{Pretty good, Smitty. Thanks! Say, mind showing me a thing or two about your craft?}

{710}{}{Heh, I could teach you more than a few things, if it's grenades and explosives you're interested in. How about $200?}
{711}{}{Sure thing, compadre. If you're interested in grenades and explosives I could teach you how to put them together. Interested?}
{712}{}{Show me.}
{713}{}{How about $100?}
{714}{}{No.}
{715}{}{I don't have the money.}

{730}{}{Ok, I'll knock it down to $125. How's that sound?}

{720}{}{Okay. First thing you need to remember is to not blow yourself up while you're at it...}
{721}{}{...and then you toss 'em towards the other guys. Should mess 'em right up. Can't say I know more about it than that.}
{722}{}{Thanks.}
{723}{}{Thanks. Can I ask something else?}

{740}{}{You have learned how to make explosives.}


##############################################
#BONUS LINES NEEDED FOR THE TALKING HEADS MOD#
##############################################
