{100}{}{You see a bandit.}
{101}{}{You see a marauder.}
{102}{}{You see a robber.}
{103}{}{You see a highwayman.}
{104}{}{You see a rogue.}
{105}{}{You see an adventurer.}

{200}{}{Surrender!}
{201}{}{Your money or your life.}
{202}{}{This is a stick up.}
{203}{}{Give me all your valuables.}
{204}{}{Don't move! This is a holdup.}
{205}{}{Put yer hands up.}
{206}{}{Stick 'em up.}
{207}{}{Don't panic; this will be over in a minute.}
{208}{}{Let's see those hands there.}
{209}{}{Cover me, fellas.}

{210}{}{Don't make this hard on yourself.}
{211}{}{Hand over the loot.}
{212}{}{Get 'em, boys.}
{213}{}{Kill them all.}
{214}{}{I promise to make your death quick.}
{215}{}{Reach for the sky.}
{216}{}{Don't move.}

# phobos2077 bounty quest
{240}{}{Damn bounty hunters!}
{241}{}{You're not taking my talisman!}
{242}{}{Spirits guide me against evil!}
{243}{}{How much they offered you?}
{244}{}{Die, bounty hunter scum!}