# Message file for epac9.ssl 
# Number of nodes: 18

{100}{}{You see a large computer.}
{101}{}{You see Mr. Chemmie!}
{102}{}{A large crafting computer for drugs.}

# Node  0  [Node001]
{200}{}{Hello user! I'm the pharmacist of the future, Mr. Chemmie! How can I help you?!}
{201}{}{What do you do?}

# Node  1  [Node002]
{210}{}{I make drugs! All kinds of drugs! When life gets you down, Mr. Chemmie is here to pick you up! How does Mr. Chemmie work?! It's simple! All you need is some scientific know-how and the right ingredients, then leave the rest up to me! Go on! Give me a try! And kids, remember to ask Mommy or Daddy for permission before playing with Mr. Chemmie!}
{211}{}{Alright, I'll give this a try.}
{212}{}{Maybe later.}

# Node  2  [Node003]
{220}{}{Alright! Let's make drugs! What do you wish to create?!}
{221}{}{Stimpak}
{222}{}{Super Stimpak}
{223}{}{Poison}
{224}{}{Poison Antidote}
{225}{}{First Aid Kit}
{226}{}{Doctor's Bag}
{227}{}{Buffout}
{228}{}{Mentats}
{229}{}{Psycho}
{380}{}{Rad-X}
{381}{}{RadAway}
{382}{}{Something Special}
{383}{}{Nothing}


# Node  3  [Node004]
{230}{}{Great choice! To make a Stimpak, please feed me: one Broc Flower, one Xander Root and one Empty Hypodermic needle! Yum-yum!}
{231}{}{Make a stimpak.}
{232}{}{I don't have those right now.}
{233}{}{Return to the menu.}

# Node  4  [Node005]
{240}{}{Great choice! To make a Super Stimpak, please feed me: two ordinary Stimpaks, one piece of Fruit and one Nuka Cola! Yum-yum!}
{241}{}{Make a Super Stimpak.}

# Node  5  [Node006]
{250}{}{Great choice! To make Psycho, please feed me: one Buffout, two pieces of Fruit, one bottle of Booze and one Super Stimpak! Yum-yum!}
{251}{}{Make a Psycho.}

# Node  6  [Node007]
{260}{}{Great choice! To make some Mentats, please feed me: one First Aid Kit, one piece of Fruit, and one bottle of Booze! Yum-yum!}
{262}{}{Make some Mentats.}
{263}{}{Exit}

# Node  7  [Node008]
{270}{}{Great choice! To make a Doctor's Bag, please feed me: one Stimpak, one First Aid Kit, one Empty Hypodermic needle and one Poison Antidote! Yum-yum!}
{272}{}{Make a Doctor's Bag.}

# Node  8  [Node009]
{280}{}{Great choice! To make a First Aid Kit, please feed me: one Stimpak, one Empty Hypodermic needle, one Poison Antidote and one RadAway! Yum-yum!}
{282}{}{Make a First Aid Kit.}

# Node  9  [Node010]
{290}{}{Great choice! To make Poison, please feed me: one Empty Hypodermic needle, one Scorpion Tail and one Nuka-Cola! Yum-yum!}
{292}{}{Make some poison.}

# Node  10  [Node011]
{300}{}{Great choice! To make Buffout, please feed me: one First Aid Kit, one bottle of Beer and one Nuka-Cola! Yum-yum!}
{302}{}{Make Buffout.}

# Node  11  [Node012]
{310}{}{Great choice! To make Rad-X, please feed me: one First Aid Kit and one Nuka-Cola! Yum-yum!}
{312}{}{Make a Rad-X.}

# Node  12  [Node013]
{320}{}{Great choice! To make RadAway, please feed me: one Nuka-Cola, one Empty Hypodermic needle and one Stimpak! Yum-yum!}
{322}{}{Make a RadAway.}

# Node  13  [Node014]
{330}{}{Great choice! To make a Poison Antidote, please feed me: one Scorpion Tail and one bottle of Booze! Yum-yum!}
{331}{}{Make Poison Antidote.}

# Node  14  [Node015]
{340}{}{Oh boy! A special request! What kind of special drug would you like Mr. Chemmie to create for you today?!}
{341}{}{Marijuana.}
{342}{}{Doctor's Chemicals.}

{343}{}{My friend Cassidy has a problem with his heart. Can you make something to help him?}
{344}{}{Environmental Rejection Syndrome Inhibitors.}

# Node  15  [Node016]
{350}{}{This is your lucky day! I have enough chemicals in my storage tanks to make these! Would you like Mr. Chemmie to make them for you?!}
{351}{}{Create.}
{352}{}{Return to Main Menu.}

# Node  16  [Node017]
{360}{}{Uh-oh! Sorry, but I no longer have the chemicals needed to create these!}

# Node  17  [Node018]
{370}{}{Selection created! That was fun! Please collect the item from the machine! Thank you for using Mr. Chemmie! Let's make drugs again sometime!}

{371}{}{More Options.}

{375}{}{Mr. Chemmie loves to help! I can create a substance called nitroglycerin, which will control an irregular heartbeat and prevent heart attacks!}

{390}{}{This is your lucky day! I have just enough chemicals in my storage tanks to make one batch of ERSIs! Would you like Mr. Chemmie to make them for you?!}
{391}{}{Create.}
{392}{}{Exit.}
