{100}{}{Unauthrorized Access Requested. Locking door.}
{101}{}{Authorization Granted. Unlocking door.}
{102}{}{Door is already unlocked.}
{103}{}{You see a door to the Security Wing.}
{104}{}{You see a reinforced door for the Security Wing. The door itself has no lock, but there is a control panel nearby.}

# phobos2077 addition:
{110}{}{It should be unlocked, but the door won't open.}
{111}{}{You have found a problem in control system curcuits. You need an advanced electronic lockpick to fix this.}
{112}{}{You have fixed the door control system.}
{113}{}{You fail to understand the problem. The systems are too complex.}
{114}{}{There is no lock to pick. Maybe you should study what's wrong with the door first.}
{115}{}{This does nothing. Looks like you need more advanced electronic lockpicks for this door.}
{116}{}{You fail to unlock the door with lockpicks. Maybe you should study what's wrong with the door.}

{200}{}{There is no lock to pick.}
