{100}{}{You see a fairly young, balding scientist. He looks intent on his job.}
{101}{}{You see Crockett, the Hubologist scientist.}
{102}{}{You see a relatively young, balding scientist. He seems like a slovenly geek.}
{103}{}{Yeah? Whaddya want?}
{104}{}{Agh. Um. Duur.}
{105}{}{Dr. Jing sent me. He wants some hardened power armor.}
{106}{}{You can upgrade power armor?}
{107}{}{Who are you?}
{108}{}{What do you do here?}
{109}{}{Nothing, thanks.}
{110}{}{I swear, there are more subhumans running around every single day. Shoo! Shoo!}
{111}{}{Awww.}
{112}{}{Yeah, I can do that. But what are you willing to trade for it?}
{113}{}{Dr. Jing will probably be willing to sell you fuel for the spaceship.}
{114}{}{I can pay for it.}
{115}{}{I'll let you live.}
{116}{}{Nothing. Forget it.}
{117}{}{I'm Crockett. I'm a scientist and fix-it guy. Can I get back to it?}
{118}{}{No. I have more questions.}
{119}{}{Yeah, sure.}
{120}{}{I develop new technology and I get my share of cultist tail, if you catch my meaning.}
{121}{}{So you're not a Hubologist?}
{122}{}{I got it. I have more questions.}
{123}{}{No. What do you mean?}
{124}{}{What new tech have you developed?}
{125}{}{Loud and clear. See ya.}
{126}{}{Well... I *guess* that'll have to do. It's a deal. Do you have the armor to be hardened on you?}
{127}{}{Yes.}
{128}{}{No.}
{129}{}{Great. That'll cost you $%d, straight up, no bartering. I need some new equipment.}
{130}{}{$%d? That's outrageous! I don't have that kind of money!}
{131}{}{All right. Here you go.}
{132}{}{I'll get back to you.}
{133}{}{::he looks amused::
Are you really threatening me for this?}
{134}{}{Yes. Do it or die.}
{135}{}{No, I was just kidding.}
{136}{}{Leave it here for a day and I'll do it. Before you go, you ought to know I've only got the material to do this for two sets of armor.}
{137}{}{Sure thing. I have more questions.}
{138}{}{I'll be back for the armor.}
{139}{}{I can't very well work my magic on it if you don't have it. Come back when you do.}
{140}{}{I have more questions.}
{141}{}{Bye.}
{142}{}{::he shrugs::
You want this armor or not? It's $%d flat out.}
{143}{}{I'll get back to you.}
{144}{}{Fine. Here.}
{145}{}{Highway robbery. No way.}
{146}{}{::he looks into your eyes and decides that you're serious::
Do you have the armor here?}
{147}{}{Yes.}
{148}{}{No.}
{149}{}{::he looks into your eyes and decides that you're bluffing::
Try it, bucko. You'll have guards down on your ass and you'll never learn how to harden your armor.}
{150}{}{Fine. Die, pencil-neck.}
{151}{}{Shit. You called my bluff.}
{152}{}{Bluffer. I think we'll see what the guards have to say about this.}
{153}{}{Dammit!}
{154}{}{These guys don't know real science - I help them justify their extravagance in exchange for some downtime with the ladies and a hefty salary.}
{155}{}{Hmm. I had more questions I wanted to ask.}
{156}{}{Not bad at all. See ya.}
{157}{}{Let's see... I built a nuclear reactor for the spaceship. I created the hardening process for power armor. And I fix things that are broken.}
{158}{}{I see. Well, I have more questions.}
{159}{}{Hmm. Gotta go. Bye.}
{160}{}{Hey, I got no beef with you. Just don't hurt me.}
{161}{}{I have some questions for you.}
{162}{}{I'm here for my armor.}
{163}{}{Too late.}
{164}{}{Bye.}
{165}{}{It's not ready yet. You have to give me time!}
{166}{}{Fine. I have some questions.}
{167}{}{Fine. I'll be back.}
{168}{}{I've got it right here for you. Take it, take it.}
{169}{}{Thanks. I have questions.}
{170}{}{Thanks.}
{171}{}{Thanks. NOW you can die.}
{172}{}{I'm out of chemicals for it. Sorry.}
{173}{}{Then you can answer me some questions.}
{174}{}{Then you can die.}
{175}{}{Oh. Damn. Bye.}
{176}{}{So where's my fuel? You promised me fuel, asshole.}
{177}{}{You'll get it, you'll get it. Now answer some questions.}
{178}{}{Yeah, well, I screwed you.}
{179}{}{And for the last time, too. GUARDS!}
{180}{}{Die, asshole.}
{181}{}{Shit. I'm outta here.}
{182}{}{Ok, now what do ya want?}
{183}{}{You ready to pay the $%d this time?}
{184}{}{Leave it here for a day and I'll do it. Remember though, this is the last set I can make.}
{185}{}{Hey, I have another suit for you to upgrade.}
