{100}{}{You see a wizened old man wearing a white smock.}
{101}{}{This is Dr. Fung.}
{102}{}{You see a wizened old man wearing a white smock.}
{103}{}{Help you with something?}
{104}{}{Owie! Ouch! Owwwwwww!}
{105}{}{Yeah - I'm hurt and it looks like you're a doctor.}
{106}{}{Yes. I need a doctor for my friend.}
{107}{}{Do you have any stimpaks? I'd like to buy some.}
{108}{}{Who are you?}
{109}{}{I have a friend who's missing a spleen. Can you help him?}
{110}{}{What can you tell me about this place?}
{111}{}{Bye.}
{112}{}{Let me take a look at that. Hmm. Yes. I'll have to charge you, of course.}
{113}{}{How much?}
{114}{}{Forget it.}
{115}{}{I can heal... but for a price, you understand.}
{116}{}{How much?}
{117}{}{Forget it.}
{118}{}{Who am I? I am Dr. Fung. I teach and I heal.}
{119}{}{Dr. Fung? Do you know Doc Holliday?}
{120}{}{Pleased to meet you. I need healing.}
{121}{}{A friend of mine needs to be healed.}
{122}{}{I see. Thanks. Bye.}
{123}{}{Holliday? Yes! I taught him all he knows! Where is he now?}
{124}{}{He's living in Broken Hills.}
{125}{}{He went home, did he. I hope he has found peace there.}
{126}{}{I think he has. I have more questions.}
{127}{}{Probably. I have to go. Bye.}
{128}{}{That'll cost you $100.}
{129}{}{I'll pay.}
{130}{}{Forget it.}
{131}{}{This appears serious. That will cost $200.}
{132}{}{I'll pay.}
{133}{}{Forget it.}
{134}{}{Those are impressive wounds. $300 is all it takes to procure my services.}
{135}{}{I'll pay.}
{136}{}{Forget it.}
{137}{}{For this much damage, I'm afraid that I will have to demand $400.}
{138}{}{I'll pay.}
{139}{}{Forget it.}
{140}{}{Sit down. You'll need to when you hear my bill. Crippled limbs cost $600.}
{141}{}{I'll pay.}
{142}{}{Forget it.}

{158}{}{What? You do not have the money? How do you expect me to survive if you ask me for free healing?}
{159}{}{Do you have stimpaks?}
{160}{}{No thanks.}
{161}{}{It has been a pleasure doing business with you.}
{162}{}{Thanks.}
{163}{}{Your offer, sadly, is not acceptable.}
{164}{}{How about this?}
{165}{}{It's all I want to offer. So long.}
{166}{}{You're hurt? Tsk, tsk. Ancient remedy will cure that. }
{167}{}{O-kay!}
{168}{}{}
{169}{}{We're done. Now, you go and be careful!}
{170}{}{Tanks!}
{171}{}{You need more?}
{172}{}{I need healing.}
{173}{}{I have a friend who needs healing.}
{174}{}{Who are you?}
{175}{}{Tell me about this place.}
{176}{}{I have a friend who's missing a spleen. Can you help him?}
{177}{}{No. Thanks, though.}
{178}{}{You have come to the right person. Would you like long history or short?}
{179}{}{Long.}
{180}{}{Short.}
{181}{}{Neither. I have other questions, though.}
{182}{}{Our people landed here on the submarine Shih-huang-ti, when the missiles exploded over the world. With the aid of a cult, we, the Shi, rebuilt San Francisco. That is the short version.}
{183}{}{How about the long version?}
{184}{}{Thanks. I have more questions.}
{185}{}{Thanks.}
{186}{}{The long version is this: We are here because our people are the descendants of the crew of a nuclear submarine, called the Shih-huang-ti. When the missiles fell in the Great Deluge, the systems aboard the submarine failed and we drifted in the dark for many days.}
{187}{}{-more-}
{188}{}{At last, we drifted ashore. We found ourselves near the ruins of San Francisco. Most of the city was devastated in the war. We had to recreate society based on the few survivors who had crept back to the city.}
{189}{}{-more-}
{190}{}{We rebuilt with what we could find, and we have scientists and technology the world must envy. We are rebuilding civilization, but not as that horrid Master creature did.}
{191}{}{I see. I have more questions.}
{192}{}{Thanks. Bye.}
{193}{}{Of course I can. And since you are aware of Doc Holliday... I will do it for no more than the sake of friendship. Tell your spleenless friend to come here and I will replace it for him.}
{194}{}{Thanks! I have more questions.}
{195}{}{Thanks!}
{196}{}{Yes. I can do this. It will cost you $1000 dollars to do it. Up front. Do you accept?}
{197}{}{Yes.}
{198}{}{No.}
{199}{}{Tell your friend to come here and I will replace it for him.}
{200}{}{Thanks. I have more questions.}
{201}{}{Thanks.}
{202}{}{I can do nothing for him, until you have the $1000. Good day.}
{203}{}{Good day.}
{204}{}{I do not treat the enemies of my people. My humble apologies.}
{205}{}{Honored sir, I recommend you seek out your cult's doctors.}

{206}{}{What can you tell me about armor implants?}
{207}{}{I helped write the article on armor implants. All it takes is my expertise and your materials. What types of implants do you desire?}
{208}{}{What types are there?}
{209}{}{The dermal implants.}
{210}{}{The dermal upgrade.}
{211}{}{Phoenix implants.}
{212}{}{The Phoenix upgrade.}
{213}{}{Umm... forget it. I have other questions.}
{214}{}{None, actually. Bye.}
{215}{}{We have dermal implants, which protect against concussive damage. If you like that work, we can add a single enhancement to it. We also have Phoenix implants, which protect against heat-based attacks, and which also have an upgrade available. If you're interested in the upgrades, you will of course have to wait until the initial set has been installed. And before you ask, yes, you CAN have all four operations.}
{216}{}{Great. I'll take the dermal implants.}
{217}{}{I want the dermal implants.}
{218}{}{Give me the dermal upgrade.}
{219}{}{I'd like the Phoenix implants.}
{220}{}{Time for the Phoenix upgrade.}
{221}{}{Umm... forget it. I have other questions.}
{222}{}{None, actually. Bye.}
#pbs: adjusted implant prices
{223}{}{Excellent. I'll need a set of combat armor and, oh, $5500. You'll need two days and the ability not to pick at scabs.}
{224}{}{Let's do it.}
{225}{}{Forget it. So long.}
{226}{}{The dermal upgrade, eh? That will cost you several days of your life, $16500, combat armor, and a brand-new set of scars that you'll never ever lose as long as you live.}
{227}{}{So? I can afford ALL of that.}
{228}{}{Hmm. I don't think I want to pay that much. So long.}
{229}{}{If you do not mind parting with $7500, a few days, and a set of combat armor, we can begin the operation now.}
{230}{}{Strap me down, doc. I'm ready to go.}
{231}{}{That's a little steep. Let me get back to you.}
{232}{}{This is a major operation. It will cost you your "good looks", a set of combat armor, and $22500. Are you willing to invest in this?}
{233}{}{Hell yes. Let's do it.}
{234}{}{Wow. That's... expensive. I'll get back to you.}
{235}{}{::he shakes his head:: Do not toy with me. You are missing necessary ingredients. Listen more carefully to me next time. Now go, and come back when I can help you.}
{236}{}{Okay.}
{237}{}{There you go! You are ... enhanced. Remember... do not pick at the scabs unless you want horrid scarring to add to your suddenly not-entirely-pleasing appearance.}
{238}{}{Thanks, doc. So long.}

{239}{}{I have the money for the spleen.}
{240}{}{Are you interested again in implants?}
