{100}{}{You see a man who looks much like a shopkeeper.}
{101}{}{You see Lao Chou, the shopkeeper.}
{102}{}{You see a man in functional, comfortable clothing.}
{103}{LAO1}{Greetings! Welcome to my shop, Flying Dragon 8.}
{104}{LAO2}{What can I do for you?}
{105}{}{Da aggle oo!}
{106}{}{Stuff!}
{107}{}{Who are you?}
{108}{}{I'm looking for some equipment.}
{109}{}{I'm looking for some information.}
{110}{}{Bye.}
{111}{LAO3}{You want to buy something?}
{112}{}{::nod head::}
{113}{}{::shake head::}
{114}{LAO4}{This is what we have, then.}
{115}{}{[DONE]}
{116}{LAO5}{Well, I'm afraid that's all I can do for you. Good day.}
{117}{}{[DONE]}
{118}{LAO6}{I'm Lao Chou. I run this establishment, Flying Dragon 8, a general store. I have been known to trade in... information.}
{119}{}{What sort of information?}
{120}{}{I see. I'd like some equipment.}
{121}{LAO7}{Little happens in this town that I do not know about. Of course, you must know the right question to ask, yes? What do you need to know?}
{122}{}{I'm looking for some upgrades to my equipment.}
{123}{}{Where can I find vertibird plans?}
{124}{}{I need to find fuel for the PMV Valdez.}
{125}{}{I understand I need a FOB to access the Valdez' computer.}
{126}{}{I need some computer parts for the PMV Valdez.}
{127}{}{I'm looking for a spleen.}
{128}{}{I hear some flying machines brought a load of villagers down this way.}
{129}{}{Nothing. Bye.}
{130}{LAO8}{Talk to Crockett, over in the Hubologist camp. He is their head scientist.}
{131}{}{Thanks. I want more information.}
{132}{}{Thanks. Bye.}
{133}{LAO9}{Look to the north, in Navarro. There is a hidden base near the gas station.}
{134}{}{Thanks. I want more information.}
{135}{}{Thanks. Bye.}
{136}{LAO10}{Have you tried looking in the old Vaults? I hear that they are a wealth of information and technology of the ancients.}
{137}{}{Thanks. I want more information.}
{138}{}{Thanks. Bye.}
{139}{LAO11}{A spleen? Ha ha! Yes, Chip from the Valdez lost his spleen in a card game the other day. I sold it to Dr. Wong. He was fascinated by it.}
{140}{}{Dr. Wong? Where can I find him?}
{141}{}{How do you lose a spleen?}
{142}{}{Thanks. I have more questions.}
{143}{}{Ah, so. Bye.}
{144}{LAO12}{Dr. Wong is the head scientist in the Steel Palace. Seek him there.}
{145}{}{How do you lose a spleen, incidentally?}
{146}{}{Thanks. I want more information.}
{147}{}{Thanks. Bye.}
{148}{LAO13}{He was drunk. Very, very drunk. He was obsessed with his spleen all night long. And then he bet it.}
{149}{}{So you took his SPLEEN?}
{150}{}{I see. Well, I have more questions.}
{151}{LAO14}{Yes. It was a debt. He is an honorable man.}
{152}{}{I see. I need more information.}
{153}{}{You're a sick, rude bastard, aren't you?}
{154}{}{Right. Bye.}
{155}{LAO15}{You are a dishonorable person. I will not have you in my shop. Come back some other time.}
{156}{}{Whatever.}
{157}{LAO16}{They did not. They came from the north and flew over us, heading out over the sea.}
{158}{}{Over the horizon? How the hell do I get there?}
{159}{}{Yeah, right they did. Tell me where they are before I open you like a can of sardines.}
{160}{LAO17}{Well... none of our boats are capable of that kind of distance. Unless...}
{161}{}{Unless...?}
{162}{}{Thanks for your "help". I'm going to get me some real advice.}
{163}{LAO18}{... unless you can get the old tanker on the docks working. It's an old ship, but probably still functional, if some work is put into it. Ask the punks for more information.}
{164}{}{Thanks. I want more information.}
{165}{}{Thanks. Bye.}
{166}{LAO19}{Word has it that the Hubologists have come into a large quantity of fuel recently. Bargain with them.}
{167}{}{Thanks. I want more information.}
{168}{}{Thanks. Bye.}
{169}{LAO20}{You might try some of the Shi scientists in the Steel Palace. Perhaps they can help you with your fuel needs.}
{170}{}{Thanks. I want more information.}
{171}{}{Thanks. Bye.}
{172}{}{You are an enemy of my people. Die!}
{173}{LAO21}{You have performed well for my people in slaying AHS-9. I hope that I can be of assistance to you in some way.}
{174}{}{Who are you?}
{175}{}{I'm looking for some equipment.}
{176}{}{I'm looking for some information.}
{177}{}{Bye.}
{178}{LAO22}{You have already given them to the Hubologists. No?}
{179}{}{Oh yeah... ah... Can I ask something else?}
{180}{}{Oh yeah... Bye.}


#RP 1.3
{200}{}{What else can you tell me about the tanker?}

{210}{LAO23}{Even if you could get the NavCom working and the tanker fueled up, you'll still need considerable good fortune
 if you really want the ship to sail again.}
{211}{}{What do you mean by 'considerable good fortune?'}

{220}{LAO24}{I mean, the hunk of junk is older than most ghouls. It would be a miracle if it didn't sink on you. That is all
 I meant.}
{221}{}{I have a feeling that there's something you're not telling me about the tanker.}

{230}{LAO25}{Perhaps there is. (smiles) Perhaps the wasteland has made you paranoid.}
{231}{}{Listen, I need to find my tribe. Those bastards who took them are dangerous and need to be stopped.}
{232}{}{Come on. What's so special about the tanker? We're just two people talking.}
{233}{}{You sure? I'll make it worth your while.} #female
{234}{}{I don't have time for these mind games. Goodbye.}

#SPEECH >90%  Listen...
{240}{LAO26}{Bah. They are nothing. However, it's not the tanker that's special. It's just a big rusty tanker like you said.
 Our submarine, on the other hand...}
{241}{}{Submarine?}

#SPEECH <90%  Come on...
{250}{LAO27}{Let's talk, then. But there's nothing special about the tanker. I give you my word.}
{251}{}{What if I paid you to tell me?}

{260}{LAO28}{Hmm... Business has been slow lately. I could use more customers. Or a donation from a very generous one. Say, $%d?}
{261}{}{Here you go. But your information better be worth it.}
{262}{}{$%d and that's my final offer.}
{263}{}{I don't think so. That's too much.}

{270}{LAO52}{(Lao Chou pockets the $%d.) It's not the tanker that's special. It's just a big rusty tanker like you said.
 Our submarine, on the other hand...}
{271}{}{Submarine?}

{280}{LAO31}{We have nothing further to discuss, then.}
{281}{}{You sure? My lovely wife Miria will certainly make it worth your while.}
{282}{}{Goodbye.}

{285}{LAO29}{You drive a hard bargain. Fine, $%d.}
{286}{}{Here you go. But your information better be worth it.}
{287}{LAO30}{(Lao Chou pockets the $%d.) It's not the tanker that's special. It's just a big rusty tanker like you said.
 Our submarine, on the other hand...}
{288}{}{Submarine?}

#SPEECH <90% BUT PC IS FEMALE AND CH >=7 OR SEX APPEAL
{290}{LAO32}{Well if you put it that way, I have been cooped up in this dusty shop for a long time. It has been a quite a while since
 I enjoyed the company of a charming woman like yourself.}
{291}{}{[CONTINUE]}

{300}{LAO33}{[Hours past with no end in sight. You begin to suspect that Lao Chou may not be completely human. You black out, eventually.]}
{301}{}{hhh... What happened?}

{310}{LAO34}{You fainted as I moved us into the triple-lotus position, and I had to finish pleasuring myself with the grinning-panda kata.
 But a deal's a deal. It's not the tanker that's special -- it's just a big rusty tanker like you said. Our submarine, on the other hand...}
{311}{}{Submarine?}
 
#IF SPEECH <90% BUT PC IS FEMALE AND CH <7
{330}{LAO35}{I... don't think so.}
{331}{}{Don't try and fight it now. You want me and you know it.}

{340}{LAO36}{No, actually. You are not my type.}
{341}{}{Oh, I see. You're not into women.}

{350}{LAO37}{I am. I just do not find you very attractive. Perhaps if I were drunk.}
{351}{}{You're obviously blind. Whatever. It's your loss.}

#IF SPEECH <90% BUT PC W/ MIRIA
{360}{LAO38}{What are you proposing? Ahh... well, I have been cooped up in this shop for a long time. I will reveal all I know
 in exchange for a sample of your lady friend's charms.}
{361}{}{Miria, honey... I guess you'll have to, erm, pump this guy for information.}
{362}{}{I was joking, old man. Like I'd let you make time with my wife... I'm leaving.}

{370}{LAO39}{[You wait outside and hear faint moans from inside the Flying Dragon 8. An hour passes, and then another. You
 bang on the door, shouting, "Hurry up in there!" Finally, the moans become a primal scream.]}
{371}{}{[Bang on the door] Hey, what are you two doing in there!?}

{380}{LAO40}{A smiling Lao Chou emerges from his bedroom, still pulling on his pants. A few moments later Miria stumbles out behind him, looking dazed and confused but deeply satisfied] Your wife is a great deal more experienced than she looks.}
{381}{}{I, erm, know. Now pull your damn pants up and tell me what's so special about the tanker.}

{390}{LAO41}{There's nothing special about the tanker. It's just a big rusty tanker like you said. Our submarine, on the other hand...}
{391}{}{Submarine?}

#Submarine?
{400}{LAO42}{The Shi-Huang-Ti. My great grandfather, Ye Li, was its captain. He unleashed her nuclear fires like a horrible dragon upon California's coast.}
{401}{}{No shit.}

{410}{LAO43}{Ironically, a malfunctioning missile from our own ancestral nation went off course and exploded over the ocean near the submarine's location. The blast knocked out the Shi-Huang-Ti's systems, leaving Captain Ye Li and his crew stranded at sea.}
{411}{}{That's karma for you.}

{420}{LAO44}{But there was salvation. After weeks of drifting, the sub finally came to rest out in the shallow waters of the
 San Francisco bay. This city became our new home. We eventually restored the Shi-Huang-Ti; its targeting systems, its
 weapons. It has enough firepower to blow any potential invaders out of the water. So even if you got that old tanker
 running, it wouldn't get far, as the submarine will destroy any non-Chinese vessel that sails through the bay.}
{421}{}{That sounds like a problem alright. So how would I get to the submarine?}

{430}{LAO45}{You swim. Or take the motorboat at the docks. It is guarded, though, by one of our best soldiers, and he will
 not let an outsider like you past him.}
{431}{}{You have any idea how I can get past him then, without shooting him in the face?}

{440}{LAO46}{He's under strict orders to guard it 24/7. He will not let anyone without the right password through.}
{441}{}{I don't suppose you know it?}

{450}{LAO47}{That depends. I don't suppose you have $%d to ensure the continued prosperity of my shop?}
{451}{}{Here's your $%d.}
{452}{}{That's outrageous for a simple password. I'll only go as high as $%d.}
{453}{}{No deal.}

#here's the $5000
{460}{LAO48}{Ah, much appreciated. The password is XY8QIV2SHI. Others may be watching me after this, so don't forget the password. If ever we discuss it again, I'll need even more money for bribes.}
{461}{}{Thank you. Goodbye.}

#pass barter check
{470}{LAO49}{You are a crafty one, I'll give you that. Fine. I accept your offer. The password is XY8QIV2SHI. Don't forget it, or you'll have buy it from me again.}
{471}{}{Thank you. Goodbye.}

#fail barter check
{480}{LAO50}{Don't insult me with your meager offers. $%d. Take it or leave it.}
{481}{}{Fine. Here's your $%d.}
{482}{}{No deal.}

#No deal.
{490}{LAO51}{Your loss then. I don't believe we have anything else to discuss. Goodbye.}
{491}{}{Bye.}

##############################################
#BONUS LINES NEEDED FOR THE TALKING HEADS MOD#
##############################################
