{100}{}{You see an unusually large molerat.}
{101}{}{You see The Brain.}
{102}{}{You see a huge, albino molerat. It seems to have a swollen cranium and is particularly
 intelligent looking.}

{110}{}{You are even more foolish than most of your kind to cross me. Now you must die.}

{120}{}{I don't know how you got in here -- but you must be able to find your way out the same way.}
{121}{}{I don't have time for your pestering. I'm planning a way to take over the world. Go away.}
{122}{}{Don't bother me. I won't warn you again.}
{123}{}{That's it. Zomak! Kill him for me!}

{130}{}{Renewal is at hand. But it won't get any closer unless you get moving on repairing our Atomic
 Reactor. (to himself) Humans... they're so disappointing.}
{131}{}{Repair the Atomic Reactor?}
{132}{}{Oh yeah. Well, I'll be going then. Goodbye.}

{140}{}{I smell one of my Talismans on you, but I don't remember giving you one.}
{141}{}{I found it.}
{142}{}{Uh, you must have forgotten.}
{143}{}{It's just my aftershave. Old Mice -- do you like it?}
{144}{}{I killed one of your drones and took it from his still warm corpse.}
{145}{}{I got it from a village near Vault City. The people there said your followers left these with them.}

{150}{}{Are you ready to become one of us?}
{151}{}{I was born ready. Where do I sign up?}
{152}{}{You mean become a giant rat?}
{153}{}{I don't want any part of what you are.}
{154}{}{Just who are us, uh, I mean, you?}

{160}{}{In order to survive, both Gecko and Vault City will need to cooperate. Vault City needs the
 power from our Atomic Reactor in order to expand, and we need Vault City's medical technology. Unless
 we cooperate, both cities will stagnate. Vault City needs to help us to repair our power plant.}
{161}{}{How are you going to get them to do that?}

{170}{}{I am known simply as The Brain. A tribute to my genius. Few things within Gecko, and only a few more
 without, escape my notice.}
{171}{}{But you're just a giant rat.}
{172}{}{You said something about joining you?}

{180}{}{I don't care where you got it. The real question is whether you intend to join us and wear it
 in earnest. }
{181}{}{Join you? What do you mean?}
{182}{}{I'd rather clean your cage than join you.}
{183}{}{That depends. Vault City's patrols keep getting attacked by molerats. I assume you're behind this?}
{184}{}{Why of course I am. All part of my grand scheme to take over the world. I wouldn't expect your deficient human brain to understand. But alas, what concern is it of yours?}
{185}{}{I just want your molerats to stop attacking Vault City's patrols.}
{186}{}{Do you? Interesting... Alright, I propose a deal, human. I shall comply with your request, *if* you complete a certain task for me.}
{187}{}{What do you want me to do?}
{188}{}{Look, we had a deal -- I repair the reactor, and you call off your creatures. I did my part of the bargain, now it's your turn.}
{189}{}{The reactor is repaired, yes. But is it optimized? No, I'm afraid not. I said I'd call off my molerats when you *complete* the task. Getting it half-done isn't good enough.}

{190}{}{Well, as part of my plan to rule the world, I intend to reward my ghoul followers by finding a
 way to restore their humanity.}
{191}{}{How are you going to do that?}

{200}{}{When I unite Gecko and Vault City under my rulership, I will dedicate Vault City's medical labs
 to finding a way to reverse the effects of radiation that turned the people into ghouls. They will be
 renewed, reborn as humans once again.}
{201}{}{That doesn't sound so bad.}

{210}{}{The Ankh is a symbol of life. Once I've given you this talisman you'll be one of us. And your
 comrades will be more likely to help you along the path towards Renewal. But be careful who you show
 it to.}
{211}{}{Are you ready to accept Renewal and wear my Ankh Talisman?}
{212}{}{OK, I'll take your Ankh Talisman.}
{213}{}{I don't want to Renew. I like myself just the way I am. I don't want your talisman.}
{214}{}{Renewal? What do you mean?}

{220}{}{Those fools in Vault City have only signed their death warrants by destroying our reactor.}
{221}{}{Now I have to think of another way to take over the world. Just get out.}
{222}{}{I've had enough of your clumsy meddling. Zomak! Kill this fool for me.}

{230}{}{Repairing the reactor was an excellent first step. One more step is needed to ensure the
 survival of both Gecko and Vault City.}
{231}{}{One more step?}
{232}{}{Aren't you the concerned citizen all of a sudden.}
{233}{}{I think I've heard more than enough. Goodbye.}
{234}{}{Just why is a giant talking rat so concerned about all of this?}

{240}{}{You have done well. Both Vault City and Gecko have reason to rejoice. With our reactor working
 at top efficiency, my plan to take over the world may near fruition. Now you may leave. I have work to
 do.}
{241}{}{Well, I sure didn't do it for you. Goodbye.}
{242}{}{Big plans for an overbred rat. Goodbye.}

{250}{}{Well, the reactor's running -- but not very efficiently. We need to use Vault City's central
 computer to analyze our reactor's output report.}
{251}{}{Vault City's central computer. I'm sure that openminded people like that would be happy to help
 a giant mutated rat and a city full of ghouls.}
{252}{}{How do you propose to make that happen?}

{260}{}{Concerned citizen? In a way. In order to take over the world, I have to make sure that there's
 something worth taking over. I need to build a strong powerbase using Gecko and Vault City.}
{261}{}{A rat plotting to take over the world?}

{270}{}{Well, despite your feelings about a rodent ruling the world, the actions I propose would benefit
 thousands of Vault City and Gecko's citizens. You may not care for me or my motives, but the results
 are still well worth working towards.}
{271}{}{Why don't you tell me about this last step, and I'll think about helping.}
{272}{}{It makes my flesh crawl to think that I've already helped you in some way. I'm leaving.
 Goodbye.}

{280}{}{Well, they will let you if you can show them how much it benefits them. We have an economic
 report that proves that optimizing the Gecko atomic power plant will directly benefit Vault City. I'll
 let our comrades here in Gecko know of your mission.}
{281}{}{They'll give you the Hydroelectric Magnetosphere Regulator if you can prove that doing so benefits Vault City. I have prepared
 an economic report that details just how much repairing our power plant benefits Vault City. I'll let
 our comrades here in Gecko know of your mission.}
{282}{}{That's great, but who in Vault City would even think of reading such a thing?}
{283}{}{Why don't you talk to that old windbag, that stinking sack Festus, in the power plant and
 see if he can dredge some useful information out of his rotting skull. He may know of a means of optimzing the power plant.
 I'll let our comrades here in Gecko know of your mission.}
{284}{}{That sounds like a good idea. Goodbye.}

{290}{}{I think that McClure is the only Councilmember in Vault City with enough brains to be able to
 see past his prejudices. He'll make sure you get what you need.}
{291}{}{No way, no how, am I going to be your message boy.}
{292}{}{Well, I guess it's worth a shot. Where do I get the disk?}

{300}{}{You need to go up above, to the junkyard. Look for a ghoul named Gordon. He has the Economic
 Data Disk that you need. You'll have my talisman, so he'll know to give you the disk.}
{301}{}{What talisman?}

{310}{}{You're sure you want to consign all the citizens of both cities to a slow death?}
{311}{}{Well, I guess not. Okay, tell me where to get the disk.}
{312}{}{Better a slow death than to be ruled by a rat. Goodbye.}

{320}{}{(Sniff, sniff) Hmmm, I smell the distinctive aroma of Cheezy Poofs on you. You don't happen to
 have some to spare do you? I just love Cheezy Poofs.}
{321}{}{Hmm, nope. No Cheezy Poofs here.}
{322}{}{I guess I could spare some Cheezy Poofs.}

{330}{}{Now you're one of us. Soon, I will take over the world and all of you will be Renewed.}
{331}{}{Uh, yeah. Whatever you say.}
{332}{}{That's it. That's enough. This stops right here. Someone's gotta stomp you out of existence --
 and that someone's me.}

{340}{}{Well, then, I suppose we have nothing more to say to one another. But you know that I cannot
 allow you to leave here alive, unless you're one of us.}
{341}{}{I'd rather die than join you.}
{342}{}{Hmm, maybe I've been hasty in my judgment.}
{343}{}{Bring it on, Willard.}

{350}{}{You fool. Zomak! Kill this intruder for me.}

{360}{}{You humans have such limited tolerances. I would have remained a normal rat if you humans
 hadn't done your best to destroy the world. If it weren't for the radiation, I wouldn't be
 what I am today.}
{361}{}{And what's that, exactly?}

{370}{}{Now that everything's been explained for you, are you ready to join us?}
{371}{}{Well, I suppose so.}
{372}{}{I'm convinced, alright. Convinced that I've got to get out of this nuthouse.}

{380}{}{I was just one of many normal rats in an advanced research lab. Then, one day, there were
 explosions. Our cages were broken open, and we were doused with some sort of fluid from a huge vat.}
{381}{}{Oh? What happened when it all went to hell?}

{390}{}{I crawled outside. As I began to heal, I noticed that I had changed. I tried to communicate with
 people, but they all just tried to kill me. Humans are just too violent to survive under their own
 leadership -- but that's another story. The first step is to repair the reactor.}
{391}{}{Repair the reactor?}

{400}{}{You must get a Hydroelectric Magnetosphere Regulator from Vault City in order to repair the Gecko reactor. If you don't,
 then Vault City will no doubt attack Gecko. Of course, by destroying the reactor, they will doom
 themselves in the long run, as well.}
{401}{}{Doom themselves? How do you mean?}
{402}{}{Why would Vault City give me a part for the Gecko Atomic power plant?}

{410}{}{You have to show them that it's in their own best interest to do so. People are easily
 manipulated through self-interest.}
{411}{}{I don't think the people in Vault City will give me a part for your atomic power plant.}

{420}{}{But right now, don't you have something to do?}
{421}{}{Uh, I guess I better get going on that atomic power plant thing. Goodbye.}
{4211}{}{Uh, I guess I better go get that disk from Gordon. Goodbye.}
{422}{}{I sure do. I need to get the heck out of here.}

{430}{}{My nose is quite keen. I'm certain that you have Cheezy Poofs. Give me some right now. Please.}
{431}{}{The only way you're getting my Cheezy Poofs is from my cold and lifeless fingers.}
{432}{}{Oh, hey. What's this in my pocket? I guess I do have some Cheezy Poofs after all. Whaddya know?}

{440}{}{(crunch, munch, crunch) Mmmm, I love Cheezy Poofs, they're so, well, uh, Cheesy. For that, you
 get to be a member of my special cult, and you can help me take over the world.}
{441}{}{(crunch, munch, crunch) Mmmm, I love Cheezy Poofs, they're so, well, uh, Cheesy. I was wise to
 allow you to join my cult. Isn't there something you should be doing right now?}
{442}{}{(crunch, munch, crunch) Mmmm, I love Cheezy Poofs, they're so, well, uh, Cheesy.}
{443}{}{(crunch, munch, crunch) Mmmm, I love Cheezy Poofs, they're so, well, uh, Cheesy.}
{444}{}{Uh...}

{450}{}{So be it. Zomak! Kill this fool for me. But be careful with the Cheezy Poofs!}

{460}{}{You have to use the Reactor Data disk on Vault City's Central Computer. You can either sneak
 in and use it or, if you have the Economic Data disk, you can go to McClure.}
{461}{}{Economic Data disk?}
{462}{}{Oh, okay.}
{463}{}{Just bring the Analyzed Reactor Data disk to Festus and he'll input the data to get the
 reactor running efficiently.}
{464}{}{Well, once you get a Hydroelectric Magnetosphere Regulator from Vault City, bring it back
 to the reactor. Then you can try to convince that pompous slug Festus to install the part, or use the
 repair robot to install the part, or you could even install the part yourself, of course - so long as
 someone does it we'll be all right.}
{465}{}{How can I get the part from Vault City?}
{466}{}{Oh, I see. Well, thanks for the information. Goodbye.}
{467}{}{Festus is the geezer that runs the atomic power plant. He's old, crotchety, and cantankerous, but
 he does actually know something about running the plant. His offices are over on the far southeast part
 the plant. Bring the data disk to him and he'll know how to use it.}
{468}{}{Oh, I get it. Okay. Thanks. Goodbye.}


{500}{}{(musing to himself) So many things pass away. Times are not what they were. (sigh) I feel that my
 sole remaining kin has died. Mad, though he was, I wish it were not so. I had hoped that
 he might find some happiness even in his dotage. (to you) Well, enough of my sad musings.}
{501}{}{Uh, okay.}

{504}{}{A Hydroelectric Magnetosphere Regulator. That's the part that you need to get from
 Vault City. Then you need to bring it back here and get it installed in the reactor.}
{505}{}{Get it installed in the reactor? How can I do that?}
{506}{}{Oh, okay. Thanks.}

{510}{}{The reactor's optimization data has been recorded on the disk you have by Vault City's
 Central Computer. Now all you have to do is to bring the disk to that pompous windbag, Festus.
 Or I suppose that you could just use the disk on the reactor robot control terminal, if you can't
 bear talking to Festus.}
{511}{}{Festus? Who's he?}
{512}{}{Oh, okay. Thanks. Goodbye.}

{600}{}{Renewal is at hand. But it won't get any closer unless you get moving on
 repairing our atomic reactor. (to himself) Humans... they're so disappointing.}
{601}{}{Renewal is almost here, but it won't get any closer unless you use the
 Reactor's Data disk on Vault City's Central Computer. Phah! One would think that
 even a human could understand that much.}
{602}{}{You're so close to providing the means for Renewal to all of us. If you'd
 only give the Reactor Data disk that you've had analyzed to Festus.}
{603}{}{You know that you need to get the Hydroelectric Magnetosphere Regulator
 from Vault City in order to install it in our atomic reactor. Sometimes I think
 that Renewal will never arrive as long as I have to depend upon humans.}
{604}{}{Repair the reactor? What do you mean?}
{605}{}{Use the Reactor Data disk? Just how am I going to do that?}
{606}{}{I have to give it to Festus?}
{607}{}{A Hydro-whatsits? Huh?}
{608}{}{What's that about the reactor?}
{609}{}{Give it to who?}
{610}{}{Oh yeah. Well, I'll be going then. Goodbye.}
{611}{}{You need to get that Hydroelectric Magnetosphere Regulator installed before the plant is operational again.}

{620}{}{I am known simply as The Brain. A tribute to my genius. Few things within
 Gecko, and only a few more without, escape my notice.}
{621}{}{But you're just a giant rat.}
{622}{}{You said something about joining you?}

{630}{}{The actions I propose would benefit thousands of Vault City and Gecko's
 citizens. You may not care for me, or my motives, but the results are still well
 worth working toward.}
{631}{}{You've received the Reactor Data disk, now you have to use it.}
{632}{}{You've had the Reactor Data disk analyzed, now you have to do something with it.}
{633}{}{Our atomic reactor needs a part if we have any hope of getting it to run
 efficiently.}
{634}{}{You've acquired the data that we need to optimize the atomic reactor. Now,
 all you have to do is give it to Festus.}
{635}{}{Why don't you tell me about whatever it is that you're proposing.}
{636}{}{Use the Reactor Data disk? How am I going to do that?}
{637}{}{Well, I figured that, but what?}
{638}{}{A part? What kind of part?}
{639}{}{Why don't you tell me about this last step and I'll think about helping.}
{640}{}{Give it to who?}
{641}{}{One more step?}

{650}{}{Well, despite your feelings about a rodent ruling the world, the actions I
 propose would benefit thousands of Vault City and Gecko citizens. You may not care
 for me or my motives but the results are still well worth working towards.}
{651}{}{You've received the Reactor Data disk, now you have to do something with it.}
{652}{}{You've had the Reactor Data disk analyzed, now you have to use it.}
{653}{}{Our atomic reactor needs a part if we have any hope of getting it to run
 efficiently.}
{654}{}{Why don't you tell me about those actions that you're proposing?}
{655}{}{Use the Reactor Data disk? How am I going to do that?}
{656}{}{Well, I figured that, but what?}
{657}{}{Like what?}
{658}{}{A part? What kind of part?}
{659}{}{Why don't you tell me about this last step and I'll think about helping?}

{670}{}{The reactor, always the reactor (sigh). Come back when you've made some
 progress on it.}
{671}{}{Come back later. I'm communing with a higher power, or something (sheesh).}

{672}{}{Look, if you don't call off the attacks, the people in the village could end up enslaved by Vault City.}

{700}{}{I have nothing more to say to you.}


{701}{}{Alright you ugly son-of-a-bitch, now I've got a new deal for you: Either you call off your rodents, or I swear to you I'll blow the damn reactor!}
{702}{}{All right, all right... Consider it done. Just, don't touch the reactor. (mumbles) Damn psychotic humans...}
{703}{}{Now that we're in agreement, what were you saying about the optimization?}
{704}{}{It's settled then. Goodbye.}
{705}{}{You came to an agreement about the molerats with The Brain.}
{706}{}{Vault City's patrols keep getting attacked by molerats. I assume you're behind this?}
{707}{}{You ask for my assistance, yet you leave a task half-finished. (to himself) Typical human. (to you) Optimize the reactor, then, and only then, shall I assist you.}
{708}{}{That depends. What is it?}
{709}{}{Listen here, you radioactive rat. You're really starting to piss me off. You said your "kin" had kicked the bucket... Well, I want you to know -- it was me, who finished him off. And now I think I'll finish the job of rendering your kind extinct.}
{710}{}{Listen here, you radioactive rat. You're really starting to piss me off. I think it's time I put a stop to this madness.}
{711}{}{I need to think this over.}
{712}{}{The safety of that village is integral to my plan. Therefore, I shall grant your request, human. For your asistance I shall count you among the ones who have earned Renewal.}
{713}{}{It seems to me, that because you have fixed and optimized the reactor, you deserve my help. What is it that you want?}
{714}{}{Thank you! What were you saying about the optimization?}
{715}{}{Thank you! Bye.}
#was 701,702,703 - killap
{716}{}{It appears that Gordon has already given you this Economic Data Disk that I speak of. Take it to Vault City immediately.}
{717}{}{I'm on it.}
{718}{}{Umm... yeah, maybe later.}

{719}{}{You *must* get a Hydroelectric Magnetosphere Regulator from Vault City in order to repair the Gecko reactor. If you don't, then Vault City will no doubt attack Gecko. If you help me, I will fulfill your request. So... will you join us?}
{720}{}{Very well, I shall help you.}
{721}{}{No, screw you rat brain! I've had enough of this. Time to die!}

{800}{}{What was this lab?}
{801}{}{It was called the Environmental Protection Agency, funnily enough. I do not remember that place fondly, and all things considered I am glad to have made the long trek of exactly [procedes to explain the exact distance and angle relative to his current position].}