{100}{}{You see a ghoul wearing old, grease-stained clothing.}
{101}{}{You see Skeeter, the Ghoul Gadgeteer.}
{102}{}{You see a grubby but intelligent-looking ghoul, wearing greasy overalls with a micrometer
 sticking out of his pocket.}

{110}{}{Just don't touch anything -- you might hurt yourself.}
{111}{}{I thought tribals were just unsophisticated.}
{112}{}{You can watch. You might learn something, but I doubt it.}
{113}{}{Well, ain't you something else.}
{114}{}{Are you just pretending to be dumb, or are you really that stupid?}

{120}{}{Funny you should ask that. Ya see, cars use replaceable fuel cells, or batteries, for fuel. What
 usually broke down was the Fuel Cell Controller. Most amateur mechanics jist assume that it's the
 battery itself. But you know what ass-uming things does, dontcha?}
{121}{}{No, I don't. What do you mean?}
{122}{}{So does that mean you have a Fuel Cell Controller?}

{130}{}{Well, assuming something makes an ass out of you and me. Get it? That's still a good one, ain't
 it? Heh heh! I haven't used that for years.}
{131}{}{Uh, thanks for the lesson. Now, do you have a Fuel Cell Controller?}

{140}{}{Yep. Sure do. Got it right here. Jist waitin' fer a car to be put into. You got a car?}
{141}{}{I know where one is. What's it going to cost me to get that Fuel Cell Controller?}
{142}{}{I might have one. Maybe I just like old chipsets. How much for the Fuel Cell Controller?}
{143}{}{I wish I did. If I find one, I'll know where to come for a new Fuel Cell Controller. Goodbye.}
{144}{}{Actually, I have another question for you.}

{150}{}{Well, money's nice, but I need sumthin' else right now. Sumthin' I cain't get for myself.}
{151}{}{What do you need?}

{160}{}{Great. You've got my Plasma Regulator. Thanks. Now I owe you some free work. What did you want
 me to work on? I'll tell you how much it would've cost, but this one's already paid for.}
{161}{}{Let me see what you can work on.}
{162}{}{I think I'll take a raincheck on that for now. Goodbye.}

{170}{}{Thanks for fixin' up our atomic reactor. It shore needed some work. I woulda show'd 'em how, but
 they don't trust me in there anymore. They got that idjit loudmouth Festus doin' all the work now. }
{171}{}{Well, I was glad to help. Right now I need something, though.}
{172}{}{It sure would have been easier if they'd let you fix it. Oh well, it's done now. See you later.}

{180}{}{Did you get my 3-Step Plasma Transformer yet?}
{181}{}{I haven't yet, but I'm still working on it. Let me ask you something else.}
{182}{}{Not yet. But I will. Goodbye.}

{190}{}{Hello there, I'm Skeeter. I sort of put things together here.}
{191}{}{Hello there. Whatcha lookin' fer?}
{192}{}{Whaddya need?}

{200}{}{Have you heard of something called a Garden of Eden Creation Kit?}
{201}{}{Do you have a battery that I could use to fix a car?}
{202}{}{I have some things that I want you to take a look at.}
{203}{}{What do you do here?}
{204}{}{Uh, I was just looking around. Goodbye.}

{210}{}{What do ya want me to look at?}
{211}{}{Ready for me to take a gander at something else? What do ya want me to look at now?}
{212}{}{I've got this telescope thing.}
{213}{}{I've got an 'X'}
{214}{}{I've got an 'X'}
{215}{}{I've got an 'X'}
{216}{}{I've got an 'X'}
{217}{}{Can I swap the parts around later?}
{218}{}{I don't need anything else. Goodbye.}

{220}{}{Hmm, I can attach this scope you've got to that rifle of yours.}
{221}{}{Well, I can attach this scope to one of your rifles. Which one do you want me to attach it to?}
{222}{}{How much is it going to cost to attach this scope to my Hunting Rifle?}
{223}{}{How much is it going to cost to attach this scope to my Assault Rifle?}
{224}{}{How much is it going to cost to attach this scope to my Sniper Rifle?}
{225}{}{Let me ask you about another item.}
{226}{}{I think that's all I need to know. Goodbye.}

{230}{}{Hmm, I thought so. Well, ya see, I cain't do nuthin' with your [Selected partname]. You need to
 have sumthin' else for me to do sumthin' with it.}
{231}{}{Hmm, what about a different item, then?}
{232}{}{What part do I need?}
{233}{}{I guess I better come back when I have something else. Goodbye.}

{240}{}{There ya go. I think that ought to work for you all right. Anything else?}
{241}{}{Yes, could you take a look at another item for me?}
{242}{}{That's all I need right now. Thanks. Goodbye.}

{250}{}{Hmm, you don't have enough money to cover the cost of working on that. Got sumthin' else ya
 want me ta look at?}
{251}{}{How much would it cost to combine something else?}
{252}{}{I don't think so. Thanks anyhow. Goodbye.}

{260}{}{Mostly I jist sorta tinker with things. Take 'em apart an try to put 'em all back t'gether...
 mostly. Make 'em work better... sometimes. Keepin' myself outta trouble. Know what I mean?}
{261}{}{I guess. Let me ask you something else.}
{262}{}{Well, I think I better go do something myself. Goodbye.}

{270}{}{You're lookin' fer a GECK, huh? Well, I don't rightly know where ya might find one of them thar
 things. I know that Vault City prolly used ta have themselves one.}
{271}{}{Vault City had one?}
{272}{}{Hmm. Well, let me ask you something else then.}
{273}{}{Oh well, I better keep looking. Goodbye.}

{280}{}{They sure did. That's how come they're so darn well off. It sure ain't 'cause they know what to
 do. It's 'cause the GECK done started up their crops, and got their town running when they came outta
 the Vault.}
{281}{}{Who would have an unused GECK?}

{290}{}{Well, lemme see here now. As I recollect, most Vaults were s'posed to have themselves a GECK.
 You might try lookin fer another vault somewheres.}
{291}{}{Thanks for the advice. Let me ask you something else.}
{292}{}{Well, I better get looking then. Goodbye.}

{300}{}{Ta be right-honest with ya, I jist dunno. If'n I get all da parts together, I jist get sort of a
 feel fer how they all goes together. Know whatta mean?}
{301}{}{Uh, you mean you're doing this by guesswork?}
{302}{}{How about taking a look at something else, then?}
{303}{}{Well, I guess that makes sense. I better go look for another part, then. Goodbye.}

{310}{}{Well, yup. But you see, it's right edu-ma-cated guesswork. That's what it is. Know whatta mean?}
{311}{}{I don't know what you mean exactly, but I guess I'll go look for another part. Goodbye.}
{312}{}{How about taking a look at something else, then?}
{313}{}{Well, I guess that makes sense. I better go look for another part, then. Goodbye.}

{320}{}{These days, good tools is harder to git than parts is. I need myself a bran' new Super Tool Kit.
 Snap-sumthin brand's best.}
{321}{}{A new tool kit? Where can I get that?}

{330}{}{I reckon that the best place to go an' git that would be down in Vault City somewheres. They've
 got all kinds of tools, but they sure as heck wouldn't give 'em to a ghoul, no how.}
{331}{}{So, you want me to bring you a Super Tool Kit, and then you'll give me the car part?}

{340}{}{Egg-zactly. That's the deal. One Super Tool Kit for one Fuel Cell Controller.}
{341}{}{Sounds like a fair deal, I guess. Let me ask you something else.}
{342}{}{What if I just do this the easy way? I kill you and take the part I need.}
{343}{}{I think I'm going to walk around a bit and think about it. Goodbye.}

{360}{}{Well, now. You could do that, maybe. Then agin, you might be in fer a little surprise there. I
 might be tougher than you think. Then again, mebbe you'd jist be slittin' yur own throat. I kin be
 pretty useful puttin' items together. Always nice to know someone's able to do that, ain't it?}
{361}{}{Well, maybe you're right. I'll let you live, for now. Tell me something else, though. }
{362}{}{You sure have a lot of answers, don't you? Hope you have an answer for what's in the afterlife,
 'cause I'm sending you there -- right now.}
{363}{}{I'll have to think about that one. Goodbye, for now. }

{370}{}{I see that you've got a mighty fine tool kit there. Snap-off, ain't it? I'll trade you this Fuel
 Cell Controller for it.}
{371}{}{Hey there! Yur back with my repair kit. Mmm, Snap-off -- they're the best. Ready to trade?}
{372}{}{It's a deal.}
{373}{}{Not right now. I'm holding on to this for a while. Goodbye.}

{380}{}{That's a mighty fine trade. You should be able to jist plug that sucker in and git your car
 a'workin'.}
{381}{}{That's a mighty fine trade. You should be able to jist plug that sucker in and git your car
 a'workin'. You know I could do you another favor by fixin' up some of yur stuff for free, too.}
{382}{}{Really? For free, huh? What do I need to do for you?}
{383}{}{Let me ask you something else.}
{384}{}{I'm going to go try that right away. Goodbye.}

{390}{}{Well, ya see, I need a darn 3-Step Plasma Transformer. An the only place I can figger to git one
 is from the supply room.}
{391}{}{Why don't you just get it from there, then?}

{400}{}{I kinda wore out my welcome there. An it was only a little fire, too. Coulda happened to jist
 anyone. Anyhow, they won't let me anywhere's inside the reactor building now. I need someone else to
 git my part for me. }
{401}{}{How do I get the Plasma Transformer for you?}

{410}{}{Youz gotta git yourself a Supply Requisition Form. Once you have that, jist give it to Jeremy in
 the Supply Room and he'll give you any darn thing you want. You can get Supply Requisitions from
 Harold or Festus.}
{411}{}{Where are Harold and Festus and will they just give me the form I need?}

{420}{}{Harold's in the Settlement, and Festus is in the reactor control room. But you might have to
 kind of get the forms on the sly, if ya know what I mean.}
{421}{}{You mean I have to steal the Requisition Form, don't you?}

{430}{}{Well, err, yeah. I guess so. You might ask them, but I wouldn't put your chances too high there.}
{431}{}{Well, I'll see what I can find out.}
{432}{}{I don't think I want any part of this. Goodbye.}

{440}{}{Didja come here to take me up on that work I owe you?}
{441}{}{I sure did. Let me see what you can work on for me.}
{442}{}{Not yet. Just came by to see if you're still here. Well, Goodbye for now.}

{450}{}{I'm sorry. You don't have anything that I can use that with. Anything else?}
{451}{}{Take a look at something else I have.}
{452}{}{I guess that's it for now. Goodbye.}

{460}{}{Let's see. It's going to cost you $[Cost of combining item a with item b]. Do you want to do
 that?}
{461}{}{Yes. I do. Thanks.}
{462}{}{I don't think that I want to do that after all. What about something else?}
{463}{}{I guess I don't want you to work on anything right now after all. Goodbye.}

{470}{}{Once I put things together they stay put. You cain't pull 'em apart later and attach 'em to
 other things. Better pick right the first time, I guess.}
{471}{}{OK, I understand. Take a look at something for me, then.}
{472}{}{I guess I don't want you to work on anything right now after all. Goodbye.}

{500}{}{I was wunderin' where the heck my Repair Kit is. You did say you were gonna git it, didn't ya?
 I cain't rightly do much fer ya without that. Sorry. Should be plenty of 'em available in Vault City.}
{501}{}{I'll have to come back when I have that. Goodbye.}
{502}{}{I don't think I need your help with anything right now, anyway. Goodbye.}

{600}{}{What do ya want me to look at?}
{601}{}{I have a pistol here and I was wondering....}
{602}{}{It sure looks as though you could bolt an accessory to this long arm here.}
{603}{}{Sometimes I like to get up close and personal. Anything you can do to improve my powered melee weapon?}
{604}{}{Uh, maybe later. Let me ask you about something else.}
{605}{}{I don't need anything else. Goodbye.}

{610}{}{[Spots your magnum revolver.] I can rig a speed loader on that there magnum for $}
{611}{}{Hmm, that Desert Eagle would sure be a sweet rig with an expanded magazine. I can do that for $}
{612}{}{Put the speed loader on the magnum.}
{613}{}{Expand the magazine in my Desert Eagle here.}
{614}{}{Actually, I had another weapon in mind....}
{615}{}{Hmm, let me ask you about something else.}
{616}{}{Maybe I'll come back later on.}
{617}{}{Too rich for my blood. I'll be back when I have more cash.}

{620}{}{[Skeeter studies your long arm, and nods slowly.]}
{621}{}{I can put a nice all-weather scope on that hunting rifle for $}
{622}{}{Nothing like having an assault rifle with an expanded magazine. I can fix
 yours up with one for $}
{623}{}{That FN FAL is a good gun. Hey, I got a low-light scope for that. It's yours
 for $}
{624}{}{All right then... put a scope on the Colt hunting rifle.}
{625}{}{Expand the magazine of the AK-112 assault rifle.}
{626}{}{Attach that low-light scope on the FN FAL.}
{627}{}{Too rich for my blood. I'll be back when I have more cash.}

{630}{}{You want that melee weapon juiced up? I can *supercharge* it for $}
{631}{}{Sure.}

{640}{}{[Skeeter takes the item and looks it over with a weird gleam in his
 eye.] Well, this is a mite challengin', but I think I can fix this up real nice
 for ya. Just sit tight for a while. [Skeeter takes the weapon over to his
 workbench and locks it in a really big vise.]}
{641}{}{Okay.}

{650}{}{[As you wait you can see Skeeter's back as he works on your weapon. You
 don't know exactly what he's doing but that weird chuckle and all the pounding are
 making you nervous.]}
{651}{}{Wait...}

{660}{}{[More pounding and cackling as you wait some more....]}
{661}{}{[You whistle tunelessly and make shadow-puppets against the back wall of
 Skeeter's workshop....]}

{670}{}{There you go. [You wake suddenly as Skeeter takes your weapon from the
 workbench - you can see a number of small shiny, metal parts lingering on the
 bench as Skeeter returns your weapon to you.] That *should* do it, I reckon. Give
 'er a try.}
{671}{}{Thanks. Can you upgrade any of my other weapons?}
{672}{}{Thanks, Skeeter. Uh, let me ask you something else.}
{673}{}{Thanks, Skeeter. I'll go try it out.}

{680}{}{[Spots your magnum revolver.] I can rig a speed loader on that there magnum for free.}
{681}{}{Hmm, that Desert Eagle would sure be a sweet rig with an expanded magazine. I can do that for free.}
{682}{}{I can put a nice scope all-weather on that hunting rifle for free.}
{683}{}{Nothing like having an assault rifle with an expanded magazine. I can fix
 yours up with one for free.}
{684}{}{That FN FAL is a good gun. Hey, I got a low-light scope for that. It's yours
 for free.}
{685}{}{You want that melee weapon juiced up? I can *supercharge* it for free.}

{700}{}{You delivered the part to Skeeter.}
{710}{}{You delivered the repair kit to Skeeter.}

# phobos2077 crafting
{1001}{}{Actually I was wondering if you could teach me to upgrade my weapons?}
{1010}{}{I don't go around teaching random smoothskins how to upgrade weapons. Besides, you would need a propper workshop...
 I could, however, teach you a thing or two about making ammunition - it's a hobby of mine. I could clue you in for... lets say, $500.}
{1011}{}{It's a deal.}
{1012}{}{$500? That's ridiculous! I can shoot things dead enough with the regular ammo.}
{1013}{}{I could only give you $250.}
{1014}{}{Not interested.}
{1020}{}{No way, it's not like you can learn about it anywhere else. $400 is my final offer.}
{1030}{}{This is my intellectual property, and that doesn't come cheap. Pay or go away.}
{1031}{}{OK, fine.}
{1032}{}{Forget it.}
{1040}{}{OK, let's see it then...}
{1041}{}{... hope it'll be useful.}
{1042}{}{I hope so too. Tell me something else.}

{5500}{}{.}
