{100}{}{You see a plain looking, sturdily built young woman with a scowl on her face.}
{101}{}{You see Maida Buckner, Mrs. Buckner's daughter.}
{102}{}{You see a plain looking, sturdily built young woman. She's looking back at you with a scowl on
 her face.}

{200}{}{You've really made me angry. I don't want anything further to do with you. Now just get out.
 Tribals, humph! (mutter, mutter) ...shiftless, worthless, lazy...}
{201}{}{You are even more infuriating than Sulik! I don't have time to talk to you. Go away.}
{202}{}{I don't want to have anything to do with you either. Goodbye.}
{203}{}{I'm very sorry that I upset you. I'm just ignorant of your ways here. I was trying to show you
 respect in the manner of my tribe.}
{204}{}{Gosh, I'm really, really sorry. I'm just an ignorant tribal, after all. Can you possibly forgive
 me?}
{205}{}{I just didn't know what to say to someone as attractive as yourself. I always get nervous when
 I'm near a beautiful woman. Please accept my apologies.}
{206}{}{It's just that you seem so civilized and so beautiful. I was jealous of you. Please forgive me.
 I have so much to learn from women like you.}

{210}{}{Hello there, my name's Maida Buckner. I help my mother run Buckner house. Can I help you?}
{211}{}{Ungh?}
{212}{}{Me }
{213}{}{Unker Rouse?}

{220}{}{Hmm - seems as though your elevator doesn't rise all the way to the top floor. Why don't you
 talk to my brother, Torr? He's a little closer to your speed. Goodbye.}

{230}{}{My name's Maida Buckner; I take care of trading and drinks here. I don't tolerate any tribals
 messing our family's place up. So you just better watch your step here, or you'll end up like Sulik.
 What do you want?}
{231}{}{My name's Maida Buckner; I take care of trading and drinks here. What will it be for you, friend?}
{232}{}{Hello there, my good friend.}
{233}{}{What may I help you with?}
{234}{}{Well, you just better be more civil from now on. Just what do you want anyway? What can I help
 you with here?}
{235}{}{I have some questions for you.}
{236}{}{I was looking for someplace to stay.}
{237}{}{I need to buy some things.}
{238}{}{I'd like a drink.}
{239}{}{I guess I don't need anything right now. Goodbye.}

{240}{}{Questions, huh? Well get on with it, then. Talking to you doesn't get my work any closer to
 being finished.}
{241}{}{More questions? Well go on, then, and be quick about it.}
{242}{}{Have you ever heard of something called a Garden of Eden Creation Kit?}
{243}{}{Tell me about Sulik.}
{244}{}{Tell me about what's going on here in Klamath.}
{245}{}{What other towns are nearby?}
{246}{}{I think that's all I need to know for now. Goodbye.}

{250}{}{My mother takes care of the rooms. You should talk to her about that.}
{251}{}{Ok, thanks. There's something else that I wanted to know, though.}
{252}{}{I'll talk to her about that then. Goodbye.}

{260}{}{You want to barter? I'm always looking for good quality gecko pelts, and I pay a fair price
 for them, too.}
{261}{}{You want to buy something? I hope you have something other than gecko pelts to pay with; we're
 overstocked on pelts right now.}
{262}{}{Yes, I'd like to trade with you.}
{263}{}{I'm more interested in something else at the moment.}
{264}{}{I guess I don't need to trade right now. Goodbye.}

{270}{}{The only way I know to create a Garden of Eden is through plain old hard work. That's something
 you tribals just don't seem to understand. But I guess that's the difference between us civilized folk
 and yourselves.}
{271}{}{Uh, I guess. Tell me about something else then.}
{272}{}{Gee, I guess I have a lot to learn from you folks. I'd like to be civilized, too, someday.}
{273}{}{Civilized? You think you're civilized because you live in the burnt-out ruins of a beforetime
 town? Tell me something else.}
{274}{}{I think I've heard just about enough. Goodbye.}

{280}{}{Well now, anything else that I can do for you?}
{281}{}{I've got enough gecko pelts to last me for a while. Anything else I can do for you?}
{282}{}{Actually, there was something else that I wanted to trade for.}
{283}{}{I was hoping for better prices. You sure aren't cheap. Tell me about something else.}
{284}{}{You're a tough bargainer, but fair. Tell me about something else.}
{285}{}{That's all I need for now. Goodbye.}

{290}{}{There are only a couple of other towns nearby. There's Redding far to the southeast, and the Den
 a few days south. But I wouldn't go to the Den.}
{291}{}{Why wouldn't you go to the Den?}
{292}{}{What about tribes in the area?}
{293}{}{Thanks for the advice. Tell me something else though.}
{294}{}{That's all I need to know about for now. Goodbye.}

{300}{}{Well, I didn't count tribes when you asked about civilized towns. But I guess there's a group of
 savages somewhere to the northwest -- and then Sulik's tribe, far to the southwest.}
{301}{}{That's funny, my tribe doesn't count pre-war towns when we talk about civilized places. Tell me
 something else.}
{302}{}{Oh, you're civilized all right... and I don't think I want any part of it. Tell me
 something else.}
{303}{}{Tell me about Sulik.}
{304}{}{What about the Den?}
{305}{}{Interesting. Let me ask you something else, though.}

{310}{}{The Den is a bad place to go. They even enslave ignorant tribals like yourself. It's a week or
 so south of here, but most folks that've gone there don't come back.}
{311}{}{Tell me about the local tribes.}
{312}{}{Isn't Sulik your slave? Or do you just treat him like one?}
{313}{}{Interesting. Let me ask you something else, though.}

{320}{}{Sulik's a tribal that's working here to pay off a debt he foolishly incurred. He is not a
 slave. We don't have slaves here in Klamath.}
{321}{}{Paying off a debt? What do you mean?}

{330}{}{Well, you see, Sulik got real upset one night and had too much booze. Then, when he was good
 and drunk, he busted up the place. He did nearly $500 worth of damage. Just now getting the place
 repaired.}
{331}{}{Why'd he get so upset?}

{340}{}{He said he found out that his sister had been kidnapped by slavers. But you'd have to ask him
 more about that. He's here until he can pay off the rest of the damage he did while he was drunk.}
{341}{}{How much does he have to work off?}

{350}{}{He still has to pay off $350. If he weren't so lazy and shiftless it would go quicker for him.
 He's not leaving here until his debt is paid in full.}
{351}{}{That's a lot of money. I think he's going to be here for a long time.}

{360}{}{Well, he may be slow, but he does sort of grow on you after a while. (looks away wistfully)...
(flustered) Now that's enough jaw flapping; do you need anything else?}
{361}{}{I was curious about something else.}
{362}{}{What if someone else paid Sulik's damages?}
{363}{}{That's all I need for now. Goodbye.}

{370}{}{I don't know why anyone would want to pay off his debt, but they could. His bill comes to $350.
 But you wouldn't want to do that -- he'd only get into trouble again.}
{371}{}{I don't like him having to stay here with a bigot like you. I want to pay for his damages.}
{372}{}{Well, I'm sure he must be happy working for you folks, but I still want to pay his damages. I
 don't think anyone should be trapped the way he is.}
{373}{}{I guess you're right. I don't have that much money to spare, anyway. Goodbye.}

{380}{}{Well, okay then. If you really want to pay for the damage he caused... I guess all of you tribals
 really stick together.}
{381}{}{Yes, I do. I have enough to pay for the damages that he caused.}
{382}{}{Maybe that is too much money. I don't think I want to pay for his damages after all. Goodbye.}

{390}{}{You must be crazy. I'll sure be glad to have that damn (sob) tribal (sob) away (sob, sob) from
 here. (sob)}
{391}{}{(sob) I suppose that's a fair trade, one idiot brother for one idiot (sob) savage. I won't miss
 him a bit.}
{392}{}{Well, somehow, I think Sulik might actually miss being here. But we'll be back to visit
 sometime, I'm sure. Right now, though, I need something.}
{393}{}{I think Sulik's going to be a lot better off away from you.}
{394}{}{Thanks; I guess maybe I should be going now.}

{400}{}{You're back, huh? I hope you're taking care of Sulik. I'm sure he's lost without me telling
 him what to do.}
{401}{}{I'm back because I need something.}
{402}{}{Well, I'm sure I can't do as good a job of taking care of him as you did, but I'll sure try.}

{420}{}{A trapper named Smiley has gone missing. Momma sure is upset about that. I'm sure she would be grateful if
 someone found him.}
{421}{}{Well, have you seen Torr anywhere? It seems as though he's run off, and we're sure worried.}
{422}{}{OK, I'll talk to Mrs. Buckner about that then. Let me ask you something else though.}
{423}{}{No, I haven't seen Torr anywhere. I'll let you know if I do. Let me ask you something else,
 though.}
{424}{}{Well, Torr has been complaining about "Bug Men" scaring the brahmin. Not sure if I really believe all his stories,
 but someone or something has been rustling cattle here in town.}
{425}{}{I'll admit I haven't been paying too much attention to all the gossip around town. Head over to the Golden Gecko,
 I'm sure someone there might know a thing or two.}
{426}{}{Cattle rustling, huh? I'll look into this. Let me ask you something else, though.}
{427}{}{Interesting. Anything else I should know?}
{428}{}{Thanks for the tip. Let me ask you something else, though.}

{430}{}{Thanks for finding my brother, Torr. Ma and I were so worried. What can I do for you?}
{431}{}{Thanks again for finding Torr. What can I do for you?}
{432}{}{I was happy to help Torr.}
{433}{}{Happy to find Torr, but I don't think I need anything right now. Goodbye.}
{434}{}{Happy to help you out. Maybe you could do me a favor and free Sulik in return for my finding
 your brother?}

{440}{}{Have you seen my brother Torr anywhere? He lost some more brahmin and ma yelled at him. He must
 have run off after that.}
{441}{}{Uh-oh, where do you think he might have gone?}
{442}{}{I'm sorry to hear that, but I need information about something else.}

{450}{}{I don't know where he went for certain, but I think that he might have run off to that canyon
 he was always talking about.}
{451}{}{A canyon? What canyon?}

{460}{}{Well, there's a canyon just east of where we graze the brahmin. Torr used to come up with wild
 stories about bugmen coming from there. He said that it was bugmen that mutilated our brahmin. Scared
 himself silly with those fool stories.}
{461}{}{Sounds as though it would scare just about anybody.}

{470}{}{I think he might have taken off to the canyon to prove his bravery or something. I sure hope
 someone can find him before he hurts himself.}
{471}{}{Maybe I should try to find him.}
{472}{}{I'm really sorry you can't find him. I'm sure he's fine. I need some information.}
{473}{}{Who knows where your idiot brother went to -- and who cares? I need some information.}

{480}{}{I'd be so grateful if you could find my brother for mom and me.}
{481}{}{I'd be happy to look for him.}
{482}{}{I'm sorry, but I don't think I really have time for that right now. Goodbye.}

{500}{}{Thanks so much. I take back all those things I said about tribals. Please find my brother for
 me.}
{501}{}{I will; you can count on me.}

{510}{}{Have you found my brother yet? I sure hope he's alright.}
{511}{}{No, not yet. I got some other questions though.}
{512}{}{Not yet, I am still looking.}

{520}{}{You want a drink? That'll be $5 for a glass of Buckner's Best Brew.}
{521}{}{I'd love a nice beer. Fill 'er up.}
{522}{}{I'd like to buy a round of drinks for everyone here by way of introducing myself. I'm }
{523}{}{ from Arroyo.}
{524}{}{I don't think I need a beer after all. Maybe just some information will do.}

{530}{}{A round for everyone. My, my - aren't you a generous one? That'll be $30.}
{531}{}{Have one on me, folks. Now, how about some information as well?}
{532}{}{I guess I'd rather just have a drink for myself after all.}
{533}{}{I think maybe I'll just settle for some information for now.}

{540}{}{Looks as though you don't have enough money for that. }
{541}{}{Uh, well, I guess I'll settle for some information then.}
{542}{}{Oh, maybe I'll come back when I have more. Goodbye.}

{550}{}{I'll sure be glad to have that damn (sob) tribal (sob) away (sob, sob) from
 here. (sob)}

{600}{}{[MORE]}

{700}{}{I found out what's been happening to your brahmin.}
{701}{}{You have? That's great, but mom's the one you'll want to talk to about that.}
{702}{}{Sure, I'll go talk to her then.}

{710}{}{Cattle rustling? Any leads?}
{711}{}{Not really. I'm not even sure if there's a connection between this and the brahmin mutilations.}
{712}{}{Interesting. Any other local news I should know about?}


#EcCo:
{1001}{}{You're tough bargainer. Maybe you can give me some tips about bartering?}
{1010}{}{Yeah, you tribals are definitely clueless when it comes to trade. First off, you need to know the actual value of what you're hauling.
 You've got to develop a feel for the right price. Ask too little, and people will think you're a pushover; ask too much, and they won't take you seriously.}
{1011}{}{And another thing: pay attention to what's in high demand locally. Find out where those items are common, buy 'em cheap there, and sell 'em for a profit here.
 Assuming your skills are up to the task, of course.}
{1020}{}{You have improved your Barter skill.}
