{100}{}{You see a tall man with facial tattoos and a large bone through his nose.}
{101}{}{You see Sulik.}
{102}{}{You see a tall, muscular, Tribal. He has a bone through his nose, facial tattooing, and a
 confident, composed demeanor.}

{103}{}{.}
{104}{slk1}{Hey, fren. Our name be Sulik. What you be needin'.}
{105}{}{Uh?}

{107}{slk2a}{Oh, no. Don't be talking at us. One of you took our sis. Bad karma... for you.}
{108}{slk2b}{Oh, no. We and I don't talk to no slave owner.}

{109}{slk3}{Most people have evil spirits. You? You have stupid spirits.
 Go see shaman, get hole in head... Big hole... Very big... Huge.}
{110}{}{Nuh?}
{111}{}{Uh-huh!}
{112}{}{Gug! (you look concerned)}

{113}{slk4}{Don't want a hole? Go see Torr, he your spirit-brother. He work for Maida-with-no-smiles. Just like we and I.}
{114}{}{Uh-huh.}
{115}{}{Huh?}

{116}{slk5a}{Ah, shit, fren. Slavers took our sister. We went drinking, then went breaking. Now paying off Maida. When
 that done, we go find sis.}
{117}{slk5b}{Now we be getting ready to leave. Go look for sis. She snatched by slavers.}
{118}{}{Uh?}
{119}{}{Hmm, how much do you have to pay before you can go free?}
{120}{}{Uh-huh.}
{121}{}{I'm looking for something. Maybe you could join me.}

{122}{slk6}{We owe Maida $350. You heading south? We walkabout with you and look for sis. You
 having $350?}
{123}{}{Nuh-uh.}
{124}{}{Uh-huh!}
{125}{}{Here's the $350.}
{126}{}{Who's we?}
{127}{}{Maybe so, Sulik. Let me ask you something though.}
{128}{}{$350 is a lot of money. You're going to be here for a while. Goodbye.}
{129}{}{A master probably keeps you out of trouble. I don't think you'll be going South
 anytime soon. Goodbye.}

{140}{slk6a}{The spirits with me, fren! They be all around. Sometimes talk.}
{141}{}{Kind of like extra bats in the belfry, huh?}
{142}{}{What spirits?}
{143}{}{Ok... Can I ask you something else?}

{150}{slk6b}{That be funny, fren. At least, Grampy Bone think so. He say you got wit. Say
 you going to need it.}
{151}{}{Why?}
{152}{}{Who's Grampy Bone?}
{153}{}{Can I ask you something else?}

{160}{slk6c}{Him got feeling about you. Grampy Bone one smart spirit.}
{162}{}{What feeling?}

{170}{slk6d}{Spirits be everywhere. Travel with we and I. Grampy Bone do most the talking.}
{171}{}{I'd like to ask something else.}

{180}{slk6e}{That all he say right now. Spirits see and say different. Not like normal folk.}
{181}{}{And you would have any idea what normal was?}
{182}{}{Tell me about Grampy Bone.}

{190}{slk6f}{Him strong spirit. Much honor carrying him.}
{191}{}{Wait. You mean that bone in your nose?}

{200}{slk6g}{Keep him close. Easier to touch his spirit. That's why he talk the most.}
{201}{}{Hey, I can only hear you talking so far.}

{210}{slk6h}{We going get along just fine.}
{211}{}{Maybe we can talk more later. Bye.}

{220}{slk7}{Vic the traitor, more like. Comes to village, says he knows about slavers, tell us
 to come see him. We go, he ain't there.}
{221}{}{Your sister was taken by slavers?}
{222}{}{Let me ask you something else.}
{223}{}{I guess that's all I need to know for now. Goodbye.}

{230}{slk8}{We and I thank you. Name's Sulik. How can we repay?}
{231}{}{Uh.}
{232}{}{Bye bye.}
{233}{}{Who's "we?"}
{234}{}{I was happy to help, Sulik. Tell me about yourself.}
{235}{}{How about telling me what's going on in town?}
{236}{}{I just didn't want to see you imprisoned here any longer. Goodbye.}
{237}{}{Tell me about yourself.}

{240}{slk9a}{We and I will do so.}
{241}{slk9b}{We and I are the spirit of wrath, fren.}

{243}{slk10a}{You got it, fren.}
{244}{slk10b}{We and I are ready to fight.}

{246}{slk11a}{We be like a turtle, fren.}
{247}{slk11b}{We and I will.}

{250}{slk12a}{This one bad trip, fren.}
{251}{slk12b}{We have felt better.}

{253}{slk13a}{It's so bad, we all hurt.}
{254}{slk13b}{Spirits think we and I may be joining them soon.}

{257}{slk14a}{Spirit of poison making home in me.}
{258}{slk14b}{Poison spirit moving in, moving out good spirits fast.}

{260}{slk15a}{Evil spirit is possessing us, fren. Chunks of hair be falling out!}
{261}{slk15b}{We and I glowing! Very bad spirit here.}

{263}{slk16a}{This good place. Maybe no one try to kill us for a change.}
{264}{slk16b}{Grandfather Bone say this good place.}

{267}{slk17a}{Bad spirits lurk here. We need to walk on.}
{268}{slk17b}{Grampy Bone say we should leave here.}

{270}{slk18a}{We and I've been in bad places before. This worse.}
{271}{slk18b}{Grampy Bone say this one bad place. If he talk, you and we need to listen.}

{280}{slk21}{Sis went trading at another village and never came back. We and I go look for her.}
{281}{}{What did you find?}

{290}{slk22}{We and I know there's slavers at Den. When we're free, we're outta here.}
{291}{}{Tell me about something else.}
{292}{}{I think that's all I need to know for now. Goodbye.}

{300}{slk23a}{We just say no.}
{301}{}{I see. That's all I need to know for now. Goodbye.}
{302}{slk23b}{We and I only use herb superb.}

{310}{slk25a}{She's the boss. We pay off and go find sis.}
{311}{slk25b}{Maida used to run our life. We think she like us - she's not happy we're free.}
{312}{}{Hmm, tell me about something else.}

{320}{slk26a}{They don't want to talk right now.}
{321}{slk26b}{The spirits are sometimes hard to understand. They see things you and we can't.}
{322}{slk26c}{Spirits be willing to talk. What you want?}
{323}{}{Uh?}
{324}{}{Nuh.}
{325}{}{Nuh-uh.}
{326}{}{What do they tell you about this place?}
{327}{}{What do they tell you about our chances?}
{328}{}{I'd rather talk about something else.}
{329}{}{I don't think I want to know what the spirits think.}

{350}{slk27aa}{They all say dark clouds gathering.}
{351}{slk27ab}{Grampy Bone say they all gone.}
{352}{slk27ac}{Spirits see more joining them. Many more.}

{360}{slk27ba}{Grampy Bone say they all standing on the Great Water... Doesn't make sense to we and I, either.}
{361}{slk27bb}{Spirits don't understand reason they gone. See it, don't understand it.}
{362}{slk27bc}{They say there was a strong spirit here. Somehow that's why all were taken.}

{370}{slk27ca}{Evil spirits aren't killing cattle.}
{371}{slk27cb}{Bad spirit under something... snaps. Not sure what that mean.}

{380}{slk27da}{Grampy Bone say this place full of bad people.}
{381}{slk27db}{They say people get lost here real easy. In many ways.}
{382}{slk27dc}{Hey! They say another bonespirit's here. Needs help.}

{390}{}{They all very sad. Say time coming soon where there'll be nothing but bonespirits here.}
{391}{}{This place has no future. We and you need to do something.}

{400}{slk27fa}{Grampy Bone laughing, even though not funny. The fight's over something lost, not taken.}
{401}{slk27fb}{Spirits not happy. Others pretend to be spirits, try to scare them like children.}
{402}{slk27fc}{He who's with the spirits isn't... That's what they said.}
{403}{slk27fd}{Everyone in the ground not be dead.}

{410}{slk27ga}{Grampy Bone say things can be made good, but help needs come from outside.}
{411}{slk27gb}{One place help the other, help self. Too bad they can't see it with their eyes open.}

{420}{slk27ha}{We need to go where the spirits go, just not be what they are.}
{421}{slk27hb}{This one is not the one, but it helps be the one... maybe spirits know more, maybe not. We
 and I think they like to talk like that.}

{430}{slk27ia}{Spirits say these are touched by shadow from city of lights.}
{431}{slk27ib}{The head isn't with the body.}

{440}{slk27ja}{Spirits see two paths, joining others. Bad path goes to bad shadows in bright area. Good
 path goes to bright place that was born of shadows.}
{441}{slk27jb}{Don't send them to the lights.}
{442}{slk27jc}{Convince them to be part of something larger.}

{450}{slk27ka}{No spirit guides these hands.}
{451}{slk27kb}{A reed bends, an oak gets blown up.}
{452}{slk27kc}{You can make a friend here.}

{460}{slk27la}{Who poisoned the youth?}
{461}{slk27lb}{Right is right.}
{462}{slk27lc}{This place is full of poison.}

{470}{slk27ma}{Those that stand in front backstab.}
{471}{slk27mb}{The ground glows with a light not of the spirits.}

{480}{slk27na}{You must be a bridge between sides.}
{481}{slk27nb}{Quiet that which is under the water or the salvation of your tribe will also go under.}
{482}{slk27nc}{That which pushes the great steel tree into the sky must go to cradle the tribe.}
{483}{slk27nd}{Your people are worth more than the dark gold. Carry them with no less care.}

{490}{}{Those who appear to be spirits but are not carry many secrets.}
{491}{}{Like an onion, there are many layers, most hidden.}
{492}{}{The lifting machine may take you to unexpected places.}

{500}{slk27pa}{The spirits see the shadow that cast your shadow here from before.}
{501}{slk27pb}{There are dangerous ones here.}
{502}{slk27pc}{There are other shadows from the one that cast your shadow here.}

{510}{slk27qa}{Taken. All taken.}
{511}{slk27qb}{The spirits see the same swallowing cloud heading to your home.}
{512}{slk27qc}{All taken to the Great Salt Water.}

{520}{slk27ra}{What you seek is not here. The path to that is.}
{521}{slk27rb}{Walk the quiet way and learn much.}
{522}{slk27rc}{A strong seed is planted here. A good seed.}

{530}{slk27sa}{An empty shell rests below those that rest.}
{531}{slk27sb}{Talons of death are close.}
{532}{slk27sc}{Small death will follow you.}

{540}{slk27ta}{The voice is louder than the sound of any gun.}
{541}{slk27tb}{Evil hops here.}
{542}{slk27tc}{The pathway of evil is laid clear here.}

{550}{}{There is great knowledge here.}
{551}{}{A stronger path through the future starts in such small places.}

{560}{slk28a}{We need a little time to be by ourself.}
{561}{slk28b}{Be needing some time off. A little smoke, a little think.}

{600}{}{Ok. Thanks.}

{704}{slk28a}{We need a little time to be by ourself.}
{705}{slk28b}{Be needing some time off. A little smoke, a little think.}

{706}{slk29a}{Let us show you how it's done in our tribe.}
{707}{slk29b}{We be knowing the earth and winds well. We take care of this one.}
{708}{slk29c}{Bonespirits help us out on this one.}

{709}{slk30a}{We be like ugly on... you.}
{710}{slk30b}{Yeah, you be needing us to stay close. Keep you out of trouble.}
{711}{slk30c}{We and I stay close if you promise to buy soap in next town.}

{712}{slk31a}{Will do.}
{713}{slk31b}{We be here if you need us.}
{714}{slk31c}{Probably a good thing to keep a little distance. People trying to kill you all the time.}

{715}{slk32a}{No problem.}
{716}{slk32b}{Good idea. You probably going to get shot at anyway.}
{717}{slk32c}{We and my nose thanks you.}

{718}{slk33a}{Time for a little herb-superb anyway. More for us.}
{719}{slk33b}{Sounds like a plan. Bad things following you around like nobody's business anyway.}
{720}{slk33c}{Good luck to you, fren. We be thinking you be needing it.}

{721}{slk34a}{We be here.}
{722}{slk34b}{Going to take a little nap, talk to Grampy Bone. Not going anywhere.}
{723}{slk34c}{This look like a good place to sit back for a bit.}

{724}{slk35a}{Hey, fren, just tell us to get out of your way.}
{725}{slk35b}{Sorry, fren.}
{726}{slk35c}{We move for you, no problem.}

{727}{slk36a}{Will do.}
{728}{slk36b}{Grampy Bone be telling us same thing}
{729}{slk36c}{Lotta fighting. Need better weapon.}

{730}{slk37a}{Spirits help, too. That and armor almost enough around you.}
{731}{slk37b}{Good idea. You draw angry people like flies on pasture pies.}
{732}{slk37c}{With you around, we be needing all we can get.}
{733}{slk37d}{It too heavy, fen. We like to dance away from the bad things.}

{734}{slk38a}{You need it, you got it.}
{735}{slk38b}{Let's do it.}
{736}{slk38c}{Trading no problem, fren. But only got one Grampy Bone. Sorry.}

{737}{slk39a}{That be a good thing, fren.}
{738}{slk39b}{Will do.}
{739}{slk39c}{We didn't want to be a little girl about it, but...}
{740}{slk39d}{No problem, fren. We're strong.}
{741}{slk39e}{Spirits have guarded us. We're fine.}

{742}{slk40a}{We and I will take a look.}
{743}{slk40b}{Grampy Bone saying we should be careful.}
{744}{slk40c}{No problem. Make sure it safe for our fren.}

{745}{slk41a}{From now on you give two for one in trades... Just kidding. Grampy Bone
 say you get funny look - like that one.}
{746}{slk41b}{Sounds good.}
{747}{slk41c}{What's ours is yours, fren.}

{750}{slk42}{We and I thank you. You try to do a good thing, just don't have the bread. Maybe you
 can raise some?}
{751}{}{Uh.}
{752}{}{Sorry, I must have miscounted. Goodbye.}
{753}{}{I thought I had enough. Sorry. Let me ask you something.}

{754}{slk43a}{Yeah. We be giving this to Maida. Then we be free. Want us to walk by-and-by?}
{755}{slk43b}{Yeah. You may be ugly outside, but you're way cool inside. We're free to find sis now.}
{756}{slk43c}{Oh, yeah. Way cool. We'd go with you, but you're already a crowd.}
{757}{}{Nuh-uh.}
{758}{}{Uh-huh.}
{759}{}{Not right now, thanks.}
{760}{}{That'd be great.}

{761}{slk44a}{We and I know many things. Travel from Great Salt Water to home of biting lizards.}
{762}{slk44b}{We and I be glad to answer.}
{763}{}{Tell me about the Great Salt Water.}
{764}{}{Biting Lizards?}
{766}{}{Why did you travel so much?}
{767}{}{What are you doing here?}
{768}{}{I'm interested in some local information.}
{769}{}{Would you like to come with me? We might be able to find your sister in the course of my travels.}
{770}{}{I don't think I need to know anything else right now.}

{771}{slk45}{The tribe's home is next to Great Salt Water. Two moons from here, fren.}
{772}{}{Let me ask you something else.}
{773}{}{Two moons? That's a long ways. How did you travel so far safely?}
{774}{}{That's all I need for now. Goodbye.}

{775}{slk46}{Geckos. The little dudes don't bite hard. It's the Goldens. They go through your leg like an
 old pipe stem.}

{776}{slk47}{Trader named Vic supposed to be here. He be saying he know about slavers. We show up, didn't
 peep him, get pretty hot.}
{777}{}{Vic's here and he ran into the slavers too, and they were holding him as one in the
 Den. Tell me something else.}
{778}{}{Bye.}

{779}{slk48a}{Slavers got our sis. Thought Vic be having information. Couldn't peep him, got p.o.'d, drank
 like a fish. Spirits of Anger and Chaos pop out and now we have to pay some coin to make it right.}
{780}{slk48b}{We be trying to know which way to go to find slavers who take sis. Maybe south.}
{781}{slk48c}{Getting down to find sis. Think we go south, but not sure yet. You want company?}
{782}{}{You were looking for Vic the trader?}
{783}{}{You have to pay for damages?}
{784}{}{Uh! Uh, uh!}
{785}{}{I'll be going South. You're welcome to travel with me.}
{786}{}{You're looking for your sister?}

{787}{slk50}{Fren, with all the spirits walking with me, not afraid to travel anywhere.}

{790}{slk52a}{You're bad news walking. Grampy Bone say we be stacking up the bad karma just being
 near you.}
{791}{slk52b}{We're there. Grampy Bone say we might find sis with you.}
{792}{}{Uh.}
{793}{}{I hope so. In any case it will be nice to travel with you, and, uh, your Grandfather's
 bone.}

{794}{slk53}{Not just Grampy Bone, all tribe's spirits. Grampy Bone just wiser and stronger than
 the rest. Let's ease on down.}
{795}{}{Uh, yeah. OK, Sulik.}

{796}{slk54}{What can we and I do ya for?}
{797}{}{I have some questions for you.}
{798}{}{Where can I find trade, a healer, or a room?}
{799}{}{Ever hear of a Garden of Eden Creation Kit?}
{800}{}{What's going on in town?}
{801}{}{What are you doing here?}
{802}{}{Now that you're free, why not travel with me?}
{803}{}{I guess I don't need anything right now. Goodbye.}

{804}{slk55}{So many questions. Maida takes care of trade here and her mother, Ardin, takes care of the
 rooms. No Shaman in town, but you may be able to trade for medicine.}
{805}{}{Oh, thanks. Let me ask you something else then.}
{806}{}{I guess that's all I need to know. Goodbye.}

{807}{slk56}{Never heard of it. But Maida's been keeping us busy.}
{808}{}{Who's Maida?}
{809}{}{Oh, well let me ask you something else.}
{810}{}{Well, I guess I'll let you get back to it then. Goodbye.}

{811}{slk57a}{Busy place. Bugmen snatching cattle, spirits walking, Smiley missing.}
{812}{slk57b}{Busy place. Bugmen snatching cattle, spirits walking, Smiley missing. Now Torr's missing too.}
{813}{slk57c}{You have more questions for Sulik?}
{814}{}{Tell me about the Bugmen.}
{815}{}{Walking spirits? Tell me about that.}
{816}{}{Smiley? Who's Smiley?}
{817}{}{Torr's missing? Where do you think he might have gone?}
{818}{}{Let me ask you about something else.}
{819}{}{I don't think I need to know anything else right now. Goodbye.}

# Will be removing the word Pistol from his dialog when the new audio is back.
{820}{slk58alt}{We be good with fists, spear, big hammer or sub-machine gun. We be a handful.}

{821}{slk59}{Torr be telling us about Bugs that walk on two feet and steal Brahmin. Shook him up.}
{822}{}{Interesting. Let me ask you something else.}
{823}{}{I guess that's all I need to know. Goodbye.}

{824}{slk60}{The canyon east of herd area supposed to have a walking, howling Spirit. Shaking the
 locals. Grampy Bone don't say a word, though.}

{825}{slk61}{Smiley's a good hunter. Say he looking for the Golden Gecko's nest. Didn't come back.}

{830}{slk62a}{Where the quaking rock dwells, follow the path you cannot see.}
{831}{slk62b}{The wind moves to secret places.}
{832}{slk62c}{Look for the vision that does not belong.}
{833}{slk62d}{The higher the place, the longer the face.}
{834}{slk62e}{Still waters don't run at all.}
{835}{slk62f}{A flower opens its petals to the sun. Seek that which is like the flower.}
{836}{slk62g}{That which is a door does not always lead to anywhere. That which is not a door does.}
{837}{slk62h}{Seek a reflection of yourself. The pathway will open before you.}
{838}{slk62i}{The grass is greener across the fence, but you must first find that fence.}
{839}{slk62j}{Lifting rocks will find more than slugs.}

{840}{slk63a}{A door is only one path to the other side.}
{841}{slk63b}{There are times to speak and times to listen.}
{842}{slk63c}{The best answer is not always the loudest.}
{843}{slk63d}{Even the smallest mind contains some knowledge.}
{844}{slk63e}{After you kill something, it will not talk to you.}
{845}{slk63f}{If it's broken, then it once worked.}
{846}{slk63g}{Tools come in strange shapes.}
{847}{slk63h}{You don't send a blacksmith to bake bread.}
{848}{slk63i}{No one questions those they see everyday.}
{849}{slk63j}{If you wait long enough, most addictions will cure themselves.}
{850}{slk63k}{Killing good people taints your soul - some people can sense this.}
{851}{slk63l}{Killing bad people is good for your Karma - some people can sense this.}
{852}{slk63m}{An act of kindness is rarely forgotten.}

{860}{slk64a}{Green will be lucky for you.}
{861}{slk64b}{A little bit softer now.}
{862}{slk64c}{Look before you fall.}
{863}{slk64d}{A porcupine is not a pillow.}
{864}{slk64e}{Where does a shadow go in the dark?}
{865}{slk64f}{A little bit louder now.}
{866}{slk64g}{Mushrooms make bad dinner hosts.}
{867}{slk64h}{It is easy to become a spirit.}
{868}{slk64i}{Shout.}
{869}{slk64j}{Whiskers grow, water runs, but rocks just sit.}
{870}{slk64k}{When daylight ends, what begins?}

{880}{slk65}{What you be needing?}
{881}{}{I need you to get out of my way.}
{882}{}{I want to change combat tactics.}
{883}{}{I need you to wait here.}
{884}{}{You should heal yourself.}
{885}{}{Tell me how you are.}
{886}{}{That's it for now, Sulik.}
{887}{}{Tell me about this place.}

{890}{slk66}{What be the fighting strategy?}
{891}{}{I want you to change your distance.}
{892}{}{I want you to use your best weapon.}
{893}{}{I want you to use your best armor.}
{894}{}{I want you to change your aggressiveness.}
{895}{}{Never mind.}

{900}{slk67}{What distance you need us at?}
{901}{}{I want you to stay at only a Short distance.}
{902}{}{I want you to stay at Medium distance.}
{903}{}{I want you to stay at Long distance.}
{904}{}{I need you to Scout Ahead.}

{905}{slk68}{How do you want us to fight?}
{906}{}{I want you to Fight Defensively for now.}
{907}{}{I need you to Fight Normally.}
{908}{}{I need you to Fight Aggressively.}

{910}{slk69}{One survivor. Dude was in bad shape. Said evil warriors came with magic torches. Fire
 would lick tribe warriors and they'd go to the spirit.}
{911}{}{What about your sis?}

{912}{slk69a}{The evil warriors tied up the rest and took off. Sis with 'em. Fren, we be finding her or
 dying trying.}
{913}{}{Sounds like slavers to me. Have you found anything out about them?}
{914}{}{I'm sorry to hear that. I hope you find her. Let me ask you something else.}
{915}{}{I think that's all I need to know for now. Goodbye.}

{916}{slk70a}{Be like middle of ant hill here. Too crowded for us.}
{917}{slk70b}{Our tribe seems smaller than this. Too many people for this trip.}
{918}{slk70c}{You have your army. Don't need we and I for help now.}

{919}{slk71}{We and I sad to see you take the mark. Think you growing dark in the soul. Have to
 go. See you.}

{920}{slk72}{You think owning people OK? Some fren. We're gone.}

{921}{slk73a}{You got a lot of problems with people. We'll go until you be figuring that one out.}
{922}{slk73b}{You like a bad dream. We gotta go.}

{923}{slk74}{No way we be frens with Child Killer.}

{924}{slk75}{We think you're making a big mistake, but OK.}

{925}{slk76}{We be hearing you helping Torr. Him losing any more Brahmin is big trouble.}
{926}{}{Uh?}
{927}{}{Uh. Bye.}
{928}{}{Well, he sure looked as though he needed help. I have some questions for you.}
{929}{}{He needed the help all right. I need some local information.}
{930}{}{Torr needs some help. I better get to it. Goodbye.}

{931}{slk77}{We be hearing you couldn't help Torr. Too bad, dude needs some serious.}
{932}{}{Well, that happens. I need some local information, though.}
{933}{}{I really tried to help him. I'm sorry I wasn't able to. Goodbye.}
{934}{}{Well, he was an idiot, so who cares what happens to him. Goodbye.}

{935}{slk78}{Hope you be finding Torr. He needs help.}
{936}{}{Where has Torr gone?}
{937}{}{I'm sorry Torr is missing. I have some questions for you, though.}
{938}{}{I'd like to help Torr but I don't have time right now. Goodbye.}
{939}{}{Torr's nothing but a defective None of us can help Torr with that. Goodbye.}

{940}{slk79}{We be hearing him talk of killing Spirit that Walks. Trying to be brave.}
{941}{}{Spirit that Walks?}
{942}{}{Whoa. Spirits? Sounds scary. Goodbye.}

{943}{slk80}{To the east is a canyon where Brahmin graze. We hear several moons back there was
 lightning and thunder... without clouds. Evil spirits come to that living land.}
{944}{}{Really?}

{945}{slk80a}{Locals start to hear strange noises. Spirits in torment, say we and I. A few even
 see something there. Spirit-creature not wearing the shape of a man.}
{946}{}{Huh.}
{947}{}{Sounds dangerous. What's Torr got to do with it?}

{948}{slk80b}{Torr be the butt of many jokes. So him think finding and killing this bad spirit
 make him hero. We think he in trouble. You be helping Torr?}
{949}{}{Huh-uh!}
{950}{}{Uh-huh.}
{951}{}{I'll go look for him right away.}
{952}{}{Of course, I'll help him. I need some information first though.}
{953}{}{We should probably give him a little more time. He can't be a hero if we step in. I
 could use some local information.}
{954}{}{Uh, interesting story but I don't think I can help Torr. I'm pretty busy. Goodbye.}

{955}{slk81a}{Sis found. We send her home. She strong, can make it fine. We want go with you. Grampy
 Bone say you have big path to travel.}
{956}{slk81b}{You be having us go with you now?}
{957}{}{Nuh-uh.}
{958}{}{Uh-huh.}
{959}{}{You should return to your village with her to make sure she's safe. I'll miss you, Sulik.}
{960}{}{Let's go, Sulik.}

{961}{slk82a}{By the time you're done, won't be a bad person in the world.}
{962}{slk82b}{Fren, you ever wonder if there's more bad people than bullets?}

{963}{slk83a}{You just like to see insides of bodies, right?}
{964}{slk83b}{Grampy Bone say I should worry if no one else around for you to kill.}

{965}{slk84a}{We and I think your little head be doing all the thinking.}
{966}{slk84b}{You spend too much time laying down on job.}

# FLOATS
{1016}{}{Be like middle of ant hill here. Too crowded for us.}
{1017}{}{Our tribe seems smaller than this. Too many people for this trip.}
{1018}{}{You have your army. Don't need we and I for help now.}
{1020}{}{You think owning people OK? Some fren. We're gone.}
{1021}{}{You got a lot of problems with people. We'll go until you be figuring that one out.}
{1023}{}{No way we be frens with Child Killer.}
{1025}{}{You be causing trouble in Klamath. We're gone.}
#killap -expansion
{1026}{}{You be causing trouble in my home village. We're gone.}

{2300}{}{De spirits be movin' us.}
{2301}{}{We and I be movin'.}
{2302}{}{OK, take it easy.}
{2303}{}{Don' worry, We an' I be movin'.}
{2304}{}{We thinkin' you need time to smell de flowers. Grampy-Bone say you're too pushy all de time. You got to be takin' life slower.}
{2305}{}{We be movin' an' groovin'.}
{2306}{}{We and I go over here now.}
{2307}{}{Relax, be happy, we move now.}

{3000}{}{To the North.}
{3001}{}{To the Northwest.}
{3002}{}{To the setting sun.}
{3003}{}{To the Southwest.}
{3004}{}{To the South.}
{3005}{}{To the Southeast.}
{3006}{}{To the rising sun.}
{3007}{}{To the Northeast.}
{3008}{}{We don't know anything about that.}
{3009}{}{Yes.}
{3010}{}{No.}
{3011}{}{What do you expect from us?}
{3012}{}{That not be nice.}
{3013}{}{Thank-you.}
{3014}{}{This is good.}
{3015}{}{This isn't good.}
{3016}{}{We have a good feeling about this.}
{3017}{}{We have a bad feeling about this.}
{3018}{}{These people are crazy.}

{3020}{}{There must be another way.}
{3021}{}{Follow us.}
{3022}{}{Try this.}
{3023}{}{We go here now.}
{3024}{}{It went this way.}
{3025}{}{They went this way.}
{3026}{}{This is the path.}
{3027}{}{We've have found the trail.}
{3028}{}{Good hunting here.}
{3029}{}{Bad hunting here.}
{3030}{}{Safe to camp here.}
{3031}{}{Not safe to camp here.}
{3032}{}{We can rest here.}
{3033}{}{We get lucky.}
{3034}{}{You need to fix this.}
{3035}{}{You need to turn this on.}
{3036}{}{You need to unlock this.}
{3037}{}{You need to open this.}
{3038}{}{Maybe we should come back here.}
{3039}{}{We don't understand.}
{3040}{}{We don't know.}

{3050}{slk86}{Being home is cool, but the place is looking a might small now. We've missed the road
 and the company of so fine a fren as you. Wan us to walk by-and-by again.}
{3051}{}{That would be great.}
{3052}{}{Sorry, not right now.}

{3053}{slk87}{We do some byes and catch you up on the road out.}
{3054}{}{OK.}

{3055}{slk88}{That be too bad. Tell you what, you be needing this stuff more than me. Walk well.}
{3056}{}{On second thought, maybe you should come with me. Sorry, I just didn't want to part you from
 your home so soon.}
{3103}{}{You too, Sulik. Take care of yourself.}

{3057}{slk89}{Good to see home, but not while sis is still gone. Be wanting to stay in your
 company, OK?}
{3058}{}{Yes.}
{3059}{}{No, I think it's time you looked for her yourself.}

{3060}{slk90}{Maybe so. We and I miss you, though. Good spirits be with you, fren.}
{3061}{}{Thanks, Sulik. Goodbye. [Sulik hands you his gear.]}
{3062}{}{Well, maybe you should continue on with me. I suppose we might still find your sister.}

{3063}{slk91a}{You be wanting some good company after all?}
{3064}{slk91b}{It be good to be back home again.}
{3065}{slk91c}{We be needing to have a talk with the herb-superb. Let the world float by-and-by.}
{3066}{slk91d}{So many young maidens to tell our travels to - and so little time.}
{3067}{slk91e}{Funny thing. We be happy to be home, but a little restless for the road already.}
{3068}{}{Yes, I do.}
{3069}{}{No, I don't.}

{3070}{}{Sulik, can you consult the spirits for me?}
{3071}{}{Sulik, please holster your weapon.}
{3080}{}{You be no fren of mine. Grampy Bone say no talk to you.}

#added by killap
{3081}{}{No, I think it is time we part our ways. Stay here with you sister, she needs you.}
{3082}{}{It be good to be back home again.}
{3083}{}{So many young maidens to tell our travels to - and so little time.}
{3084}{}{We be needing to have a talk with the herb-superb. Let the world float by-and-by.}

{3086}{}{Take care, fren.}
{3087}{}{We and I wish you the best of luck.}
{3088}{}{Thanks again for everything, fren.}

{3090}{}{This here be our village. We and I go speak with our friends.}
{3091}{}{We and I go speak with our friends again before headin out.}

{3100}{}{[MORE]}
{3101}{}{Where exactly is your tribe, Sulik?}
{3102}{}{Thanks. Let me ask you something else.}

{3200}{}{Yes, I spoke with Mrs. Buckner regarding your debt. I just now need to make all the arrangements with Maida. I'll check with you again after I speak  with her.}

#added by killap - warns the player if something is wrong with the NPC
{3500}{}{We and I think something be wrong with us. You better be having a look at this limb of ours.}
{3501}{}{We and I think something be wrong with us. We be glowing like the sun.}
{3502}{}{We and I think something be wrong with us. We be feeling poisoned.}


