{100}{}{You see a scruffy looking person.}
{101}{}{You see a citizen of Klamath.}
{102}{}{You see a squatter.}
{103}{}{You see a backwoodsman.}
{104}{}{You see a trapper.}
{105}{}{You see a trapper.}

{110}{}{Heh, heh - you reckon you're one of us now?}
{111}{}{We ain't got nothing left to steal here.}
{112}{}{Trapper Town's got bigger rats every day. Some even stand erect.}
{113}{}{No room for you here.}
{114}{}{No squats left here.}
{115}{}{What are you looking at?}
{116}{}{Damn tribals, always stirring up trouble.}
{117}{}{You should go south.}
{118}{}{Something smells worse than a gecko pelt.}
{119}{}{Rats everywhere!}
{120}{}{By the Great Rat Spirit, what's next?}
{121}{}{I'd offer a prayer to the Great Rat Spirit if you're in town for long.}
{122}{}{Watch out, or you'll end up just like Phil.}
{123}{}{You're just like the Duntons.}
{124}{}{I don't think we want you in this part of town.}
{125}{}{What's your problem?}
{126}{}{(Mumble, mumble)...only one kind of good tribal, and that's a...(mumble)}

{130}{}{This part of town's for us professionals only.}
{131}{}{Hmm... You don't look as though you could find a gecko if it bit you.}
{132}{}{I'm surprised you made it all the way here from your tribe.}
{133}{}{Watch out for the rats here.}
{134}{}{Golden geckos can grow five times as long as a man is tall.}
{135}{}{Them golden geckos have a deadly poison in their fangs.}
{136}{}{Anyone seen Phil? I think we lost another trapper to the rats last night.}
{137}{}{Have you seen Phil?}
{138}{}{Those rats are so hungry these days.}
{139}{}{There are supposed to be old mine tunnels underneath here.}
{140}{}{Wish I could figure out how to get to that Corvega.}
{141}{}{Watch out for slavers. They just love to take tribals.}
{142}{}{I sure wish I had enough money to get a bath.}
{143}{}{I want to go visit my Jenny.}
{144}{}{Another few pelts and I'll be able to buy myself a bath.}
{145}{}{Mmm, I love that Dunton's Drymeat.}
{146}{}{If the bugmen ever show up here, the rats will eat them. Heh, heh.}
{147}{}{Yessir, there are old tunnels underneath Klamath. You better believe it.}
{148}{}{Lots of stuff crawling around in those buildings.}

{150}{}{You look as though you know your way around the woods.}
{151}{}{Trapping geckos is dangerous -- but it pays well.}
{152}{}{I hate all the rats here. They're too dang smart for the traps!}
{153}{}{Watch out for golden geckos; they're twice as tough as the ordinary ones.}
{154}{}{You're from the Arroyo tribe, ain't you? Can tell by your looks.}
{155}{}{Sometimes I think I've seen a really big rat back in the buildings here.}
{156}{}{It's cheap to live here, but you have to put up with rats.}
{157}{}{(Chewing noisily) Rat tastes better than most people think. Hungry?}
{158}{}{You know, geckos taste a lot like something else if you cook them right. Can't rightly
 remember what, though.}
{159}{}{Some animals like drymeat so much that they'll run for it instead of you.}
{160}{}{Remember, if you ever sell too many gecko hides at once, their price will drop.}
{161}{}{Someday, I want to get a weapon with some range to it.}
{162}{}{I swear I've seen bugmen out near the brahmin grazing area east of town. }

{170}{}{I hated the rats here. I'm sure glad they're gone.}
{171}{}{Trapping geckos is dangerous but it pays well.}
{172}{}{Watch out for golden geckos, they're twice as tough as the ordinary ones.}
{173}{}{You're from the Arroyo tribe ain't you? Can tell by your looks.}
{174}{}{There used to be a lot more rats. Can't say's I miss 'em.}
{175}{}{Those rats been deserting this place like it was sinkin'.}
{176}{}{(Chewing noisily) Rat tastes better than most people think. Hungry?}
{177}{}{You know geckos taste a lot like something else if you cook them right. Can't
 rightly remember what though.}
{178}{}{Some animals like drymeat so much that they'll run for it instead of you.}
{179}{}{I haven't heard that weird voice comin' from the rat caves lately. Wonder
 where it went?}
{180}{}{Y'know, don't laugh at me, but I think the Rat God's dead.}
{181}{}{I heard that the Rat God's dead. Not that I believe in stuff like that.}

{200}{}{You see a rough-hewn person with leather boots.}
{201}{}{You see a person who must spend a lot of time outdoors.}
{202}{}{You see a person with roughly made and repaired clothing.}
{203}{}{You see a rough-hewn trapper with gecko-hide boots.}
{204}{}{You see someone who spends a lot of time in the wilderness. They're wearing
 a gecko-pelt shirt.}
{205}{}{You see a trapper who makes his home in Trapper Town.}

#by phobos2077 - alternative gecko skinning teacher
{500}{}{What do you want, tribal?}
{501}{}{You look like you know how to handle geckos. Can you teach me something?}
{502}{}{Me wants skin Gecko. Trapper knows. Trapper teach us.}
{503}{}{Nothing.}
{505}{}{Damn right I can. But I see no reason to help you for free. $300 should cover it.}
{506}{}{Here is your money.}
{507}{}{I don't have such money.}
{508}{}{Money, here.}
{509}{}{No money, no money...}
{510}{}{Trapper named Smiley taught me this. Good fella... Anyway, here's how you skin them (the Trapper demonstrates)... You will get your money back in no time. They give pretty decent price for those skins here.}
{511}{}{Thanks, I'm sure that will come in handy.}
{512}{}{Urk. Pretty, heh, heh, heh. Money. Heh, heh, heh. Bye.}
{515}{}{Then we have nothing else to talk about.}
{520}{}{I already taught you everything.}
{521}{}{There is nothing else I can do for you.}
{522}{}{You better go out and hunt some geckos.}
{523}{}{Those golden geckos can be very profitable for their skin.}

# leather jacket crafting
{530}{}{Hey, what do people do with all the gecko skins?}
{531}{}{They make tough clothing and leather armor, as far as I know. Well, I know they make leather jackets, because I even know how to do it.}
{532}{}{You know how to make a leather jacket? Could you teach me?}
{533}{}{Sure, if you give me $300. Don't ask me, how to make Leather armor though, there's more to it than I know. Jackets are simple enough.}

{534}{}{All right, here's your money.}
{535}{}{I think I'll pass.}

{537}{}{All right, you don't need more than silver gecko pelts, a load of rope and some patience (the Trapper takes you through the process). And there you go - leather jacket.
 If I were younger I'd go find someone who could teach me what the deal with proper leather armor is. Much better use of Gecko pelts. But few people can make them, all the good leather comes from Modoc.}

{540}{}{Who's Modoc?}

{541}{}{Buggered if I know. It's just something people say, "All good leathers come from Modoc". We get ours from the Den, like everything else. As far as I know.}
{542}{}{Oh, well, if that's so. Thanks for the leathercrafting tips, anyway.}