{100}{}{You see a heavy set man wearing a leather apron.}
{101}{}{You see Balthas the tanner.}
{102}{}{You see a tall, muscular man who looks and smells of leather.}

{151}{}{My son was mistakenly killed in the fight.}
{152}{}{I can't bear to live without Jonny.}
{153}{}{[Sob]}
{154}{}{Meet us down at the Ghost Farm. We're going to attack the ghosts.}
{155}{BAL1}{Hello, my name's Balthas. I run the tannery here in Modoc. Can I help you?}
{156}{}{You seem a bit preoccupied; is there something wrong?}
{157}{}{I'd like to see your wares.}
{158}{}{Have you seen a gold watch lying around anywhere?}
{159}{}{I'll be back later.}
{160}{}{I'm searching for an item called a GECK. Do you by any chance know anything about it, or how I
 might obtain one?}
{161}{}{GECK?}
{163}{BAL2}{What can I help you with?}
{168}{}{Just looking, thanks.}
{171}{BAL3}{Any luck finding Jonny?}
{172}{}{I found this at the bottom of the old dry well. A part of the well had fallen in, and
 this was in the debris. I'm sorry, but I believe Jonny is dead.}
{173}{}{No, nothing yet.}
{175}{BAL4}{Thank you for returning my boy to me. There's no way I can ever repay you, but please take this
 leather armor as thanks. I've been experimenting with a new curing process; I think you'll find this
 armor very durable, and besides -- you look really good in it.}
{176}{BAL23}{Thank you for saving my son!}
{177}{BAL5}{Please leave me to my grief.}
{178}{}{Jonny is alive! Some people called Slags have rescued him. If you can wait just a little longer,
 I'm working on a way to get Jonny back home to you.}
{179}{}{Jonny's been kidnapped. The ghosts at the farm have got him, and plan to sacrifice him to their
 dark god.}
{180}{}{I understand; sorry to disturb you.}
{181}{BAL6}{Huh? Look, I don't discuss my personal life with strangers. Do you have any business with me or
 not?}
{182}{}{Pardon me, my name is }
{183}{}{. Now that we're properly introduced, you seem troubled.}
{184}{}{Yes, I'm interested in some leather goods.}
{186}{}{I guess I don't.}
{187}{}{Did you say }
{188}{}{? Yes, I think I've heard of you. One of the guards on a passing caravan mentioned some good
 things about a person with that name. I know we've just met, but I could really use your
 help.}
{189}{}{Why don't you tell me what your problem is, and maybe I'll be able to help.}
{190}{}{I have problems of my own, sorry.}
{191}{BAL8}{[He picks up a metal chisel and starts to wring it anxiously. To your amazement, the chisel begins
 to bend like putty. This guy's strong!] My boy, Jonny, is missing! He went out to play a few days ago and
 never came back. We've searched everywhere, but still haven't found him.}
{192}{}{Where does Jonny normally play? Does he usually play with someone else?}
{193}{}{I'm sorry about your kid, but what could I possibly do?}
{194}{}{That's horrible! But I just stopped in to look at some leather goods. I don't suppose I could
 see some of your merchandise?}
{195}{}{Oooh! Look at the time. I have to be going.}
{196}{BAL9}{Does that mean you'll help me? Thank you! Jonny was last seen playing cowboys and Indians with
 his dog Laddie out front. The two of them are inseparable; in fact, that's how we knew something was
 wrong. One day, Laddie came back without Jonny. We've been searching ever since. Take Laddie with
 you; maybe the two of you will be able to find Jonny.}
{197}{BAL10}{Well, you have the air of an experienced traveler. With your skills, maybe you'll be able to
 track down my son.}
{198}{}{Well, yes! I am quite a skillful tracker, if I do say so myself. Okay, I'll help.}
{199}{}{Flattery will get you nowhere. Look, I need to ask you some questions.}
{200}{BAL11}{My prayers are answered! Take Laddie with you; maybe he can help. Please
 hurry!}
{201}{BAL12}{Well, maybe you're right. Thanks for listening.}
{202}{BAL13}{I've heard of you. Look, I don't want any trouble; we're a peaceful community. Let's just keep
 the subject to business, OK?}
{203}{}{I have some questions for you.}
{204}{}{I don't have any business with you for now. Bye.}
{205}{BAL14}{Well... I'm worried about my missing son, Jonny. We've searched everywhere, but still can't find
 him. I fear that maybe wild animals got him.}
{206}{}{Maybe I can help. I do a lot of traveling; I'll keep a lookout for your boy.}
{208}{BAL15}{I would really appreciate that. Every little bit helps. In the mean time, did you have some
 business with me?}
{210}{}{No, not really. I'll be going now, thanks.}
{211}{BAL16}{Sorry, I never heard of it.}
{214}{BAL17}{Hehehe. Has Old Cornelius got you looking for his pocket watch, too? No, you won't find it here.
 That old coot probably just left somewhere and forgot about it.}
{215}{}{Thanks anyway. I'll keep looking. Bye}
{216}{BAL18}{[He looks at you closely and then smiles.] Why don't you be a good little boy and run outside
 and play?}
{217}{BAL19}{[He looks at you closely and then smiles.] Why don't you be a good little girl and run outside
 and play?}
{218}{}{Please keep looking. I know he's still alive, I can feel it!}
{219}{BAL20}{That's Jonny's BB gun all right. Noooooooooooooooooooo! [Balthas breaks down and starts to cry
 uncontrollably.]}
{2199}{}{That's Jonny's BB gun all right... I don't believe he is dead. Please keep looking for my boy. I
 am sure he is still out there.}
{220}{BAL21}{I knew Jonny wasn't dead! You say I have to wait... I don't understand! Is he hurt? My instincts
 tell me to go to my son, but I sense you have my son's best interest at heart. Please hurry, and bring
 my son back to me.}
{221}{BAL22}{Oh no! Not the ghosts! I knew we should've burned that place to the ground. I won't let them
 take my boy... I'm going to get little Jonny back, whatever the cost. I'm sure the residents of Modoc
 will help me get my son back! Meet us at the Ghost Farm. We'll kill them all!}

{230}{}{You have safely returned Jonny back to Modoc.}

#added by killap - RP
{240}{}{Please, bring my son back to me safely.}


# phobos2077 crafting
{1001}{}{Actually I was wondering if you could teach me about tanning?}
{1002}{}{Not yet, sorry... Maybe you can teach me about tanning, though?}
{1003}{}{Can you teach me about tanning?}
{1010}{}{I could teach you... but I'm not sharing no trade secrets for less than $400.}
{1011}{}{It's a deal.}
{1012}{}{Let's cut it to $200.}
{1014}{}{Not interested.}
{1020}{}{$300 is my final offer.}
{1030}{}{Sure thing! For saving my son, you have all my attention. Let's get started, shall we?}
{1031}{}{Yes.}
{1032}{}{Maybe later.}
{1040}{}{OK, so first you need to understand that this involves a ton of rope...}
{1041}{}{... and if you've stitched it all right you got yourself a fine piece of armor. Oh, and if you can get your hands on some metal junk - you could probably attach that for extra protection.}
{1042}{}{This will definitely come in handy!}

# phobos2077 bring hides quest
{1101}{}{How's the tanning bussines? Need any help?}
{1102}{}{Not yet. Got anything else that needs doing?}
{1103}{}{I've brought some hides...}
{1110}{}{To be honest, I do. Word got out my armor's good, so I'm running out of raw materials. I need %1% mole rat hides. I can pay you $%2% for them.}
{1111}{}{Sounds good. I'll start hunting right away.}
{1112}{}{Not interested.}
{1120}{}{Well, I'm still waiting for that mole rat hides.}
{1130}{}{No, the materials you brought last time are enough for now.}
{1131}{}{I'll see you later then.}
{1140}{}{Let me see... Eh, those are some rough cuts... Nothing too bad, mind you. I'll take them...
 You know what, I can offer you something else instead of cash. I have this leather armor,  finished it only yesterday. What do say?}
{1141}{}{I'll take the cash.}
{1142}{}{Armor sounds good.}
{1150}{}{Let me see them... Looks nice. I see you are getting better at skinning those rats.}
{1151}{}{Thanks, now how about my payment?}
{1160}{}{Here is your reward.}
{1161}{}{It was a pleasure doing business. Goodbye.}
{1162}{}{Good, I'll go now.}


##############################################
#BONUS LINES NEEDED FOR THE TALKING HEADS MOD#
##############################################
{7700}{BAL7}{Did you say Stranger? Yes, I think I've heard of you. One of the guards on a passing caravan mentioned some good things about a person with that name. I know we've just met, but I could really use your help.}
