{100}{}{You see the leader of the Slags.}
{101}{}{You see Vegeir.}
{102}{}{A tall, stately man. His movements remind you of a cat stalking its prey.}

{150}{}{You may leave through the trap door located at the rear of this building.}
{151}{}{Please deliver the message to Modoc.}
{152}{}{Modoc is south of here.}
{153}{}{South.}
{154}{}{No, the other south.}
{155}{}{A visitor - how convenient. I've been contemplating on a way to make contact with the surfacers,
 but now I don't have to worry about that -- thanks to your timely arrival. Welcome to the home of the
 Slags.}
{156}{}{How good of you to return. I take it you have delivered the message to Modoc, then. How was it
 received?}
{157}{}{They need time to think it over.}
{158}{}{They have some reservations.}
{159}{}{I want to take Jonny home to his parents.}
{160}{}{Have you reconsidered helping us?}
{161}{}{I need to ask you some questions, first.}
{162}{}{The answer is still no.}
{163}{}{I have decided to help you.}
{165}{}{Thank you for helping us. You will always be welcome here. For your services, I offer this as a
 reward. [Vegeir hands you a hunting rifle.]}
{166}{}{Thank you for helping us. You will always be welcome here.}
{167}{}{Would it be all right to take Jonny home to his parents?}
{168}{}{Please let me apologize for the unpleasant circumstances under which we meet. Normally, the
 Protectors would have tried to scare you off. Usually rattling chains and some low moaning is
 enough to scare anybody off, but recently they have been instructed to bring any surfacers they find
 to me.}
{169}{}{That's all right. I'll just be going now.}
{170}{}{What do you want with me?}
{171}{}{Ghosts?}
{172}{}{You will go IF and WHEN I decide you can go. Not before.}
{173}{}{A simple request. We need to make contact with the town to the southwest; I believe it is called
 "Modoc." Would you do us this favor?}
{174}{}{What do I get out of this?}
{175}{}{I have many questions to ask before I can possibly take this mission.}
{176}{}{Fair enough. I wouldn't expect anyone to blindly accept tasks from strangers without first
 learning a little bit about them. Ask your questions, and I will answer them as best I can.}
{177}{}{Why don't you send one of your own people to deliver the message?}
{178}{}{Tell me about your people.}
{179}{}{What are your defenses?}
{180}{}{I have heard enough. I am ready to make my decision.}
{181}{}{Ask your questions.}
{190}{}{Why did you come back to the surface?}
{191}{}{Why the big ghost charade on the surface?}
{192}{}{What is the purpose of your message?}
{194}{}{Since the Sealing, we, as a people, have changed. Few can bear to be on the surface because they
 are not used to having a black sea of nothingness above them. The sensation of falling upward is so
 great for them that they lie frozen, clutching the ground. But that is not the main reason. All of us
 cannot stand the bright light of that which you call the sun; living underground for so long has made
 our eyes too sensitive to light. We cannot travel far from the safety of our homes beneath the ground.}
{195}{}{Can I ask you some more questions?}
{197}{}{Once, long ago, we were once like the surfacers. We too dwelled above ground, until the world
 above caught fire. Our ancestors -- who were part of a secret militia -- sealed themselves and their
 families down here for protection. For generations, down here we've remained, safely hidden within
 the womb of Mother Earth.}
{200}{}{Our population steadily increased since the Sealing. It soon became apparent that we could
 no longer survive down here without further supplies. So the Seal was broken, and we once again looked
 to the surface for survival.}
{203}{}{Years ago, someone tried to take over our farm, harvesting crops and stealing animals
 they had no right to. We are not a violent people by nature, but something had to be done. Our
 survival at the time depended on those crops. That's when we came up with the ghost idea. Smearing
 ourselves with glowing fungus, we were able to scare away this person and any other nosy neighbors.
 Unfortunately, this has been a little too effective. Lately, we've been seeking to make contact with
 the surfacers, but no one comes to the farm anymore for fear of the ghosts. Luckily, you dropped by.}
{206}{}{Enough! No more questions. Make your decision now!}
{207}{}{I am sorry; I cannot help you.}
{208}{}{Yes, I will gladly carry your message to Modoc.}
{209}{}{I am sorry to hear that. Please consider yourself a guest of the Slags. When we finally
 establish contact with the surfacers, you will be allowed to leave. Until then, do not try to
 the leave the caves - the consequences would be most unpleasant.}
{210}{}{With the completion of the new irrigation systems, our food supply far exceeds our needs. We
 wish to establish trade with the surfacers and exchange surplus foods for much needed medicines.}
{213}{}{Please enlighten us with your wisdom.}
{216}{}{I knew you would understand. Here is a message relaying our request. Please take it to Modoc
 and give it to the person in charge. Return here when your task is complete. I will tell the Protectors
 to expect your return. We thank you for doing us this service.}
{217}{}{How typical of surfacers. Never doing anything for anyone unless there is some kind of personal
 gain involved. Obviously, we cannot trust such a person as you. We will find someone else to deliver the
 message. Although we are not a violent people, do not attempt to leave the caves or you will regret it.}
{218}{}{Hmm... I understand. Such a decision cannot be made lightly. Please keep me informed of their
 progress.}
{219}{}{Then do not bother me any more.}
{220}{}{About what?}
{221}{}{They don't trust you. After all, they think you kill passersby and stake the bodies out in front of your
 farm.}
{222}{}{They want to know what happened to the farmer that was living here.}
{223}{}{We are a peaceful people, and have killed no one. Those bodies are merely props we manufactured
 to scare off those who try to steal from us. If you examine the bodies closely, you'll notice that they
 are nothing but brahmin guts and dummies.}
{224}{}{Then what about poor Karl? You know, the farmer that was living on your farm?}
{225}{}{Was that his name, Karl? We scared him off the farm, nothing more. I assume he went back home
 when he discovered the farm was haunted. The Protectors reported him headed west. You might try
 searching for him that way.}
{226}{}{I'll keep you informed of my progress.}
{227}{}{We scared him off the farm -- nothing more. I assume he went back home when he discovered the
 farm was haunted. The Protectors reported him headed northwest. You might try searching for him that
 way.}
{231}{}{I see you've met Jonny. We found him wandering in the darkness of one of our deepest tunnels.
 He said he had fallen down a dry well by his house, and then was trapped in a tunnel by a cave in. We
 have treated him as one of our own and he is loved by all -- so you will understand that I am wary of
 entrusting him to a stranger who has yet to prove himself to me as trustworthy. I will return Jonny
 when I am sure he will make it home safely.}
{232}{}{You have proven your trustworthiness without doubt. Despite the fact that we'll miss little Jonny
 down here, we have arranged an escort for you and Jonny to go back to Modoc right now.}
{233}{}{Oh boy! No wonder you weren't scared away by our little tricks. You're too stupid to be scared.
 I hate to depend on such an intellectually challenged individual, but we have need of your services.
 Take this message to Modoc. Give to leader of Modoc and try not to get lost.}

{300}{}{I'll just be going now.}
{301}{}{What do you want with me?}
{302}{}{Bye.}
{303}{}{Ghosts?}

{400}{}{The message was received well. The town of Modoc would like to establish trade with your people.}
