# 0. QUICK LOOK )
{100}{}{You see ol' slack-jawed Algernon.}
{101}{}{You see Algernon.}

# 0. LOOK )
{150}{}{You see a dirty, slack-jawed man. He is rocking on his feet and making little
 whistling noises to himself.}
{151}{}{You see Algernon. He looks like he is playing Missile Command in his head.}

# 1. FLOAT DIALOGUES (WTG)
{200}{}{Pew Pew}
{201}{}{Thoom!}
{202}{}{Zark! Zark!}
{203}{}{Sssssshhhhhhuuuu... *BOOM!*}
{204}{}{Zap!}
{205}{}{Boooom! Budda-budda-boom!}
{206}{}{Budda-budda-budda}
{207}{}{Budda-budda-budda}
{208}{}{Blammo! Blam blam blam!}
{209}{}{Blam!}
{210}{}{Ptow! Ptow!}
{211}{}{Phooom!}
{212}{}{Kablooie!}
{213}{}{Ratta-tatta-tatta}
{214}{}{Kaa-booom}

# 2.  INTRO (WTG)
{220}{}{(Algernon looks at you and gives a toothless smile.) Boom! }
{221}{}{(The slack-jawed young man looks at you with a toothless smile. Stitched on his shirt is a small tag that says "Algernon"
 in cursive letters.) Boom! }
{222}{}{(When he sees your weapons, he starts pointing at them excitedly.) Boom!}
{223}{}{Boom!}
{224}{}{Wander away.}
{225}{}{Uh... do you want to see one of these weapons?}
{226}{}{Yeah, "boom" to you, too. Algernon, can you upgrade any of these things I have here?}
{227}{}{Uh, no "boom" right now, thanks. Bye.}

# 3. RETARD (2)
{230}{}{Hunh! Huh-huh! (Algernon gives a gurgling laugh, then points his finger at you like a gun.) Blam Blam!}
{231}{}{Miss me, miss me! Take thiz! (Point finger at him like a pistol.) POW! POW!}
{232}{}{Ugh. Me dead. Me go to better place now}

# 4. AL DIES (3)
{235}{}{(Algernon gets a shocked expression on his face, then looks slowly at the place where you 'shot' him. He suddenly
 staggers, then his eyes roll up into his head and he falls over, dead.)}
{236}{}{Uh, Al? U okay?}
{237}{}{Uh-oh.}

# 5. AL DEAD (4)
{240}{}{(He doesn't move.)}
{241}{}{(Start clapping.)}

# 6. START CLAPPING (5)
{245}{}{(He doesn't get up. He isn't breathing, either.)}

# 7. GIVE ITEMS MENU (2, 8, 9, 10, 11, 12)
{250}{}{(What do you want to give him?)}
{251}{}{Give him one of your pistols.}
{252}{}{Give him one of your rifles.}
{253}{}{Give him your flamethrower fuel.}
{254}{}{Give him one of your melee weapons.}
{255}{}{Sorry, I don't think I have anything to give you, Al. Maybe next time.}
{256}{}{Actually, I don't think giving an obvious retard any sort of weapon is a smart idea. Fun, maybe, smart, no. Later.}

# 8. RETURN ITEMS MENU (7, 9, 10, 11, 12)
{260}{}{(Al takes the item, and his eyes light up. He tinkers with it for a few minutes, then a few minutes more,
 then a few more... an hour later, Al hands it back to you with a nod and an evil smile.) *Booooooom.*}
{261}{}{Say... can you upgrade THIS?}
{262}{}{Thanks, Al.}

# 9. PISTOLS MENU (7)
{265}{}{[Which one?]}
{266}{}{Your .44 Magnum?}
{267}{}{Your Desert Eagle.}
{268}{}{Your Wattz 1000 laser pistol.}
{269}{}{Your Glock 86 Plasma Pistol.}
{270}{}{Dig in your pack and give him something else...}
{271}{}{Nevermind, Al. See you later.}
{272}{}{Nevermind, kid... no toys for you today. Bye.}

# 10. RIFLES MENU (7)
{276}{}{Your Colt hunting rifle.}
{277}{}{Your AK-112 assault rifle.}
{278}{}{Your FN FAL.}
{279}{}{Your Wattz 2000 Laser Rifle.}
{280}{}{Your Flambe 450 Flamethrower.}
{281}{}{Your Plasma Rifle.}

# 11. FUEL MENU (7)
{291}{}{Want to take a swig of this flamethrower fuel?}
{292}{}{Here's some flamethrower fuel. Can you do anything with this?}

# 12. MELEE MENU (7)
{301}{}{Give him your cattle prod. Uh... after making sure that he grabs it hilt first.}
{302}{}{Your BeatCo "Bigger Frigger" Power Fist.}

{400}{}{Me kill Al. Me better get outta here}

# by phobos2077
{500}{}{He doesn't reply, looks tired.}