{100}{}{You see a short man with jet-black hair and a nice smile.}
{101}{}{You see Ascorti, Redding's Mayor.}
{102}{}{You see a well-dressed man with a greasy look to him.}
{103}{}{Keep on movin', pal.}
{104}{}{If you're here to try your luck, you're welcome.}
{105}{}{Play or get out.}
{106}{}{You better not make a mess in my place.}
{107}{}{You should try the tables, tribal.}
{108}{}{You should try the slots, tribal. Heap good magic there.}
{109}{}{Take it easy on the firewater, tribal.}
{110}{}{Hello there; welcome to the fine city of Redding... and welcome to my casino. Everyone's an Ace
 here at Ascorti's. I'm Ascorti, proprietor and mayor of this fine town.}
{111}{}{What can Mayor Ascorti do for you?}
{112}{}{Is there any work here in Redding?}
{113}{}{What's going on here in town lately?}
{114}{}{Have you heard of anything called a Garden of Eden Creation Kit?}
{115}{}{What do you do here?}
{116}{}{I was just looking around, Mayor. See you later. Goodbye.}
{117}{}{I run this here casino, and I help to run things in town, too. I keep track of things like deeds
 and such.}
{118}{}{Deeds? Deeds to what?}
{119}{}{I see; let me ask you something else, Mayor.}
{120}{}{Deeds like the one to that Great Wanamingo Mine that I want to buy from you. Ready to sell it
 yet?}
{121}{}{I might be. How much were you going to offer for it?}
{122}{}{Maybe. Let me ask you about something else first.}
{123}{}{I'm still thinking it over. Goodbye, Mayor.}
{124}{}{Well, just the one deed. The one I sold to you. You know, for the Great Wanamingo Mine?}
{125}{}{Oh, that deed. Now I remember. Let me ask you about something else, Mayor.}
{126}{}{Of course - I was just wondering if you had any other bargains. Well, I better get to work
 clearing that mine. Goodbye.}
{127}{}{Just that deed for the Great Wanamingo Mine that you sold back to me. Remember?}
{128}{}{Of course I do. Uh, let me ask you about something else, Mayor.}
{129}{}{Yes, of course. I was just checking. Goodbye, Mayor Ascorti.}
{130}{}{All kinds of private property. Why, right now, I have a Jim-dandy of a deed for sale.}
{131}{}{What's that?}
{132}{}{I bet you do, but let me ask you about something else first, Mayor.}
{133}{}{Hmm, I think I'll look around town first, Mayor. Goodbye.}
{134}{}{It's the deed to the Great Wanamingo Mine just outside of town. I can sell it to you for only
 $1,000, too. Special offer; just your luck to hit me on a generous day like this.}
{135}{}{That sounds interesting. Tell me more.}
{136}{}{What's the catch, Mayor?}
{137}{}{I don't think I want to buy that right now, Mayor. Let me ask you about something else.}
{138}{}{Well, there are some dang critters in there that need to be killed before anyone will work the
 mine. If'n you were to buy the deed - and then kill off the critters infesting it - I'd be happy to buy
 the deed back off you for a nice profit.}
{139}{}{A profit? How much of a profit?}
{140}{}{Why don't you clear it out yourself if it's so profitable?}
{141}{}{Critters? What kind of critters?}
{142}{}{No catch. No catch at all. You just have to evict some of the squatters that have taken up
 residence there. No hardship at all for a rugged customer like yourself. I can tell you more if you'd
 like.}
{143}{}{Okay, I'll bite. Tell me more.}
{144}{}{I don't think I want to get into that sort of business, Mayor. Let me ask you about something
 else.}
{145}{}{I see. I think I'll leave that to someone else. Goodbye, Mayor.}
{146}{}{Heck, more than double. I figure that's the least that your time's worth to you. I couldn't
 afford to pay any more than that. There's still a lot of work that needs to be put back into the mine
 before I can start to turn a profit with it.}
{147}{}{Sounds good to me. How much was that again?}
{148}{}{I don't think I want to do that. Let me ask you about something else, Mayor.}
{149}{}{$1,000 for the deed to the Great Wanamingo Mine. You want it?}
{150}{}{Yes, I'll buy the deed.}
{151}{}{I'd like to buy the deed, but I don't have enough money for it right now. Let me ask you about
 something else.}
{152}{}{I don't think I want to buy that right now. Let me ask you about something else.}
{153}{}{Maybe some other time, Mayor. Goodbye.}
{154}{}{I'll go ahead and record the Great Wanamingo Mine's deed in your name. Let me know when you've
 got it all cleared out, and I'll buy it back from you.}
{155}{}{I'll do that. Let me ask you about something else right now, though.}
{156}{}{Okay. See you in a while, Mayor.}
{157}{}{I can't really do that. I'm not a real danger-seeking kind of guy. I know my strengths and
 fighting just isn't one of them. Now you, you look like a real tough hombre. This should be just up
 your alley.}
{158}{}{Maybe so. How much are you willing to pay to buy the deed back once I clear it out?}
{159}{}{Maybe, maybe not. I'll think about it. Let me ask you something else, Mayor.}
{160}{}{I don't think I have time for that right now. Sorry, Mr. Mayor. Goodbye.}
{161}{}{So, you clear out that mine yet?}
{162}{}{I sure did.}
{163}{}{I haven't right now, but I will. In the meantime, let me ask you about something else.}
{164}{}{I'm working on it. Goodbye, Mayor Ascorti.}
{165}{}{You know, I don't think you got all of those damn Wanamingos. You better go back and check. I
 won't buy it back from you until every last one of them is dead.}
{166}{}{I see. Let me ask you about something else first, Mayor.}
{167}{}{Well, I better go back and check then.}
{168}{}{You did a great job of clearing all them damn Wanamingos out of that mine, but you've got a
 problem.}
{169}{}{A problem? Like what?}
{170}{}{You cleared out the whole mine. Thanks so much. Ready to sell me the deed? I'll give you $2,500
 for it.}
{171}{}{I don't think so. I think I'll hold on to it for now. Goodbye, Mayor.}
{172}{}{You bet. I'll be happy to unload this deed, Mayor Ascorti.}
{173}{}{We call 'em Wanamingos. They're some kind of all-fired weird critter with nasty teeth and suckers
 or somesuch. Not too intelligent, but nasty up-close.}
{174}{}{I see. And you want me to get rid of them?}
{175}{}{You've got it. I knew you weren't as slow as you look. You can be right quick when you're of a
 mind to be.}
{176}{}{Yeah. So how much do I stand to make on my $1,000?}
{177}{}{It was so homey-looking that someone else moved in. A nasty type by the name of Frog Morton, uh,
 and his gang too, from what I hear.}
{178}{}{Why do they call him Frog Morton?}
{179}{}{How's that my problem?}
{180}{}{Great, what do I do about this?}
{181}{}{I guess it's because he's got a reputation for croaking people. He's a real nasty customer who
 won't be missed... and you'll be a hero. You'd like to be a hero, wouldn't you?}
{182}{}{Maybe, but I still don't see how this is my problem.}
{183}{}{Yeah, sure. What do I do about this?}
{184}{}{I guess I've got some more house-clearing to do. I'll be back when I've kicked some more ass,
 Mayor.}
{185}{}{Well, until the mine is cleared out I can't send miners in to work it. So, if you want to sell
 me the mine, it's your problem.}
{186}{}{Why do they call him Frog Morton?}
{187}{}{Great. What do I do about this?}
{188}{}{I better get busy, then. Goodbye, Mayor.}
{189}{}{I think you should go back to the Wanamingo Mine and kill off Frog and his gang. When you do
 that, you can come back here and I'll be happy to buy the mine from you.}
{190}{}{Nothing's ever easy, is it? Okay, Mayor. I'll see you later. I've got some business to attend to.}
{191}{}{You ready to sell that Wanamingo Mine deed back to me yet?}
{192}{}{Sure thing, Mayor. How much was that again?}
{193}{}{Not yet, Mayor. Goodbye.}
{194}{}{I hear that you've decided to help the Sheriff. Good. I can't afford to allow that deadbeat
 Rooney to keep her marvelous house.}
{195}{}{You mean that tiny, drafty shack you're overcharging her for?}
{196}{}{I bet. How much does she owe you?}
{197}{}{Well, I'll see what I can find out. Let me ask you something else, though.}
{198}{}{Yeah. So who are you, anyway?}
{199}{}{I prefer to call it cozy, with flow-through seasonal ventilation. It's quite reasonably priced,
 too.}
{200}{}{I bet it is. How much back-rent does she owe you?}
{201}{}{Hmm, well I better be going, Mayor. Goodbye.}
{202}{}{Let's see here... Mrs. Rooney owes me... yes, here it is, $120. That's it. $120.}
{203}{}{Is that all? I've got that right here.}
{204}{}{That's not that much. Let me ask you about something else.}
{205}{}{I'll see what I can do to make her pay up. Goodbye.}
{206}{}{That'll do it. Now she's current. Thanks for settling that account.}
{207}{}{Not a problem. Let me ask you about something else, though.}
{208}{}{I guess some people are just more generous than others. Goodbye, Mayor.}
{209}{}{Thanks for clearing out my property, Sheriff. Now I can rent it to someone that can actually pay
 for it.}
{210}{}{I sure didn't feel good about what I did.}
{211}{}{That makes sense. }
{212}{}{Why not? You should have. By kicking out Widow Rooney, you've enabled me to keep paying all of
 my employees. If I didn't pay them, then their families would go hungry. That's not right, is it?}
{213}{}{I guess not. I didn't think about it that way. But I still don't feel great about it.}
{214}{}{It doesn't look like you're suffering much here. I'm sure your casino makes enough.}
{215}{}{It takes a big individual to do the right thing, even when that thing doesn't leave them
 feeling good. You did a hard thing, and you did it well. Have a beer on me.}
{216}{}{Thanks, Mayor; that's mighty nice of you.}
{217}{}{I don't think I want to drink with you. Now or ever. Goodbye.}
{218}{}{No problem at all. Happy to wet the whistle of local law enforcement.}
{219}{}{Thanks again, Mayor. Let me ask you about something else, though.}
{220}{}{Thanks, Mayor. I'll see you around. Goodbye.}
{221}{}{Today, maybe, but it's not always so lucky. I've got to maintain a good balance, good income. I
 owe it to my employees - as well as a little something for myself, of course.}
{222}{}{I guess that's fair enough.}
{223}{}{You're lower than a gecko's belly. I've heard enough. Goodbye.}
{224}{}{I just wanted to thank you again for doing the right thing by Mrs. Rooney. I sure didn't want to
 kick that old gal out of her home.}
{225}{}{But you would have. Well, let's talk about something else.}
{226}{}{Somehow, I knew you'd say something like that. Goodbye, Mayor.}
{227}{}{You went too far with the Widow Rooney. She wasn't no threat to nobody. Why'd you have to go and
 kill her?}
{228}{}{She had it coming.}
{229}{}{It was an accident.}
{230}{}{Had it coming? She weren't nothing but a little harmless old lady. You're plumb crazy. Just get
 out of here.}
{231}{}{You talkin' to me?}
{232}{}{I was already on my way out of this shack. Goodbye.}
{233}{}{An accident? They still can't find all of her body parts. You just better make sure you don't
 make a habit out of accidents like that. They're bad for business.}
{234}{}{I understand. Let me ask you about something else, Mayor.}
{235}{}{I'll be more careful next time.}
{236}{}{Yes, I'm talking to you. Do you see anyone else around that I might be talking to? Get the hell
 out of my bar.}
{237}{}{Are *you* talkin' to *me*?}
{238}{}{I'm going, I'm going.}
{239}{}{What? Are you deaf or just stupid? *I'm* talking to *you*, all right. Now get out!}
{240}{}{Well, you must be talkin' to me 'cause I don't see no one else around here.}
{241}{}{All right. I'm leaving. Don't give yourself a stroke. Goodbye.}
{242}{}{Is everyone in your tribe this stupid? That's it. You want to dance? Then let's dance. Guards!}
{243}{}{You've gotta be talkin' to me and I don't like what you're saying.}
{244}{}{Whoa, hey... easy there, sparky. I was just leaving.}
{245}{}{I hear you're working for Earl Marion as a sort of fill-in Sheriff until he gets better. That
 oughta keep your hands full for a while. Cain't think of any other real work for you in town, anyhow.}
{246}{}{I see. Let me ask you about something else then, Mayor Ascorti.}
{247}{}{Hey, tell me about the mine owners.}
{248}{}{Thanks anyhow, Mayor. Goodbye.}
{249}{}{I hear you did a real good job of helping Sheriff Marion out. Town's been pretty quiet since you
 helped him out. I cain't rightly think of anything that would suit your talents.}
{250}{}{Thanks, Mayor. That means a lot coming from you. Let me ask you about something else here.}
{251}{}{Hey, tell me about the mine owners.}
{252}{}{Thanks anyhow. Guess I'll be moseying on then. Goodbye.}
{253}{}{I understand that Sheriff Earl Marion is looking for someone to fill in for him until his bum
 leg heals up a fetch. You might go talk to him. His office is just South of here, across the street.}
{254}{}{Thanks for the tip. Before I go, though, let me ask you about something else.}
{255}{}{Hey, tell me about the mine owners.}
{256}{}{Maybe I'll take a look over there, then. Thanks.}
{257}{}{Well, there's the Sheriff, the mine owners are looking for someone to retrieve some
 kind of part for one of their machines, and then some troubles with our caravan runs.}
{258}{}{What about the Sheriff?}
{259}{}{What about the mine owners?}
{260}{}{Interesting. Let me ask you about something else, Mayor.}
{261}{}{Maybe I'll look around a bit. Thanks and goodbye.}
{262}{}{Heck, that's right. I hear you already went ahead and got that chip for one of 'em.}
{263}{}{Well, tell me about the Sheriff, then.}
{264}{}{Yup, that was me. Tell me about something else then, Mayor.}
{265}{}{Oh, I thought there was something new. Well, goodbye then.}
{266}{}{I don't know too much about it. You should go talk to either Dangerous Dan McGrew at the
 Morningstar Mine, or to Marge LeBarge at the Kokoweef Mine. They're both just north of the downtown
 area here, across from the graveyard.}
{267}{}{Thanks. Now, what about the Sheriff?}
{268}{}{Thanks. Let me ask you about something else, though.}
{269}{}{Maybe I'll take a walk up there and talk to them. Thanks, Mayor. Goodbye.}
{270}{}{Lately our gold shipments have started to slow down because the miners are spending too much
 time flying high on Jet.}
{271}{}{Almost all of the miners are spending more time flying Jet than mining for gold... so our prices
 are up, and our exports are down. Bad for business all the way around.}
{272}{}{Everyone's getting too high on Jet to work effectively. We aren't making but a tenth of our
 regular gold shipments, and we've jacked the price way up on that. This can't last.}
{273}{}{Seems like everyone got a bad batch of Jet. All of the regular Jet Jockeys are going through
 some kind of massive detox. I guess something didn't agree with 'em. I don't know what all happened but
 I think it'll turn out for the better.}
{274}{}{Things are almost back to normal. Everyone who was sick on Jet has just about sworn it off. Our
 mine production and shipping schedule is just about back up to normal, too. Looks like the worst is
 over.}
{275}{}{Hmm. That's interesting. Let me ask you about something else, Mayor Ascorti.}
{276}{}{I see. Thanks for the info, Mayor. Goodbye.}
{277}{}{A Garden of Eden Creation Kit? I think they made Vault City out of one of those. All of the
 vaults were supposed to have one, but there sure ain't one around here nowheres.}
{278}{}{Oh, well. Let me ask you something else, Mayor.}
{279}{}{I better keep looking then. Thanks, Mayor Ascorti.}

# added by phobos2077: bounty hunt
{401}{}{What about the caravans?}
{402}{}{I brought some of those... tattoos for you.}
{403}{}{I think I've eliminated all those robbers.}
{404}{}{I'm working on your robbers problem. Gotta go now.}
{405}{}{Recently we started losing too many outgoing gold shipments. Looks like some new gang of robbers came down from the north.
 Those bastards not only prey for caravans with little protection, but they are also brutal with their victims. This is bad for business. I want you to remove them.}
{406}{}{I'm up for it. How many are there and where can I find them?}
{407}{}{Sounds troublesome. What's in it for me?}
{408}{}{I don't have time for this.}
{410}{}{I will pay adequately when I'll see that they're gone. Also you will get $300 for each dead robber leader.}
{411}{}{Oh? Sounds good to me. Where can I find them?}
{412}{}{I'll pass.}
{415}{}{From the reports it seems that several different groups are operating in the area to the north-east of here. I would say there are about 20 robbers all in all.
 Just patrol long enough and you don't have to worry about finding them, they'll find you.}
{416}{}{I'll start right away.}
{417}{}{Ok.}
# first time
{420}{}{Oh... I forgot one thing. To get the reward for each robber leader you kill, I'll need some kind of proof. Just a matter of principle.
 I've heard this particular gang has their members tattoo their arms... Take this knife, you know what to do...}
{421}{}{Eh, sure, thanks.}
{422}{}{This is getting more interesting by the minute. I'll go now.}
# rewards
{430}{}{Disgusting. But I guess they've got what they deserved. Here is your money.}
{431}{}{Thanks.}
{435}{}{So I've heard those robbers were not seen for a while now. You either got them all or got them all too scared to stick around. Either way,
 the reward is yours. Stop by from time to time, maybe there will be more work.}
{436}{}{Glad I helped. Goodbye.}
{437}{}{I will.}
{440}{}{That gang is still out there. You have to deal with them.}
{445}{}{Everything is quite right now. Come back later.}
{450}{}{Looks like the robbers are out in force again, and our caravans are getting hit. Will you help us out again?}
{455}{}{You know, I don't think you're ready for this job. Come back when you get a bit more experienced.}
{456}{}{Let me ask you something else, then.}
{457}{}{If you say so.}