{100}{}{You see a thin, nervous-looking man.}
{101}{}{You see Painless Doc Johnson, Redding's Resident Physician.}
{102}{}{You see a cadaverous, nervous fellow with bulging eyes.}
{103}{}{Your head is larger than I would think.}
{104}{}{Your beetling brow confirms my suspicions.}
{105}{}{You have a very well developed sagittal crest.}
{106}{}{I wonder if it was long exposure to radiation that so reduced your cranial capacity.}
{107}{}{No food here. Go away!}
{108}{}{Shoo, shoo!}
{109}{}{Go back to the wilderness, you savage.}
{110}{}{If only tribals were as passive as brahmin, they could be just as useful.}
{111}{}{Looks like you came to the right person. I'm Doc Johnson and I can patch you up.}
{112}{}{Hello there. You brought your friend to be patched up? I'm Painless Doc Johnson, and I'll
 take care of 'em.}
{113}{}{Looks like you fellers got caught on the short end of the stick. I'm Doc Johnson, and I can
 patch you up if you want.}
{114}{}{Hello, I'm Doc Johnson, and my professional opinion is that you're looking a mite poorly. Need
 me to fix you up?}
{115}{}{Hello, I'm Doc Johnson. I'll have to take a closer look at your friend if you want me to fix 'em
 up. They don't look too good.}
{116}{}{Whatever you fellers caught, I'm sure I can fix it. I'm Doc Johnson.}
{117}{}{Got yourself all scraped up, huh? Well, let Doc Johnson take a look at that. Easy now, I'm a
 professional.}
{118}{}{What have you folks been getting yourselves into? Let old Doc Johnson take a look at ya.}
{119}{}{Thanks, Doc. How much will this cost?}
{120}{}{I just wanted to try to buy some supplies.}
{121}{}{I don't need healing right now so much as some answers to some questions.}
{122}{}{Nice to meet you, but I don't think any healing's needed right now. Thanks anyway, Doc. Goodbye.}
{123}{}{It's going to cost $50 to patch you up good as new.}
{124}{}{It'll cost you $50 to have your friend all patched up. Good as new, I guarantee it.}
{125}{}{Here's your money, Doc.}
{126}{}{I guess I can't afford that right now. Sorry, Doc; maybe another time.}
{127}{}{$50, huh? Maybe I'll have that done later. Goodbye, Doc.}
{128}{}{Tell you what; I'll give you a group rate seeing as how you're all broken up. $100 to patch up
 the lot of you.}
{129}{}{Here's your money, Doc. Fix us up.}
{130}{}{I guess we can't afford that right now. Sorry, Doc; maybe another time.}
{131}{}{$100, huh? Maybe we'll have that done later. Goodbye, Doc.}
{132}{}{Looks like you're not doing too well there. I can cure what ails you for $100. You want me to
 try?}
{133}{}{Your pal's not doing too well. I think I can cure what ails 'em for $100. You want me to try?}
{134}{}{I hope you can do better than try, Doc. Here's your money.}
{135}{}{I guess I can't afford that right now. Sorry, Doc; maybe another time.}
{136}{}{$100, huh? Maybe I'll have that done later. Goodbye, Doc.}
{137}{}{What a bunch of sick pups. Well, I can try to fix you up and cure what ails you, but it's going
 to cost you $150. Want me to have at it?}
{138}{}{Yes, please. Here's your money, Doc.}
{139}{}{We can't afford that right now. Sorry, Doc; maybe another time.}
{140}{}{$150, huh? Maybe I'll have that done later. Goodbye, Doc.}
{141}{}{I'd sure like to help you, but you don't have enough to cover your bill. Medical supplies cost
 money.}
{142}{}{Aww, come on, Doc. We sure need your help.}
{143}{}{I'll come back when I have more money. Goodbye. }
{144}{}{Well, okay. I'll do it this once - but you better have the money to pay me next time.}
{145}{}{That worked... once. Just like I told you. This time I need the money. You aren't going to get
 anything in this world for free - my services included.}
{146}{}{Thanks, Doc. I sure appreciate it. Next time I'll have cash. I promise.}
{147}{}{I feel kind of guilty imposing on you like that. I better come back when I have money to pay
 you.}
{148}{}{Okay, sorry. But before I go, let me ask you about something.}
{149}{}{Okay, okay. I'll be on my way, then. Goodbye, Doc.}
{150}{}{Sorry. No money, no service. I can't give meds away to everyone who asks for them. I'd be broke
 inside of a week. You'll have to come back when you've got money to pay my fee.}
{151}{}{I don't have cash, but I have stuff to barter. Can I trade you something for your services?}
{152}{}{Before I go, let me ask you something.}
{153}{}{OK, I'll try to raise some cash. Goodbye.}
{154}{}{What would you like to know?}
{155}{}{What now?}
{156}{}{I think I have a solution for the Jet problem that you have here.}
{157}{}{I hear that Redding has been having a problem here with its exports lately.}
{158}{}{I could sure use some healing.}
{159}{}{I'm just wondering about what's going on here in town.}
{160}{}{Why do they call you Painless Doc Johnson?}
{161}{}{Got any medical supplies I could trade for?}
{162}{}{I was just looking around. Goodbye, Doc.}
{163}{}{What does this look like to you? A general store? No, I don't barter for medical services. I
 just want payment in honest gold dollars, thank you very much. Come back when you have some.}
{164}{}{All right. I get the picture. Goodbye.}
{165}{}{I might be able to provide you with some supplies; let's see what you've got in trade.}
{166}{}{Okay, Doc.}
{167}{}{I didn't mean right now. I was just wondering if you had stuff to trade. I have some questions,
 though.}
{168}{}{Oh, I don't need anything right now. See you later, Doc.}
{169}{}{Did you get everything you need?}
{170}{}{Well? Did that do it for you?}
{171}{}{Actually, let me take one more look at your stuff.}
{172}{}{Thanks, Doc. Let me ask you something.}
{173}{}{I sure did, Doc. Thanks. Goodbye for now.}
{174}{}{There you go. All better. That do it for you?}
{175}{}{Actually, I had some questions I wanted to ask you.}
{176}{}{That'll do it. Thanks, Doc.}
{177}{}{Wouldn't let that go too long. Some wounds fester and start oozing puss. Then there's always
 gangrene. Course, lately, I haven't used my knives as much as I'd like. Getting a bit rusty. Tell you
 what: Go ahead and let it go as long as you want. Maybe I can get some practice later on.}
{178}{}{I see. While I'm festering, let me ask you about something.}
{179}{}{Uh, yeah, well I'll think about that. Goodbye, Doc.}
{180}{}{Lately, it seems as though more miners are spending their time flying on Jet than mining. If this
 keeps up, Redding's gold production will come to a halt. New Reno doesn't seem to mind, though.}
{181}{}{All of the miners here are only working enough to get their next hit of Jet. Production here has
 really slowed down. If this keeps up, New Reno's going to own Redding.}
{182}{}{All miners are doing here lately is getting high. Hardly anyone's mining for gold any more. I'm
 worried that New Reno's going to own this town. I sure wish there was a way to stop this Jet addiction.}
{183}{}{What does New Reno have to do with it?}
{184}{}{Where does the Jet come from?}
{185}{}{I see. Let me ask you about something else.}
{186}{}{Thanks for the information. I'll see you around, Doc. Goodbye.}
{187}{}{Hello there. I'm Painless Doc Johnson. What can I do for you?}
{188}{}{What can old Doc Johnson do for you this time?}
{189}{}{Hey, Doc. I just had some questions to ask you.}
{190}{}{I was wondering if you had any meds I could trade for.}
{191}{}{Doc, I heard about some special armor implants. Do you know anything about that?}
{192}{}{I was just looking around, Doc. Nice to meet you. Goodbye.}
{193}{}{Thanks to you, I'm turning this Jet problem around. That antidote of yours that I slipped into
 the Jet supply is doing a great job of grounding all those Jet Jockeys.}
{194}{}{I'm glad it's working. Let me ask you about something else.}
{195}{}{Aren't people suspicious about getting sick on the Jet that you sold them?}
{196}{}{Glad it's working, Doc. I guess I'll be on my way. Goodbye.}
{197}{}{Thanks to the antidote that you brought me, Redding's problems with Jet are at an end. It looks
 as though New Reno will have to find another way to try and take over here.}
{198}{}{I'm happy I was able to help. Let me ask you something else.}
{199}{}{Weren't people suspicious about getting sick on the Jet that you sold them?}
{200}{}{What did New Reno have to do with it?}
{201}{}{Glad it worked, Doc. Goodbye for now.}
{202}{}{A solution? What do you mean?}
{203}{}{I mean that I have an antidote to Jet. Dr. Troy in Vault City made it, and it should solve the
 Jet-addiction problem that you have here.}
{204}{}{Oh, nothing. Let me ask you about something else, Doc.}
{205}{}{We sure do. Too much Jet, not enough work... but where did you hear about that?}
{206}{}{McClure in Vault City told me.}
{207}{}{I just heard a rumor, that's all.}
{208}{}{It's not really important. Let me ask you about something else.}
{209}{}{New Reno sells Jet pretty cheap. Jet's real addictive, like nothing you've ever seen before.
 They figure that if they get enough people in an area using it, those people will do anything to get
 more. That gives them de facto control of an area - like Redding.}
{210}{}{I see. Let me ask you about something else, Doc.}
{211}{}{So if you don't want New Reno to control Redding, just who do you want in charge here?}
{212}{}{Thanks for explaining that to me, Doc. Goodbye.}
{213}{}{All of the Jet here in town is shipped here from the Mordino family in New Reno. It comes mostly
 in bulk packages, and then I process it into user-ampoules... so I end up selling all of it right here.}
{214}{}{You must make a tidy profit out of that.}
{215}{}{You must be real chummy with New Reno, then.}
{216}{}{I see. Let me ask you about something else.}
{217}{}{Have any Jet that I could have, then?}
{218}{}{Not really. I guess they're so used to me processing the bulk batches of Jet into user-ampoules
 that they haven't even thought twice about it. I've been doing it for quite a while before this, and
 I've been the doctor here for a long time.}
{219}{}{I'm glad that you're not in trouble. Let me ask you about something else, Doc.}
{220}{}{Good. I bet things would get ugly if they ever suspected. Well, goodbye, Doc.}
{221}{}{Well, everyone wants a part of the gold here in Redding, so we're going to be controlled
 by someone, eventually. I just want us to have the master that's going to do the best job for Redding.}
{222}{}{And who do you think that is?}
{223}{}{The way I see it, Redding's best chance is with Vault City controlling things here. That's where
 I'm from - so I might be biased - but I really do think that Vault City can do a better job of helping
 the citizens of Redding.}
{224}{}{Why is that?}
{225}{}{Because they handle Vault City in a just and humane manner. They would do the same for Redding.
 I'm sure of it.}
{226}{}{Vault City takes care of their citizens all right, but they treat non-citizens like dirt.}
{227}{}{I see, Doctor. That makes a certain kind of sense.}
{228}{}{They'll realize the benefits soon enough. I'm certain that they'll welcome Vault City's
 administration with open arms, uh, eventually.}
{229}{}{I see. Well, let me ask you about something other than politics.}
{230}{}{Hmm, I don't know about that. Goodbye.}
{231}{}{That's nonsense. Vault City does extend special privileges to citizens, but only because they're
 better qualified to enjoy those things than brutish non-citizens. Besides, everyone can qualify for
 Vault City citizenship if they pass the tests.}
{232}{}{I'm not sure how the people here in Redding would react to rule by Vault City.}
{233}{}{Yeah, no doubt. Goodbye, Doc.}
{234}{}{I fill the user-ampoules with Jet and then distribute it purely as a service to the people of
 Redding. I don't make a profit doing it. If I didn't do it, then some other quack would be preparing
 the drug with germ-encrusted, rusty equipment. I'd never get this population disease-free after that.}
{235}{}{What a nice guy you are, Doc. That's great. Let me ask you about something else, then.}
{236}{}{How *noble* of you, Doctor.}
{237}{}{That's interesting. I'll see you later, Doc. Goodbye.}
{238}{}{I'll thank you not to use such heavy sarcasm when you say that. Call it nobility if you like; I
 prefer practicality. The mine owners pay me a stipend to keep the miners relatively healthy and able to
 work. If I let someone else work with the Jet, I'd never be able to do the job I'm paid to do.}
{239}{}{I see. Well, let me ask you about something else, then. }
{240}{}{Hmm, thanks for telling me that. Goodbye, Doc.}
{241}{}{Dr. Troy? I know him. A wonderfully talented physician. We worked together when I was in Vault
 City. Tell me about this antidote.}
{242}{}{You worked in Vault City?}
{243}{}{Dr. Troy said that I should bring the antidote to you, and that you'd know what to do with it.}
{244}{}{Yes, that's where I received my medical training. I'm a Vault City citizen. I found that there
 are many places in the world that needed my medical expertise more than Vault City. So here I am. Now,
 about that antidote...}
{245}{}{Dr. Troy said that I should bring the antidote to you, and that you'd know what to do with it.}
{246}{}{Indeed I will. Let me have it, then.}
{247}{}{Here it is, Doc.}
{248}{}{Not so fast Doc. What's it worth to you?}
{249}{}{I don't think I'm ready to hand it over just yet. See you around, Doc. Goodbye.}
{250}{}{What's it worth to me? Why, you little weasel! I oughta...}
{251}{}{Easy there, Doc; that kind of talk makes me feel so bad that I get all shaky. I could drop
 things... like this antidote bottle.}
{252}{}{Okay, okay. Hey, I was just kidding. Here it is.}
{253}{}{Thank you. I'll make sure the miners get a little something *extra* with the next batch of
 Jet that they pick up.}
{254}{}{Aren't they going to be suspicious of you, Doc?}
{255}{}{I'm glad I could help. Let me ask you about something else, Doc.}
{256}{}{Good. I hate seeing all those damn Jet Pilots flying around all the time. Goodbye, Doc, and
 good luck to you.}
{257}{}{Okay, you've got me. I'll give you $2,000 for it. That's all I've got.}
{258}{}{I guess that will have to do. Okay, here it is, Doc.}
{259}{}{I think I'll hold on to it for a while yet. Goodbye, Doc.}
{260}{}{You can do that, but you won't get a better price from me. That's really all I have.}
{261}{}{Well, okay, I guess I'll take the $2,000. Here's the antidote, Doc.}
{262}{}{We'll see. Goodbye, Doc.}
{263}{}{I know McClure. He's on the Vault City council. What did he tell you?}
{264}{}{That mine production is way down and gold prices are way up.}
{265}{}{I'm not sure I should tell you.}
{266}{}{Oh? And what did this rumor say?}
{267}{}{That mine production is way down and gold prices are way up.}
{268}{}{Oh, just the usual garbage. Hey, let me ask you about something else, Doc.}
{269}{}{That's true. The miners here are all getting high on Jet instead of working. So exports are
 down and prices are up. This situation can't last.}
{270}{}{That's not good. Hmm, let me ask you about something else.}
{271}{}{That doesn't sound good, Doc. Goodbye.}
{272}{}{It's because my patients usually pass out before they get to screamin' too much. It's kind of a
 joke.}
{273}{}{I see. Well, that's uh, comforting. I guess. Let me ask you something else, then.}
{274}{}{I think I need to be going. I just remembered an important appointment that I have, uh,
 somewhere. Uh, goodbye, Doc.}
{275}{}{You can tell me. I'm a doctor.}
{276}{}{Oh, yeah. Well, okay. He told me that gold production here in Redding is way down and prices are
 way up.}
{277}{}{I read something about that, too. It's not too hard to do if you've got the training. And the
 equipment.}
{278}{}{Do you have what you need to perform the operations?}
{279}{}{Mostly. I have the skill and the training, but I don't have the implant material.}
{280}{}{So, what does that mean?}
{281}{}{That means that we'll just have to improvise. I think I can get what I need from a set of
 standard combat armor. I can take the concussive protection plates and also the thermal cells from the
 armor.}
{282}{}{That's great. So you can do it?}
{283}{}{Well, yes - but if I pack too much armor in, the patient sure isn't going to win any beauty prizes.}
{284}{}{I don't care about that; I just want the protection. What can you do, exactly?}
{285}{}{There are actually four different operations that can be performed. There's Dermal Impact Armor
 that protects against impact, and there's Phoenix Armor Implants that protects against heat. Then each
 one has an Assault Enhancement as well. You have to get the basic armor before you can get the Assault
 Enhancement.}
{286}{}{What operation did you want to know about?}
{287}{}{I don't think I want to do anything like that. Let me ask you about something else.}
{288}{}{Tell me more about the implants. I think I may want you to operate on me.}
{289}{}{I think I know enough now. I'll have to think about it. Goodbye.}
{290}{}{Which operation were you interested in?}
{291}{}{The Dermal Impact Armor.}
{292}{}{The Phoenix Armor Implant.}
{293}{}{The Assault Enhancement for the Dermal Impact Armor.}
{294}{}{The Assault Enhancement for the Phoenix Armor Implants.}
{295}{}{Doc, I think I'd rather ask you about something less... uh, invasive.}
{296}{}{I guess I don't want to hear about an operation right now. Goodbye.}
{297}{}{According to what I've read, Dermal Impact Armor gives you 5% resistance to normal and explosive
 damage - over and above any other armor you're wearing. The operation takes about two days, one suit of
 Combat Armor (for parts), and it will cost you $5,000. This procedure should be fairly simple... I think.
 Hmm, you may not even scar all that badly.}
{298}{}{That sounds great, Doc. Let's do it. I just hate getting shot, stabbed, and blown up all the
 damn time.}
{299}{}{Let me ask you about one of the other operations, Doc.}
{300}{}{I'll have to come back when I have more money, Doc. Goodbye.}
{301}{}{I'll have to come back when I dig up a set of Combat Armor, Doc. Goodbye.}
{302}{}{I don't think I want to do this right now after all. Goodbye, Doc.}
{303}{}{You need to have the Dermal Impact Armor installed before I can give you the Assault
 Enhancement. But I'll tell you what it should do. The Assault Enhancement should give you a total of
 10% resistance to normal and explosive damage - over and above any other armor you're wearing. The
 operation takes a few days and it'll cost you $15,000. In addition, you're not going to be too
 Charismatic after I finish. Cramming all those impact plates under your skin is going to make you look
 pretty damn angular, but in a very streamlined way. But who doesn't like the way a new car looks - I'll
 try not to give you tail-fins.}
{304}{}{The Assault Enhancement of the Dermal Impact Armor should give you a total of 10% resistance to
 normal and explosive damage - over and above any other armor you're wearing. The operation takes a few
 days and it'll cost you $15,000. In addition, you're not going to be too charismatic after I finish.
 Cramming all those impact plates under your skin is going to make you look pretty damn angular, but in
 a very streamlined way. But who doesn't like the way a new car looks - I'll try not to give you tail-fins.
 Ready to begin?}
{305}{}{That sounds great, Doc. Let's do it. I'm all assault, all the time, and I don't mind looking the
 part.}
{306}{}{Let me ask you about one of the other operations, Doc.}
{307}{}{I'll have to come back when I have more money, Doc. Goodbye.}
{308}{}{I'll have to come back when I dig up a set of Combat Armor, Doc. Goodbye.}
{309}{}{I don't think I want to do this right now after all. Goodbye, Doc.}
{310}{}{According to the reports, Phoenix Armor Implants give you 5% resistance to thermal damage (fire,
 laser, and plasma) - over and above any other armor you're wearing. The operation takes a few days, one
 suit of Combat Armor (for the thermal-dissipative membranes), and it will cost you $7,000. Not to worry,
 though; this operation *should* create only minimal scarring - at least that's what I read.}
{311}{}{That sounds great, Doc. I sure won't have to worry about extra sunscreen after this.}
{312}{}{Let me ask you about one of the other operations, Doc.}
{313}{}{I'll have to come back when I have more money, Doc. Goodbye.}
{314}{}{I'll have to come back when I dig up a set of Combat Armor, Doc. Goodbye.}
{315}{}{I don't think I want to do this right now after all. Goodbye, Doc.}
{316}{}{You need to have the Phoenix Armor Implants before I can give you the Assault Enhancement. But
 I'll tell you what it should do. The Assault Enhancement should give you a total of 10% resistance to
 thermal damage (fire, laser, and plasma) - over and above any other armor you're wearing. The operation
 takes a few days and it'll cost you $21,000. In addition, you're not going to be too charismatic after
 I finish. Layering all those thermal dissipaters under your skin is going to make you look a bit lumpy,
 sort of like an overstuffed burrito.}
{317}{}{The Assault Enhancement of the Phoenix Armor Implants should give you a total of 10% resistance
 to thermal damage (fire, laser, and plasma) - over and above any other armor you're wearing. The
 operation takes a few days and it'll cost you $21,000. In addition, you're not going to be too
 Charismatic after I finish. Cramming all those impact plates under your skin is going to make you look
 a bit lumpy, sort of like an overstuffed burrito. Ready to begin?}
{318}{}{That sounds great, Doc. Let's do it.}
{319}{}{Let me ask you about one of the other operations, Doc.}
{320}{}{I'll have to come back when I have more money, Doc. Goodbye.}
{321}{}{I'll have to come back when I dig up a set of Combat Armor, Doc. Goodbye.}
{322}{}{I don't think I want to do this right now after all. Goodbye, Doc.}
{323}{}{There, that should do it. The operation was a success. You shouldn't have to worry about bumps
 and bruises so much anymore. That swelling and tenderness will go down in a few days.}
{324}{}{I wouldn't have thought that your skin could accommodate so many of those impact plates, but
 you're ready for action now. You not only look sort of like Frankenstein, but you should be as tough as
 him as well. Uh, try to stay out of the sun until most of the scabs slough off.}
{325}{}{That turned out rather well, I think. The Phoenix Armor implanted much more neatly than I would
 have thought it would. That burning and itching feeling will probably go away in a few weeks...once your
 innards get used to the fibers.}
{326}{}{Coming around, are we? You're just jam-packed with thermal-dissipaters and dissipative membranes.
 You won't look quite so lumpy in a few weeks, but you won't be winning any beauty pageants again,
 either. Try not to pick at the pus-crusts near the drainage incisions until they stop suppurating.}
{327}{}{Thanks for the advice, Doc. This is great. Hey, let me ask you about something else.}
{328}{}{Thanks for your handiwork, Doc. I better be moving on now. Goodbye.}
{329}{}{You deliver the Jet antidote to Doc Johnson.}

# phobos2077 crafting
{501}{}{Say, you think you could show me how to make drugs myself?}
{502}{}{Where can I learn about more advanced drugs?}

{510}{}{I could... Pay me $1000 and I'll show you how to mix some stuff.}
{511}{}{Uh.. Okay, here you go.}
{512}{}{That's a lot of money...}
{513}{}{Cut it down to $500 and I'm in.}
{514}{}{Never mind.}

{520}{}{Time is money and information is gold, you know. My recipes are *very* useful.}
{521}{}{Hm.. maybe you're right. Here is your thousand.}
{522}{}{Hm.. I think you're just *afraid* that I might ruin your business making my own drugs and selling them next door. Is that it?}

{530}{}{What?! Me afraid of your chemistry skills? That's ridiculous! Take them for... $400.}
{531}{}{That's a deal. Let's get started then.}
{532}{}{I changed my mind.}

{540}{}{No. $750 is as low as it gets.}
{541}{}{Deal. Let's get started.}

{550}{}{[Doctor briefly disappears in his back room and returns with a few notebooks.] Let's start with antidotes,
 they are fairly easy...}
{551}{}{... and this chemical reaction allows you.. Ah well, I bet you don't understand a single word. You need to step up your basic chemistry and medicine.}
{552}{}{I'll figure it out, thanks.}
{553}{}{That's useful indeed. Let me ask you something else.}

{560}{}{More advanced than this? You'd need a proper scientist for that. Either try the Vault City, the Vault in the Vault City, that is or...
 I have no idea. Someone *is* making jet, so I suppose there's at least a few other scientists out there somewhere, but good luck finding them.}