{100}{}{You see an old, kindly looking fellow.}
{101}{}{It's Doc Jubilee.}
{102}{}{He's an old man with a snow-white beard and a slightly blank stare.}
{103}{}{I'm Doc Jubilee. What's wrong, young man?}
{104}{}{What's wrong, young man?}
{105}{}{Me hurt.}
{106}{}{I need a doctor.}
{107}{}{Can't you just take some pills or something and stop bothering me with this twaddle?}
{108}{}{Hell, you're hardly bleeding.}
{109}{}{I don't know. Don't think I can save it. We may have to cut that leg off.}
{110}{}{You're kidding.}
{111}{}{Ha-ha.}
{112}{}{There you are, sonny.}
{113}{}{Again.}
{114}{}{Thanks, Doc. Maybe you can help me out with some answers.}
{115}{}{Goodbye.}
{116}{}{It'll cost you $%d.}
{117}{}{Just heal me.}
{118}{}{I'm not staying here.}
{119}{}{You make better.}
{120}{}{Me go now.}
{121}{}{Nope. Never joke. Best I cut that leg off before gangrene sets in.}
{122}{}{No way you're cutting anything off, understand?}
{123}{}{That's it, I'm leaving.}
{124}{}{Well, if it festers, don't blame me.}
{125}{}{I don't run a charity hospital. You'll need to get some cash before I do anything.}
{126}{}{So what can I do for you?}
{127}{}{Shoot.}
{128}{}{Vault 13?}
{129}{}{Know where I could find Vault 13?}
{130}{}{I heard somebody saying Mr. Westin's not well. That true? I'm worried something might happen to him. He owes me money.}
{131}{}{There's this Saltbeef fellow says you stole a map from him. What's the deal?}
{132}{}{I'm looking for a job. Know of any?}
{133}{}{Doc, you wouldn't know anything about a group that's fighting those evil slavers, would you?}
{134}{}{Well you shouldn't worry, son. As long as he doesn't tax his system, he'll probably outlast us all. 'Course that's if he'd ever mind my doctoring or his medicine.}
{135}{}{Well, that's good to know. There's something else I was wondering.}
{136}{}{Thanks, doc.}
{137}{}{That old drunk! The only thing I ever got from him was my "Velvet Elvii" painting - in lieu of cash.}
{138}{}{A Velvet Elvii? Could I see it?}
{139}{}{Not exactly a map, eh? Well, let me pick your brains on some other things.}
{140}{}{Well, I've got to get on.}
{141}{}{I ain't heard that mentioned since old Saltbeef was brought in here. Sunstroke. Burned with fever for three days, all the time ranting how he'd found Vault 13, his mother lode.}
{142}{}{Mother Lode?}
{143}{}{So where is it?}
{144}{}{Where vault?}
{145}{}{Couldn't tell you. Saltbeef always claimed he had a map, but nobody's ever seen it.}
{146}{}{Saltbeef?}
{147}{}{Ask more.}
{148}{}{Well, that's more than what I had before.}
{149}{}{The big one. Saltbeef's an old uranium prospector - more accurately, a drunk. Lives out on the Westin spread these days.}
{150}{}{Another question...}
{151}{}{Thanks for the story.}
#CMH changing per Fergus.. Now you have to pay 1000 or steal the painting off of him.
{152}{}{Well, I was really hoping to get some money for it. I'll let it go for $}
{153}{}{Maybe later, another question...}
{154}{}{Maybe later, I have to go.}
{155}{}{Saltbeef's an old uranium prospector. Lives out on the Westin spread these days.}
{156}{}{Another question...}
{157}{}{Thanks for the story.}
{158}{}{You best go talk to President Tandi. I've heard she's looking for a special type of person.}
{159}{}{Another question...}
{160}{}{Thanks.}
{161}{}{I might... There is a group set against slavery and- well, most the other vices, too. You can sometimes find them over at the big shop, working on some automobile.}
{162}{}{Another question...}
{163}{}{Thanks.}
{164}{}{Hey, get your hands off that, punk!}
{165}{}{Careful there! Just takes tiny amount to expose yourself.}
{166}{}{Put that back! You could seriously hurt yourself with that stuff.}
{167}{}{Those meds are for Mr. Westin, not you. Put them back.}
{168}{}{Get away from that. Got to be careful, see. Wouldn't want Mr. Westin getting the wrong meds now.}
{169}{}{Watch it! I just measured out Mr. Westin's dose.}

{170}{}{I'm Doc Jubilee. What's wrong, young miss?}
{171}{}{What's wrong, young miss?}
{172}{}{There you are, miss.}
{173}{}{Well you shouldn't worry, miss. As long as he doesn't tax his system, he'll probably outlast us all. 'Course that's if he'd ever mind my doctoring or his medicine.}
{174}{}{Sure. Here's the $}
{175}{}{Thanks, I've been trying to get the money out of Saltbeef, but that bum never had any.}
{176}{}{.}

#RP content - killap
{200}{}{Whoa there, }
{201}{}{son! }
{202}{}{missy! }
{203}{}{You can't be messing with that stuff! I just measured out Mr. Westin's dose and we wouldn't want him getting the wrong meds now. What in blazes do you think you're doing?}
{204}{}{I was just trying to get a look at those pills you have on the shelf there.}
{205}{}{Oh, don't mind me. I was just window shopping.}
{206}{}{Sorry. I've just always had this irresistible compulsion to dig around in other people's stuff that I've never been able to shake.}
{207}{}{Honestly? Not expecting you to be that observant. I guess I'm going to have to improvise.}

{210}{}{Were you, now? (Doc Jubilee regards you coolly.) I'd guess you were a mite young to be suffering from a bum ticker.}
{211}{}{And you'd be right. I'm asking for my friend Cassidy. Older fella. He's got a bad heart, and traveling the wastes is getting kind of rough on him.}
{212}{}{And I'd wish you were right. I got it from my pa. Or so they tell me.}
{213}{}{Oh, nothing like that. I'm just overbearingly inquisitive, I guess.}

{220}{}{Well, you can't. This is a private practice, not a drugstore. You might want to try Duppo's, a tetch north of here.}
{221}{}{Sounds like just what I'm looking for. Bye.}
{222}{}{I'll check 'em out. In the meantime, though, do you mind if I ask you a few things?}
{223}{}{No, I think I came to the right place. I can see you're doing good work here. I thought I might offer a donation.}

{230}{}{(The doctor blinks. He blinks again.) You should probably talk to somebody about that. Unfortunately,
 I ain't the right kind of doctor. All's you need to know about that shelf is that if you mix up or taint any of those
 prescriptions, some poor fella's liable to end up in a world of hurt, if they're still in this world at all. Best keep
 your hands to yourself.}
{231}{}{Will do, doc. But, uh, say-- I've got a buddy who could really use some of those heart pills you've got there.
 Think you'd be willing to sell me some?}

{240}{}{Awww, }
{241}{}{son, }
{242}{}{miss, }
{243}{}{I wish I could help you, but I'm not taking on any new patients right now. Council's got me on retainer. Can't sell you no pills, neither-- Councilman Westin's people are supposed to pick those ones up in }
{244}{}{ days, }
{245}{}{ day, }
{246}{}{and just ain't no way I'm going to have time to mix up another batch before then.}
{247}{}{I understand, doc. Maybe I'll find a decent pharmacist somewhere else. If it's not too much to ask, though, is there any advice you could give me on the subject? You don't find medicine like that too often.}
{248}{}{Those are the breaks, I guess. Anyway, I should be alright. I've picked up *tons* about cardamomagy from old comic books. Cut the hard chems back to twice a day, TOPS, make sure to get your exercise in short, strenuous bursts so your heart doesn't have time to act up, all kinds of good stuff.}

{250}{}{I feel for you, friend, but I'm afraid those pills are for Councilman Westin, and I ain't taking on any new patients right now so I wouldn't be able to write you up a script. Now please, don't go messing around on that shelf anymore. Those prescriptions get mixed up, someone could wind up in a pretty bad way.}

{260}{}{Let's be clear here, }
{261}{}{mister. }
{262}{}{missy. }
{263}{}{What exactly do you mean by "donation?"}
{264}{}{A charitable contribution, in furtherance of your service to the public, say... $150? You can count it out in the back room. Should only take a minute, right?}
{265}{}{Uh, actually, I think I'd better check with my accountant before I do anything rash. See you later, doc.}

{270}{}{No can do, I'm afraid. Those are for Councilman Westin. His people are due by to pick them up in }
{271}{}{ days, }
{272}{}{ day, }
{273}{}{and I'm not going to have the time to mix up another batch before then. I'm sure you can find a pharmacist with a lighter workload.}
{274}{}{I see. Well, thanks anyway.}

{280}{}{(Doc Jubilee gapes at you for a moment.) Aw, you're puttin' me on, right? You've gotta be puttin' me on. (Glances at you again, shakes head, blows out cheeks.) Hooo, boy. Either way, I wouldn't be no kind of doctor if I let you walk out of here without a few pointers, at least.}
{281}{}{Let's see... for starters, you should prob'ly stop doing... well, near to just about everything oughta cover it. No drinking, no smoking, no red meat, NO chems. Try to get a half-hour a day of MILD exercise. And take it easy. Life ain't a race, 'least not the kind where you want to be first to finish. Truth told, no one ever listens to this stuff, but at least I'll be able to rest easier tonight.}
{282}{}{More important, you need to find you a half-decent chemist and tell 'em you need set up with a regular supply of Triproxinil. Tri-prox-i-nil. Wasteland stock ain't gonna be as fancy as what I got on the shelf there, but chemically, it's all the same once you get down to brass tacks. 30 milligrams, twice a day.}
{283}{}{Now, you gotta be sure to drink plenty of water while you're on this stuff. And for criminy sakes, you stay *as far as you can* from those pecker pills like they got up in New Reno, understand? They don't play nice together. Fella takes one while he's on the other, his John Thomas ain't nearly the only part of him going stiff that day, if you follow.}
{284}{}{(To yourself) Hmm, that could work. Yeah. Maybe something in the way of a PDE-5 inhibitor compound...}
{285}{}{Oh-- And if you *do* go through one of them Reno hucksters, they might go tellin' you that this stuff'll proof your heart against just about any pusher's poison you'd care to try. I ain't gonna lie to you-- there's prob'ly some truth to that. Still don't make bein' a junkie any more glamorous. You're grown and out of britches, so I ain't gonna lecture, but there it is.}
{286}{}{Thanks a million, doc. You have no idea what a help you've been. Take care.}
{287}{}{Tri-prox-i-nil, no bo-ner-pill. Heh heh. I'll keep that in mind. See you around, doc.}

{290}{}{You think you're dealing with some shifty bartertown sawbones, }
{291}{}{son, }
{292}{}{girlie, }
{293}{}{is that it? Don't. I am a trained and accredited NCR medical professional, and that's worth a lot more than that pocketful o' chump change.}
{294}{}{My apologies. Obviously, a practitioner of your caliber rates a donation of no less than $250.}
{295}{}{(Hang head.) Look, I'm really sorry. I'm not proud of myself, and I would normally never have tried anything like that, but I'll be honest with you: I was desperate for those pills.}
{296}{}{Sorry for the trouble. I think I'd better just go before I dig myself a bigger hole.}

{300}{}{(Doc Jubilee begins to turn red.) I don't think you heard me the first time,}
{301}{}{ boy, }
{302}{}{ woman, }
{303}{}{so listen close: I am a doctor of the NCR. It's a solemn duty, and it came with a solemn oath. You ask me one more time to piss on that oath, the ONLY part of it that's going out the window is "first, do no harm." You got me?}
{304}{}{Alright, screw it. If you're as great as you seem to think you are, maybe you'll be able to sew yourself back together after this.}
{305}{}{Whoa, now. Didn't mean to step on any toes, doc. I'll just leave you be for awhile.}

{310}{}{Say, doc, I was wondering about those heart pills you've got up there on the shelf.}
{311}{}{Are you sure you can't reconsider selling me some of those pills?}

{320}{}{Sorry, Councilman Westin's people are due by to pick those up in }
{321}{}{ days, }
{322}{}{ day, }
{323}{}{and I'm just too busy to mix up another batch in time.}

{324}{}{(Mutters to himself.) Where the hell did I put those pills for Mr. Westin. His heart aint gonna last long without 'em. (He looks up.)
 Oh, sorry. What can I do for you today?}
{325}{}{I couldn't help overhearing what you said about heart pills. I was actually going to ask you about such medicine.}
{330}{}{(Mutters to himself.) I can't believe Mr. Westin's dead. Couldn't have been my fault, I measured out those pills precisely. (He looks up) Oh, sorry. What can I do for you today?}
