{100}{}{You see a pudgy guy with a shiny bald head and thick-lensed glasses.}
{101}{}{It's Dr. Henry.}
{102}{}{This guy is so out of place it's painful. He's got that egghead, not living in the real world air about him, that's for sure.}
{103}{}{Excuse me, I'm Dr. Henry and I'm very busy. What do you want?}
{104}{}{You again? What do you want?}
{105}{}{Hurgh.}
{106}{}{I'm}
{107}{}{Enough chit-chat. You've got some papers Mr. Merk wants. Hand 'em over and nobody gets hurt.}
{108}{}{Ever heard of a place called the Enclave?}
{109}{}{None of your business.}
{110}{}{Hmm, sub-par cranial development... Stunted intellectual development. No gross physical mutation, though. No, you just simply won't do, I'm afraid. Good day.}
{111}{}{The Chosen One? Of course, that makes sense. Interesting... I'm afraid I can't help you. I was assigned to cyber-genetics research, not the Vault Behavioral Project.}
{112}{}{What are you talking about?}
{113}{}{Vault Behavioral project?}
{114}{}{Cyber-genetics? I don't remember ever studying that one.}
{115}{}{Right. You're mad as a hatter. Goodbye.}
{116}{}{Oh my, I've said more than I should already. Never mind, and if anybody asks I didn't say anything.}
{117}{}{Something about extreme sociological conditioning. Mind you, I thought it was all so much mumbo-jumbo, no real science in it at all. But I did hear something about 13 having to be improvised during the course of the experiment. Sloppy work, I'd say.}
{118}{}{Experiment? What experiment?}
{119}{}{What's this about cyber-genetics?}
{120}{}{You expect me to believe any of this? You are a loon.}
{121}{}{Oh, it's a whole new field - very exciting. Why I'm working on some projects right now - a radical new concept for the mutant problem. You see, it's really quite simple - mutantcy isn't absolute. It can be cured.}
{122}{}{Of course, my simple-minded colleagues were just trying to solve the whole problem the crudest way possible. Purification, indeed. I'll admit there were some early problems, but I've got them worked out now... I think.}
{123}{}{}
{124}{}{Continue}
{125}{}{In fact, you could help me perform the field testing. Interested?}
{126}{}{Field testing? What do you mean?}
{127}{}{Not a chance.}
{128}{}{I've prepared a small sample of the serum but it needs to be injected into a host.}
{129}{}{I'm not letting you stick any needles in me!}
{130}{}{That's it, I'm out of here.}
{131}{}{You? Oh, no - the serum's not refined enough to handle such a low mutagenic quotient. It must be used on a super-mutant. Inject the serum into a super-mutant and then come back and report the results. I understand Broken Hills is full of them.}
{132}{}{What's it do?}
{133}{}{What's in it for me?}
{134}{}{Well, it should cause a regression in the genetic matrix that results in the destabilization and assimilation of aberrant DNA, leaving the host free of mutagenic potential. If I knew for sure, I wouldn't need you to test it.}
{135}{}{What's in it for me?}
{136}{}{You'll be participating in an important experiment, in fact, the most important, scientific-oh, you mean money. Well, I do have a Cyber-Hound Mk. II, Personal Security Model that I brought with me. I suppose I could have it activated and on-line by the time you got back. Would that do?}
{137}{}{Cyber-hound? Sure, why not.}
{138}{}{You are out of your mind. Just completely loony.}
{139}{}{Excellent. Here's the serum, fitted up in a stim hypo. All you have to do is use it on a super-mutant and then report back to me. Like I said, Broken Hills - that's the place to look. Good luck.}
{140}{}{Tell your Mr. Merk that my answer hasn't changed. I have no interest in any of his "joint ventures." Thank you and good day.}
{141}{}{It's no use, I'm not going back. None of you appreciated the work I was doing, so don't pretend to be my friend. Thank you very much!}
{142}{}{Well then, we've nothing to talk about. Good day.}
{143}{}{So, how did it go? Is the test done?}
{144}{}{Yes.}
{145}{}{No.}
{146}{}{Well, if you don't mind, would you please get on with it? I'm not a young man anymore.}
{147}{}{And... How did it work?}
{148}{}{It killed him! You said it would cure mutants!}
{149}{}{He's dead, Jim.}
{150}{}{You misunderstood. I said it would remove their mutagenic potential. The process does seem violent on the system, though. Oh well, more refining to do.}
{151}{}{What about my pay?}
{152}{}{You're a monster! I want nothing to do with you.}
{153}{}{Still some bugs, I see. Well, try and try again.}
{154}{}{What about my pay?}
{155}{}{You're a monster! I want nothing to do with you.}
{156}{}{Of course. The cyberdog is all yours. Now, I have work to do.}
{157}{}{...so the mutation rate stabilizes over-don't bother me now.}
{158}{}{Primitive adaptation to environmental conditions. Fascinating.}
{159}{}{You don't have an oscillating calibrator? No, of course not.}
{160}{}{, the Chosen One. I'm looking for Vault 13.}
{161}{}{Good day, my ass, bucko, I'm here to be polite. You hand over those papers or I'll start removing fingers. Let's see how good of a doc you are then.}
{162}{}{Fine, I'll let him know.}
{163}{}{Uh... Ok, the papers are in my desk over there. Take them; just don't hurt my hands. Ok?}
{164}{}{Kiss my ass, you cretin! Guards! Guards!}
{165}{}{Now you're being reasonable. I'll let Mr. Merk know.}
{166}{}{You'll regret that, Doc.}
{167}{}{Hey! You have exactly ten seconds to put those papers back before I call the guards.}
{168}{}{Caught you again, huh? Fine, I'll let the law deal with you. Guards! Guards!}

# phobos2077 bring tentacles quest
{400}{}{Are you here because of those tentacles I'm looking for?}
{401}{}{You're looking for tentacles?}
{402}{}{Do you need more of those tentacles?}
{403}{}{I've brought the tentacles you wanted.}
{404}{}{I'm still collecting those tentacles for you. Goodbye.}
{405}{}{Yes, I need a bit of specific biomaterial for my research. It can be found in tentacles of several stranger varieties of mutants, ones often called "floaters" or "centaurs". Bring me %1% of them and I'll pay you $%2%.}
{406}{}{Where can I find them?}
{407}{}{I'll see what I can do.}
{408}{}{I don't have time for this.}
{410}{}{Remnants of the masters army still infest much of the region from here all the way to the coast. Some of them should have what I need. I've herd of groups in the desert west of New Reno, although that could be only rumors.}
{415}{}{Good. Here is your money. Come again later, maybe I will need more biomaterial.}
{416}{}{I will.}
{420}{}{No, I have enough of those for the time being.}
