{100}{}{You see a young man wearing the badge of the NCR police.}
{101}{}{It's Karl, the town deputy.}
{102}{}{You see a young man barely out of his teens. He looks eager to please.}
{103}{}{Welcome, stranger. I'm Deputy Karl. What can I do for you?}
{104}{}{Such as?}
{105}{}{Uh... nugh..}
{106}{}{I'm new to NCR. What can you tell me about your town?}
{107}{}{Well, I'm looking for Vault 13.}
{108}{}{President Tandi sent me over to talk to some prisoner you've got.}
{109}{}{My name's}
{110}{}{I'm looking for a guy named Jack. Some folks call him Whack Jack.}
{111}{}{Where can I find Roger Westin?}
{112}{}{Okay, had a little too much party did you? Look, there's an unlocked cell back there. Why don't you go in back and sleep it off?}
{113}{}{Look, take my advice - get your friends to take you home so you can sleep it off. Drunk in public's a crime here.}
{114}{}{This is NCR, capitol of the New California Republic. Population 3000 and growing. No slavery, no gambling, no drugs. President is Mrs. Tandi, my boss is Sheriff Dumont. That answer your questions?}
{115}{}{Well, I've got some other questions.}
{116}{}{Yeah, that's all.}
{117}{}{So did I when I was a kid. Let me know if you find it!}
{118}{}{Well, I've got some other questions.}
{119}{}{Gee, thanks.}
{120}{}{His name's Oswald. That's all we could get out of him. He's supposed to be a squatter, from vault 15, but... I doubt it. He's a bit too tough. You know what I mean?}
{121}{}{Tough guy, huh?}
{122}{}{What're you going to do to him?}
# phobos2077 changed lines
{123}{}{Say, I've heard of you haven't I? Yeah - some pretty good stuff. Look, there's some folks I know, they could use a fellow like you. Just go to the auto shop and ask for Elise. Tell her Karl sends his regards.
 If you're up for some bounty hunting, there is some people on wanted list. Dead or alive.}
{124}{}{Work? The Stockman's Association is looking for guards. Raiders been hitting the cattle drives hard again. And I heard that President Tandi's been looking for somebody "resourceful," as she puts it.
 If you're up for some bounty hunting, there is some people on wanted list. Dead or alive. That help?}
# end of changed lines
{125}{}{Well, I've got some other questions.}
{126}{}{Some. Thanks.}
{127}{}{That's Officer Jack, stranger. One of our men. You haven't been talking to Mira, have you?}
{128}{}{Yes.}
{129}{}{Mira who?}
{130}{}{That SOB? He's got a spread just outside town. Just take the road past Stockman's.}
{131}{}{You don't like him much.}
{132}{}{Well, I've got some other questions.}
{133}{}{Thanks.}
{134}{}{Yeah. He's a real bad one. Killed two of our men and hasn't said a thing.}
{135}{}{Give me a little time alone with him. Maybe I can convince him to be cooperative.}
{136}{}{Can I see him now?}
{137}{}{Hang the bastard, I hope. Him and his buddies killed two good men. Won't be any pain for me to see him dead.}
{138}{}{Can I see him now?}
{139}{}{She and Jack used to be married, you know. Had themselves a really messy divorce. I wouldn't believe spit from her, not about Jack. 
Do yourself a favor, stay out of it. Jack's a good man, it's just this stuff's got him a little high-strung.}
{140}{}{Okay, let's move on to other topics.}
{141}{}{Well, thank you kindly for that advice, deputy.}
{142}{}{His ex, that's all. If he's not here, he might be over at the power plant. He's been moonlighting over there for Dorothy.}
{143}{}{Well, I've got some other questions.}
{144}{}{Thanks.}
{145}{}{Guess I'm pretty obvious. Lot of folks look up to him because he's a councilman, but not me. He thinks he's a big man, like the law don't always apply to him. I'd like to take him down a notch or two someday.}
{146}{}{Stranger things have happened. What can you tell me about him?}
{147}{}{I've got to go. Just outside of town, you say?}
{148}{}{No problem. Next five minutes, maybe I won't hear a thing. Follow me.}
{149}{}{Sure, for what good it will do you.}
{150}{}{Well, a couple of years ago he had a stroke and now Doc Jubilee's got him on some kind of medicine. What's it to you, anyway?}
{151}{}{Nothing, just talk. I'll quit wasting your time.}
{152}{}{. I'm in need of some honest work.}
{153}{}{Tandi say you got bad man here.}
{154}{}{Me want to see bad man.}

# phobos2077 bounty hunt
{200}{}{Work? There's plenty. The Stockmen's Association is looking for guards. Raiders been hitting the cattle drives hard again. And I heard that President Tandi's been looking for somebody "resourceful," as she puts it. If you're up for some bounty hunting, there are people on the wanted list. Dead or alive. That help?}
{201}{}{Tell me more about that wanted list.}
{202}{}{Do you have someone else on that list?}
{203}{}{Can you describe the current target again?}
{204}{}{I'm here to claim the bounty for that tribal.}
{205}{}{The information on bounties is public, you take out people on the list, bring some proof and receive your bounty. Simple. Interested?}
{206}{}{Go on.}
{207}{}{How come YOU people are putting up offers such as those?}
{208}{}{I'm not a killer for hire.}
{210}{}{Let's see who's on the list... Hmmm, you don't look like you could deal with any of them. We don't want people going on suicide missions. Return later with some more experience under your belt.}
{211}{}{If you say so.}
{215}{}{People from all over ask for aid against violent criminals and offer rewards. We just make the information public, for a small fee. We only deal with community officials, of course, and the wanted people are all obvious criminals.}
{220}{}{There is a guy who's crossed way too many people, judging from the number of bounties. Dead only.
 A tribal from somewhere far up north, rounded up a bunch of followers, they run around with guns.
 He's been spotted around Modoc recently, so you can look for him there. The bounty is $%1%.}
{221}{}{I suppose I need some proof?}
{225}{}{Well, apparently, he's from a tribe where all warriors are wearing these amulets. They only take those off after death. So I guess that would do.}
{226}{}{I'll keep my eyes open, thanks.}
{230}{}{You won't believe this, but there's another guy from the same tribe. This one's gathered quite a posse too, and is hiding somewhere in the desert east of Broken Hills. His head is priced at $%1%.}
{235}{}{What is the deal with this tribe? I've got another one! And this one's got a regular army of followers! Found an old army bunker loaded with guns and armor and whatnot in a cave somewhere up north, burnt his way down to San Francisco. He's somewhere east of it now. The bounty is $%1%.}
{250}{}{Yes, my sources confirm that your target has disappeared. Do you have proof of your work?}
{251}{}{Yes, here is his amulet.}
{252}{}{No, I don't have it...}
{255}{}{Yeah, this is the guy. Here is your bounty.}
{256}{}{Thanks. Goodbye.}
{260}{}{Well, from all I know he may be just laying low. Or someone else got him. No proof - no money.}
{261}{}{Damn it...}
{265}{}{No, there is nothing more for you, sorry.}
{266}{}{It was a pleasure doing business.}
{267}{}{That's a shame... I just started to like it.}

{300}{}{Nothing. Goodbye.}