{100}{}{You see a scowling slaver covered in grime.}
{101}{}{You see a tough looking slaver. He appears to be in charge here.}
{102}{}{You see Don, the slaver in charge of this camp.}

{105}{}{Hey, what the fuck!? Who the hell are you?}
{106}{}{I'm your worst nightmare. Prepare to die!}
{107}{}{Metzger sent me.}
{108}{}{I'm here to join.}
{109}{}{Uhh, this isn't where I left my car...}

{200}{}{You first, asshole.}
{201}{}{I don't have time for this, get 'em boys.}
{202}{}{Join us? This aint a fuckin recruiting center. If you want to join the slavers go to the Den and speak with Metzger.
 Now do you need something or are you just here to piss me off?}
{203}{}{Metzger sent you? [He fidgets uncomfortably.] Don't tell me he wants more slaves already -- for fuck's sake, we just sent a shipment last week.}

{300}{}{Actually yes, I do need something.}
{301}{}{So, why are you here?}
{302}{}{I don't think I need anything else.}
{303}{}{Well then get the fuck outta here. You're trespassing and you ain't wanted.}
{304}{}{I'm leaving.}
{305}{}{Oh, I'll leave--but not until I've killed you and your buddies.}

{307}{}{As a matter of fact, he does. He's going to be entertaining some big shot from New Reno, and wanted a couple more girls for the occasion. But, hey if you can't spare any... I'm sure the boss will be thrilled when I return empty handed.}
{308}{}{[Sweat begins to form on the man's tattooed head.] Whoa, hold on a second. I never said I couldn't spare a few. In fact, here, take the key to the shack, that's where we keep our, uh, personal favorites. The pick of the litter, you might say. [He hands you a key and smiles nervously.]}
{309}{}{Thanks. I'll put in a good word for you. Bye.}
{310}{}{Metzger sent you, huh? Do I look blind to you? You're not even wearing our fuckin mark. I don't know who you are, but you're full of shit and you're wasting my time. For that, you die. [Signals to his men.] Let's waste this loser.}
{311}{}{Yeah right. You're full of shit and you're wasting my time. For that, you die. [Signals to his men.] Let's waste this loser.}

{400}{}{I'm busy. Go see Metzger in the Den if you want to do a run.}

{450}{}{Didn't I tell you to scram? We don't take too kindly to trespassers. Time to die.}

{500}{}{[DONE]}

{600}{}{Now you die!}
{601}{}{Die Ranger scum!}

{800}{}{Umm... Give Metzger my regards.}

#RP 1.3
{900}{}{No, actually, he sent me to have a look at your stock. You see, I have very particular tastes, but I'm willing to
 pay a premium price.}
{901}{}{Bullshit. Metzger's never sent a customer out here before. I don't know what you're trying to pull, but you've
 got three seconds to get the fuck outta my face before I have my boys pump you full of lead.}

#Lujo
{1001}{}{Wait up! See this fat old bastard here? He was here already! He had him brought in to fix a radio! Don't tell me you don'tremember the sorry sack of lard!}
{1002}{}{[Stares at you in disbilief] Wow. You actually bought that guy?}
{1003}{}{Yes! And let me tell you, he was not worth nowhere near what I paid for him! The only thing he was good for was bringing me here, and even that almost got me killed!}
{1004}{}{Yeah, you sorry bastard... [Laughs] Metzger sure knows how to screws people over! But you're right, he wouldn't like us shooting a proper customer one bit, especially one with your taste in merchandise. Look around, take your pick!}
{1005}{}{Thank you. I'd tell you to keep the fatass, but then you might change your mind and I wouldn't blame you.}
{1006}{}{Oh, hell no, you bought him, you keep him! Here's the keys, check the ones in the shack out in case you're not buying for yourself. You won't like them, though, they're good for stuff! [Laughs]}
{1007}{}{Thank you!}
{1008}{}{[Slavers eyes go wide with recognition] Oh, no! No! Don't tell me Metzger sent him BACK!? Cuz I'll shoot both of you and play dumb!}
{1009}{}{No! Metzger made me BUY him, sold him to me as a "guide"!} 
{1010}{}{[Slavers eyes go wide with recognition] No! Hell, no! I'm not taking that guy back! You're both dead!}