# 0 - 5000  reserved for traps
# traps look at
{50}{}{You see a spike trap.}
{60}{}{You see a mine-trap.}
{70}{}{You see a sensor bomb trap.}

# traps description
{100}{}{You see a spike trap, not yet armed.}
{101}{}{You see a spike trap, waiting for it's prey.}
{102}{}{You see a spike trap, already used.}
{110}{}{You see a mine trap, not yet armed.}
{111}{}{You see a mine trap, carefully concealed and armed with %1%.}
{112}{}{You see remains of a mine.}
{120}{}{You see a sensor bomb trap, not yet armed.}
{121}{}{You see a sensor bomb trap, armed with %1%.}
{122}{}{You see remains of a sensor bomb.}

# actions
{200}{}{You have successfully armed the trap.}
{201}{}{You have successfully armed the trap with %1%.}
{202}{}{You have successfully disarmed and disassembled the trap.}
{203}{}{You have assembled the trap.}
{204}{}{You have disassembled the trap.}
{300}{}{You fail to arm the trap.}
{301}{}{You fail to arm the trap with %1%.}
{302}{}{You fail to disarm the trap.}
{311}{}{You critically fail to install the trap, setting it off.}
{312}{}{You critically fail to disarm the trap, setting it off.}
{401}{}{There is already another trap here.}
{404}{}{You cannot disassemble armed trap.}
{411}{}{Cannot arm the trap with this item.}
{414}{}{You have disassembled the trap, but it is not usable anymore, so you throw it away.}
{421}{}{Failed to find appropriate armament for this trap.}
{431}{}{You cannot use this on the trap. Use your Traps skill to arm it.}
{441}{}{You cannot pickup the trap. Use Traps skill to arm it or Repair to disassemble.}
{460}{}{You cannot assemble trap from the inventory. Use it from hands.}
{461}{}{You cannot assemble trap during combat.}
# trap types
{1000}{}{frag grenade trap}
{1025}{}{frag grenade trap}
{1026}{}{plasma grenade trap}
{1027}{}{pulse grenade trap}
{1051}{}{dynamite trap}
{1081}{}{plastic explosives trap}
{1159}{}{fire trap}
{1320}{}{spike-trap}
{1365}{}{enhanced spike-trap}
{1613}{}{home-made grenade trap}
# trap events
{2001}{}{You gain }
{2002}{}{ experience points for a trap kill.}


# combat messages
# stealth
{5001}{}{Sneak attack!}