{100}{}{You see a scruffy-looking man in a dirty brown shirt. His arms are covered with a bright red rash, which he scratches frequently.}
{101}{}{You see "Doctor" Andrew.}
{102}{}{You see a scruffy-looking man in a dirty brown shirt. His arms are covered with a bright red rash, which he scratches frequently.}
{103}{}{Looks like you've seen some fighting, friend.}
{104}{}{Whoa... looks like you've seen some serious action, friend.}
{105}{}{Whoa... looks like you've been in some heavy fighting, friend.}
{106}{}{Holy...! You're bleeding all over the floor!}
{107}{}{You here to get patched up?}
{108}{}{Patssshh.}
{109}{}{Nup.}
{110}{}{Yeah, I could use some medical attention.}
{111}{}{Um, I need a growth removed. My sixth toe.}
{112}{}{Actually, my friend here could use some medical attention.}
{113}{}{Actually, my friends here could use some medical attention.}
{114}{}{What is this place?}
{115}{}{Uh, what is this place again?}
{116}{}{I found some combat implant schematics in the Vault City medical database. Could you perform the operation?}
{117}{}{Not right now. It looks worse than it is.}
{118}{}{No, I'm fine. Just stopping by.}
{119}{}{All right... from the looks of it, it's gonna cost }
{120}{}{ bucks. You got the cash, then you're good to go.}
{121}{}{No guarantees with the ol' Doc in the back room, of course...}
{122}{}{Patshhh? Patshh! Take moneee, fixx leaks.}
{123}{}{Bye-bye.}
{124}{}{Not nuff moneee. Bye-bye.}
{125}{}{All right.}
{126}{}{That's pretty steep. How about }
{127}{}{?}
{128}{}{Never mind. How about my friend instead?}
{129}{}{Never mind. How about my friends instead?}
{130}{}{What is this place?}
{131}{}{I found some combat implant schematics in the Vault City medical database. Could you perform the operation?}
{132}{}{I don't have enough. I'll be back when I have some more cash.}
{133}{}{No, thanks. Maybe some other time.}
{134}{}{Well... all right. That sounds fair.}
{135}{}{Let's get to it, then. I'll just hook you up to the ol' Doctor here... slip your arms into the slots there, and I'll tighten the braces and secure the clamps...}
{136}{}{Fade out for 3 Seconds}
{137}{}{All right! Knew the ol' Doctor wouldn't let me down.}
{138}{}{Me wanna ride agin! Agin!}
{139}{}{Buyhye.}
{140}{}{Can you cure my friend here?}
{141}{}{Can you cure my friends here?}
{142}{}{What is this place?}
{143}{}{I found some combat implant schematics in the Vault City medical database. Could you perform the operation?}
{144}{}{I feel much better, thanks.}
{145}{}{Uh, well now, that might not be the safest thing for you, friend. Seems like you already took a few trips in the ol' Doctor from the way you talk. But if you want to...}
{146}{}{Fade out for 3 Seconds}
{147}{}{Uh... how you feel? Any better? Any worse?}
{148}{}{Agin! Agin! Agin!}
{149}{}{Me feel like maxxx hup puints incrise so me fine for nowww. Buhyyee.}
{150}{}{Uh, well, I warned you...}
{151}{}{Fade out for 3 Seconds}
{152}{}{Uh-oh. Looks like the ol' Doctor took a pound of flesh this time.}
{153}{}{Urrrhkkk... me hurt... insighde... me never want ta ride in bad thin agin...}
{154}{}{Well, now I ain't a mechanic, so I can't help that brain whazzit you got with you. Sorry, friend.}
{155}{}{Can you heal me instead?}
{156}{}{I see. Say, I had some questions I wanted to ask you...}
{157}{}{Oh, well. Thanks anyway.}
{158}{}{All right... from the looks of it, it's gonna cost }
{159}{}{ bucks. You got the cash, then you're good to go.}
{160}{}{No guarantees with the ol' Doctor in the back room, of course...}
{161}{}{All right.}
{162}{}{That's pretty steep. How about }
{163}{}{?}
{164}{}{Never mind. How about me instead?}
{165}{}{What is this place?}
{166}{}{I found some combat implant schematics in the Vault City medical database. Could you perform the operation?}
{167}{}{I don't have enough. I'll be back when I have some more cash.}
{168}{}{I've changed my mind. Maybe some other time.}
{169}{}{Well, now... tell you what. }
{170}{}{ bucks for the whole lot of you, and we'll call it even. What do you say?}
{171}{}{All right.}
{172}{}{I don't know. That's a little steep. How about }
{173}{}{ bucks?}
{174}{}{Can you heal just me instead?}
{175}{}{What is this place?}
{176}{}{I found some combat implant schematics in the Vault City medical database. Could you perform the operation?}
{177}{}{I don't have enough. I'll be back when I have some more cash.}
{178}{}{I've changed my mind. Maybe some other time.}
{179}{}{Well... all right. That sounds fair.}
{180}{}{Let's get to it, then. I'll just hook up the ol' Doctor here... have 'em lay down, and I'll tighten the braces and secure the clamps...}
{181}{}{Fade out for 3 Seconds}
{182}{}{There, all stitched up! Knew the ol' Doctor still had some life left in 'im.}
{183}{}{Thanks. Say, there was another thing I needed...}
{184}{}{Much appreciated. We may be back.}
{185}{}{This here's the common body shop for Vault City. Me an' the ol' Doctor in the back patch up whoever needs some attention.}
{186}{}{"Ol' Doctor?"}
{187}{}{I see. Say, I had some other questions for you...}
{188}{}{Hmmm. Maybe I'll be back when I need your services.}
{189}{}{Yeah, the "Auto-Doctor" in the back room there. It's a loaner from the city.}
{190}{}{It can be a little ornery sometimes, but mostly it does its job. Mostly.}
{191}{}{Been running a lot smoother lately, which is good. Cuts down on repeat visitors.}
{192}{}{Yeah, I replaced some of the cables and cleaned out the interior. It shouldn't give you any more trouble.}
{193}{}{I see. Say, I had some other questions for you...}
{194}{}{Ornery, huh? Maybe I'll go take a look at it...}
{195}{}{Good to hear it. Talk to you later, Andrew.}
{196}{}{Eh... well... thank you very much. That was decent of you to volunteer to fix it like that.}
{197}{}{Oh, it wasn't a volunteer job. I expect some money for my services.}
{198}{}{Any chance I could get some sort of discount?}
{199}{}{No problem. Glad to help.}
{200}{}{Hell, no! I didn't ask you to fix it, so you don't get jack. I wouldn't push your luck as long as the guards are in earshot.}
{201}{}{Go ahead. Call them. They won't get here in time to save your ass.}
{202}{}{Well, then. You're welcome.}
{203}{}{So... was there something else I could help you with?}
{204}{}{What can I help you with?}
{205}{}{I could use some medical attention.}
{206}{}{Um, I need a growth removed. My sixth toe.}
{207}{}{My friend here could use some medical attention.}
{208}{}{My friends here could use some medical attention.}
{209}{}{What is this place?}
{210}{}{What is this place again?}
{211}{}{I found some combat implant schematics in the Vault City medical database. Could you perform the operation?}
{212}{}{Nothing more today, actually.}
{213}{}{Combat implants? What do you mean?}
{214}{}{Well, according to the schematics I saw, you can graft dermal plates and thermal dissipaters to a person's skeleton using the following procedure...}
{215}{}{Huh. Well, I suppose with help from the ol' Doctor I could do that operation. Course, I'd need some impact plates and dissipaters first... might be able to pry some out of a suit of combat armor, if you can find one.}
{216}{}{Can you give me the information on some of the implants?}
{217}{}{I've got a suit of combat armor right here. Can you give me the information on some of the implants?}
{218}{}{Hmmm. All right then. Say, I needed something else...}
{219}{}{Thanks. I may be back.}
{220}{}{Heh! You're serious then, I see. Well, now, this is a risky venture. The Citizens find out I'm using the ol' Doctor for this, an' they'll take it right back.}
{221}{}{I see. How much for the implants?}
{222}{}{Never mind then. I needed something else, though.}
{223}{}{Forget it, then. Maybe some other time.}
{224}{}{Depends what you want. You want low impact, high impact, low thermal, or high thermal? Each one's got its price tag.}
{225}{}{Which one? Low impact, high impact, low thermal, or high thermal?}
{226}{}{Low impact.}
{227}{}{High impact.}
{228}{}{Low thermal.}
{229}{}{High thermal.}
{230}{}{Nevermind. I had some other questions...}
{231}{}{Forget it. I have to be going.}
{232}{}{Standard Dermal Impact Armor takes the kick outta most explosions, punches, kicks, stuff like that. Say, 5%. I'll need to strip some Combat Armor for the plates, and it'll take two days to do the grafts. 7K oughta cover it.}
{233}{}{Sounds good. Here's the Combat Armor and the cash.}
{234}{}{7000? Uh, 5000 bucks is all I have.}
{235}{}{Hmmm. Tell me about the other implants.}
{236}{}{Never mind. I had some other questions...}
{237}{}{I'll come back when I have more money.}
{238}{}{I'll come back when I get a set of Combat Armor.}
{239}{}{I see. Maybe some other time.}
{240}{}{Well, technically, "high impact" is standard Dermal Impact Armor with extra assault-issue impact plates crammed under your skin.}
{241}{}{So you're gonna need the basic dermal graft first.}
{242}{}{Okay, what's involved?}
{243}{}{Tell me about the other implants.}
{244}{}{Never mind. I had some other questions.}
{245}{}{I see. Maybe some other time.}
{246}{}{Well, I'm gonna need another set of combat armor to get the extra assault plates. Good thing is, the plates'll double the strength of the original grafts, so they'll absorb 10% of the kick. Except...}
{247}{}{Yes?}
{248}{}{Tell me about the other implants.}
{249}{}{Never mind. I had some other questions.}
{250}{}{I see. Maybe some other time.}
{251}{}{It'll take a stretch, a few days at least, assuming the ol' Doctor don't mess it up. An' it's expensive. 21K, as I see it. Plus... well, it ain't gonna help your looks none.}
{252}{}{How much will it hurt my looks?}
{253}{}{Tell me about the other implants.}
{254}{}{Never mind. I had some other questions.}
{255}{}{I see. Maybe some other time.}
{256}{}{All the curves you got are gonna become right angles, near as I can tell.}
{257}{}{You're gonna be all blocky-looking when I'm done.}
{258}{}{Shoving all those plates into your body means your charisma's gonna take a hit. You still game?}
{259}{}{Oh, what the hell. Here's the cash and the combat armor.}
{260}{}{I don't know. 21K's pretty steep. I do have $15,000 on me, though.}
{261}{}{Tell me about the other implants.}
{262}{}{Never mind. I had some other questions.}
{263}{}{I'll come back when I have more money.}
{264}{}{I'll come back when I get a suit of Combat Armor.}
{265}{}{I see. Maybe some other time.}
{266}{}{The Phoenix Implants take the bite outta fire, lasers and plasma burns... about 5%. I'll need to strip some combat armor for the thermal membranes, and it'll take two days for the operation. 9K oughta cover it.}
{267}{}{Sounds good. Here's the armor and the cash.}
{268}{}{$9,000's a bit out of my league. How about $7000?}
{269}{}{Tell me about the other implants.}
{270}{}{Never mind. I had some other questions.}
{271}{}{I'll come back when I have more money.}
{272}{}{I'll come back when I get a suit of combat armor.}
{273}{}{I see. Maybe some other time.}
{274}{}{Well, technically, "high thermal" is standard Phoenix Armor with some thermal dissipaters layered over the membranes.}
{275}{}{So you're gonna need the basic Phoenix implant graft first.}
{276}{}{Okay, what's involved?}
{277}{}{Tell me about the other implants.}
{278}{}{Never mind. I had some other questions.}
{279}{}{I see. Maybe some other time.}
{280}{}{Well, I'm gonna need to scavenge thermal dissipaters from another set of combat armor. Good thing is, the dissipaters'll double the thermal resistance, absorbing 10% of the bite. But...}
{281}{}{Yes?}
{282}{}{Tell me about the other implants.}
{283}{}{Never mind. I had some other questions.}
{284}{}{I see. Maybe some other time.}
{285}{}{It's gonna make your skin blister. Bad. You'll look a lot like that bubbly pre-war packaging material, so don't expect to be getting too many dates after this. And it's gonna cost you. 27K. Up front.}
{286}{}{What the hell. Here's the cash... and another set of combat armor.}
{287}{}{21,000 and it's a deal.}
{288}{}{Tell me about the other implants.}
{289}{}{Never mind. I had some other questions.}
{290}{}{I'll come back when I have more money.}
{291}{}{I'll come back when I have another set of combat armor.}
{292}{}{I see. Maybe some other time.}
{293}{}{Well... that sounds fair.}
{294}{}{All right, let me just bolt you into the ol' Doctor here... hope the anesthesia reservoir ain't clogged again... maybe you better bite down on this piece of brahmin hide just in case.}
{295}{}{Uh... okay. I mean, the Auto-Doc has regularly scheduled maintenance times, right? Heh-heh. How bad could it be?}
{296}{}{You know what? Forget it. I don't want to run the risk that the "ol' Doctor's" not up to it.}
{297}{}{Aieeeeeeeeeee!}
{298}{}{Wait 2 Seconds.}
{299}{}{Uh-oh.}
{300}{}{Player explodes in gruesome death animation.}
{301}{}{Wait 2 Seconds.}
{302}{}{Looks like the ol' Doctor wasn't up to it, after all...}
{303}{}{Wait 2 Seconds}
{304}{}{Nice boots on this one, though. Maybe I can sell them...}
{305}{}{Goto Death Screen}
{306}{}{Well... that sounds fair.}
{307}{}{All right, let me just bolt you into the ol' Doctor here... hope the anesthesia reservoir ain't clogged again... maybe you better bite down on this piece of brahmin hide just in case.}
{308}{}{Fade out for 3 Seconds}
{309}{}{Well, they're in, I guess. Uh, about the swelling and soreness, I'm pretty sure that both are just temporary side effects. Oh, that stabbing sensation you feel when you move your arms and legs should fade in a few weeks.}
{310}{}{Can you hear me? Whew. I didn't think there was any room left for those impact plates, but I was able to pry a lot of muscle tissue and cartilage out of the way. They're in a jar over there, if you want a souvenir.}
{311}{}{Mercy... that was trial and error surgery if I ever saw it. I ended up having to amputate some of your nerve endings... that's the burning and itching sensation you're feeling right now. It'll probably fade in a few weeks.}
{312}{}{I hope to heaven you can hear me right now. Look, when you regain feeling in your extremities, you'll feel an incredible itching sensation all over. Don't scratch! If you do, those pus-crusts over the drainage incisions'll burst and leave scars. Give 'em a few weeks to heal, okay?}
{313}{}{Fanks. Kuh uh ast yew sum mewr kesstions?}
{314}{}{Fanks, Adrew. Bye.}
{315}{}{Well... all right. That sounds fair.}
{316}{}{Let's get to it, then. I'll just hook up the ol' Doctor here... let me tighten the braces and secure the clamps...}
{317}{}{Fade out for 3 Seconds}
{318}{}{Hmmph. Looks like the ol' Doctor's being stubborn again. Piece of junk... still, I was glad I was able to pop the clamps before it started the exploratory surgery routine. Maybe it'll work better next time.}
{319}{}{Wha...? I want my money back!}
{320}{}{Oh, well, I hope so. Look, I needed something else...}
{321}{}{Yeah, maybe. I'm leaving.}
{322}{}{Sorry, no guarantees, no refunds. You take your chances. If you got a problem with it, take it up with the guards.}
{323}{}{Give me my money back right now, or I'll put you in the "ol' Doctor."}
{324}{}{Forget it then. I needed something else...}
{325}{}{Whatever. I'm leaving.}
{326}{}{Well, I can try. No guarantees with the ol' Doctor in the back room, of course. It's gonna cost you... and there's no telling if the operation'll take. Might grow back.}
{327}{}{I don't care. I want it off before it grows into a new me.}
{328}{}{Never mind then. I had some other questions...}
{329}{}{Forget it, then. Maybe I'll be back.}
{330}{}{Hmmmmm. Five hundred, and we'll call it a deal. I'm not authorized to perform amputations with the Auto-Doc, and it'll be my job if they find out.}
{331}{}{Fine. Five hundred. Now get the damn thing off.}
{332}{}{That's a little steep. How about $300?}
{333}{}{Never mind then. I had some other questions...}
{334}{}{Forget it, then. Maybe I'll be back.}
{335}{}{Forget it. I don't have that kind of cash right now. I may be back.}
{336}{}{Well... all right. That sounds fair.}
{337}{}{Let's get to it, then. I'll just hook up the ol' Doctor here... have 'em lay down, and I'll tighten the braces and secure the clamps...}
{338}{}{Fade out for 3 Seconds}
{339}{}{That little friend of yours should be gone now. I hope. It's hard to squeeze out all of that mutated pus out of the bone marrow. Anyway, here you go.}
{340}{}{Glad that's taken care of then. Say, there was another thing I needed...}
{341}{}{It better not grow back this time. I mean it.}
{342}{}{Much appreciated. I may be back.}
{343}{}{You have gained +2 Max HP.}
{344}{}{You have gained +4 Max HP.}
{345}{}{You have lost -2 Max HP.}
{346}{}{Uh, well, okay... but I warned you last time that it might not be safe.}
{347}{}{ bucks for the whole lot of you, and we'll call it even. The procedure won't work on your robot brain, buddy. What do you say?}
{348}{}{Cool! I've always wanted to look like Kryten! Here's the cash and the combat armor.}
{349}{}{All right. Here we go.}
# Added by Seraph:
{350}{}{You have lost -4 Max HP.}
# Added by killap:
{351}{}{Wahh? Me still fee no good. Me go sleep now.}
{352}{}{Ugh... otay. Byeeee}