{100}{}{You see a dirty but strong-looking man.}
{101}{}{You see Connar.}
{102}{}{Hey you! What're you doing here?!}
{103}{}{Stay where you are for now, wanderer. What are you doing here?}
{104}{}{I'm killing off all these mole rats.}
{105}{}{Why, what's it to you?}
{106}{}{Why you Yell!}
{107}{}{I bet those bastards at Vault City sent you. Well, you best be off, and leave everything else alive.}
{108}{}{Well, it's a little late for that.}
{109}{}{Why?}
{110}{}{Sorry, I have a job to do.}
{111}{}{Those creatures are the only thing stopping Vault City from making us their so-called "servants".}
{112}{}{Look, they're paying me to get rid of these beasts, so that's what I'm gonna do.}
{113}{}{They didn't tell me that.}
{114}{}{They're paying me to get rid of them, and the job's done.}
{115}{}{You idiot! Why the hell did you do that!}
{116}{}{I needed the money.}
{117}{}{They'll come for us if you do that, you know.}
{118}{}{Not my problem.}
{119}{}{Well I hope you choke on it. They'll be here for us soon.}
{120}{}{I didn't know this was why they wanted the job done.}
{121}{}{Yeah, well, I don't deal with trash like you anyway.}
{122}{}{Well, we can't let you do that.}
{123}{}{You gotta do what you gotta do.}
{124}{}{You believed them at face value? You've a lot to learn about the world, friend.}
{125}{}{Is there anything I could do to help?}
{126}{}{The Vault City boys aren't the bravest. You show them any kind of a fight and they run for the
 hills. We've already pooled all the money we could for a few rifles and shotguns, but that won't be enough to scare them off. What we need is explosives.}
{127}{}{I might be able to help you out, but those aren't exactly easy to find. What kind of explosives are we talking about?}
{128}{}{[He eyes you with a tentative grin.] You're serious about helping us, aren't you? Alright, if you're up for it,
 then ten or so grenades and at least two bundles of dynamite ought to do the trick - all it takes is a couple of them getting blow up and they'll back right off.}
{129}{}{I'll see what I can do. But like I said, explosives aren't cheap, so I'm gonna need some money.}
{130}{}{You're not wanted here. Leave now.}
{131}{}{I changed my mind. What can I do to help?}
{132}{}{Yeah, well, you're not going to be here for long anyway.}
{133}{}{Like I care.}
{134}{}{What's on your mind?}
{135}{}{What was it that you needed again?}
{136}{}{I got your explosives.}
{137}{}{We need ten grenades and two bundles of dynamite. The sooner you can get them to us, the better.}
{138}{}{Okay.}
{139}{}{Alright! With these babies, we should able to fight them off! Thanks a
 lot, and hey, if you ever need a place to rest, you'll always be welcome here, friend.}
{140}{}{You're welcome.}
{141}{}{Hello! Things are going well. We're going to work on expanding the Village in the next month.}
{142}{}{Hello again! Things have been going well, as you can see. Look around if you have the time.}
{143}{}{We're still building. We're hoping to expand the walls again in the next month.}
{144}{}{Greetings! The village has expanded again, just as we've hoped. Of course, you're welcome as always.}
{145}{}{We no longer have anything to fear from Vault City--it looks like we'll be able to live here in peace. Thanks again, wanderer.}
{146}{}{Just don't kill anything out there, you simpleton.}
{147}{}{What the hell have you done?!?! You fucking traitor! I hate you!!!}
{148}{}{Oooooops...}
{149}{}{Let me out of here!!!}
{150}{}{What did I ever do to you?}
{151}{}{Help me!}
{152}{}{Of course. Here, this is all we can afford. [He hands you $2,500.] I might be a damn fool for trusting it to a
 stranger, but you're the only hope we've got of staying free. Speak to Old Joe in Vault City's courtyard. He's usually
 in or around the bar. He'll know what to do.}
{153}{}{I'm on my way.}
{154}{}{Can I ask you a few questions?}
{155}{}{Certainly, what's on your mind?}
{156}{}{I've spoken to Joe, and before we all do anything stupid I need to know one thing - where did these mole rats come from, and why aren't they aggressive?}
{157}{}{Nothing, bye.}
{158}{}{Well, it's kind of a strange story. You see, a bunch of ghouls came here one day, mumbling something about a "renewal",
 and giving out these funky amulets. [He shows you an Ankh shaped amulet.] These big rodents came with em, and the ghouls said
 they'd be protecting us from now on. The ghouls left--probably back up to Gecko--but the rodents stayed put, and they've
 been here ever since. Like I said, it's pretty strange stuff.}
{159}{}{Very interesting. Do you think I could have one of those amulets?}
{160}{}{By all means. They gave us so many, and we don't know what the hell to do with em. Here, take one.}
{161}{}{Thanks a lot. Bye.}
{162}{}{No, but I've got some great news: I convinced the Vault City council not to touch your village.}
{163}{}{What? They're seriously going to just leave us alone? I don't understand... how did you that? I swear if you're bullshitting me...}
{164}{}{It's true--trust me. I was able to pull some strings and broker a deal, but the details don't matter. The important thing is that you and your people are safe now.}
{165}{}{Thank you from the bottom of my heart... em... By the way, I still don't know your name.}
{166}{}{My name is - }
{167}{}{Thank you, }
{168}{}{, but what about the money I gave you to buy the guns?}
{169}{}{You are always welcome here! Goodbye.}
{170}{}{I don't think you're gonna need explosives. At least not against Vault City. You see, I've convinced the Vault City council not to touch your village if you get rid of the rats.}
{171}{}{I'll do it. I have some questions before I go though.}
{172}{}{Nevermind. Bye.}
{173}{}{Not yet. I'll return when I have them.}
{174}{}{Thanks! See you around.}
#additions
{200}{}{It just so happens that I've already got what you need right here.}
{201}{}{As it turns out, I'm already have what you're looking for. I suppose I could give all these explosives to you, but are you sure this is the best way to go about this?}
{202}{}{I've got the guns you need, but honestly, I think there could be a better way to do this. There's a reasonable man on the council in Vault City, Senior Council Member McClure. I'm sure I could get him to convince the council to come to a peaceful solution.}
{203}{}{Honestly, I think there could be a better way to do this. There's a reasonable man on the council in Vault City, Senior Council Member McClure. I'm sure I could get him to convince the council to come to a peaceful solution.}

{205}{}{Ha! You really think any of those big shot council members give a damn about what happens to us? Don't be so naive my friend, those bastards in Vault City can't be trusted. }
{206}{}{Ok. I'll report back when I have some news.}

{210}{}{Trust me, we've considered the alternative, but the only thing these Vault City bastards will respond to is violence. Now, will you give us the weapons? I'll pay $2500 for em. No price can be set on freedom.}
{211}{}{You do?! Excellent. Here, I'll give you $2,500 for those explosives. It's all the money we have, but there's no price too high for freedom. You've done us a great service, and shall always be welcome here.}
{212}{}{Alright. Here are the grenades.}
{213}{}{No, I have decided not to. Goodbye.}
{214}{}{No price too high, eh? Well, I know how economics work. Increase in demand means an increase in prices.}
{217}{}{Listen, starting a war with Vault City isn't the answer. Sure, you'll give them reason to back off, but you won't be able to buy or make explosives forever and when you run out you're doomed. And if they get in close, you'll just all die. But if I can just get one member of the Vault City council to see reason, then I know we can reach a peaceful agreement.}
{218}{}{Hmm... Alright, I trust you have our best interests in mind. If you really think you can reason with one of their council members, then by all means, give it a shot. However, I think you should talk to Old Joe and see what he has to say. You can find him in or around the courtyard bar. Good luck. We're all counting on you.}

{220}{}{I shoulda known you'd be another heartless opportunist. It's people like you that we started this community to try and get away from. You know what? Forget it. We don't need the help of someone like you. Now I suggest you leave.}
{221}{}{I shoulda known you'd be another heartless opportunist. It's people like you that we started this community to try and get away from. [He sighs.] Fine, we'll throw in an extra five hundred, but that leaves us with nothing. Will you give us the explosives now?}
{222}{}{Sure, pleasure doing business with you. Bye.}
{223}{}{Actually, I think I can find a better deal elsewhere. Goodbye.}
{215}{}{[DONE]}
{216}{}{[ATTACK]}

{225}{}{Excellent. Here, I'll give you $2,500 for those explosives. It's all the money we have, but there's no price too high for freedom. You've done us a great service, and shall always be welcome here.}
{226}{}{Alright, take care then.}

{300}{}{Any news on our dilemma?}
{301}{}{Not yet. I'll report back when I find something.}
{302}{}{Good news: I've convinced the Vault City council not to touch your village.}

{310}{}{If you're willing to part with those explosives, we're willing to pay you $2500 for them.}
{311}{}{You've got yourself a deal. Here's the explosives.}
{312}{}{No deal. It's a dangerous world out there and I didn't get this much firepower by handing it out to anyone who asks. Goodbye.}

{400}{}{Thanks friend. Thanks to you we stand a chance!}
{401}{}{Welcome back. Thanks to you we were successful in pushing back the Vault City patrol. They won't be bothering us anymore.}

{500}{}{Don't bother me.}

{600}{}{What was the name of your contact in Vault City again?}
{601}{}{Old Joe. As the name implies, he's a real old fella. You'll either find him in the courtyard bar or wandering nearby.}
{602}{}{Alright, thanks.}
{603}{}{So, who exactly is he?}
{604}{}{Old Joe's a real character, is who he is. Claims to be over a hundred years old, but I dunno if I buy it. He claims all sorts of things. Even says he helped save the world once. The guy's full of stories--I reckon most of em are bullshit, but they sure are entertaining. He keeps an eye on things in Vault City for us, and he does a damn fine job considering he's old as dirt and nearly blind.}
{605}{}{Interesting. I must be going.}
{606}{}{He says he helped save the world? You know, I'm kind of on a world saving quest myself--at least a quest to save *my* world.}
{610}{}{Right. Good for you. Well, you keep at it then. Just don't forget about helping us.}
{611}{}{Oh I won't. See you later.}
{612}{}{I probably will, actually. I get so many quests it's hard to keep track. If it wasn't for this handy Pip-Boy, who knows where I'd be? See ya.}

#RP 1.3
{700}{}{Oh, right. Here you go. [Hand him $2,500.]}
{701}{}{Sorry, I had to spend it as part of the deal.}
{702}{}{Shit, I don't have enough to pay you back. I must've spent some without thinking about it. I'll get I get it back to you as soon as I can.}

{710}{}{Thanks. Here. [He hands you back $1,250.] Keep it. It's the least we could do to repay you.}

{720}{}{Oh, I see. Well, if it bought us our freedom, then it was worth every coin. Thanks again for all you've done for us.}

{730}{}{Tell you what--how 'bout you just pay us back half? Do you have $1,250?}
{731}{}{Sure, here. [You give him $1,250.]}
{732}{}{Sorry, I don't even have that much.}

{740}{}{Thank you, }
{741}{}{. We won't forget what you've done for us.}

{750}{}{I see . . . well, don't worry about it. The money isn't as important as our freedom. Thank you.}

{800}{}{Great! Can I ask you a question?}
{801}{}{I never would've agreed to that. How can I help you guys?}
{802}{}{All right, can I ask you about something else?}
{803}{}{I'll be back.}
{804}{}{I talked to councilman McClure. He is not the slightest bit interested in attacking you, but as long as the rats hang around, they will see you as a threat. But if there's no rats, he swears they won't bother you.}
{805}{}{The seargeant who was out to enslave you all was looking to line his pockets, that was never authorized. He only ever got backing from the council because of the rat attacks. So the rats are actually working against you.}
{806}{}{The  Vault City council only ever backed any action against you because of the rats. Whatever you do you'll run out of grenades eventually, or Vault City will find your supplier, or even attack you with all their might. You can't hope to match their resources.}
{807}{}{Well, that actually makes a whole lot of sense. If they're so busy, by the time they get around to us we could have a fortress here! Feel free to inform mister big shot councilor that we'll be getting rid of the rats. And one more thing...}
{808}{}{Yes?}
{809}{}{Ahhh, but that migh be a problem. The rats don't attack us, but they don't OBEY us either. We don't really know how those ghouls even trained them, and they never came around after the one time they brough the rats.}
{810}{}{Which ghouls?}
{811}{}{Heh, the problem with that is... As I allready told you when I gave you the amulet - those ghouls brought them here one day and left us with them. But we're not controlling them in any way. If we did there'd be a lot less rat shit around, I'll tell you that.}
{812}{}{I guess I'll go find who *is* controling them, then.}
{813}{}{I'll have to thing about this.}
{814}{}{Are you clear on the fact that you've only been sent here to help enslave us all?}
{813}{}{I'll have to double-check that.}
{815}{}{Ok, another question?}
{816}{}{Exactly! That's just the point, they don't! They don't want to take you as servants, either, they've got plenty of those. In fact, they don't care whatever you do with yourselves as long as there isn't a load of huge rats running around. They've got far bigger threats to deal than you, and if someone sent soldiers to get servants at any point they'd be furious. Epecially now that they know about you.}
{817}{}{I'll think about it.}

{818}{}{Did you manage to get it sorted out with the council?}
{819}{}{We're holding them off for now. But they just won't let us be!}