{100}{}{You see a middle-aged man in a white lab coat. He looks preoccupied.}
{101}{}{You see Dr. Troy.}
{102}{}{You see a middle-aged man in a white lab coat. He looks preoccupied.}
{103}{}{Let's see... we have three inoculation shots scheduled for tomorrow morning.}
{104}{}{I swear Gregory's a hypochondriac...}
{105}{}{Still need to give those new Servants their physicals.}
{106}{}{Phyllis, could you bring me the Proconsul's blood test, please?}
{107}{}{Odd... these results aren't consistent with low platelet levels.}
{108}{}{Maybe we can clone that spleen from those cells taken this afternoon.}
{109}{}{Need to introduce more vitamins into the dietary supplements...}
{110}{}{Hmmmmm.}
{111}{}{Phyllis, could you bring me a hardcopy of Helen's file please?}
{112}{}{To think I could have taken that job with LoveLine...}
{113}{}{Getting tired of making these lists for the First Citizen...}
{114}{}{Another request for a list of medical supplies? I just submitted one yesterday!}
{115}{}{A mutant! Guards!}
{116}{}{A ghoul! Guards!}
{117}{TROY1}{Hello, I'm Dr. Troy. How may I be of assistance?}
{118}{}{Me got ouchie}
{119}{}{Ass-is-tense?}
{120}{}{(Shamble off)}
{121}{}{I'm looking for the main computer. Can you tell me where it is?}
{122}{}{What is it you do here?}
{123}{}{Just passing through, thanks.}
{124}{TROY2}{You are? It's a pleasure to meet you. If you have the time, perhaps we could compare notes? It
 is not often that I get the chance to speak to another physician.}
{125}{}{Absolutely. I'd love to learn some of the medical techniques you Citizens use.}
{126}{}{Not right now. I had some other questions...}
{127}{}{Maybe later. I have to be going.}
{128}{TROY3}{Excellent! Well, first, let me take you on a tour. Over here, we have the monitoring systems...}
{129}{}{}
{130}{TROY4}{... and that is how we can clone cells to make replacement limbs. We have to be careful that the
 tissue cultures don't get contaminated, but... in any event, I think I've talked enough... hope it was
 informative.}
{131}{}{It certainly was. I had some other questions I wanted to ask you...}
{132}{}{Thanks for the tour, Doctor Troy. It's been very educational.}
{133}{TROY5}{The main computer? It's down on the third level. Just take the elevator down, walk straight
 until you hit the T-intersection, then make the first left. That'll take you right to the control room.}
{134}{}{What is it you do here?}
{135}{}{Thanks.}
{136}{TROY6}{I am Vault City's primary physician. I take care of all the Citizens within Vault City and do my
 best to keep everyone healthy.}
{137}{}{I'm looking for the main computer. Can you tell me where it is?}
{138}{}{I see. Maybe we'll talk later, then.}
{139}{TROY7}{Hold on a moment... I don't recall seeing you around before. Are you a Citizen?}
{140}{}{Yes. I just got my Citizenship papers only recently.}
{141}{}{Actually, I'm }
{142}{}{. I am the Captain of the Guard.}
{143}{}{Uh... sure. Sure I am.}
{144}{}{No, I'm not.}
{145}{}{A pleasure to meet you, }
{146}{}{. If you are ever in need of my services, you can find me here.}
{147}{}{Thanks. Goodbye.}
{148}{TROY9}{You're not a Vault City native, though, am I right? I'm certain I would remember someone like
 you. Where are you from?}
{149}{TROY10}{Hold on a moment... you're an Outsider, correct? Where are you from?}
{150}{}{From a small village to the west, Arroyo.}
{151}{}{Why do you want to know?}
{152}{}{None of your business, "doctor." Can I go now, or do you have more questions for me?}
{153}{}{I don't like to discuss my past.}
{154}{TROY11}{Arroyo? I don't believe I've heard of it. I'm sorry to pry. I was just looking for someone who
 had traveled beyond the walls of Vault City... most Citizens here have never left the City.}
{155}{}{Looking for someone? Why?}
{156}{}{That's *fascinating.* What's that got to do with me?}
{157}{TROY12}{I'm sorry to pry. I was just looking for someone who had traveled beyond the walls of Vault
 City... most Citizens here have never left the City.}
{158}{}{Looking for someone? Why?}
{159}{}{That's *fascinating.* What's that got to do with me?}
{160}{TROY13}{You must have gotten turned around in the city streets... head back to the corridor you entered
 from, then make a right. That'll take you back to the surface, all right?}
{161}{}{Thanks for the directions... sometimes I get so turned around, you know? I'll just head back up
 to the surface right now.}
{162}{}{I don't think I'm ready to go right now, "doctor." First, I'd like to see what you've got in
 stock.}
{163}{TROY14}{I've been looking for someone who might be able to perform a special errand for me.}
{164}{}{What is it?}
{165}{}{Not interested, thanks.}
{166}{TROY15}{Excellent! I'm glad you've reconsidered.}
{167}{TROY16}{It has come to my attention that there is a new drug in the wastes. It's called "Jet," I
 believe. I'm willing to pay a thousand dollars for a sample of this drug.}
{168}{}{Jet? I have a sample right here.}
{169}{}{I happen to have some Jet on me. It's yours for twelve hundred.}
{170}{}{I have some Jet on me... I'll part with it for fifteen hundred.}
{171}{}{So... you want me to smuggle some Jet into Vault City for you?}
{172}{}{What do you want me to do?}
{173}{}{Not interested, thanks.}
{174}{TROY17}{I'm sorry to hear that. Return if you change your mind... I'll gladly reimburse you for your
 trouble.}
{175}{}{I had some other questions for you...}
{176}{}{Reimburse? Uhhhh... I'd rather have cash, thanks. Goodbye.}
{177}{}{All right. Goodbye.}
{178}{TROY18}{Hmmmmm. Considering the fact you have it on you, that is more than a fair price. Very well. Here
 is your money... and thank you.}
{179}{}{I had something else I wanted to ask you...}
{180}{}{You know, I don't think you really want to inhale that... crap. Trust me.}
{181}{}{Need any help on how to use that? I mean, I've found to get the best rush, you need to close
 your nostrils, force all the air out of your lungs, then take a deep breath, inhale, and hold it for
 about a minute...}
{182}{}{Pleasure doing business with you, doctor. Be careful with that stuff.}
{183}{TROY19}{*Thank* you. You can leave now.}
{184}{}{I had something else I wanted to ask you first...}
{185}{}{You know, I don't think you really want to inhale that... crap. Trust me.}
{186}{}{Sorry, just trying to help. Later, Doctor.}
{187}{TROY20}{What are you talking about?}
{188}{}{Forget it. I had something else I wanted to ask you...}
{189}{}{Well, they make that stuff from brahmin shit.}
{190}{}{Those are brahmin shit fumes in that Jet canister. Gross, huh?}
{191}{}{Those are brahmin shit fumes in that Jet canister. Gross, huh? Hey, by the way... I've been
 looking for some endorphin blockers. Do you have any?}
{192}{}{Well, according to the boy genius here, they make that stuff from brahmin shit.}
{193}{}{Well, according to the boy genius here, those are brahmin shit fumes in that Jet canister.
 Gross, huh?}
{194}{}{Well, according to the boy genius here, those are brahmin shit fumes in that Jet canister.
 Gross, huh? Hey, by the way... we've been looking for some endorphin blockers. Do you have any?}
{195}{}{Uh... nevermind. Maybe it's better you don't know.}
{196}{TROY21}{I think you must be... mistaken.}
{197}{}{Well, it's pretty hard to swallow. I had some other questions...}
{198}{}{No, really. They grow Jet in brahmin shit... they use it as fertilizer.}
{199}{}{No, really. They were originally growing hallucinogens in brahmin shit, but then they discovered
 that the *fumes* were actually making the workers high. See, it turns out there's this contaminated
 pre-war protein extract in the brahmin systems...}
{200}{}{Probably so. I don't think I believe it myself. See you later, Doctor.}
{201}{TROY22}{Really? Hmmmmm. I suppose brahmin... excrement would make a good fertilizer. I hadn't considered
 that before. Thank you, friend. I was curious about the manufacturing process.}
{202}{}{Yeah, except they use brahmin shit to make the Jet, not excrement. See you, Doc.}
{203}{}{No problem. Be careful with that stuff, all right?}
{204}{}{Hey, aren't we all? See you later, Doctor.}
{205}{TROY23}{That's... fascinating. Hmmmmm. Perhaps I could take blood samples from the brahmin in the
 courtyard, then... thank you, my friend. Thank you very much, indeed. I was curious about the
 manufacturing process.}
{206}{}{No problem. Be careful with that stuff, all right?}
{207}{}{Hey, aren't we all? See you later, Doctor.}
{208}{TROY24}{Endorphin blockers? Whatever for?}
{209}{}{I think endorphin blockers could be used to neutralize Jet once it's in someone's system. I
 can't test it without some endorphin blockers, though.}
{210}{}{Never mind. I had something else I wanted to ask you...}
{211}{}{Nothing. I have to be going.}
{212}{TROY25}{We don't have endorphin blockers here, but I could program the Auto-Doc to manufacture some.
 Would you care to explain to me your theory?}
{213}{}{Well, you see Jet's chemical addiction is probably the hardest thing to shake, so I was thinking
 that if we introduced endorphin blockers into the body we could...}
{215}{TROY26}{I'm... speechless. That's simply the most brilliant solution I have ever heard. I've been
 experimenting with methods of curing Jet addiction for months, and came up with nothing.}
{216}{}{You've been working on an antidote, too?}
{217}{}{Yes, that's what I needed a Jet sample for.}
{218}{}{Yes... and unsuccessfully.}
{219}{}{This drug's stranglehold needs to be stopped before it can spread. Why... with the information
 you've provided, we could manufacture the antidote today! Hold on.}
{220}{}{Great! Thanks, Doctor.}
{221}{TROY29}{This young man here? He made Jet?}
{222}{}{I wouldn't say "man," but yes, he designed Jet. Or so he says.}
{223}{}{Yeah, you wouldn't think it to look at him.}
{224}{}{Myron, Dr. Troy... Dr. Troy, Myron.}
{225}{TROY30}{Then I have some questions for this young man...}
{226}{}{Uh, sure. You might want to take some aspirin before you start, though. I'll wait here.}
{227}{}{Be my guest.}
{228}{}{Go ahead. Call me if you need anything... like a baseball bat.}
{229}{TROY31}{Brahmin fumes? Not a conventional manufacturing process, but... hmmmmm. Perhaps I could take
 blood samples from the brahmin in the courtyard, then... thank you, my friend.}
{230}{}{No problem.}
{231}{}{Sure.}
{232}{TROY32}{You may also tell your little hooligan friend that he is wasting his considerable intellect
 manufacturing drugs. His manners and language also leave MUCH to be desired.}
{233}{}{Tell me about it.}
{234}{}{Maybe you should loosen up a little, Doc. A little drug use never hurt anyone. Well, except for
 those super stimpacks... and Buffout... and Psycho. Actually, never mind. I'll be going.}
{235}{}{I'll pass that along.}
{236}{TROY33}{Yes, I'm willing to pay you a thousand dollars for the sample... and your silence.}
{237}{}{I have a sample of Jet right here.}
{238}{}{What do you want the Jet for?}
{239}{}{Sounds good. I'm in.}
{240}{}{I'm not interested.}
{241}{TROY34}{It would be... helpful to me and my work if you could bring me a sample of this drug. I will pay
 you a thousand dollars for the delivery. But it is of utmost importance that you keep this transaction
 confidential.}
{242}{}{Uh... confidential?}
{243}{}{Oh really? How much are you going to pay me to keep silent? I could turn you in right now.}
{244}{}{I have a sample of Jet right here.}
{245}{}{What do you want the Jet for?}
{246}{}{No problem. You can count on me.}
{247}{}{I'm not interested.}
{248}{TROY35}{Uh, yes... confidential. As in, keep the matter between you and me. Tell no one.}
{249}{}{I have a sample of Jet right here.}
{250}{}{What do you want the Jet for?}
{251}{}{What's to keep me from turning you in right now?}
{252}{}{No problem. I'll keep it "confidential" and all that, uh, no talking stuff.}
{253}{}{I'm not interested.}
{254}{TROY36}{That is not your concern. Obtain a sample of Jet, bring it to me, and I will pay you a thousand
 dollars... and that price includes your silence.}
{255}{}{Well, I have a sample of Jet right here.}
{256}{}{What's to keep me from turning you in right now?}
{257}{}{No problem. You can count on me.}
{258}{}{I'm not interested.}
{259}{TROY37}{Wha --? You wouldn't! How *dare* you threaten me!}
{260}{}{Whoa! Calm down, I was just asking. No need to panic.}
{261}{}{I would, and I will. How much is your Citizenship worth to you? Life out in the wastes can be
 pretty rough on a person...}
{262}{TROY38}{I was a fool for trusting you! Very well... what is it you want?}
{263}{}{Five hundred on the first of every month, and we'll keep your drug smuggling between the two of
 us.}
{264}{}{A thousand on the first of every month, and you get to keep your Citizenship.}
{265}{}{Two thousand on the first of every month, and I'll keep quiet.}
{266}{TROY39}{Are you insane?! There's no way I can afford that!}
{267}{}{All right, all right. Make it five hundred, and we don't need to involve the First Citizen at all.}
{268}{}{You better FIND a way to afford it, or you'll be begging for scraps in the Courtyard like the
 rest of the Outworlders.}
{269}{TROY40}{Very well. Here is your first payment. I hope you choke on it.}
{270}{}{It's been a pleasure, Doctor. You'll be seeing me again real soon.}
{271}{}{You better watch your mouth, or you'll be the next patient in that Auto-Doc. Understand?}
{272}{TROY41}{This is NOT something to be joking about; this is a very serious matter. I will pay a thousand
 dollars for the Jet, your silence... and no more questions. Do you want the job?}
{273}{}{Well, what do you know? I have a sample of Jet right here.}
{274}{}{What's to keep me from turning you in right now?}
{275}{}{Sure, I'll do it.}
{276}{}{I'm not interested.}
{277}{}{You do?}
{278}{TROY43}{Excellent! Thank you, my friend... you have no idea how important this is to my work. Here is
 your payment, as promised.}
{279}{}{Great. Before I go, I had some other questions...}
{280}{}{You know, I don't think you really want to inhale that... crap. Trust me.}
{281}{}{No problem. Thanks, Doc.}
{282}{TROY44}{Hello, Captain. How may I be of assistance?}
{283}{TROY45}{Hello, Citizen. How may I be of assistance?}
{284}{TROY46}{How may I be of assistance?}
{285}{TROY47}{Yes?}
{286}{}{Me got ouchie}
{287}{}{Ass-is-tense?}
{288}{}{(Shamble off)}
{289}{}{I'm in need of your medical expertise.}
{290}{}{You mentioned before you were a doctor... I'm something of a doctor myself.}
{291}{}{Do you have any endorphin blockers?}
{292}{}{I got that Jet you wanted.}
{293}{}{I'm interested in that job, if it's still available.}
{294}{}{About that Jet you wanted... I think the other Citizens might like to know about it, too.}
{295}{}{Nothing today. Good day, Doctor.}
{296}{TROY48}{Certainly. I'm sorry... it's been some time since I actually had to administer them. Most
 Citizens received theirs many, many years ago. Let me prep the Auto-Doc for the procedure...}
{297}{}{All right.}
{298}{TROY49}{All finished. A word of caution: This vaccination doesn't make you immune to poison and
 radiation, but it does bolster your natural resistance.}
{299}{}{Much appreciated. Say, I had some other questions I wanted to ask you...}
{300}{}{Great. Thanks, Doctor.}
{301}{TROY50}{Oh, it's you. What do you want?}
{302}{}{I'm in need of healing.}
{303}{}{I've been poisoned.}
{304}{}{I've been irradiated.}
{305}{}{I've come to pick up my cash. You got it?}
{306}{}{I'm here to remind you that the first is coming up, and you better have my money.}
{307}{}{Nothing... today.}
{308}{TROY51}{I haven't forgotten. Here is your money. Now leave.}
{309}{}{Hold on... I want some healing, too.}
{310}{}{Hold on... I've been poisoned. I need you to cure it.}
{311}{}{Hold on... I've been irradiated. I need you to cure it.}
{312}{}{Pleasure doing business with you. See you soon, Doc.}
{313}{TROY52}{I haven't forgotten. You'll get your money. Now leave.}
{314}{}{Hold on... I want some healing, too.}
{315}{}{Hold on... I've been poisoned. I need you to cure it.}
{316}{}{Hold on... I've been irradiated. I need you to cure it.}
{317}{}{That's all I want to hear. See you soon, Doc.}
{318}{TROY53}{I see. First, I'll need to check your vital signs... lean back and we'll hook you up to the
 Auto-Doc here...}
{320}{TROY54}{Hmmmm. It seems that during the start-up procedure, an operator priority override has caused the
 Auto-Doc to accidentally inject you with Sodium Tri-Ethylene.}
{321}{}{What? What's that mean?}
{322}{TROY55}{It means you have less than ten seconds to live. Your stupidity is really quite staggering.
 Blackmail someone, then put your life in their hands? Simply amazing. Goodbye... and good riddance.}
{323}{}{Now I have to reload! This is so shitty! I'll get you during my next save game.}
{324}{}{What about the Hippocratic Oath?! Hey! I...}
{325}{}{I'll haunt you from the grave. I swear it.}
{326}{TROY56}{How did you get down here? I'm afraid you'll have to leave. Hold a moment while I summon some
 guards to escort you out.}
{327}{}{ME NO GOH!}
{328}{}{(Stand around for a moment)}
{329}{}{I have some good news. I was able to make an antidote from that sample of Jet you gave me.}
{330}{}{Good news... I was able to use the information you gave me to make an antidote.}
{331}{}{Once taken, it nullifies Jet's withdrawal symptoms and also... removes the euphoria associated
 with the drug.}
{332}{}{Great. Can I have some?}
{333}{}{Can I get a sample of it? I think it could help the people in Redding.}
{334}{TROY59}{Of course. Here you go. Take it to one of my colleagues, Dr. Johnson, in Redding. He should be
 able to see that it gets to those that need it.}
{335}{TROY60}{Of course - here you go. I understand that the Jet problem is especially prevalent in Redding.
 If you take the antidote to the physician there, Dr. Johnson, he should be able to see that it gets to
 those that need it.}
{336}{}{Great! I'll be sure to keep this safe. I had some questions for you...}
{337}{}{Thanks for the antidote.}
{338}{TROY61}{Excellent! Return here when you have obtained the Jet sample, and I will have your payment
 ready.}
{339}{}{Deal. I had some other questions...}
{340}{}{I'll be back with the Jet.}
{341}{TROY62}{Yes, I'm familiar with them. It's an invasive procedure, where impact plates and thermal
 dissipater membranes are grafted to the skeleton to help protect against physical trauma and heat. Why
 do you ask?}
{342}{TROY63}{Yes, you mentioned the implants before. I will not perform the operation, I'm sorry. The
 procedure is irreversible, and the implants do more harm than good.}
{343}{}{I ran across them in the Vault City medical database. Could you perform the operation on me?}
{344}{}{Could you perform the operation? I can't do it myself.}
{345}{}{All right. I had some other questions...}
{346}{}{Fine. Just checking.}
{347}{}{Fine. Maybe I can find somebody else to do the procedure.}
{348}{TROY64}{No, I'm sorry... as I said, the implants are an invasive procedure and the recovery period is
 long and arduous. Patients undergoing the operation in the past have also frequently developed skeletal
 deformities.}
{349}{}{I'm willing to risk it. Can you do it anyway?}
{350}{TROY65}{I would consider performing the operation only in the event of an emergency, not for the sake of
 convenience. The risk is too great, and the implants are not a substantial improvement over standard
 combat armor.}
{351}{}{Hmmm. Okay, I had some other questions...}
{352}{}{Well, thanks anyway.}
{353}{}{Well, thanks anyway. Maybe I can find somebody else to perform the operation.}
{354}{TROY66}{I'm sorry. The facilities are only for Citizens, and a list of all patients is kept in the
 database... [Lowers voice.] However, the stimpacks in the lower level supply lockers would not be missed
 if you put them to good use.}
{355}{}{Hmmm. Okay, I had some other questions...}
{356}{}{Thanks. I'll go look for them.}
{357}{TROY67}{Of course, Captain. Let me see what I can do for you and your friends.}
{358}{TROY68}{Of course, Captain. Let me see what I can do for you and your friend.}
{359}{TROY69}{I just need to check your vital signs first... lean back and we'll hook you up to the Auto-Doc
 here...}
{361}{TROY70}{My, your mutant friend had a great deal of bullets and shrapnel lodged in his body. It's a
 wonder he didn't have lead poisoning. I finally managed to get it all out. Here it all is.}
{362}{TROY71}{That should take care of the problem. Let me know if you need any other healing.}
{363}{}{I'm in need of healing, too.}
{364}{}{I could use some help... I've been irradiated.}
{365}{}{I've been poisoned. Can you help me?}
{366}{}{Thanks, Doctor. Say, do you know anything about dermal implants?}
{367}{}{Much appreciated, Doctor. Say, I had some other questions I wanted to ask you...}
{368}{}{I'll probably be back. Thanks, Doctor.}
{369}{TROY72}{Of course, Citizen. What seems to be the problem?}
{370}{TROY73}{Of course, Captain. What seems to be the problem?}
{371}{TROY74}{Of course. What seems to be the problem?}
{372}{}{I'm in need of healing.}
{373}{}{I've been irradiated.}
{374}{}{I've been poisoned.}
{375}{}{Can you heal my friend?}
{376}{}{Can you heal my friends?}
{377}{}{Do you know anything about dermal implants?}
{378}{}{Never mind. I had some other questions...}
{379}{}{Nothing. Thanks, Doctor.}
{380}{TROY75}{Very well. Just let me check your vital signs... lean back and we'll hook you up to the Auto-Doc
 here...}
{382}{TROY76}{That should fix you up nicely. How do you feel?}
{383}{}{Great. Say, can you heal my friend, too?}
{384}{}{Great. Say, can you heal my friends, too?}
{385}{}{Do you know anything about dermal implants?}
{386}{}{Much better, thanks. I had some other questions...}
{387}{}{Great. Thanks, Doctor.}
{388}{TROY75}{Very well. Just let me check your vital signs... lean back and we'll hook you up to the Auto-Doc
 here...}
{390}{TROY76}{That should fix you up nicely. How do you feel?}
{391}{}{Much better, thanks. Say, before I get poisoned or irradiated again, during that tour you gave
 me, you mentioned you had a vaccine that gave resistance to poison and radiation. Could I get that?}
{392}{}{Great. Say, can you heal my friend, too?}
{393}{}{Great. Say, can you heal my friends, too?}
{394}{}{Do you know anything about dermal implants?}
{395}{}{Much better. I had some questions for you...}
{396}{}{Great. Thanks, Doctor.}
{397}{}{Guards!}
{398}{}{Zzzzzzz.}
{399}{}{You explain to Dr. Troy about the manufacturing process of Jet.}


# phobos2077 crafting
{1001}{}{Actually, I am seeking knowledge about advanced drugs.}
{1010}{}{I really don't have time for teaching, you know. We have a large community here and a lot of patients to treat...}
{1011}{}{Maybe we can work something out? I'd consider this information extremely valuable.}
{1012}{}{Forget it, then.}
{1020}{}{In this case... I would need proper compensation for my trouble. I suppose $2000 would be enough...
 OR, maybe you can really help my clinic with some supplies. We can usually produce all we need, but a specific poison requires scorpion tails, and we have trouble obtaining those.
 If you could bring me at least 8 large tails, it would help us a lot.}
{1021}{}{Let's cut this to $1000.}
{1022}{}{Here is the money.}
{1023}{}{Here are your tails.}
{1024}{}{I changed my mind.}
{1030}{}{I do not barter, I'm a very busy man. And that is how much my time costs.}
{1031}{}{OK, fine, here is the money.}
{1040}{}{Good. Now let's get this over with... }
{1041}{}{[Doctor Troy explains some basics of pharmaceutics and then uploads several schematics to your pipboy.] Done. Good luck with that.}

##############################################
#BONUS LINES NEEDED FOR THE TALKING HEADS MOD#
##############################################
{7700}{TROY8}{A pleasure to meet you, Citizen. If you are ever in need of my services, you can find me here.}
{7701}{TROY27}{Yes, that's what I needed a Jet sample for. This drug's stranglehold needs to be stopped before it can spread. Why... with the information you've provided, we could manufacture the antidote today! Hold on.}
{7702}{TROY28}{Yes... and unsuccessfully. This drug's stranglehold needs to be stopped before it can spread. Why... with the information you've provided, we could manufacture the antidote today! Hold on.}
{7703}{TROY42}{You do? Excellent! Thank you, my friend... you have no idea how important this is to my work. Here is your payment, as promised.}
{7704}{TROY57}{I have some good news. I was able to make an antidote from that sample of Jet you gave me. Once taken, it nullifies Jet's withdrawal symptoms and also... removes the euphoria associated with the drug.}
{7705}{TROY58}{Good news... I was able to use the information you gave me to make an antidote. Once taken, it nullifies Jet's withdrawal symptoms and also... removes the euphoria associated with the drug.}


