{100}{}{You see Lydia.}
{101}{}{You see a brown-haired woman dressed in brown fatigues and metal armor. She looks like the bartender.}
{102}{}{You see Lydia.}
{103}{}{You see a brown-haired woman dressed in brown fatigues and metal armor. She looks like the bartender.}
{104}{}{Welcome! Care for a drink, Chosen One?}
{105}{}{Welcome, Chosen One! Please, take a seat in the bar.}
{106}{}{Please! Take a seat, rest for a while!}
{107}{}{It's the Chosen One! Everybody give it up for the HERO of Fallout 2!}
{108}{}{Good day, Captain.}
{109}{}{Vault City prevails, Captain.}
{110}{}{Good day, Citizen.}
{111}{}{Vault City prevails, Citizen.}
{112}{}{A mutant! Guards! Guards!}
{113}{}{A ghoul! Guards! Guards!}
{114}{}{We're closed. Come back in the morning.}
{115}{}{Sorry, last call was a while ago. Come back in the morning.}
{116}{}{We're closed. Once I finish making this list of our stock, I'll be closing up.}
{117}{}{Hey there, Chosen One! We were just talking about your adventure... can I get you anything to drink?}
{118}{}{Dwinkie-winkie me make stinkie}
{119}{}{Shamble off}
{120}{}{What's on tap?}
{121}{}{I was looking for some information.}
{122}{}{I have that shipment of alcohol you wanted.}
{123}{}{Nothing today, thanks.}
{124}{}{Uh... so I smell. Um, thanks again for saving the world and all.}
{125}{}{Stinkie-blinkie me make twinkie!}
{126}{}{Shamble off}
{127}{}{Look, maybe you saved the world and all, but a poet, you're not. Now cut it out.}
{128}{}{Flinkie-flinkie klinkie-klinkie!}
{129}{}{Shamble off}
{130}{}{Look, take these and get out of here, okay? They ought to keep your mouth busy for a while.}
{131}{}{Thankie wankie my stankie}
{132}{}{Shamble off}
{133}{}{Uh... what can I do for you, Captain?}
{134}{}{What can I do for you, Citizen?}
{135}{}{Yes? Can I help you?}
{136}{}{You? Yoo? Yew? Yewwwww. E-yewwww is sound otherz make when see me}
{137}{}{Shamble off}
{138}{}{What's on tap?}
{139}{}{I was looking for some information.}
{140}{}{I have that shipment of alcohol you wanted.}
{141}{}{Nothing today, thanks.}
{142}{}{That is perhaps the most fascinating thing I've ever heard. Hold on a second... I want the guards to hear it, too.}
{143}{}{Too? Tew. Tewwwww. Tewwww sexeee fur my clothez}
{144}{}{Shamble off}
{145}{}{We have synthetic beers and liquor... vodka-H, tequila derivatives W and W2. Oh, and water. And brahmin milk. Beer or liquor is ten bucks, water or milk's three bucks.}
{146}{}{Like...?}
{147}{}{Uh, do you have any real alcohol?}
{148}{}{I could go for some synthetic beer.}
{149}{}{Some synthetic vodka would really hit the spot.}
{150}{}{Some tequila W2 would be great.}
{151}{}{Some water'd be great.}
{152}{}{Brahmin's milk.}
{153}{}{Actually, I was looking for some information.}
{154}{}{I'll come back when I have more money.}
{155}{}{I think I'll pass, thanks.}
{156}{}{The brahmin milk's not on tap... well, not exactly. I'd have to go out and snag some really quick.}
{157}{}{That's fine. I don't mind waiting. I just feel like having a refreshing glass of milk. Mmmmm-mmm. That would really hit the spot.}
{158}{}{I think I'll try something else then.}
{159}{}{Never mind then. Say, I was looking for some information...}
{160}{}{Forget it. I'll come back some other time.}
{161}{}{There you go. Anything else?}
{162}{}{Uh, do you have any real alcohol?}
{163}{}{I could go for some synthetic beer.}
{164}{}{Some synthetic vodka would really hit the spot.}
{165}{}{Some tequila W2 would be great.}
{166}{}{Some water would be great.}
{167}{}{Brahmin's milk.}
{168}{}{Actually, I was looking for some information.}
{169}{}{I'll come back when I have more money.}
{170}{}{I think I'll pass, thanks.}
{171}{}{Oh? Like what?}
{172}{}{Who's in charge of Vault City?}
{173}{}{Where's the Vault?}
{174}{}{Can you tell me about the slavery in Vault City?}
{175}{}{Does Vault City have much contact with the outside world?}
{176}{}{What have you got on tap?}
{177}{}{I have that shipment of alcohol you wanted.}
{178}{}{All right then. Good day.}
{179}{}{Uh, First Citizen Lynette... you are a Citizen, aren't you?}
{180}{}{First Citizen Lynette. She's in the council building up north if you need to talk to her.}
{181}{}{I wanted to know something else...}
{182}{}{All right. I'll go speak to her, then.}
{183}{}{Uh, it's the big hole in the side of the mountain to the east of here... say, you are a Citizen, aren't you?}
{184}{}{It's that big hole in the mountain to the east of here. You can't miss it. You also can't get inside unless you're a Citizen, though.}
{185}{}{I wanted to know something else...}
{186}{}{But I am a Citizen.}
{187}{}{Yeah, just getting my bearings, thanks. I'll go check it out.}
{188}{}{Hmmm. Thanks for the information.}
{189}{}{Sure you are. I'd just be careful who you say that to, "Citizen." Somebody's gonna recognize whatever stolen papers you bought from that bloodsucker Skeev. So keep your head down, all right?}
{190}{}{Uh, okay. Say, I wanted to know something else...}
{191}{}{Oh. Well, thanks for the advice.}
{192}{}{Look, first thing I have to say is that you better not call it "slavery" around here or you're going to get yourself in a whole mess of trouble. They're called "servants," not slaves. Just a word of advice.}
{193}{}{Point taken. Say, I wanted to know something else...}
{194}{}{Thanks. I'll keep that in mind.}
{195}{}{Not much. Most contact we have with Outsiders is merchants travelling the Big Circle caravan trail from Broken Hills, New Reno, and Redding. Only other place outside the caravan trail that I know of is Gecko.}
{196}{}{Tell me about Broken Hills.}
{197}{}{Tell me about New Reno.}
{198}{}{Tell me about Redding.}
{199}{}{Tell me about Gecko.}
{200}{}{I wanted to know something else...}
{201}{}{Thanks for the information.}
{202}{}{It's a mining community like Redding, except it's located to the far South. We get many of our uranium shipments from there.}
{203}{}{Tell me about New Reno.}
{204}{}{Tell me about Redding.}
{205}{}{Tell me about Gecko.}
{206}{}{I wanted to know something else...}
{207}{}{Thanks for the information.}
{208}{}{It's a ways to the southwest. I hear conflicting reports about Reno. Some merchants, especially the slavers, really love it there. Other merchants... don't. City with a lot of glitter... and a lot of trouble, I hear.}
{209}{}{Tell me about Broken Hills.}
{210}{}{Tell me about Redding.}
{211}{}{Tell me about Gecko.}
{212}{}{I wanted to know something else...}
{213}{}{Thanks for the information.}
{214}{}{It's a mining town far to the west. We haven't seen too many caravans from them recently, and it's got some of the high-ups a little worried. Senior Councilman McClure especially.}
{215}{}{Tell me about Broken Hills.}
{216}{}{Tell me about New Reno.}
{217}{}{Tell me about Gecko.}
{218}{}{I wanted to know something else...}
{219}{}{Thanks for the information.}
{220}{}{A town of ghouls less than a day's travel to the northeast, as I understand it. Rumor is they prey on any travelers that enter their territory. Best stay away.}
{221}{}{Tell me about Broken Hills.}
{222}{}{Tell me about New Reno.}
{223}{}{Tell me about Redding.}
{224}{}{I wanted to know something else...}
{225}{}{Thanks for the information.}
{226}{}{Why? You looking for something with some more kick than these synthetic drinks?}
{227}{}{Perhaps. Drinking synthetic alcohol can't really compare to the real thing.}
{228}{}{Not really. I was looking for some information instead...}
{229}{}{Not today.}
{230}{}{That's for sure. I used to have a... well, I used to know this merchant who had a bottle of Maddog 30/30. Bitter stuff... couldn't feel my tongue afterwards, but it was refreshingly different.}
{231}{}{What happened to this "merchant's" stash?}
{232}{}{I was looking for some information.}
{233}{}{I see. Well, it was good talking to you.}
{234}{}{It got drunk. Or so I heard. There were a few other "friends" here in Vault City who helped this merchant friend drink the stash. They were willing to pay a good price to have the real stuff for a change.}
{235}{}{I'll bet. You know, I could probably get some more of the real stuff, easy. I've been traveling the wastes a lot, and getting a hold of alcohol is no big deal.}
{236}{}{I was looking for some information.}
{237}{}{I see. Well, it was good talking to you.}
{238}{}{Is that so? Well, if you happened to be looking to relieve yourself of some real alcohol, then I could make it worth your while. If you could keep quiet about our deal. And get the contraband past the gate.}
{239}{}{How much real alcohol would you need?}
{240}{}{Say, a case of ten bottles of premium alcohol, and ten bottles of beer. And none of that radioactive stuff I hear comes out of Gecko. Just good old "booze," all right?}
{241}{}{I happen to have just that amount right here.}
{242}{}{I might be able to get you some. Say, I was looking for some information...}
{243}{}{Hmmmm. I'll think about it and get back to you.}
{244}{}{Excellent! Here's something for you... that amount's double the price the cases are worth. And this transaction never happened, all right?}
{245}{}{No problem. Hey, I was looking for some information...}
{246}{}{Thanks. Pleasure doing business with you.}
{247}{}{No, those wasteland concoctions they call alcohol are illegal here in Vault City. I don't even want to know how they brew them. Now did you want something to drink, Captain...?}
{248}{}{Nothing wrong with a little real alcohol now and then. Sure, your perception suffers, but it can when you have too much healing powder, too.}
{249}{}{I'll just have something else, then.}
{250}{}{Nevermind then. I was looking for some information...}
{251}{}{I see. Thanks anyway.}
{252}{}{I wouldn't know anything about that. I only serve synthetic alcohol here. If any real alcohol were to enter Vault City, I wouldn't know anything about it.}
{253}{}{Never mind then. I was looking for some information...}
{254}{}{I see. Thanks anyway.}
{255}{}{I... see. Well, uh, take care now. Okay?}
{256}{}{Thankie wankie my stankie}
{257}{}{Shamble off}
{258}{}{Zzzzzzzz.}

# by Lujo - flow fixes
{259}{}{That's for sure. I used to have a... well, I used to know this merchant who'd smuggle in some incredible wine. Problem was, it was so good that word got out and he got thrown out for good. Never happened with any regular booze that managed to find it's way in, though.}
{260}{}{Where in the world did he find any kind of wine, let alone the good stuff?}
{261}{}{I have no idea. The guy was strange, he'd sit there for hours an read books. But his wine got me in trouble so I haven't been able to sneak in any plain old booze and my stash dried up. I've got friends who'd pay quite nicely for some real stuff.}