{100}{}{You see a short, jovial man.}
{101}{}{You see Happy Harry, the store owner.}
{102}{}{Well, hello there... what can I do for you?}
{103}{}{I'm looking to trade. Can I see what you have in stock?}
{104}{}{You still selling that plow out there?}
{105}{}{Me Buy}
{106}{}{Nothing today, thanks.}
{107}{}{Sorry. Can't help you, neighbor.}
{108}{}{Why, yes I am. I'll let it go for... say, eight hundred.}
{109}{}{I'll give you six hundred for it.}
{110}{}{It's a deal. I'll take it.}
{111}{}{Eh, eight hundred? I'll be back... with the money.}
{112}{}{Forget it. The Smiths can starve.}
{113}{}{It's yours. [Pockets the money.] You just going to take it, or do you need it
 delivered somewhere?}
{114}{}{Drop it off with the Smiths.}
{115}{}{Sorry, friend. It's going to cost you eight hundred.}
{119}{}{You need the money to pay me, friend.}
{120}{}{I'll be back with the money.}
{121}{}{Not a problem. I'll have it dropped off right now.}
{122}{}{Thought you'd just help yourself, huh? Damn thief... guards! Guards!}

{123}{}{Dave sent me. We're trying to fix a broken water pump, and he said you'd have a replacement motor.}
{124}{}{Working with Dave, eh? Yeah, I know the fella. I see he's still got a knack for getting others to do his leg work--lazy bastard.
 [He chuckles.] Anyway, I think I got what you're lookin for, but lemme just go back an' check. [Harry goes into his back room where you
 hear boxes being shuffled and moved around. He returns a minute later.] Yep, got it right here. $500 and she's all yours.}
{125}{}{Sure. Here's the money.}
{126}{}{500? Damn. I hope I get reimbursed for this. Fine, here is the money.}
{127}{}{Thanks for the business. Take care.}
{128}{}{Bye.}
{1288}{}{Looks like I don't have enough money. Bye.}

{129}{}{Connar sent me for the goods.}
{130}{}{[Harry's eyes dart around quickly, he seems a bit nervous] Yes, sure. Just a moment...}
{131}{}{[Harry brings you the explosives.] Here, take em. That'll be four thousand, and let's make this snappy.}
{132}{}{Of course, here's the money.}
{133}{}{But Connar only gave me two and a half grand!}
{134}{}{But Connar only gave me one grand.}
{135}{}{Not my problem. Look, my business struggles enough as it is. If anyone finds out I'm providing Connar with explosives, then things will turn real ugly, real fast. Besides, I'm giving him a discount already.}
{136}{}{Look, I'm putting my neck on the line . . . Oh, to hell with it, I don't have time to argue. Just take em. [He quickly pockets your money.] Now get outta here. And remember, you didn't buy those from me.}
{137}{}{Excellent. But remember, you didn't buy these explosives here.}
{138}{}{It's a deal. Bye.}
{139}{}{[MORE]}
{140}{}{Well then, wait a bit until I get the money.}
{141}{}{Well, have you brought the money?}
{142}{}{What if I just give you twenty five hundred?}
{143}{}{How about a thousand?}
{144}{}{Ehmmm... four grand?! I don't have that much money; wait a bit until I get it.}
{145}{}{Damn! Who could possibly have turned me in?!}
{146}{}{Hey! What was I imprisoned for?}
{147}{}{Well, at least the food's not bad.}
{148}{}{What are you staring at?}
{149}{}{What will happen to my shop now?}

#added in RP 1.3
{200}{}{$500? Hey, maybe you could give me some kind of discount, I mean, you and Dave are friends, right?}
{201}{}{To tell you the truth, I never really cared for the fella. $500 for the motor. Take it or leave it.}
{202}{}{Fine. Here's the money.}
{203}{}{Forget it, I'm outta here.}
{204}{}{$500!? Forget this, I'm outta here.}
