{100}{}{You see Chief Librarian Kohl.}
{101}{}{You see a gentle-looking man in a Vault City uniform.}
{102}{}{You see Chief Librarian Kohl.}
{103}{}{You see a gentle-looking man in a Vault City uniform.}
{104}{}{I shall make certain that your heroic feats are recorded in the Vault City archives, }
{105}{}{My word! An intruder! Help! Guards!}
{106}{}{My word! A mutant in Vault City! Guards! Guards!}
{107}{}{My word! A ghoul in Vault City! Guards! Guards!}
{108}{}{The Information Office is closed for the evening. Come back in the morning.}
{109}{}{The Information Office is closed for the evening. I'll be heading home after I tabulate all these lists.}
{110}{}{Shhhhh.}
{111}{}{Tread quietly, please.}
{112}{}{Shhhhh.}
{113}{}{Silence IS a virtue.}
{114}{}{Oh... hello! Was there something I could help you with?}
{115}{}{Frazz-urb-luuw!}
{116}{}{Shamble off}
{117}{}{What is this place?}
{118}{}{Nothing. Sorry to disturb you.}
{119}{}{Uh... pardon me?}
{120}{}{Cripple-cripple creep}
{121}{}{Shamble off}
{122}{}{Oh my, you must be one of the Servants. You should REALLY head back to Master Barkus at once, or he'll be quite irate!}
{123}{}{Okee!}
{124}{}{This is the Information Center for Vault City. Is this the place you were looking for?}
{125}{}{Yes, actually. I had some questions maybe you can answer.}
{126}{}{Information Center? Do you have any books or manuals?}
{127}{}{Not really. Sorry to disturb you.}
{128}{}{Unfortunately, our books are currently being transcribed into electronic format. The extras are being shipped to the
 Amenities Offices down the street. You might try there.}
{129}{}{Where are these electronically-formatted books stored?}
{130}{}{All the books are gone?}
{131}{}{Oh. I have a few questions...}
{132}{}{Maybe I'll check there, then.}
{133}{}{Hello, again. Did you need help finding anything?}
{134}{}{Certainly. What questions did you have?}
{135}{}{What is this place?}
{136}{}{Do you know where I can find a GECK?}
{137}{}{Do you know where I could find the Vault?}
{138}{}{Nothing today, thanks.}
{139}{}{A GECK? That name sounds familiar. What does it do?}
{140}{}{You know, I don't know myself. To hear the Elder of my village tell it, it's supposed to be some panacea for my village.
 I'm a little more skeptical.}
{141}{}{I don't really know.}
{142}{}{Can I ask you some other questions?}
{143}{}{Never mind. Maybe we'll talk some other time.}
{144}{}{The Vault? Why, the entrance is just down the street... it's the large hole in the side of the mountain.}
{145}{}{Do you know of any other Vaults?}
{146}{}{Can I ask you some other questions?}
{147}{}{Thanks for the directions.}
{148}{}{Other Vaults? Hmmm. No, not really. I know other Vaults were built, but we have never come across any of them.
 There may be some mention of them in the Central Computer in the Vault.}
{149}{}{How can I get down to the Vault?}
{150}{}{Can I ask you some other questions?}
{151}{}{Thanks for the information.}
{152}{}{Hmmmm. Well, you know, the Central Computer down in the Vault might have some information about it. We keep most
 of the older archives down there.}
{153}{}{How can I get down to the Vault?}
{154}{}{Can I ask you some other questions?}
{155}{}{Thanks for the information.}
{156}{}{Well, you are a Citizen of the community, aren't you? You are permitted to walk down there.}
{157}{}{Oh you are? Pardon me, pardon me... well, then, you are permitted to simply walk down there and use the computer.}
{158}{}{Well, you'd need to be a Citizen of Vault City first. If you want, you could take the Citizenship test... or better yet,
 speak to First Citizen Lynette. I'm sure she might make an exception in your case.}
{159}{}{Uh, but I am a Citizen.}
{160}{}{Can I ask you some other questions?}
{161}{}{Thanks for the information.}
{162}{}{Yes, well, everything is being transcribed because... hmmm. This is a somewhat delicate matter, but I believe my post here
 in Vault City has become obsolete.}
{163}{}{Ob-so-lete? What do you mean?}
{164}{}{Obsolete?}
{165}{}{Oh. I had some other questions...}
{166}{}{Sorry to hear it. I have to go.}
{167}{}{It means my post here is no longer necessary. It's all for the best.}
{168}{}{They are discussing putting information terminals in every household. These new terminals would all be tied to the List
 Server and the Information Archives. Once that is done, the information center... and I... will be unnecessary. It's all for the
 best, really.}
{169}{}{Are you sure?}
{170}{}{Oh. I had some other questions...}
{171}{}{Sorry to hear it. I have to go.}
{172}{}{Oh my, yes. The First Citizen is rarely wrong in such matters. Still, I will be sorry to leave this place. I heard they have a position waiting for me in the List Office.}
{173}{}{Oh. Well, I'm sorry to hear that all the books were transcribed. I'd much rather read a book than stare at a computer screen.}
{174}{}{Oh. Well, I'm sorry to hear that all the books were transcribed. I'd much rather read a book than stare at a computer screen.}
{175}{}{Oh. I had some other questions...}
{176}{}{Sorry to hear it. I have to go.}
{177}{}{That's how I feel as well! I have nothing against electronic format mind you, but there is a certain... solidity... in having a book in your hands and turning the pages one by one. Hmmm. You know...}
{178}{}{Yes?}
{179}{}{Oh. I had some other questions...}
{180}{}{Sorry to hear it. I have to go.}
{181}{}{They haven't shipped all the books out to the Amenities Offices yet. I know Randal won't miss them if I gave them to someone who appreciated them... someone like yourself.}
{182}{}{I'd love to have them. Thanks.}
{183}{}{I'll go fetch them...}
{184}{}{All right.}
{185}{}{Here you go. I hope you enjoy reading them. They are some of my favorites... a little on the technical side, but still quite good.}
{186}{}{Thanks. Do you mind if I ask you some other questions?}
{187}{}{Great. I'll go check these out.}
{188}{}{The books are being entered into one of the library terminals on the third level of the Vault.
 I don't recall which one... it's not one of the ones in the central core, though.}
{189}{}{Why is everything being transcribed?}
{190}{}{How can I get down to the Vault?}
{191}{}{I see. Do you mind if I ask you some other questions?}
{192}{}{Maybe I'll go see if I can find it.}
{193}{}{! Well done! Bravo!}

# by Lujo - flow fixes
{194}{}{Oh, I will for sure! I whish there were more people who did, too.}
{195}{}{I certainly share the sentiment! It's been a while since I've seen someone who's the least bit interested. I used to know a trader shared the passion though...}
{196}{}{Really? Used to?}
{197}{}{Well, it's nice to know there's more of us. Mind if I ask you about something else?}
{198}{}{Well, I hope there's more of us out there. Thank you very much and goodbye!}
{199}{}{Yes, he'd come around to the courtyard to trade alcoholic beverages, but he'd come in to buy books from me. I wouldn't even charge him, but he insisted. He said his people back home loved them.}
{200}{}{Wow, that's a very comforting thought! Where was his home?}
{201}{}{Why doesn't he come around anymore?}
{202}{}{He said it was a place they call the Abbey, a bit north of here. He even showed me exactly where, it's right... here. I'd love to see it, but the sight of the courtyard is enough to make me panic.}
{203}{}{Well, I suppose he might have tried selling alcoholic beverages inside the city. It is illegal, you know.}
{204}{}{Ah, most unfortunate. Well, thank you for the information. Mind if I ask you something else?}
{205}{}{Ah, pushed his luck. Where did he say he was from?}