{100}{}{You see Val. Or Valerie. Or whatever.}
{101}{}{You see a brown-haired woman dressed in brown fatigues and metal armor. She looks like a mechanic.}
{102}{}{You see Val. Or Valerie. Or whatever.}
{103}{}{You see a brown-haired woman dressed in brown fatigues and metal armor. She looks like a mechanic.}
{104}{}{Oh, hello, "Dad."}
{105}{}{1 Second}
{106}{}{Valerie. Good to see you again.}
{107}{}{Oh, uh, hi, Dad. It's good to see you. Really.}
{108}{}{1 Second}
{109}{}{Hello, Valerie. It's good to see you, too.}
{110}{}{You better get that mutant out of here before the guards see it.}
{111}{}{You better get that ghoul out of here before the guards see it.}
{112}{}{Stupid metal bore's acting up again...}
{113}{}{That metal lathe needs to be oiled again...}
{114}{}{Need to make a list of those surplus parts for the First Citizen.}
{115}{}{Work, you stupid piece of junk!}
{116}{}{I'm surrounded by idiots...}
{117}{}{If I just had the right tools!}
{118}{}{I'm going to kill that bald-headed monkey in the Purchasing Office...}
{119}{}{It's late. Come back in the morning.}
{120}{}{Shop's closed. After I finish this list for the First Citizen, I'm heading home.}
{121}{}{I'm busy. Come back in a day or so, and I should be finished.}
{122}{}{I have a whole backlog of stuff that needs fixing. Come back in a day or two.}
{123}{}{Well, if it isn't my Dad's "boss."}
{124}{}{Yes?!}
{125}{}{Did you WANT something, or are you just going to stand there gawking like a moron?}
{126}{}{Mooo-ron}
{127}{}{Shamble off}
{128}{}{Whoa, easy. I was just stopping in to see what this place is.}
{129}{}{Watch it. I'm not in the mood for any bullshit today.}
{130}{}{I was looking for the Vault. Can you tell me where it is?}
{131}{}{Actually, I was just leaving.}
{132}{}{It's that big hole in the mountain to the east, past those two heavily-armed guards. Anything else you want to ask or can I get back to work?}
{133}{}{What is this place?}
{134}{}{Watch it. I'm not in the mood for any bullshit today.}
{135}{}{Thanks for the directions. Goodbye.}
{136}{}{As if Vault City didn't have enough human brahmin... look, you CANT BE IN HERE, OKAY? You could HURT yourself! NOW GET OUT! GO!}
{137}{}{*Snfff* You big meenie... *snff*... me go sumplace n' have partee wiff clowns... *snfff*... and ice creem... and kake... and me no invit smart meen peuple like YOU!}
{138}{}{Shamble off}
{139}{}{Get out of here. Or I'm going to summon the guards to MAKE you get out.}
{140}{}{Try it. I'll like it.}
{141}{}{All right, I'm leaving.}
{142}{}{It's the maintenance shed for Vault City. Or did you just HAPPEN to miss the huge sign on
 the side of the building?}
{143}{}{No, sorry. I thought this might be a shop of some sort.}
{144}{}{Forget it. Sorry to disturb you.}
{145}{}{You've got the "of some sort" right, anyway. Look, did you need something repaired or did you just want to ask me a bunch of dumb questions?}
{146}{}{What do you repair here?}
{147}{}{Watch it. I'm not in the mood for any bullshit today.}
{148}{}{Just dumb questions today, actually. Talk to you later.}
{149}{}{Synthetic alcohol dispensers, radios, firearms, laser turret parts, computer monitors, you name it... when I can get the tools to do my job.}
{150}{}{Tools?}
{151}{}{Sounds like a tough job. I'll leave you to it.}
{152}{}{Right now, I've got the metal lathe barely working, and my wrench has gone missing... AGAIN... and my pliers' teeth are stripped.}
{153}{}{Anything I could help with?}
{154}{}{What's the problem with getting more tools?}
{155}{}{All right then. Good day.}
{156}{}{You? I doubt it.}
{157}{}{Well, I have a wrench and a pair of pliers right here.}
{158}{}{Would getting you a new wrench and a set of pliers help you out?}
{159}{}{What's the problem with getting more tools?}
{160}{}{Just thought I would offer to help. Nevermind then.}
{161}{}{The PROBLEM is, I can't just go out and buy some new ones, I have to requisition them from Vault City. That means filling out five billion lists, submitting them in triplicate, then WAITING.}
{162}{}{So why d --?}
{163}{}{Sorry to h --}
{164}{}{Hell, I ordered a Super Snap-Off Tool Kit MONTHS ago, but just like always, it won't show until I don't need it anymore. It's a wonder things ever get done around here...}
{165}{}{Maybe I could help you.}
{166}{}{Oh. Well, sorry to hear it. I may be back.}
{167}{}{Yes. Why?}
{168}{}{Well, I have a wrench and a pair of pliers right here.}
{169}{}{Maybe I could go find some and bring them back to you.}
{170}{}{What's the problem with getting more tools?}
{171}{}{Oh. Well, thanks for the advice.}
{172}{}{I won't hold my breath, but if you want to, go ahead. It's your time, not mine. I might be able to scrape together a little to pay you for your trouble.}
{173}{}{If I find a wrench and a pair of pliers, I'll bring them by.}
{174}{}{You do?}
{175}{}{Yeah. Here you go.}
{176}{}{Uh... thanks. I mean, they're not great, but they'll do. Where did you... oh, never mind. It's not important. Here's a few bucks for your trouble.}
{177}{}{Thanks. Say, I had some questions...}
{178}{}{Maybe you can use those tools to help fix that attitude of yours.}
{179}{}{No problem. Glad to help.}
{180}{}{Yeah, yeah... look, I have some work to do. Come back in a day or two, all right? I'll have
 time to chat then.}
{181}{}{See you tomorrow, then.}
{182}{}{Uh, all right. I'll be back in a day or two. Goodbye.}
{183}{}{You won't believe this. Not less than a DAY after you gave me those tools, that Super Tool Kit I ordered arrives. But not just one. They send me FIVE. What the hell is wrong with the ordering office?!}
{184}{}{Could you part with one of those tool kits?}
{185}{}{Why not?! What am I going to do with FIVE?! Take it! I swear that I'm going to beat the living tar out of the List Office for this.}
{186}{}{Thanks. Say, I had some questions...}
{187}{}{Appreciate it. I'll put this kit to good use.}
{188}{}{Oh, I see how it is. Well, what is it you want?}
{189}{}{What? I haven't got time to chat all day.}
{190}{}{Yeah? What?}
{191}{}{Can you repair anything of mine?}
{192}{}{What have you got in stock?}
{193}{}{What's the deal with you and your father?}
{194}{}{Never mind. I'll leave you to your work.}
{195}{}{Nothing worth mentioning. He came here twenty years ago on one of his caravan trips, knocked up Mom and left. Until he stopped by, I hadn't seen him in about five years. No loss.}
{196}{}{Sounds like you and him have some things to work out.}
{197}{}{Oh. Well, uh, I had some other questions...}
{198}{}{Never mind. I'll leave you to your work.}
{199}{}{No, we don't. We've said all we need to say a long time ago. }
{200}{}{Are you sure?}
{201}{}{All right then. I had some other questions...}
{202}{}{I'll leave you to your work then.}
{203}{}{Yes, I'm SURE. Well... except for the fact that I think he should lose some weight. He's got quite a spare tire going. And he should stop wandering all around the wastes selling junk to tribals. That's pretty much it.}
{204}{}{Look, he was in a mess of trouble with slavers, and he's trying to make up for lost time now. But you're right, he could stand to lose some weight.}
{205}{}{Oh, uh, okay. I had some other questions...}
{206}{}{Never mind. I'll leave you to your work.}
{207}{}{Heh-heh. You've got a sarcastic edge. I like that. As for ol' "Dad"... well... hmmm. I'll try and be a little more civil. For a while, anyway.}
{208}{}{Um... make sure he stays out of trouble, all right?}
{209}{}{Great. Look, I had something else I wanted to ask you...}
{210}{}{I'll do my best. I had something else I wanted to ask you...}
{211}{}{That's all I ask. I'll leave you to your work.}
{212}{}{I'll try. He seems to find it wherever we go. See you, Valerie.}
{213}{}{Look, I don't have anything in "stock." This isn't a store. Most of the stuff I fix here ends up in the Amenities Office... it's out the door and to your left.}
{214}{}{Like I said BEFORE, this isn't a store. Go to the Amenities Office if you want a gun. Come here if you want something repaired.}
{215}{}{Oh. Well, can you repair anything of mine instead?}
{216}{}{Can you repair anything of mine?}
{217}{}{All right, all right. Goodbye.}
{218}{}{Well... maybe. Let's see what you got.}
{219}{}{Show her your pistols.}
{220}{}{Show her your rifles.}
{221}{}{Show her your general inventory.}
{222}{}{Never mind. I wanted to know something else...}
{223}{}{Maybe some other time.}
{224}{}{I could put a speed loader on that magnum of yours for $800.}
{225}{}{Hmmmm. That Desert Eagle you have... I could give it an expanded magazine, if you want. That'll cost $1000.}
{226}{}{Upgrade the magnum.}
{227}{}{How about $650 for the magnum upgrade instead?}
{228}{}{Upgrade the Desert Eagle.}
{229}{}{How about $850 for the Desert Eagle?}
{230}{}{Forget the pistols. Can you upgrade any of my other weapons?}
{231}{}{I wanted to know something else...}
{232}{}{I'll be back when I have some more cash.}
{233}{}{Hmmm. Maybe some other time.}
{234}{}{That assault rifle you got there... I can give it an expanded magazine for $1500.}
{235}{}{Hmmmm. I've got a low-light scope I can put on that FN FAL you got for $3500.}
{236}{}{Expand the magazine of the AK-112 assault rifle.}
{237}{}{How about $1350 for upgrading the assault rifle?}
{238}{}{Attach that low-light scope on the FN FAL.}
{239}{}{How about $3100 for the low-light scope?}
{240}{}{Could you upgrade one of my other weapons?}
{241}{}{Never mind. I wanted something else...}
{242}{}{Actually, none of them. I have to go.}
{243}{}{I'll be back when I have more cash to spare.}
{244}{}{I suppose I could juice up that cattleprod for you. It'll cost you $750.}
{245}{}{All right. }
{246}{}{How about $650 instead?}
{247}{}{Actually, could you upgrade one of my other weapons instead?}
{248}{}{Nevermind. I wanted something else...}
{249}{}{Actually, none of them. I have to go.}
{250}{}{Too rich for my blood. I'll be back when I have more cash.}
{251}{}{I see you've picked up some tricks from my cheapskate father. Give me about an hour, and it'll be good to go...}
{252}{}{All right, all right. You sound just like my cheapskate Dad. Give me about an hour, and it'll be good to go...}
{253}{}{All right, give me about an hour, and it'll be good to go...}
{254}{}{All right.}
{255}{}{There you go. Anything else?}
{256}{}{I had some other questions...}
{257}{}{Can you upgrade anything else I have?}
{258}{}{Nothing more, today. Thanks.}
{259}{}{What do you... uh... Dad?}
{260}{}{I'm sorry?}
{261}{}{Uh, no, I'm not. I mean, I don't think so.}
{262}{}{Dad?!}
{263}{}{2 Seconds}
{264}{}{Valerie?! Honey, is that you?}
{265}{}{2 Seconds}
{266}{}{Where the hell have you been?! Still running around the wastes, selling shiny junk to tribals?}
{267}{}{4 Seconds}
{268}{}{Uh, heh-heh... ignore her, Boss, she doesn't know what she's saying... Val, honey... you see, there were slavers and...}
{269}{}{4 Seconds}
{270}{}{Cut the crap, Dad. Are you STILL calling everybody you meet "Boss?" I always hated that about you.}
{271}{}{4 Seconds}
{272}{}{Valerie, honey, please... let me explain... you see...}
{273}{}{2 Seconds, then Fade Out}
{274}{}{... and that's how we got out of the Den.}
{275}{}{2 Seconds}
{276}{}{What a load of brahmin crap.}
{277}{}{2 Seconds}
{278}{}{It's the truth!}
{279}{}{2 Seconds}
{280}{}{Don't you start. I'm glad Mom isn't here to hear this.}
{281}{}{2 Seconds}
{282}{}{What? What happened to your mother?}
{283}{}{2 Seconds}
{284}{}{Brain fever. Caught it out on the wastes. Probably looking for YOU.}
{285}{}{2 Seconds}
{286}{}{Oh. I... uh... I'm sorry, Val.}
{287}{}{2 Seconds}
{288}{}{I'm just kidding.}
{289}{}{2 Seconds}
{290}{}{Wh -?!}
{291}{}{2 Seconds}
{292}{}{She actually died of radiation poisoning. She drank some of the unfiltered water from the courtyard well.}
{293}{}{4 Seconds}
{294}{}{Wha... what?!}
{295}{}{2 Seconds}
{296}{}{Wasn't your fault. She had too many rads running through her system for Dr. Troy to save her. She was glowing like a lamp.}
{297}{}{2 Seconds}
{298}{}{Oh. I... well, I...}
{299}{}{2 Seconds}
{300}{}{Don't worry. She was pretty batty before that, anyway. It was only a matter of time.}
{301}{}{3 Seconds}
{302}{}{I'm still sorry I didn't get a chance to see her again.}
{303}{}{2 Seconds}
{304}{}{No, you aren't. You used to call her the 'desert viper,' didn't you?}
{305}{}{2 Seconds}
{306}{}{Well... yes. But you shouldn't call your mother th--}
{307}{}{2 Seconds}
{308}{}{Why not? It was true. She could be an awful bitch when she wanted to be.}
{309}{}{3 Seconds}
{310}{}{Uh... you look like you've done well for yourself. Inherited your father's knack for repairing stuff, it seems.}
{311}{}{4 Seconds}
{312}{}{Dad... you can barely tie your shoelaces, much less repair anything with moving parts.}
{313}{}{3 Seconds}
{314}{}{Wh-?! The devil you say!}
{315}{}{2 Seconds}
{316}{}{Let's ask your "boss."}
{317}{}{2 Seconds}
{318}{}{Well... he can fix radios. And stuff.}
{319}{}{Ub nuwb ub}
{320}{}{2 Seconds}
{321}{}{If you give him ALL the parts, right?}
{322}{}{I see you're traveling with people slightly smarter than you are.}
{323}{}{2 Seconds}
{324}{}{Well, yes.}
{325}{}{Ub nuwm ub?}
{326}{}{2 Seconds}
{327}{}{Ha! I knew it. Sloppy, sloppy.}
{328}{}{Your "boss" is probably better at fixing things than you are.}
{329}{}{2 Seconds}
{330}{}{Well, Val, last I saw you, you could barely tell a lug nut from a wrench.}
{331}{}{2 Seconds}
{332}{}{Keep it up, Dad, and you'll NEED a wrench to get my boot out of your ass.}
{333}{}{2 Seconds}
{334}{}{Oh, yeah?! Well, "honey," you better watch it or -}
{335}{}{2 Seconds}
{336}{}{Shut up! Shut up both of you! This has gone on LONG ENOUGH! Now, c'mon, Vic, let's get going.}
{337}{}{UGRGHH! GO! NO MORE TALK! WE GO!}
{338}{}{3 Seconds}
{339}{}{We'll talk later, Val.}
{340}{}{2 Seconds}
{341}{}{Yeah, sure, Dad.}
{342}{}{2 Seconds}
{343}{}{Fade out for 3 Seconds}
{344}{}{Hey! Glad you made it back. Last I heard, you were traveling down south, gunning up old tankers and blowing up oil derricks.}
{345}{}{You come back here for a little peace and quiet, Mr. Big Hero?}
{346}{}{You come back here for a little peace and quiet, Ms. Big Heroine?}
{347}{}{HE-wo? Hee-hee! Yup!}
{348}{}{Shamble off}
{349}{}{Thought I'd come back and touch base with Vault City for a while. The peace and quiet doesn't hurt, either. I needed something first, though...}
{350}{}{Nothing today, thanks. Take care.}
{351}{}{Well, you be careful around here, you hear? Don't be blowing up Vault City if you can help it. And... hey, thanks for saving us all.}
{352}{}{Swure! Bye-bye!}
{353}{}{Shamble off}
{354}{}{Nevermind. I'll talk to you later.}
{355}{}{You helped Valerie obtain new tools.}
{356}{}{You convinced Val to give her Dad a chance.}
{357}{}{ ***DO NOT DELETE THE NEXT LINE (#358)! IT'S NEEDED FOR THE SCRIPT. DON'T BOTHER TRANSLATING THIS, EITHER***}
{358}{}{}
{359}{}{Hey, I have those tools you wanted.}
{360}{}{It doesn't look like you have much of anything that I could tinker with. I mostly do pistols, rifles, that sort of thing.}

# phobos2077: crafting
{501}{}{Hey, you look like you're handy with tools. Could you teach me anything?}
{502}{}{Actually I was wandering if you could you teach me anything?}
{505}{}{Yeah, I'm about angry enough at the management to teach you some pretty good electronics.}
{506}{}{Oh, without compensation?}
{507}{}{Naah, wouldn't want to get you into trouble.}
{510}{}{Oh, with compensation, deffinitely. It'll take a $%1%.}
{511}{}{Never mind.}
{512}{}{So much? Really? how about $%1%?}
{515}{}{You know what, I'll do it. $%1% it is.}
{516}{}{Let's get to it.}
{520}{}{I'll teach you how to make mines with sensors, those things go off if you just look at them funny...}
{521}{}{...and that's how you do it. You'd think I made you the terror of the wasteland right now, right? Well, it's not so simple - these things require fusion cells, and good luck finding any.
 Only people who can get a hold of any are the ones crazy enough to try to trade with the ghouls.}
