{100}{}{You see Senior Council Member McClure.}
{101}{}{You see an elderly Vault City official. His hair is graying around the edges.}
{102}{}{You see Senior Council Member McClure.}
{103}{}{You see an elderly Vault City official. His hair is graying around the edges.}
{104}{}{I have heard of your act of heroism. We are all in your debt... Chosen One.}
{105}{}{I have to tabulate these lists before I leave. Return in the morning, and I will speak to you then.}
{106}{}{A ghoul?! Guards! Guards!}
{107}{}{A mutant?! Guards! Guards!}
{108}{}{I have nothing to say to you. Leave, or I will call the guards.}
{109}{MCCLR2}{Good day... Captain, is it? I've heard a great deal about you. Is there something I could help you with?}
{110}{MCCLR3}{Good day... Citizen, is it? I'd heard we had gained a new member of the community. Is there anything I could help you with?}
{111}{MCCLR4}{Hello... can I help you?}
{112}{MCCLR5}{Good day, Captain. Everything is well, I trust?}
{113}{MCCLR6}{Good day, Citizen. Can I help you?}
{114}{MCCLR7}{Yes? Was there something else you wanted?}
{115}{}{San-tah Klass?}
{116}{}{Shamble off}
{117}{}{Can I ask you some questions?}
{118}{}{Who are you?}
{119}{}{Just looking around, thanks. Good day.}
{120}{MCCLR8}{How did you get into our City? Guards! We have an Outworlder that needs to be escorted to the gate!}
{121}{}{I go no I GO NO}
{122}{}{Ahhh... Ples no go? Me be good}
{123}{}{Of course, Captain.}
{124}{}{Of course, Citizen.}
{125}{MCCLR11}{What is it you would like to know?}
{126}{}{What's your job here?}
{127}{}{I'm looking for a Garden of Eden Creation Kit.}
{128}{}{What can you tell me about the First Citizen?}
{129}{}{I'd like to ask you some questions about Gecko.}
{130}{}{What can you tell me about Redding?}
{131}{}{I need to speak to you about Redding.}
{132}{}{How does one become a Citizen?}
{133}{}{I think you might have a part that could fix Gecko's power plant.}
{134}{}{I repaired Gecko's plant.}
{135}{}{I have an economic data disk here you might find interesting.}
{136}{}{I found a way to optimize the Gecko reactor.}
{137}{}{Here's the Gecko reactor disk. Can you optimize it?}
{138}{}{Nothing today, thanks.}
{139}{MCCLR12}{I am Senior Councilor McClure. And you are...?}
{140}{}{None of your business.}
{141}{}{. Pleased to meet you.}
{142}{}{I really have to run. Maybe we can do introductions some other time.}
{143}{MCCLR13}{I expect that kind of rudeness from an Outworlder, not a Citizen. I am a member of the Vault City Council, and you will show me the proper respect, or I will have your Citizenship revoked. Do you understand me?}
{144}{}{Screw you, old man.}
{145}{}{Whatever. I'm done talking to you anyway.}
{146}{}{Sorry. Didn't mean to offend you.}
{147}{MCCLR14}{Well, this is the rudeness I've come to expect from Outworlders! Give me your Day Pass and go with the guards. There is no place for your kind in our city.}
{148}{}{I'm not giving you anything. You want it? You come get it.}
{149}{}{I'm NOT an Outworlder. I'm a Citizen.}
{150}{}{Okay, okay, I'm going.}
{151}{MCCLR15}{I find that hard to believe. Let me see your papers.}
{152}{}{Here, take them!}
{153}{}{You want them? You come get them.}
{154}{MCCLR16}{I don't know how someone of your inferior breeding became a Citizen but these papers seem to be in order. Strange... I don't recall seeing you around before. No matter, I shall honor your Citizenship.}
{155}{}{You're damn right you'll honor my Citizenship!}
{156}{}{Yeah, right. I'm outta here.}
{157}{MCCLR17}{Don't ever speak to me again. If you do, I will have your Citizenship revoked. Good day.}
{158}{}{Good day.}
{159}{}{You try and revoke my Citizenship, you'll regret it.}
{160}{}{Your powers are weak, old man. You are no match for me.}
{161}{MCCLR18}{That's it! Citizen or not, you're out of here. Guards, show this degenerate to the gates!}
{162}{}{I'm going. This place sucked anyway.}
{163}{}{I'm not going anywhere.}
{164}{MCCLR19}{What can I do for you?}
{165}{}{I don't know, old man. What CAN you do for me?}
{166}{}{I'm looking for a Garden of Eden Creation Kit.}
{167}{}{Can I ask you some questions?}
{168}{}{Nothing today. I was just taking a tour of the council building.}
{169}{MCCLR20}{A GECK? As I understand it, we only had one. I read that it lasted a long time but it broke down a number of years before I was even born. We were supposed to have two...}
{170}{}{Supposed to?}
{171}{MCCLR21}{... but apparently the old government messed up the shipments and we received a shipment that was meant to go to a Vault number... thirteen, I think it was. They probably received our other GECK.}
{172}{}{What was in the shipment that was meant for Vault 13?}
{173}{}{What happened to the GECK that broke down?}
{174}{}{Can I ask you another question?}
{175}{}{I see. Thanks for the information.}
{176}{MCCLR22}{Water Chips, a hundred or so. I don't know why they sent so many... we have never needed to replace ours. We have had the same water chip since the day our people lived underground in the Vault.}
{177}{}{What happened to the GECK that broke down?}
{178}{}{Can I ask you another question?}
{179}{}{Interesting. Thanks for your time.}
{180}{}{The irony is razor sharp. Maybe we'll talk later after I stop the bleeding.}
{181}{MCCLR23}{It was disassembled, and its parts were used for other applications.}
{182}{}{What was in the shipment meant for Vault 13?}
{183}{}{Can I ask you another question?}
{184}{}{I see. Thanks for your time.}
{185}{MCCLR24}{She is the leader of the people. The Citizens of Vault City look to her for guidance, but the Citizens, through the Council, still have final say on matters. In these trying times, she is a pillar of our society.}
{186}{}{"Trying times?" What do you mean?}
{187}{}{What is it you do?}
{188}{}{Can I ask you another question?}
{189}{}{Thanks for your time. Goodbye.}
{190}{MCCLR25}{Gecko? What do you want to know?}
{191}{}{Where is Gecko?}
{192}{}{What is Gecko?}
{193}{}{Can I ask you another question?}
{194}{}{Thanks for your time. Goodbye.}
{195}{MCCLR26}{Not much to tell, other than the fact that our ore shipments have become few and far between.}
{196}{}{Any idea why?}
{197}{}{Where is Redding?}
{198}{}{Can I ask you another question?}
{199}{}{Thanks for your time. Goodbye.}
{200}{MCCLR27}{I am the Senior Council Member. I oversee the council meetings.}
{201}{}{Then what does the First Citizen do?}
{202}{}{Can I ask you another question?}
{203}{}{Thank you for your time. Goodbye.}
{204}{MCCLR28}{Well, Citizenship isn't for everyone, you understand. You seem more like an adventurer to me... I really don't think that Citizenship is for you.}
{205}{}{Aw, c'mon... just tell me what I need to do to become a Citizen.}
{206}{}{I'd still like to become a Citizen anyway.}
{207}{}{Can I ask you another question?}
{208}{}{Nevermind then.}
{209}{MCCLR29}{You wish to become a Citizen? Well, we would be pleased to have you. All you need to do is talk to Proconsul Gregory and he will give you the Citizenship test.}
{210}{}{Where can I find Proconsul Gregory?}
{211}{}{Can I ask you another question?}
{212}{}{Thanks. I'll go find him now. Goodbye.}
{213}{MCCLR30}{Very well. All you need do is talk to Proconsul Gregory and he will give you the Citizenship test.}
{214}{}{Where can I find Proconsul Gregory?}
{215}{}{Can I ask you another question?}
{216}{}{All right. I'll go speak to the Proconsul now.}
{217}{MCCLR31}{You'll find him in the East Wing. His office is across from the First Citizen's.}
{218}{}{Can I ask you another question?}
{219}{}{Thanks for your time. Goodbye.}
{220}{MCCLR35}{Things have been tough these last two years. The NCR has been getting more aggressive in their attempts to get Vault City to join the Republic.}
{221}{}{They tell us that if we were to join, they would be able to defend us from the raider attacks on our city. As of late, these raider attacks have become more brutal.}
{222}{}{On top of all of this, we have ghouls in Gecko contaminating our groundwater.}
{223}{}{Where is Gecko?}
{224}{}{What is Gecko?}
{225}{}{Trying times, indeed. Can I ask you another question?}
{226}{}{Sorry to hear it. Thanks for your time. Goodbye.}
{227}{MCCLR36}{It is just northeast of here, but if you are planning on going there, I would advise you to purchase some anti-radiation drugs. If they are contaminating our water, it is likely their town itself is irradiated.}
{228}{}{What is Gecko?}
{229}{}{Can I ask you another question?}
{230}{}{Thanks for the warning. Goodbye.}
{231}{MCCLR37}{It is a forsaken place, a shantytown built around the remnants of an old atomic power plant.}
{232}{}{Where is Gecko located?}
{233}{}{Can I ask you another question?}
{234}{}{Thanks for your time. Goodbye.}
{235}{MCCLR38}{No. I don't understand it at all. We are willing to pay top dollar for their ore, but whenever we try to talk to them about it, they become evasive. If only I knew what was going on...}
{236}{}{I could go check it out for you.}
{237}{}{Where is Redding?}
{238}{}{Thanks for your time. Goodbye.}
{239}{MCCLR39}{You will? It is not in my power to pay you, but your aid will be much appreciated.}
{240}{}{Where is Redding?}
{241}{}{No problem. I'll check it out and return when I find out what's wrong.}
{242}{MCCLR40}{Redding is a week or so west of here. I've never been there. Never been outside Vault City, for that matter. As I understand it, Redding is supposed to be one of the more pleasant settlements in the wastes.}
{243}{}{Do you have any idea what's causing the shipments to drop off?}
{244}{}{I see. Thanks for the information.}
{245}{MCCLR41}{What is it? Anything you could tell me would be a great help.}
{246}{}{What can you tell me about Redding?}
{247}{}{I found that a large part of Redding is addicted to a drug called Jet. The miners are trading most of their ore to New Reno just to keep supplied.}
{248}{}{Dr. Troy has created an antidote for Jet.}
{249}{}{I delivered the antidote to Redding.}
{250}{MCCLR42}{What is this "Jet" that they are all addicted to?}
{251}{}{I'll tell you later when I find out more.}
{252}{}{It's a drug with a 100% addiction rate, and severe withdrawals.}
{253}{MCCLR43}{Please keep me posted.}
{254}{}{Can I ask you some other questions?}
{255}{}{Sure.}
{256}{MCCLR44}{This is sad news, we need to find a way to put a stop to this. If this keeps up, our ore supplies will dwindle to nothing. Please help us.}
{257}{}{I'll see what I can do.}
{258}{MCCLR45}{He has? Well then, what are you doing here? Take it to Doc Johnson in Redding! He should be able to find a way to administer it to the miners.}
{259}{MCCLR46}{I know, you already told me. Please take it to Redding and see if you can help them.}
{260}{}{Before I go, can I ask you some other questions?}
{261}{}{Okay, goodbye.}
{262}{MCCLR47}{Thank you! Now all we can do is wait. Hopefully, this fixes our problem. Thank you again for all of your assistance.}
{263}{}{You're welcome. I was glad to be of service.}
{264}{}{Not a problem. Could I ask you some other questions?}
{265}{}{Whoa... don't I get anything for my troubles?}
{266}{MCCLR48}{If it is money you want, money you will receive. Here's $500 for your troubles. Now good day.}
{267}{}{THANK you.}
{268}{}{Five hun --? You better cough up some more and fast, or your life won't be worth $2.}
{269}{MCCLR49}{What do you mean?}
{270}{}{If I had a hydroelectric magnetosphere regulator, I could make their plant run clean.}
{271}{}{Oh, nothing. Sorry to trouble you.}
{272}{MCCLR50}{That's an acceptable solution. Stopping the radiation poisoning is all I care about.}
{273}{}{I'm worried that Lynette will withhold my Citizenship if I fix the plant.}
{274}{}{Great! Where can I get the part?}
{275}{}{I'll keep that in mind.}
{276}{MCCLR51}{If you fix their plant, I'll give you Citizenship, and there's not a damn thing she can do about it.}
{277}{}{Excellent! Where can I get the part?}
{278}{MCCLR52}{Go see Randal, the Chief Amenities Officer. He should have the part in stock.}
{279}{}{Thanks. I'll go see him right now.}
{280}{}{There's one other thing. You might find this economic data disk interesting.}
{281}{}{Excellent! I was worried that the radiation build-up might force us to relocate. You are to be commended on a job well done.}
{282}{}{Vault City prevails, Citizen.}
{283}{}{Vault City, prevails, Captain.}
{284}{}{Here's your Citizenship papers. If you ever need anything, come see me.}
{285}{}{Vault City prevails, Councilor.}
{286}{}{Thanks.}
{287}{}{Yes, you mentioned that.}
{288}{}{Well done, Captain.}
{289}{}{Well done, Citizen.}
{290}{}{Well done.}
{291}{}{I had some other questions...}
{292}{}{Thanks.}
{293}{MCCLR60}{I'm sorry... an economic data disk? What do you mean?}
{294}{}{Here, take a look.}
{295}{}{It's an economic data disk that shows the amount of energy that Gecko's atomic power plant produced before the war... and could produce again.}
{296}{}{Never mind. I had some other questions.}
{297}{}{Nothing. Sorry to disturb you.}
{298}{MCCLR61}{Very well. Give me a moment...}
{299}{}{All right.}
{300}{MCCLR62}{Hmmm. How did you come by this disk?}
{301}{}{I... found it.}
{302}{}{I found it while searching some of the archives in the Vault City library.}
{303}{}{I got it from someone in Gecko.}
{304}{}{I received it from a ghoul in Gecko. His name is Gordon Gecko. He's interested in optimizing the power plant and sharing the energy with Vault City... in exchange for Vault City's medical technology.}
{305}{MCCLR63}{I... see. So. What does this have to do with me?}
{306}{}{Well, as I understand it, Vault City's power generator can only support so many people. In fact, it's already nearing its limit.}
{307}{MCCLR64}{I'm not going to ask you how you came by that information, but if it were true, what are you proposing?}
{308}{}{Once the Gecko power plant is fixed, the disk indicates it's possible it could produce enough energy for Vault City, too. It looks like the reactor would need to be optimized first, though.}
{309}{}{The disk shows that Gecko's power plant... if it were optimized... could produce a great deal of energy. Far more than Gecko needs. Vault City could use that energy.}
{310}{MCCLR65}{Are you suggesting we SEIZE Gecko and take their power plant? I will NOT lis --}
{311}{}{No, no... if Gecko could receive the optimization data for their plant, I'm betting they would be willing to trade their excess power for medical assistance.}
{312}{MCCLR66}{Hmmm. As far as medical assistance goes, I'm not unsympathetic to the plight of the ghouls. They have certainly suffered enough... but how could we optimize their plant?}
{313}{}{I don't know. Maybe there's someone I can talk to once the plant is repaired.}
{314}{}{I don't know. Maybe there's someone I can talk to at the plant.}
{315}{}{I would just need access to the Vault City computer. It could optimize the power plant reactor disk and allow the plant to run more smoothly.}
{316}{MCCLR67}{I have no objections to your proposal. If you can find some means of optimizing the plant, let me know.}
{317}{}{All right. I'll go get that part from Randal and see about repairing the reactor first.}
{318}{}{Very well, Captain.}
{319}{}{Very well, Citizen.}
{320}{MCCLR70}{You have my permission to use the Vault computer and optimize the reactor disk. You can find it on the third level of the Vault, near the Operations Room.}
{321}{}{Excellent. Thank you, Councilor. I'll go do that.}
{322}{MCCLR74}{It is done. Here you go.}
{323}{MCCLR73}{I'll keep the economic disk and study it some more... Perhaps I can persuade the Council to enter negotiations with Gecko to trade for their power. The data disk would be a strong argument in of itself.}
{324}{}{I appreciate it. Thanks.}
{325}{MCCLR75}{Hmmm. Well, I cannot allow you access to the Vault, but I could optimize the reactor disk for you.}
{326}{}{All right. But I don't have the reactor disk on me. I'll be back with it.}
{327}{}{That'd be great.}
{328}{}{Excellent!}
{329}{}{All right.}
{330}{}{Let me take the reactor disk, and I'll have the Vault central computer optimize it.}
{331}{}{Great. Thanks.}
{332}{MCCLR78}{What is it?}
{333}{}{I have a reactor data disk here from Gecko. According to... the... uh, technician at the power plant, the Vault City computer can optimize the reactor disk and make the plant run more smoothly.}
{334}{}{Guards! Guards!}
{335}{}{}
{336}{}{You told McClure about the Redding Jet addiction problem.}
{337}{}{You gave the economic data disk to McClure.}
{338}{}{I'm still looking for a way to optimize the power plant.}
{339}{}{I'm still looking for a way to optimize the power plant.}
{340}{MCCLR59}{I wish I could help, but I'm afraid my knowledge of reactors is... limited. Perhaps one
 of the technicians at the Gecko plant would know how to optimize the plant?}
{341}{}{Perhaps. I had some other questions...}
{342}{}{Maybe so. I'll go see.}
{343}{}{You told McClure about the Jet antidote delivery.}
{344}{}{The disk shows that if the plant is fully functional and optimized, it can produce a great deal of energy. Far more than Gecko needs. Vault City could use that energy. I feel that the council should consider what this disk has to offer.}

{345}{}{Do you know anything about the nearby village that's swarming with mole rats?}
{346}{MCCLR79}{Actually, yes. Sergeant Stark reported something on this to me recently. What interest do you have in this matter?}
{347}{}{Is it true that you intend to make servants of those people?}
{348}{}{Nothing really. May I ask you about something else?}
{349}{}{Doesn't matter. Bye.}
{350}{MCCLR80}{Recruiting servants is not the issue here. The issue is the threat that these monsters pose to Vault City. According to Sergeant Stark's report, the people of that village seem to coexist with those huge rat creatures. If that's true, they may have found a way to control them, and perhaps that's why these creatures have begun to attack our patrols. Sergeant Stark plans to eliminate these pests, and he has my full support.}
{351}{}{I assure you the people of that village aren't controlling the mole rats. In fact, I've got a proposition for you: I'll take care of this mole rat problem, and in return, I want your assurance that Vault City will leave the people of that village alone.}
{352}{MCCLR81}{An interesting proposition, but how exactly do you plan to deal with all those rat creatures?}
{353}{}{I think I might know who *is* controlling them.}
{354}{}{Don't really know, but I'll think of something. I always do.}
{355}{MCCLR82}{Really? Very well then, I'll take your word for it. I will tell Stark to postpone any raids for a month.}
{356}{}{You're a good man, McClure, and you won't regret this. I'll be back once the problem's taken care of.}
{357}{MCCLR1}{It's amazing, the mole rat attacks on our patrols suddenly stopped without warning. I don't know how you did it, but I thank you. Also, I shall uphold my end of the bargain -- I'll order Stark to cancel the raid at once. As long as the people of that village pose no threat to Vault City, they'll have nothing to fear from us -- I'll see to that.}
{358}{}{Thank you!}
{359}{}{You solved the village problem.}

{360}{}{This is quite interesting.} #was 345-killap

{370}{}{Alright. Well, I won't get in your way then.}

# by Lujo:
{371}{}{The villagers are too well armed to attack, but there might be a way to get rid of the rats regardless.}
{372}{}{Really? I'm certainly more interested in a peaceful solution. I will tell Stark to postpone any raids for a while.}
{373}{}{By pests, you mean just the rats, or the future servants?}
{374}{}{I don't like the implication that Vault City would go around "raiding" for servants. We are not slavers. Officially, the orders Stark was given do not include any mention of servants. But he *is* showing these people a great mercy. However you look at it, there are rats right outside the walls, and these people are responsible.}
{375}{}{In other words, if the villagers don't have a bunch of rats loafing around... Excuse me while I go check something out!}
{376}{}{What if the villagers aren't the ones controlling the rats? What if I could make the rats go away?}
{377}{}{Have you had any luck in persuading the villagers to do away with the rats?}
{378}{}{I'm still working on it.}


##############################################
#BONUS LINES NEEDED FOR THE TALKING HEADS MOD#
##############################################
{7700}{MCCLR9}{Of course, Captain. What is it you would like to know?}
{7701}{MCCLR10}{Of course, Citizen. What is it you would like to know?}
{7702}{MCCLR32}{Things have been tough these last two years. The NCR has been getting more aggressive in their attempts to get Vault City to join the Republic. They tell us that if we were to join, they would be able to defend us from the raider attacks on our city. As of late, these raider attacks have become more brutal. On top of all of this, we have ghouls in Gecko contaminating our groundwater.}
{7703}{MCCLR33}{Things have been tough these last two years. The NCR has been getting more aggressive in their attempts to get Vault City to join the Republic. They tell us that if we were to join, they would be able to defend us from the raider attacks on our city. As of late, these raider attacks have become more brutal.}
{7704}{MCCLR34}{Things have been tough these last two years. The NCR has been getting more aggressive in their attempts to get Vault City to join the Republic. On top of all of this, we have ghouls in Gecko contaminating our groundwater.}
{7705}{MCCLR53}{Excellent! I was worried that the radiation build-up might force us to relocate. You are to be commended on a job well done. Vault City prevails, Citizen.}
{7706}{MCCLR54}{Excellent! I was worried that the radiation build-up might force us to relocate. You are to be commended on a job well done. Vault City, prevails, Captain.}
{7707}{MCCLR55}{Excellent! I was worried that the radiation build-up might force us to relocate. You are to be commended on a job well done. Here's your Citizenship papers. If you ever need anything, come see me.}
{7708}{MCCLR56}{Yes, you mentioned that. Well done, Citizen.}
{7709}{MCCLR57}{Yes, you mentioned that. Well done, Captain.}
{7710}{MCCLR58}{Yes, you mentioned that. Well done.}
{7711}{MCCLR68}{Very well, Captain. You have my permission to use the Vault computer and optimize the reactor disk. You can find it on the third level of the Vault, near the Operations Room.}
{7712}{MCCLR69}{Very well, Citizen. You have my permission to use the Vault computer and optimize the reactor disk. You can find it on the third level of the Vault, near the Operations Room.}
{7713}{MCCLR71}{It is done. Here you go. I'll keep the economic disk and study it some more... Perhaps I can persuade the Council to enter negotiations with Gecko to trade for their power. The data disk would be a strong argument in of itself.}
{7714}{MCCLR72}{This is quite interesting. I'll keep the economic disk and study it some more... Perhaps I can persuade the Council to enter negotiations with Gecko to trade for their power. The data disk would be a strong argument in of itself.}
{7715}{MCCLR76}{Excellent! Let me take the reactor disk, and I'll have the Vault central computer optimize it.}
{7716}{MCCLR77}{All right. Let me take the reactor disk, and I'll have the Vault central computer optimize it.}