{100}{}{You see an old man with a crazy gleam in his eye.}
{101}{}{You see Old Joe, the local idiot savant.}
{102}{}{Hello. Haven't seen you in a while.}
{103}{}{Do I know you?}
{104}{}{Ah, yeah. It's been a while. What have you been doing?}
{105}{}{Well, it has been a while. What have you been up to?}
{106}{}{This and that. Where do you know me from?}
{107}{}{Look, old man, I don't know who the hell you are.}
{108}{}{Sure has. Well, I've been around; finally ended up here in this god-forsaken place. Not like the
 good old days. No sir.}
{109}{}{Yeah, the good old days. Remember that time we...}
{110}{}{It hasn't been the same lately, that's for sure. Now... what did we do together?}
{111}{}{Don't remember me, do you? Well, you do seem to be a bit young.}
{112}{}{What are you trying to tell me?}
{113}{}{You look so familiar, though. Ah, must be my old eyes. Well, good day to you.}
{114}{}{Uh, yeah... goodbye.}
{115}{}{Yeah, we sure gave the Master hell, didn't we? Shit fell apart after you left, though. Had to
 move around and change my name. Where'd you end up?}
{116}{}{I've been living up in a small village.}
{117}{}{Well, you better be careful around here. Things ain't as clear as they once were. You best watch
 your back.}
{118}{}{Okay, thanks.}
{119}{}{Yeah, I looked for your Vault for a while, but never found it. So you got any good stories for
 your old friend Ian?}
{120}{}{Ian?}
{121}{}{Yeah, Ian. Don't you remember me? It's been a bunch of years. You'd think someone wouldn't
 forget his best buddy. Well... except for the shooting in the back thing. Sorry about that again.}
{122}{}{I am sorry, but you must think I am the Vault Dweller. My village was founded by the one who
 came from the Vault.}
{123}{}{Well, that makes a bit more sense. Well, it's good to hear my friend did well. Well, old Ian's
 got some advice for you. You be careful out there. This place ain't as peachy as it seems. }
{124}{}{What's going on here?}
{125}{}{Well, the Vault Citizens think very highly of their bloodline and don't care much for
 people like me and you. You take this. It'll protect you if things get a little out of control.
 You probably shouldn't be seen talking with this crazy old man. Best get on your way.}
{126}{}{Thanks for your help. Bye.}
{127}{}{Let an old man rest.}
{128}{}{So familiar...}
{129}{}{Leave me be now.}
{130}{}{You better get going.}
{131}{}{They'll get suspicious if we talk anymore.}
{132}{}{Go on, get. Make my old friend proud.}

{133}{}{Thanks. One more thing though. I'm trying to help this little village that's north-east of here. A guy there named Connar told me to seek you out and speak with you.}
{134}{}{Connar, huh? He's a good guy. I've been keeping my eye on things for him. So what exactly does Connar want, now?}
{135}{}{He's trying to get his hands on some explosives. He thinks if they had that kind of firepower, they'd be able to make the Vault City patrols give them a wide berth.}
{136}{}{Ah, so that's his new plan, eh? Well, head over to Happy Harry's general store. Tell Harry Connar sent you, and he should be able to fix you up -- I believe he's got a case or two of grenades stashed away in case Stark ever gets funny ideas. But if you ask me, I'm not sure this is the best way to handle things.}
{137}{}{I'm off to speak with Harry then. Take care ol' friend.}
{138}{}{Why, what do you mean?}
{139}{}{Connar and his people have that strong fighting spirit, but it won't be enough in this case. Sooner or later they'll run out of explosives, and it won't take too long for Vault City to find out. Sometimes, it's best to talk things out and try to reason with people. That's a lesson I learned from my old friend, the Vault Dweller. Senior Council Member McClure has shown to be a reasonable man. Perhaps some agreement can be made with him?}
{140}{}{Hmm... I may have to consider this. Thanks for everything, bye.}
{141}{}{Perhaps I'll go speak with him then. However, I was curious about the mole rats that are guarding the village.}
{142}{}{Yeah, what about them?}
{143}{}{Any idea where they're from or who's controlling them?}
{144}{}{That, I'm not sure about. A bunch of ghouls came by with them. They were carrying strange amulets and talking about some "Renewal". That's pretty much all I know. You might wanna check out Gecko though. That place is bustling with ghouls. Speaking of big rats, did I ever tell you about the time the Vault Dweller and I went to Vault 15?}
{145}{}{No, but I'm well versed in the tale, as it's become a sacred legend in my tribe. Anyway, maybe I'll go see what I can find in Gecko. Take care, Ian.}
{146}{}{Uh, thanks for the tip. I think you are the man I need to see though. Connar sent me to ask you for some things.}
{147}{}{Wait a minute! Connar told me you have some information.}
{148}{}{No, but I'm well versed in the tale, as it's become a sacred legend in my tribe. Anyway, maybe I'll go see what I can find in Gecko. Take care.}

{150}{}{He was interested in getting some explosives to fend off the Vault City patrols, but I convinced him that there's a better solution.}
{151}{}{Ah, so that's his new plan, eh? Yeah, Connar's a good man, but he doesn't always think things all the way through. Sometimes, it's best to talk things out and try to reason with people. That's a lesson I learned from my old friend, the Vault Dweller.}

{152}{}{Well, any idea who on the council I might be able to talk to?}
{153}{}{I think Senior Council Member McClure might be the man to talk to. What do you think?}
{154}{}{Senior Council Member McClure is a smart man here in Vault City. Perhaps some agreement can be made with him?}

{155}{}{Alright. I'll try to speak with him. Bye.}
{156}{}{Perhaps I'll go speak with him then. However, I was curious about the mole rats that are guarding the village.}

{157}{}{He'd be your best bet. He is the only one on the council that has a reasonable soul left.}
{158}{}{Alright. I'll try to speak with him. Bye.}
{159}{}{I will go speak with him then. I was curious about the molerats that are guarding the village though.}

#added by killap - new in RP 1.3
{200}{}{Hey, if you really are the same Ian that journeyed with my ancestor, then I've got a question for you.}
{201}{}{Alright, let's hear it.}
{202}{}{How the hell are you still alive? You must be over a hundred years old. Not to mention the Vault Dweller's memoirs, which say you were burnt to death in Necropolis by a super mutant with a flame thrower.}
{203}{}{[He barks gruff laughter for awhile; finally, he settles down and wipes a couple tears from his eyes.] Oh, that's rich. Burnt to death by a flame thrower, ha! You see, I told the Vault Dweller to make up some story about how I died, 'cause I didn't want any of our old enemies trying to hunt me down -- that's why I changed my name. I told him to have me going down in a blaze of glory, and it looks like he took that literally. Ha, that's classic.}
{204}{}{Heh, I guess that solves that. I was curious about the molerats that are guarding the village though.}
{205}{}{That still doesn't explain how you're still alive and well after all these years.}
{206}{}{Hey, I'm just as confused as you are. Who knows? Maybe it's got something to do with all that radiation I was exposed to back in the old days. Hell, when we went to the Glow, I remember the Vault Dweller was popping Rad-X like candy, but did he offer any to ol' Ian? Of course not. I think he was still upset over a little friendly fire mishap. Heh heh. [Sigh.] Those were some good times.}
{207}{}{I'm sure they were. Thanks for the story Joe, er, Ian. Take care.}
{208}{}{I'm sure they were. Thanks for the story Joe, er, Ian. I was curious about the molerats that are guarding the village though.}

{300}{}{Wait a minute! Are you the contact in Vault City that Connar was talking about?}

{301}{}{If we talk too often they'll find out I'm helping you out. What is it?}
{302}{}{One important thing - how *did* Connor get a bunch of huge rats to protect the village?}
{303}{}{That, I'm not sure about. The way I herd it, a bunch of ghouls came by with them in tow. That's pretty much all I know. You might wanna ask Connor about it, or check Gecko out. That place is bustling with ghouls.}
{304}{}{Interesting, thank you and goodbye.}
