{100}{}{You see Citizen Sergeant Stark.}
{101}{}{You see a huge black man in heavy armor. He's watching you carefully.}
{102}{}{You see Citizen Sergeant Stark.}
{103}{}{You see a huge black man in heavy armor. He's watching you carefully.}
{104}{}{Good job down south. Saw the fireworks all the way up here.}
{105}{}{Good day... sir.}
{106}{}{Vault City prevails... sir.}
{107}{}{Good day, Citizen.}
{108}{}{Vault City prevails, Citizen.}
{109}{}{You'll wish you stayed out of the city... Guards!}
{110}{}{A mutant! Guards!}
{111}{}{A ghoul! Guards!}
{112}{}{Need to compile those ammunition lists...}
{113}{}{Need to check the weapon lockers down in the Vault tomorrow...}
{114}{}{Maybe being in these cells will teach you to behave yourselves.}
{115}{}{And you'll STAY in these cells until the First Citizen pardons you.}
{116}{}{I'm sorry, Citizen, but no one's permitted in the Corrections Center after dark. Come back in the morning.}
{117}{}{It's past curfew. What are you still doing in the city?}
{118}{}{Yah!}
{119}{}{Uh, as a Citizen, I am allowed to be in the city after dark.}
{120}{}{I just had some business to take care of before I left.}
{121}{}{I'm leaving right now.}
{122}{}{Is that so? Well, I know EVERY Citizen in Vault City, and I don't recognize you. Where's your papers?}
{123}{}{You want them? Come get them.}
{124}{}{I don't have them on me.}
{125}{}{Here you go.}
{126}{}{Then stop wasting my time, "Citizen." Come on, let's move it.}
{127}{}{Your business is over for the day. Come on, let's move it.}
{128}{}{I'm not going anywhere. You try and move me, you'll regret it.}
{129}{}{All right, I'm going.}
{130}{}{Captain. Can I help you... sir?}
{131}{}{Can I help you, Citizen?}
{132}{}{What do you want?}
{133}{}{Yah!}
{134}{}{Shamble off}
{135}{}{Who are you?}
{136}{}{Nothing, sorry to disturb you.}
{137}{}{Come with me, boy. NOW.}
{138}{}{Come with me, lady. NOW.}
{139}{}{Me leave? Me leave!}
{140}{}{ME NO GO. NOW.}
{141}{}{You'll wish you left.}
{142}{}{ME NO GO LEFT.}
{143}{}{Sergeant Stark... sir. Did you need something?}
{144}{}{I am Citizen SERGEANT Stark, Citizen. Was there something I could help you with?}
{145}{}{I am Citizen SERGEANT Stark, Outsider. What do you want?}
{146}{}{What do you do here?}
{147}{}{Can you tell me where the Vault is?}
{148}{}{Nothing, sorry to disturb you.}
{149}{}{I do YOUR job, sir.}
{150}{}{I run the Corrections Center. And obey your orders, sir.}
{151}{}{I run the Corrections Center. Keep the Outworlders in line. Make sure the Servants behave. Organize patrols. Try and protect the city from raiders.}
{152}{}{You got a problem, Sergeant?}
{153}{}{You the one who busted up Cassidy's bar?}
{154}{}{Have you heard of a servant named Joshua?}
{155}{}{Patrols?}
{156}{}{Raiders?}
{157}{}{About those Raiders...}
{158}{}{Can I ask you some questions?}
{159}{}{Thanks. Goodbye.}
{160}{}{Permission to speak freely, sir.}
{161}{}{Granted.}
{162}{}{No. I had some other questions for you, first.}
{163}{}{Not today, Sergeant.}
{164}{}{You don't DESERVE your post. I have lived in Vault City all my life. The men and women under MY command trust me and respect me, not you... sir.}
{165}{}{That's why I need you at your post, Sergeant. There is no doubt that you are capable and know Vault City better than I do. Nevertheless, I have shown RESULTS where you have NOT. Never forget that.}
{166}{}{Noted, Sergeant. Now I have some questions for you.}
{167}{}{Noted, Sergeant. I suggest you swallow your attitude and get on with doing your job. Good day.}
{168}{}{Understood, sir.}
{169}{}{Now I have some questions for you.}
{170}{}{Carry on then, Sergeant.}
{171}{}{Yes, sir. I conducted an authorized raid on Mr. Cassidy's establishment.}
{172}{}{Maybe your friend Cassidy there didn't tell you that he had illegal substances on the premises, and his license for alcohol distribution had expired. You forget to tell your friend here that, Cassidy?}
{173}{}{Cassidy says he was all paid up and you raided his place anyway.}
{174}{}{Forget it. I had some other questions...}
{175}{}{Never mind then. Goodbye.}
{176}{}{No, sir. Mr. Cassidy had not paid his licensing fee for alcohol for the month, yet was still selling it on the premises. His list of payments are logged in the computer.}
{177}{}{Cassidy was guilty of possession without a license. He doesn't like it, he can leave Vault City. That simple.}
{178}{}{I believe you, Sergeant. Well done. Now listen to me: I want you to pardon Mr. Cassidy, wipe his record clean, and pay him restitution for the damages you caused his establishment.}
{179}{}{You know, I think my fist and your face are about to have a conversation.}
{180}{}{Forget it. I had some other questions...}
{181}{}{Nevermind then. Goodbye.}
{182}{}{Thanks for looking out for me, friend. Stark's one stubborn sonuvabitch.}
{183}{}{Just try it. I'll look forward to putting trash like you and Cassidy in their place.}
{184}{}{Fine. I was looking forward to kicking your ass anyway.}
{185}{}{Forget it. I had some other questions...}
{186}{}{Nevermind then. Goodbye.}
{187}{}{Yes... SIR.}
{188}{}{NOW, Sergeant.}
{189}{}{Come on, Sergeant. Chop-chop.}
{190}{}{Here you are, SIR.}
{191}{}{Now I have some questions for you, Sergeant.}
{192}{}{Very good, Sergeant. Carry on.}
{193}{}{Yeah, he was that drunk Outworlder who struck one of my guards in that brawl in the Spittoon. He's over at the Servant Allocation Center getting... broken in. It's just down the street.}
{194}{}{I had another question...}
{195}{}{Hmmm. I'll head over there now.}
{196}{}{The Vault's right outside the door... sir.}
{197}{}{The Vault's right outside the door. Just tell the guards you're a Citizen, and they'll let you through.}
{198}{}{The Vault's right outside the door. Only Citizens are allowed in there, so I don't want to catch you bothering the guards.}
{199}{}{Can I ask you something else?}
{200}{}{But I am a Citizen.}
{201}{}{How do you become a citizen?}
{202}{}{Thanks. Goodbye.}
{203}{}{That so? I don't recognize you, and I know every Citizen in Vault City.}
{204}{}{Here's my papers. I think you'll find everything in order.}
{205}{}{Uh, never mind. I had some other questions...}
{206}{}{I better be going.}
{207}{}{Well, well, if it isn't those papers that were stolen last month. Looks like I finally found the culprit. Come with me, Outsider.}
{208}{}{Touch me, and you'll regret it.}
{209}{}{I'm going, I'm going. Stop pushing.}
{210}{}{I was BORN a Citizen. Interested in becoming a Citizen? Find a council member.}
{211}{}{Can I ask you something else?}
{212}{}{I will, thanks. Goodbye.}
{213}{}{Yeah, what about them?}
{214}{}{I found their base.}
{215}{}{I wiped them out.}
{1215}{}{I convinced their guide to no longer lead them through the mountains. They will never find their way without him.}
{216}{}{Any idea where these raiders are striking from?}
{217}{}{Never mind. I had some questions...}
{218}{}{Forget it. Maybe we'll talk some other time.}
{219}{}{You did? Where is it?}
{220}{}{Yes, you said that before. You should tell the First Citizen if you haven't already.}
{221}{}{Down south, in a series of caves in the mountains. Here, let me point it out...}
{222}{}{I had some questions for you.}
{223}{}{All right. I'll go tell her.}
{224}{}{You wiped them out?}
{1224}{}{You did? So, they will no longer be a threat to us?}
{225}{}{Yes, you said that before. You should tell the First Citizen if you haven't already.}
{226}{}{Yeah, Vault City shouldn't have to worry about them anymore.}
{227}{}{I had some questions for you.}
{228}{}{All right. I'll go tell her.}
{229}{}{Go tell the First Citizen at once. She'll want to know about this immediately.}
{230}{}{I had some questions first.}
{231}{}{All right. I'll go tell her.}
{232}{}{Yeah, raiders. They've been hitting us pretty hard lately. (Frowns.) Why do you want to know about them?}
{233}{}{I'd like to try and find their base, maybe stop the attacks if I can.}
{234}{}{I was just curious.}
{235}{}{Never mind. I had some questions...}
{236}{}{Forget it. Maybe we'll talk some other time.}
{237}{}{What, you some kind of good Samaritan? I don't buy it.}
{238}{}{I am not a Samaritan. I'm actually a native of Arroyo - it's a village to the west.}
{239}{}{I'd like to help if I could.}
{240}{}{Look, I've seen enough of the world to know that helping out people seems to come back and help me in the end.}
{241}{}{Never mind. I had some questions...}
{242}{}{Forget it. Maybe we'll talk some other time.}
{243}{}{What, you come in here to be a smartass? That it?}
{244}{}{Oh, yeah? Well, tackling this band of raiders may be more than you can handle.}
{245}{}{No, but if you need help, I'm willing to help you out.}
{246}{}{I'd still like to try and help.}
{247}{}{Never mind then. I had some questions...}
{248}{}{Forget it. Maybe we'll talk some other time.}
{249}{}{Hmmm. Well, I ain't going to turn down any help at this point. You find their base, or even better, wipe them out, go tell the First Citizen.}
{250}{}{Actually, I already found their base.}
{251}{}{Actually, I wiped them out already.}
{1251}{}{Actually, I already put a stop to them. I convinced their guide to no longer lead them through the mountains. They will never find their way without him.}
{252}{}{Any idea where these raiders are striking from?}
{253}{}{All right. I had some other questions...}
{254}{}{I'll do that.}
{255}{}{Curious, huh? So am I. Now, what do you know about the raiders?}
{256}{}{I'd like to try and find their base, maybe stop the attacks if I can.}
{257}{}{I don't know anything. That's why I'm asking you.}
{258}{}{Never mind. I had some questions...}
{259}{}{Forget it. Maybe we'll talk some other time.}
{260}{}{Don't know anything? Maybe I'll keep you here in the Corrections Center until you REMEMBER something.}
{261}{}{I'd like to try and find their base, maybe stop the attacks if I can.}
{262}{}{You got me. I'm obviously in league with the raiders. Arrest me.}
{263}{}{Look, I'm walking out of here right now. If you try and stop me, there's going to be trouble.}
{264}{}{You're already in trouble. You looking to make it worse?}
{265}{}{No, I'd like to try and find their base, maybe stop the attacks if I can.}
{266}{}{You got me. I'm obviously in league with the raiders. Arrest me.}
{267}{}{I'm leaving. You want to stop me? Go ahead.}
{268}{}{All right then...}
{269}{}{Whoa! Whoa! I didn't --}
{270}{}{Bring it on, dead man.}
{271}{}{I don't think we'll be dropping the subject quite that easily. Now... what do you know about the raiders?}
{272}{}{I'd like to try and find their base, maybe stop the attacks if I can.}
{273}{}{I was just curious.}
{274}{}{Look, I'm walking out of here right now. If you try and stop me, there's going to be trouble.}
{275}{}{I don't know. These raiders don't make much sense. IF they are raiders.}
{276}{}{What do you mean?}
{277}{}{I had some other questions...}
{278}{}{I have to be going.}
{279}{}{They've got heavy firepower. Expensive firepower. They know military tactics. They stay in formation. They never cross their lines of fire. And they always stop short of breaking through our defenses.}
{280}{}{Uh... they stop short of breaking through the defenses?}
{281}{}{I had some other questions...}
{282}{}{I have to be going.}
{283}{}{I've seen them do it. The last attack, they disabled a laser turret on the western perimeter. They had a clear shot into the city. Then I saw one of their "captains" ORDER them to fall back. Makes no sense.}
{284}{}{Any idea where they're coming from?}
{285}{}{Hmmm. I had some other questions...}
{286}{}{Interesting. I have to be going.}
{287}{}{No. That's the most frustrating part. They keep retreating south. I can't spare any men to go and scout the area. I think the raiders have some native guide that leads them through the southern canyons.}
{288}{}{What's the deal with the south?}
{289}{}{Hmmm. I had some other questions...}
{290}{}{Interesting. I have to be going.}
{291}{}{Plenty of places to hide if you don't know where to look. The place is riddled with caves.}
{292}{}{I could probably find them.}
{293}{}{I had some other questions...}
{294}{}{Hmmm. I'll keep that in mind. Goodbye.}
{295}{}{Go ahead and try. I'm betting the only way they'd let us find them is by giving us a map.}
{296}{}{I had some other questions...}
{297}{}{If that's what it takes... thanks for the information.}
{298}{}{Yeah, we have a small group of patrols. Can barely spare the men to protect Vault City, much less do all the reconnaissance that needs to be done.}
{299}{}{Recon-o-what?}
{300}{}{I do a lot of traveling. Anything I can help with?}
{301}{}{Sorry to hear that. I had some other questions...}
{302}{}{Never mind then. Goodbye.}
{303}{}{Scouting.}
{304}{}{What do you mean?}
{305}{}{I could do some recon for you if you're short-handed.}
{306}{}{Forget it. I had some other questions...}
{307}{}{Never mind then. Goodbye.}
{308}{}{No, you'd need a Pip-Boy to get the job done right, and I can't spare one right now.}
{309}{}{I already got a Pip-Boy. It's old... and cranky... and seems to have wires and buttons yanked out everywhere... but it works.}
{310}{}{Well, all right. I had some other questions...}
{311}{}{Never mind then. Goodbye.}
{312}{}{Yeah? Has it got a Northern California world map installed?}
{313}{}{Yes. Well, at least from what I can see through the fog of war on the damn thing.}
{314}{}{I got a job for you, then. I need someone to scout the terrain around Gecko... that ghoul encampment to the northeast. Hit the eight sectors on the world map around the town, then report back.}
{315}{}{Why?}
{316}{}{No problem. I've already scouted out the area.}
{317}{}{All right. I'll come back when I've scouted the area.}
{318}{}{On second thought, count me out. Goodbye.}
{319}{}{If they keep poisoning our groundwater, we may be forced to take military action.}
{320}{}{I want to see how much damage the plant meltdown caused to the area.}
{321}{}{We may be forced to take military action against them in the future, especially if they start poisoning the groundwater again.}
{322}{}{Now do you want the job or not?}
{323}{}{Yes. I've already scouted out the area, though.}
{324}{}{I'll take the job. I'll report back when I'm done.}
{325}{}{I'll take the job. I had some questions first, though...}
{326}{}{No thanks. Maybe some other time.}
{327}{}{That so? Heh. Well... all right then.}
{328}{}{Good job. Download the information into my Pip-Boy, and I'll log it into the patrol computers.}
{329}{}{All right...}
{330}{}{This intelligence looks good. Well done. Here's your payment... three hundred dollars.}
{331}{}{All right then... you got any more work for me?}
{332}{}{Great. I had some other questions...}
{333}{}{Thanks. Pleasure doing business with you.}
{334}{}{Yeah, actually... I need someone to travel to NCR. Lately, I've been hearing reports that
 the Republic might be building up military strength. True or not, I need someone to plot a route to NCR and report back.}
{335}{}{No problem. Already done.}
{336}{}{Just travel to NCR, then come back?}
{337}{}{Forget it. I had some other questions...}
{338}{}{No thanks. Goodbye.}
{339}{}{That's all I need. I'm more interested in the route than the Republic itself, but I'll still need you to enter the city once you get there.}
{340}{}{No problem. Already done.}
{341}{}{I'll take the job. I'll report back when I'm done.}
{342}{}{I'll take the job. I had some questions before I left, however...}
{343}{}{No thanks. I had some other questions, though...}
{344}{}{I don't think I want this job. Maybe some other time.}
{345}{}{That so? Heh.}
{346}{}{All right then. Download the information into my Pip-Boy, and I'll log it into the patrol computers.}
{347}{}{All right.}
{348}{}{This intelligence looks good. Well done. Here's payment for your services, five hundred dollars... plus, you might find this useful.}
{349}{}{What is it?}
{350}{}{It's a Vault-Tec Motion sensor. We were going to strip it for parts, since it's too old for our Pip-Boys, but it looks like it's compatible with your model.}
{351}{}{How does it work?}
{352}{}{Keep it in your hand and it IDs hostiles in your immediate area when you use it. Or you can call up the Pip-Boy automap as normal, then just click the "scanner" button and they're lit up like a neon sign.}
{353}{}{Thanks, this could be useful. Say, can I ask you some other questions?}
{354}{}{Much appreciated. I'll go try it out.}
{355}{}{Hello... Captain. Did you want something?}
{356}{}{Hello again, Citizen. Something I can help you with?}
{357}{}{You're back again? You lost, or do you need something?}
{358}{}{Like what... sir?}
{359}{}{Yes, Citizen. What did you want to know?}
{360}{}{Like what?}
{361}{}{Hep-Hep Schlep-Bep}
{362}{}{Shamble off}
{363}{}{You got some kind of problem, Sergeant?}
{364}{}{You the one who busted up Cassidy's bar?}
{365}{}{Have you heard of a Servant named Joshua?}
{366}{}{What do you do here?}
{367}{}{Can you tell me where the Vault is?}
{368}{}{I surveyed the area around Gecko for you.}
{369}{}{Got any more recon work for me?}
{370}{}{I plotted that route to NCR for you.}
{371}{}{About those Raiders...}
{372}{}{Never mind. Goodbye.}
{373}{}{Good day...ma'am.}
{374}{}{Vault City prevails... ma'am.}
{375}{}{Captain. Can I help you... ma'am?}
{376}{}{Sergeant Stark... ma'am. Did you need something?}
{377}{}{I do YOUR job, ma'am.}
{378}{}{I run the Corrections Center. And obey your orders, ma'am.}
{379}{}{Permission to speak freely, ma'am.}
{380}{}{You don't DESERVE your post. I have lived in Vault City all my life. The men and women under MY command trust me and respect me, not you... ma'am.}
{381}{}{Understood, ma'am.}
{382}{}{Yes, ma'am. I conducted an authorized raid on Mr. Cassidy's establishment.}
{383}{}{No, ma'am. Mr. Cassidy had not paid his licensing fee for alcohol for the month, yet was still selling it on the premises. His list of payments are logged in the computer.}
{384}{}{Yes... MA'AM.}
{385}{}{Here you are, MA'AM.}
{386}{}{You pulled rank on Stark to help out your friend Cassidy.}
{387}{}{The Vault's right outside the door... ma'am.}
{388}{}{You have scouted Gecko for Vault City.}
{389}{}{You have scouted NCR for Vault City.}
{390}{}{Like what... ma'am?}

{391}{}{Yeah, there is something... I have been looking through your reconnaissance report and I found a small village nearby swarming with uhh..."mole rats", that's what the outsiders call them, right? I want you to go there and exterminate all those beasts.}
{392}{}{Just gun down a few rats? Ok, I'm on it.}
{393}{}{What for?}
{394}{}{What about the NCR expedition?}
{395}{}{I'll think about it. Can I ask you a few questions?}
{396}{}{No, not my kind of job. Goodbye.}
{397}{}{Excellent. Here, let me show you the exact location of the village. [Stark marks the village on your Pip-Boy map.] Pay's $750, just come back and collect once the rats are gone. One more IMPORTANT thing...}
{398}{}{Bye.}
{399}{}{What for? [He hesitates for a moment, then frowns.] Because they're huge damned rats and they're running around too damned close to the walls. I've got orders here - the only reason I'm offering you the job is because I don't want to put any of my boys in danger unless I have to }

{400}{}{Got it. I'll take the job.}
{401}{}{It's clear. What's with that village, anyway?}
{402}{}{About that village...}
{403}{}{You killed all those big ugly rats? Really?}
{404}{}{I was told you plan on turning the people of that village into servants, and that the mole rats were preventing you from doing it -- that's the real reason you wanted them exterminated.}
{405}{}{Yes.}
{406}{}{Not yet.}
{407}{}{You were missinformed. The rats are the main objective. But we *are* going to take the villagers as servants -- it's for their own good. Here, they'd be well fed and taken care of.}
{408}{}{It kind of looks like they're happy with where they are.}
{409}{}{You mean to say they'd rather live with rat shit up to their knees than be servants in Vault City? Either you're mad, or they are. And besides, I was *ordered* to remove the threat those rats pose, the only way it turns into a paying job is if there's servant money at the end. The question is do you want the job, or do I send in a squad in to get it done.}
{410}{}{Ok, understood. Back to the job.}
{411}{}{I don't think I want to be part of this.}
{412}{}{Great, return when you are done.}
{413}{}{All right, I'm dispatching a battle squad there immediately. Somebody HAS to do it.}
{414}{}{[DONE]}
{415}{}{Return when all is done.}
{416}{}{Great work, soldier. Here's your $750 -- your cut out of a village full of new servants. You've done Vault City a great service.}
{417}{}{Wait -- You never said anything about making the villagers your servants.}
{418}{}{Whatever. Goodbye.}
{419}{}{It's for their own good. Once they're servants of Vault City, there'll be no need for them to strife for survival. They'll be fed and taken care of. In return, they'll work for the good of the City. Everyone wins.}
{420}{}{But it's slavery!}
{421}{}{It's not slavery, but a mutually beneficial co-existence, a symbiosis so to speak.}
{422}{}{Disgusting! Goodbye.}
{1422}{}{Well, I agree. They're better off this way. Goodbye.}

{423}{}{Those primitives must have lost their minds completely! They started shooting at us on sight! They even started lobbing grenades at us! So I called the whole thing off.}

{424}{}{What village? Oh, the one we got our new servants from... what about it?}
{425}{}{You say what!? You enslaved them all?}
{426}{}{I know who provided them with explosives. It was that trader in the courtyard, Harry. }
{427}{}{Happy Harry, you say? ... figures it'd be one of them scumbags in the courtyard. Ok I'll deal with him. We'll see how "Happy" he is when I'm through. As for you, you can take whatever you find in his store as a reward for selling him out.}
{428}{}{I don't know why, but proconsul McClure has ordered me to wait with the village a little. It's applying to you as well. }
{429}{}{Hmm... Ok.}

# by Lujo - flow fixes
{430}{}{Hmmm, how about a scouting? Is there somewhere else you want reconaissance on?}
{431}{}{There is. I need you to scout the area around Broken Hills. It's a mining comunity down south, we don't know much about them. Still, their caravans go north after they stop here, so we suspect they might be in cahoots with the ghouls.}
{432}{}{So... same deal as with Gecko? Scout the place out?}
{433}{}{Same deal. Get the lay of the land around Broken Hills, return here for your reward. There's no rush so don't go unprepared - from the little we've seen the terrain looks nasty.}
{434}{}{You have scouted Broken Hills for Vault City.}
{435}{}{Mutants and humans mixing up? Really? It's a sick world out there... Well, it's not your fault. Here's your pay, you earned it.}
{436}{}{I surveyed the area around Broken Hills for you.}
{437}{}{Is there anything that you need done closer to home?}
{438}{}{Do you have anything closer to home? I don't think I'll be going that way right now.}
{439}{}{I surveyed the area around Broken Hills for you.}
{440}{}{You have one month to get it done. Any later than that and I'm sending a squad in, they shoot the place up and you don't get paid. I don't want to risk my boys unless I need to, so you better get to it right away. Understood?}
{441}{}{Yes?}
{442}{}{Understood. A few questions before I get on it?}

{443}{}{Understood. Getting right on it!}
{444}{}{Well, at least you don't have to bother with them anymore, right?}
{445}{}{To hell with them. We have enough servants as is. If I got a whole squad blown to pieces over this McClure would forget about his bullshit principles just long enough to make ME a servant.}
{446}{}{So, it's over?}
{447}{}{Like hell it is, now there's a bunch of rats attacking our patrols and we can't do anything about it! The council wants the rats gone, but they also don't want anyone getting blown up. So I'm screwed.}
{448}{}{Well, I'm sure you'll think of something, I'm out of this. I don't want to get blown up either.}
{449}{}{Ok, if I ever find a way to get rid of the rats I'll let you know.}
{450}{}{Who does? And yeah, I guess we'll just have to be content with shooting off any rats that come too close and that's it. I've got nothing to pay you with, but you got out of it alive, so that's something.}
{451}{}{Let the council know. And if you make the rats go away, tell them there's no threat. Because I'm not too hot on the idea of getting my men killed over one lousy village. Hell, if you could get the council to let it go right now, I wouldn't mind it one bit.}
{452}{}{Yep. I'm glad I got out in on piece. Bye.}
{453}{}{Sure thing.}
{454}{}{Sure thing. Another question?}
{455}{}{McClure ordered me to postpone the raid for one month. I'll postpone it permanently, just make sure you get it all sorted out so he forgets there ever was a problem.} 
{456}{}{Well, what do I do now? Can I help?}
{457}{}{You can drop the whole thing right now, I won't blame you. If you could find a way to make the rats go away, that would get the council off my ass. And I'd love to get my hands on the son of a bitch who gave those savages explosives.}
{458}{}{I have to think about this. I'll see you when I do.}
{459}{}{[Lie about it]. Ok, I'll do it for you.}

{460}{}{Those primitives must have lost their minds completely! They started shooting at us on sight! They even started lobbing grenades at our patrol! Lucky for us, proconsul McClure ordered us to call everything off for a while.}
