
variable dialog_shown := false;

procedure butpress begin
   reg_anim_clear(dude_obj);
   //play_sfx("IB2P1XX1");
end

procedure Node001 begin
end

procedure NodeWTF begin
   display_msg("wtf?");
end

procedure party_order_x begin
   call butpress;
   set_sfall_global("p_ordbtn", 6);
end

procedure close_dialog begin
   call butpress;
   deletewin("win1");
   display_msg("close");
   //game_ui_enable;
   dialog_shown := false;
end

procedure show_dialog begin
//game_ui_disable;
dialog_shown := true;
   createwin("win1",get_screen_width-340,get_screen_height-199,340,199);
   SelectWin("win1");
   
   //create window bakground graphics
   //display("graph_filename.pcx")
   //file must be in pcx format and have fallout2 standart palette
   display("pcx\\w_opt.pcx");
   ShowWin;
   
   //Now we will add four buttons to this window
   //addbutton("nameofbutton",posx,posy,widht,height)
   // 0,0 point for posx and posy paremeters is left upper corner of a new window.
   /*AddButton("button1",17,30,16,15);
   AddButton("button2",17,50,16,15);*/
   AddButton("button3",17,70,16,15);
   AddButton("button4",17,90,16,15);
   
   //adding graphics to buttons
   //addbuttongfx("buttonname","buttonpres_file.pcx","buttonrelise_file.pcx","mouse_over_file.pcx")
   //graph files must be in pcx format and in fallout2 standart color palette
   /*addbuttongfx("button1","pcx/boxon.pcx","pcx/boxoff.pcx"," ");
   addbuttongfx("button2","pcx/boxon.pcx","pcx/boxoff.pcx"," ");*/
   addbuttongfx("button3","pcx/boxon.pcx","pcx/boxoff.pcx"," ");
   addbuttongfx("button4","pcx\\boxon.pcx","pcx\\boxoff.pcx","pcx\\boxoff.pcx");
   set_self(dude_obj);
   //adding procedures to buttons
   //addbuttonproc("nameofbutton",mouse_on_procedure,mouse_out_procedure,buttonpres_procedure,buttonrelase_procedure);)
   /*AddButtonProc("button1",nullproc,nullproc,butpress,nullproc);
   AddButtonProc("button2",nullproc,nullproc,butpress,nullproc);*/
   AddButtonProc("button3",0,0,butpress,party_order_x);
   AddButtonProc("button4",0,0,0,close_dialog);
   
   //this command draws sprite on given coordinates in window
   //displaygfx("filename.pcx",posx,posy,hight,weight)
   //it draws elevator level arrow
   //displaygfx("pcx/items/DRUG_BOT.pcx",120,40,92,55);
   
   //addregion "reg" {0,0,340,0,340,199,0,199};
   //activateregion ("reg", NodeWTF);
   
   //addregionflag("reg", 0xFFFFFFFF);
   //checkregion;
   //addregionproc("reg", Node001, Node001, butpress, butpress);
   
   //This command will redraw curent window
   
   ShowWin;
   
   
   display_msg("Dialog "+get_screen_width+"x"+get_Screen_height);
   
end