/*
	Metal doors guarding a bunch of loot at Bishop's
*/

#define SCRIPT_REALNAME "nibasdor"

#define LOCKED_STATUS      STATE_ACTIVE
#define Crowbar_Bonus      (-3)
#define Lock_Bonus         (-80)
#define MIN_DAMAGE         (30)
#define MAX_DAMAGE         (50)

import variable bishop_stair_guard_obj;

#define WATCHER_OBJ     bishop_stair_guard_obj

// TODO: try to use the new doors.h while keeping the watcher logic

#include "../generic/_custom_door.h"
#include "../headers/newreno.h"
