variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable tmp_gen_rep;
variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable last_timed_obj;
variable last_timed_param;
variable check_still_kill;
variable stored_msg;
variable stored_node;
variable top_msg;
variable var_num;

procedure ChooseFromList;
procedure CLICK_PREV;
procedure CLICK_0;
procedure CLICK_1;
procedure CLICK_2;
procedure CLICK_3;
procedure CLICK_4;
procedure CLICK_MORE;

variable floater_patch_msg;
variable hs_temp;

procedure start;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure Node998;
procedure Node999;
procedure Node000;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;

variable coin_mult;
variable win_payoff;
variable reel_1;
variable reel_2;
variable reel_3;

procedure Node997;
procedure Node981;
procedure Node982;
procedure Node983;
procedure Node984;
procedure Node985;


procedure checkPartyMembersNearDoor
begin
	if (party_member_obj(16777278) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777376) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777377) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777305) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777313) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777323) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777352) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777378) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777368) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777379) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777380) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777295) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777381) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777407) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777411) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777412) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777413) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777481) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777558) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777600) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777718) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777718)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777719) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777719)) <= 5) then begin
			return 1;
		end
	end
	if (party_member_obj(16777720) != 0) then begin
		if (tile_distance_objs(self_obj, party_member_obj(16777720)) <= 5) then begin
			return 1;
		end
	end
	return 0;
end

procedure ChooseFromList
begin
	variable LVar0 := 0;
	gsay_reply(377, stored_msg);
	if (message_str(353, top_msg - 1) != "") then begin
		giq_option(1, 377, message_str(353, 150), CLICK_PREV, 50);
	end
	if (LVar0 == 0) then begin
		if (message_str(353, top_msg + 0) != "") then begin
			giq_option(1, 377, message_str(353, top_msg + 0), CLICK_0, 50);
		end
		else begin
			LVar0 := 1;
		end
	end
	if (LVar0 == 0) then begin
		if (message_str(353, top_msg + 1) != "") then begin
			giq_option(1, 377, message_str(353, top_msg + 1), CLICK_1, 50);
		end
		else begin
			LVar0 := 1;
		end
	end
	if (LVar0 == 0) then begin
		if (message_str(353, top_msg + 2) != "") then begin
			giq_option(1, 377, message_str(353, top_msg + 2), CLICK_2, 50);
		end
		else begin
			LVar0 := 1;
		end
	end
	if (LVar0 == 0) then begin
		if (message_str(353, top_msg + 3) != "") then begin
			giq_option(1, 377, message_str(353, top_msg + 3), CLICK_3, 50);
		end
		else begin
			LVar0 := 1;
		end
	end
	if (LVar0 == 0) then begin
		if (message_str(353, top_msg + 4) != "") then begin
			giq_option(1, 377, message_str(353, top_msg + 4), CLICK_4, 50);
		end
		else begin
			LVar0 := 1;
		end
	end
	if (LVar0 == 0) then begin
		if (message_str(353, top_msg + 5) != "") then begin
			giq_option(1, 377, message_str(353, 151), CLICK_MORE, 50);
		end
	end
end

procedure CLICK_PREV
begin
	top_msg := top_msg - 5;
	call ChooseFromList;
end

procedure CLICK_0
begin
	set_global_var(var_num, (global_var(var_num) / 100 * 100) + (top_msg % 100));
	call stored_node;
end

procedure CLICK_1
begin
	set_global_var(var_num, (global_var(var_num) / 100 * 100) + ((top_msg + 1) % 100));
	call stored_node;
end

procedure CLICK_2
begin
	set_global_var(var_num, (global_var(var_num) / 100 * 100) + ((top_msg + 2) % 100));
	call stored_node;
end

procedure CLICK_3
begin
	set_global_var(var_num, (global_var(var_num) / 100 * 100) + ((top_msg + 3) % 100));
	call stored_node;
end

procedure CLICK_4
begin
	set_global_var(var_num, (global_var(var_num) / 100 * 100) + ((top_msg + 4) % 100));
	call stored_node;
end

procedure CLICK_MORE
begin
	top_msg := top_msg + 5;
	call ChooseFromList;
end

procedure start
begin
end

procedure pickup_p_proc
begin
	if (source_obj == dude_obj) then begin
		call Node998;
	end
end

procedure talk_p_proc
begin
	start_gdialog(377, self_obj, 4, -1, -1);
	gsay_start;
	call Node000;
	gsay_end;
	end_dialogue;
end

procedure destroy_p_proc
begin
end

procedure look_at_p_proc
begin
	script_overrides;
	display_msg(message_str(377, 100 + (get_critter_stat(dude_obj, 4) <= 3)));
end

procedure description_p_proc
begin
	variable LVar0 := 0;
	script_overrides;
	display_msg(message_str(377, 100 + local_var(0)) + message_str(377, ((local_var(0) == 2) * random(165, 165)) + ((local_var(0) == 3) * random(180, 180)) + ((local_var(0) == 1) * random(151 - metarule(18, dude_obj), 151))) + message_str(377, 140) + ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3))) + message_str(377, 141));
end

procedure use_p_proc
begin
	variable LVar0 := 0;
	if (obj_pid(self_obj) == 33554898) then begin
		LVar0 := metarule3(106, tile_num_in_direction(tile_num(self_obj), 2, 1), elevation(self_obj), 0);
	end
	else
	if (obj_pid(self_obj) == 33554897) then begin
		LVar0 := metarule3(106, tile_num_in_direction(tile_num(self_obj), 3, 1), elevation(self_obj), 0);
	end
	if (LVar0 != 0) then begin
		if ((LVar0 != dude_obj) and ((party_member_obj(obj_pid(LVar0)) != 0) == 0) and has_trait(1, LVar0, 666)) then begin
			LVar0 := 1;
		end
	end
	if (LVar0 == 1) then begin
		display_msg(message_str(377, 4000));
	end
	else begin
		dialogue_system_enter;
	end
end

procedure use_skill_on_p_proc
begin
	variable LVar0 := 0;
	if ((action_being_used == 16) and ((get_critter_stat(dude_obj, 4) > 3) and (has_skill(dude_obj, 16) >= 25))) then begin
		script_overrides;
		LVar0 := roll_vs_skill(dude_obj, action_being_used, 0);
		if (is_success(LVar0)) then begin
			if (is_critical(LVar0)) then begin
				display_msg(message_str(377, 1015 + ((local_var(0) == 2) or (local_var(0) == 3))));
			end
			else begin
				display_msg(message_str(377, 1010 + ((local_var(0) == 2) or (local_var(0) == 3))));
			end
		end
		else
		if (is_critical(LVar0)) then begin
			display_msg(message_str(377, 1000 + ((local_var(0) == 2) or (local_var(0) == 3))));
		end
		else begin
			display_msg(message_str(377, 1005 + ((local_var(0) == 2) or (local_var(0) == 3))));
		end
	end
end

procedure damage_p_proc
begin
end

procedure map_enter_p_proc
begin
	variable LVar0 := 0;
	if (metarule(14, 0)) then begin
		if (local_var(0) == 0) then begin
			set_local_var(0, 1 + (random(1, 11) == 5) + (random(1, 74) == 13));
		end
	end
	if ((local_var(2) < game_time) and (local_var(3) < (((18 * (local_var(0) == 1)) + (100 * (local_var(0) == 2)) + (200 * (local_var(0) == 3))) * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3))) * ((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3))))) and ((7 * (24 * (60 * (60 * 10)))) != 0)) then begin
		set_local_var(3, 3 * (((18 * (local_var(0) == 1)) + (100 * (local_var(0) == 2)) + (200 * (local_var(0) == 3))) * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3))) * ((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3)))));
	end
	add_timer_event(self_obj, game_ticks(random(1, 30)), 1);
end

procedure timed_event_p_proc
begin
	if ((combat_is_initialized == 0) and (tile_distance(tile_num(self_obj), tile_num(dude_obj)) <= 10)) then begin
		float_msg(self_obj, message_str(377, random(2004 - (4 * (get_critter_stat(dude_obj, 34) == 0) * metarule(18, dude_obj)), 2009 + (3 * (get_critter_stat(dude_obj, 34) == 1) * metarule(18, dude_obj)))), 12);
	end
	add_timer_event(self_obj, game_ticks(random(5, 30)), 1);
end

procedure Node998
begin
end

procedure Node999
begin
end

procedure Node000
begin
	if (((get_critter_stat(dude_obj, 4) > 3) and (has_skill(dude_obj, 16) >= 25)) == 0) then begin
		call Node004;
	end
	else
	if ((local_var(3) <= 0) or local_var(1) or (item_caps_total(dude_obj) < ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3))))) then begin
		call Node003;
	end
	else begin
		call Node001;
	end
end

procedure Node001
begin
	gsay_reply(377, 201 + (metarule(18, dude_obj) * ((get_critter_stat(dude_obj, 34) == 1) - (get_critter_stat(dude_obj, 34) == 0))));
	if ((((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3))) >= 1) and (item_caps_total(dude_obj) >= (1 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))))) then begin
		if (item_caps_total(dude_obj) == ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) then begin
			giq_option(1, 377, message_str(377, 252) + (1 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 253), Node981, 50);
		end
		else
		if ((1 == ((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3)))) and (has_skill(dude_obj, 16) >= 50)) then begin
			giq_option(1, 377, message_str(377, 250) + (1 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 251) + (message_str(377, 3000) + message_str(377, random(1105, 1107)) + message_str(377, 3001 + (get_critter_stat(dude_obj, 34) == 0))), Node981, 50);
		end
		else begin
			giq_option(1, 377, message_str(377, 250) + (1 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 251), Node981, 50);
		end
	end
	if ((((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3))) >= 2) and (item_caps_total(dude_obj) >= (2 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))))) then begin
		if (item_caps_total(dude_obj) == ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) then begin
			giq_option(1, 377, message_str(377, 252) + (2 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 253), Node982, 50);
		end
		else
		if ((2 == ((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3)))) and (has_skill(dude_obj, 16) >= 50)) then begin
			giq_option(1, 377, message_str(377, 250) + (2 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 251) + (message_str(377, 3000) + message_str(377, random(1105, 1107)) + message_str(377, 3001 + (get_critter_stat(dude_obj, 34) == 0))), Node982, 50);
		end
		else begin
			giq_option(1, 377, message_str(377, 250) + (2 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 251), Node982, 50);
		end
	end
	if ((((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3))) >= 3) and (item_caps_total(dude_obj) >= (3 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))))) then begin
		if (item_caps_total(dude_obj) == ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) then begin
			giq_option(1, 377, message_str(377, 252) + (3 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 253), Node983, 50);
		end
		else
		if ((3 == ((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3)))) and (has_skill(dude_obj, 16) >= 50)) then begin
			giq_option(1, 377, message_str(377, 250) + (3 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 251) + (message_str(377, 3000) + message_str(377, random(1105, 1107)) + message_str(377, 3001 + (get_critter_stat(dude_obj, 34) == 0))), Node983, 50);
		end
		else begin
			giq_option(1, 377, message_str(377, 250) + (3 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 251), Node983, 50);
		end
	end
	if ((((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3))) >= 4) and (item_caps_total(dude_obj) >= (4 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))))) then begin
		if (item_caps_total(dude_obj) == ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) then begin
			giq_option(1, 377, message_str(377, 252) + (4 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 253), Node984, 50);
		end
		else
		if ((4 == ((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3)))) and (has_skill(dude_obj, 16) >= 50)) then begin
			giq_option(1, 377, message_str(377, 250) + (4 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 251) + (message_str(377, 3000) + message_str(377, random(1105, 1107)) + message_str(377, 3001 + (get_critter_stat(dude_obj, 34) == 0))), Node984, 50);
		end
		else begin
			giq_option(1, 377, message_str(377, 250) + (4 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 251), Node984, 50);
		end
	end
	if ((((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3))) >= 5) and (item_caps_total(dude_obj) >= (5 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))))) then begin
		if (item_caps_total(dude_obj) == ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) then begin
			giq_option(1, 377, message_str(377, 252) + (5 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 253), Node985, 50);
		end
		else
		if ((5 == ((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3)))) and (has_skill(dude_obj, 16) >= 50)) then begin
			giq_option(1, 377, message_str(377, 250) + (5 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 251) + (message_str(377, 3000) + message_str(377, random(1105, 1107)) + message_str(377, 3001 + (get_critter_stat(dude_obj, 34) == 0))), Node985, 50);
		end
		else begin
			giq_option(1, 377, message_str(377, 250) + (5 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 251), Node985, 50);
		end
	end
	if (global_var(756) == 1) then begin
		giq_option(1, 377, 5000, Node020, 50);
	end
	if (metarule(18, dude_obj) == 0) then begin
		giq_option(1, 377, 254 + (item_caps_total(dude_obj) == 0) + (((game_time_hour < 600) or (game_time_hour >= 1900)) * 2), Node999, 50);
	end
	else begin
		giq_option(1, 377, 258 + (get_critter_stat(dude_obj, 34) == 0), Node999, 50);
	end
end

procedure Node002
begin
	variable LVar0 := 0;
	item_caps_adjust(dude_obj, -(coin_mult * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))));
	set_local_var(2, game_time + (7 * (24 * (60 * (60 * 10)))));
	set_local_var(3, local_var(3) - -(coin_mult * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))));
	if ((-(coin_mult * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) >= (100 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3))) * coin_mult)) and (coin_mult == ((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3))))) then begin
		set_local_var(1, 1);
	end
	if (-(coin_mult * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) > 0) then begin
		play_sfx("winner");
	end
	else
	if (-(coin_mult * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) == 0) then begin
		play_sfx("looser");
	end
	debug_msg("\nSlot money remaining == " + local_var(3));
	LVar0 := random(1, 3);
	if (win_payoff == 1) then begin
		win_payoff := 2;
		if (LVar0 == 1) then begin
			reel_1 := 1001;
		end
		else begin
			reel_1 := random(1002, 1007);
		end
		if (LVar0 == 2) then begin
			reel_2 := 1001;
		end
		else begin
			reel_2 := random(1002, 1007);
		end
		if (LVar0 == 3) then begin
			reel_3 := 1001;
		end
		else begin
			reel_3 := random(1002, 1007);
		end
	end
	else
	if (win_payoff == 2) then begin
		win_payoff := 5;
		if (LVar0 != 1) then begin
			reel_1 := 1001;
		end
		else begin
			reel_1 := random(1002, 1007);
		end
		if (LVar0 != 2) then begin
			reel_2 := 1001;
		end
		else begin
			reel_2 := random(1002, 1007);
		end
		if (LVar0 != 3) then begin
			reel_3 := 1001;
		end
		else begin
			reel_3 := random(1002, 1007);
		end
	end
	else
	if (win_payoff == 3) then begin
		win_payoff := 10;
		if (LVar0 == 1) then begin
			reel_1 := 1002 + ((random(1, 2) == 1) * (1005 - 1002));
		end
		else begin
			reel_1 := 1002;
		end
		if (LVar0 == 2) then begin
			reel_2 := 1002 + ((random(1, 2) == 1) * (1005 - 1002));
		end
		else begin
			reel_2 := 1002;
		end
		if (LVar0 == 3) then begin
			reel_3 := 1002 + ((random(1, 2) == 1) * (1005 - 1002));
		end
		else begin
			reel_3 := 1002;
		end
	end
	else
	if (win_payoff == 4) then begin
		win_payoff := 14;
		if (LVar0 == 1) then begin
			reel_1 := 1003 + ((random(1, 2) == 1) * (1005 - 1003));
		end
		else begin
			reel_1 := 1003;
		end
		if (LVar0 == 2) then begin
			reel_2 := 1003 + ((random(1, 2) == 1) * (1005 - 1003));
		end
		else begin
			reel_2 := 1003;
		end
		if (LVar0 == 3) then begin
			reel_3 := 1003 + ((random(1, 2) == 1) * (1005 - 1003));
		end
		else begin
			reel_3 := 1003;
		end
	end
	else
	if (win_payoff == 5) then begin
		win_payoff := 18;
		if (LVar0 == 1) then begin
			reel_1 := 1004 + ((random(1, 2) == 1) * (1005 - 1004));
		end
		else begin
			reel_1 := 1004;
		end
		if (LVar0 == 2) then begin
			reel_2 := 1004 + ((random(1, 2) == 1) * (1005 - 1004));
		end
		else begin
			reel_2 := 1004;
		end
		if (LVar0 == 3) then begin
			reel_3 := 1004 + ((random(1, 2) == 1) * (1005 - 1004));
		end
		else begin
			reel_3 := 1004;
		end
	end
	else
	if (win_payoff == 6) then begin
		win_payoff := 100;
		if (LVar0 == 1) then begin
			reel_1 := 1006 + ((random(1, 2) == 1) * (1005 - 1006));
		end
		else begin
			reel_1 := 1006;
		end
		if (LVar0 == 2) then begin
			reel_2 := 1006 + ((random(1, 2) == 1) * (1005 - 1006));
		end
		else begin
			reel_2 := 1006;
		end
		if (LVar0 == 3) then begin
			reel_3 := 1006 + ((random(1, 2) == 1) * (1005 - 1006));
		end
		else begin
			reel_3 := 1006;
		end
	end
	else
	if (win_payoff == 7) then begin
		win_payoff := 100;
		reel_1 := 1005;
		reel_2 := 1005;
		reel_3 := 1005;
	end
	else
	if (win_payoff == 8) then begin
		win_payoff := 200;
		reel_1 := 1007;
		reel_2 := 1007;
		reel_3 := 1007;
	end
	else begin
		win_payoff := 0;
		reel_1 := random(1002, 1007);
		reel_2 := random(1002, 1007);
		if (reel_1 != reel_2) then begin
			reel_3 := random(1002, 1007);
		end
		else begin
			reel_3 := random(1002, 1007);
			while((reel_3 == reel_1) or (reel_3 == 1005)) do begin
				reel_3 := reel_3 + 1;
				if (reel_3 > 1007) then begin
					reel_3 := 1002;
				end
			end
		end
	end
	LVar0 := message_str(377, 500) + message_str(377, reel_1) + message_str(377, 599) + message_str(377, reel_2) + message_str(377, 599) + message_str(377, reel_3) + message_str(377, 599);
	if ((200 <= win_payoff) and (coin_mult == ((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3))))) then begin
		LVar0 := LVar0 + message_str(377, 605);
	end
	else
	if ((100 <= win_payoff) and (coin_mult == ((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3))))) then begin
		LVar0 := LVar0 + message_str(377, 604);
	end
	else
	if (10 <= win_payoff) then begin
		LVar0 := LVar0 + (message_str(377, 603) + message_str(377, (reel_1 * (reel_1 != 1005)) + (reel_2 * (reel_1 == 1005)) + 100) + message_str(377, 613));
	end
	else
	if (5 <= win_payoff) then begin
		LVar0 := LVar0 + message_str(377, 602);
	end
	else
	if (2 <= win_payoff) then begin
		LVar0 := LVar0 + message_str(377, 601);
	end
	else begin
		LVar0 := LVar0 + message_str(377, 600);
	end
	win_payoff := win_payoff * (coin_mult * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3))));
	if (win_payoff > 0) then begin
		LVar0 := LVar0 + (message_str(377, 700) + win_payoff + message_str(377, 701));
	end
	if (metarule(18, dude_obj)) then begin
		if (win_payoff == 0) then begin
			LVar0 := LVar0 + message_str(377, random(2204 - (3 * (get_critter_stat(dude_obj, 34) == 0)), 2206 + (3 * (get_critter_stat(dude_obj, 34) == 1))));
		end
		else begin
			LVar0 := LVar0 + message_str(377, random(2250 - ((get_critter_stat(dude_obj, 34) == 0) * ((win_payoff >= (100 * (coin_mult * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))))) + (win_payoff >= (10 * (coin_mult * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))))) + (win_payoff >= (5 * (coin_mult * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))))))), 2250 + ((get_critter_stat(dude_obj, 34) == 1) * ((win_payoff >= (100 * (coin_mult * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))))) + (win_payoff >= (10 * (coin_mult * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))))) + (win_payoff >= (5 * (coin_mult * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3))))))))));
		end
	end
	item_caps_adjust(dude_obj, win_payoff);
	set_local_var(2, game_time + (7 * (24 * (60 * (60 * 10)))));
	set_local_var(3, local_var(3) - win_payoff);
	if ((win_payoff >= (100 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3))) * coin_mult)) and (coin_mult == ((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3))))) then begin
		set_local_var(1, 1);
	end
	if (win_payoff > 0) then begin
		play_sfx("winner");
	end
	else
	if (win_payoff == 0) then begin
		play_sfx("looser");
	end
	debug_msg("\nSlot money remaining == " + local_var(3));
	gsay_reply(377, LVar0);
	if ((((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3))) >= 1) and (item_caps_total(dude_obj) >= (1 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))))) then begin
		if (item_caps_total(dude_obj) == ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) then begin
			giq_option(1, 377, message_str(377, 252) + (1 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 253), Node981, 50);
		end
		else
		if ((1 == ((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3)))) and (has_skill(dude_obj, 16) >= 50)) then begin
			giq_option(1, 377, message_str(377, 250) + (1 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 251) + (message_str(377, 3000) + message_str(377, random(1105, 1107)) + message_str(377, 3001 + (get_critter_stat(dude_obj, 34) == 0))), Node981, 50);
		end
		else begin
			giq_option(1, 377, message_str(377, 250) + (1 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 251), Node981, 50);
		end
	end
	if ((((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3))) >= 2) and (item_caps_total(dude_obj) >= (2 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))))) then begin
		if (item_caps_total(dude_obj) == ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) then begin
			giq_option(1, 377, message_str(377, 252) + (2 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 253), Node982, 50);
		end
		else
		if ((2 == ((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3)))) and (has_skill(dude_obj, 16) >= 50)) then begin
			giq_option(1, 377, message_str(377, 250) + (2 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 251) + (message_str(377, 3000) + message_str(377, random(1105, 1107)) + message_str(377, 3001 + (get_critter_stat(dude_obj, 34) == 0))), Node982, 50);
		end
		else begin
			giq_option(1, 377, message_str(377, 250) + (2 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 251), Node982, 50);
		end
	end
	if ((((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3))) >= 3) and (item_caps_total(dude_obj) >= (3 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))))) then begin
		if (item_caps_total(dude_obj) == ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) then begin
			giq_option(1, 377, message_str(377, 252) + (3 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 253), Node983, 50);
		end
		else
		if ((3 == ((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3)))) and (has_skill(dude_obj, 16) >= 50)) then begin
			giq_option(1, 377, message_str(377, 250) + (3 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 251) + (message_str(377, 3000) + message_str(377, random(1105, 1107)) + message_str(377, 3001 + (get_critter_stat(dude_obj, 34) == 0))), Node983, 50);
		end
		else begin
			giq_option(1, 377, message_str(377, 250) + (3 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 251), Node983, 50);
		end
	end
	if ((((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3))) >= 4) and (item_caps_total(dude_obj) >= (4 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))))) then begin
		if (item_caps_total(dude_obj) == ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) then begin
			giq_option(1, 377, message_str(377, 252) + (4 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 253), Node984, 50);
		end
		else
		if ((4 == ((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3)))) and (has_skill(dude_obj, 16) >= 50)) then begin
			giq_option(1, 377, message_str(377, 250) + (4 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 251) + (message_str(377, 3000) + message_str(377, random(1105, 1107)) + message_str(377, 3001 + (get_critter_stat(dude_obj, 34) == 0))), Node984, 50);
		end
		else begin
			giq_option(1, 377, message_str(377, 250) + (4 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 251), Node984, 50);
		end
	end
	if ((((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3))) >= 5) and (item_caps_total(dude_obj) >= (5 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))))) then begin
		if (item_caps_total(dude_obj) == ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) then begin
			giq_option(1, 377, message_str(377, 252) + (5 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 253), Node985, 50);
		end
		else
		if ((5 == ((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3)))) and (has_skill(dude_obj, 16) >= 50)) then begin
			giq_option(1, 377, message_str(377, 250) + (5 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 251) + (message_str(377, 3000) + message_str(377, random(1105, 1107)) + message_str(377, 3001 + (get_critter_stat(dude_obj, 34) == 0))), Node985, 50);
		end
		else begin
			giq_option(1, 377, message_str(377, 250) + (5 * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) + message_str(377, 251), Node985, 50);
		end
	end
	if (global_var(756) == 1) then begin
		giq_option(1, 377, 5000, Node020, 50);
	end
	if (metarule(18, dude_obj) == 0) then begin
		giq_option(1, 377, 254 + (item_caps_total(dude_obj) == 0) + (((game_time_hour < 600) or (game_time_hour >= 1900)) * 2), Node999, 50);
	end
	else begin
		giq_option(1, 377, 258 + (get_critter_stat(dude_obj, 34) == 0), Node999, 50);
	end
end

procedure Node003
begin
	if ((item_caps_total(dude_obj) < ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3)))) and (local_var(1) == 0)) then begin
		gsay_reply(377, 2175);
		if (global_var(756) == 1) then begin
			giq_option(1, 377, 5000, Node020, 50);
		end
		giq_option(1, 377, 2176, Node999, 50);
	end
	else begin
		gsay_reply(377, 2185);
		giq_option(1, 377, 2186, Node999, 50);
	end
end

procedure Node004
begin
	gsay_reply(377, 2100);
	giq_option(-3, 377, message_str(377, 2101) + obj_name(dude_obj) + message_str(377, 2102), Node005, 50);
	giq_option(-3, 377, message_str(377, 2103) + obj_name(dude_obj) + message_str(377, 2104), Node005, 50);
	giq_option(-3, 377, 2105, Node006, 50);
	giq_option(-3, 377, 2106, Node005, 50);
	giq_option(-3, 377, 2107, Node005, 50);
	giq_option(-3, 377, 2108, Node005, 50);
	giq_option(-3, 377, 2109, Node999, 50);
	giq_option(4, 377, 2110, Node999, 50);
end

procedure Node005
begin
	gsay_reply(377, 2130);
	giq_option(-3, 377, message_str(377, 2131) + obj_name(dude_obj) + message_str(377, 2132), Node005, 50);
	giq_option(-3, 377, 2133, Node006, 50);
	giq_option(-3, 377, 2134, Node005, 50);
	giq_option(-3, 377, 2135, Node005, 50);
	giq_option(-3, 377, 2136, Node005, 50);
	giq_option(-3, 377, 2137, Node999, 50);
	giq_option(4, 377, 2138, Node999, 50);
end

procedure Node006
begin
	gsay_reply(377, 2151);
	giq_option(1, 377, 2152, Node999, 50);
	giq_option(4, 377, 2153, Node999, 50);
end

procedure Node013
begin
	gsay_reply(377, 2280 + (get_critter_stat(dude_obj, 34) == 1));
	giq_option(1, 377, 2282, Node014, 50);
	giq_option(1, 377, 2283, Node014, 50);
	giq_option(1, 377, 2284, Node999, 50);
end

procedure Node014
begin
	gsay_reply(377, 2300 + (get_critter_stat(dude_obj, 34) == 0));
	giq_option(1, 377, 2302, Node015, 50);
	giq_option(1, 377, 2303, Node001, 50);
	if (get_critter_stat(dude_obj, 34) == 0) then begin
		giq_option(1, 377, 2304, Node999, 50);
	end
	giq_option(1, 377, 2305, Node999, 50);
end

procedure Node015
begin
	gsay_reply(377, 2320 + (get_critter_stat(dude_obj, 34) == 0));
	giq_option(1, 377, 2322, Node016, 50);
	giq_option(1, 377, 2303, Node001, 50);
	if (get_critter_stat(dude_obj, 34) == 0) then begin
		giq_option(1, 377, 2304, Node999, 50);
	end
	giq_option(1, 377, 2305, Node999, 50);
end

procedure Node016
begin
	gsay_reply(377, 2340 + (get_critter_stat(dude_obj, 34) == 0));
	if (global_var(494) == 8) then begin
		giq_option(1, 377, 2345, Node017, 50);
		giq_option(1, 377, 2346, Node017, 50);
		giq_option(1, 377, 2347, Node017, 50);
	end
	else
	if ((global_var(494) == 5) or (global_var(494) == 6)) then begin
		giq_option(1, 377, 2344, Node017, 50);
	end
	else
	if (global_var(494) == 4) then begin
		giq_option(1, 377, 2343, Node017, 50);
	end
	else
	if (global_var(494) == 0) then begin
		giq_option(1, 377, 2342, Node017, 50);
	end
	giq_option(1, 377, 2348, Node017, 50);
	giq_option(1, 377, 2305, Node999, 50);
end

procedure Node017
begin
	gsay_reply(377, 2370 + (get_critter_stat(dude_obj, 34) == 0));
	giq_option(1, 377, 2372, Node018, 50);
	giq_option(1, 377, 2373, Node018, 50);
	giq_option(1, 377, 2305, Node999, 50);
end

procedure Node018
begin
	gsay_reply(377, random(2381 - (get_critter_stat(dude_obj, 34) == 1), 2381 + (get_critter_stat(dude_obj, 34) == 0)));
	giq_option(1, 377, 2383, Node019, 50);
end

procedure Node019
begin
	gsay_reply(377, random(2401 - (get_critter_stat(dude_obj, 34) == 1), 2401 + (get_critter_stat(dude_obj, 34) == 0)));
	giq_option(1, 377, 2403, Node999, 50);
end

procedure Node020
begin
	if ((get_critter_stat(dude_obj, 6) * 10) > random(0, 99)) then begin
		item_caps_adjust(dude_obj, 3 * (((18 * (local_var(0) == 1)) + (100 * (local_var(0) == 2)) + (200 * (local_var(0) == 3))) * ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3))) * ((5 * (local_var(0) == 1)) + (2 * (local_var(0) == 2)) + (2 * (local_var(0) == 3)))));
		gsay_reply(377, 5001);
		giq_option(1, 377, 5002, Node999, 50);
	end
	else begin
		gsay_reply(377, 600);
		giq_option(1, 377, 2186, Node999, 50);
	end
	set_local_var(2, game_time + (30 * (24 * (60 * (60 * 10)))));
	set_local_var(3, 0);
end

procedure Node997
begin
	variable LVar0 := 0;
	variable LVar1 := 0;
	if (((local_var(3) <= 0) or local_var(1) or (item_caps_total(dude_obj) < ((1 * (local_var(0) == 1)) + (5 * (local_var(0) == 2)) + (5 * (local_var(0) == 3))))) == 0) then begin
		win_payoff := 0;
		LVar0 := roll_vs_skill(dude_obj, 16, (-50 * (local_var(0) == 1)) + (-75 * (local_var(0) == 2)) + (-100 * (local_var(0) == 3)) + (win_payoff * -5));
		if (is_success(LVar0) and (((18 * (local_var(0) == 1)) + (100 * (local_var(0) == 2)) + (200 * (local_var(0) == 3))) >= 2)) then begin
			win_payoff := 1;
			LVar1 := roll_vs_skill(dude_obj, 16, (-50 * (local_var(0) == 1)) + (-75 * (local_var(0) == 2)) + (-100 * (local_var(0) == 3)) + (win_payoff * -5));
			if (is_critical(LVar0) or is_success(LVar1) and (((18 * (local_var(0) == 1)) + (100 * (local_var(0) == 2)) + (200 * (local_var(0) == 3))) >= 5)) then begin
				win_payoff := 2;
				LVar0 := roll_vs_skill(dude_obj, 16, (-50 * (local_var(0) == 1)) + (-75 * (local_var(0) == 2)) + (-100 * (local_var(0) == 3)) + (win_payoff * -5));
				if (is_critical(LVar1) or is_success(LVar0) and (((18 * (local_var(0) == 1)) + (100 * (local_var(0) == 2)) + (200 * (local_var(0) == 3))) >= 10)) then begin
					win_payoff := 3;
					LVar1 := roll_vs_skill(dude_obj, 16, (-50 * (local_var(0) == 1)) + (-75 * (local_var(0) == 2)) + (-100 * (local_var(0) == 3)) + (win_payoff * -5));
					if (is_critical(LVar0) or is_success(LVar1) and (((18 * (local_var(0) == 1)) + (100 * (local_var(0) == 2)) + (200 * (local_var(0) == 3))) >= 14)) then begin
						win_payoff := 4;
						LVar0 := roll_vs_skill(dude_obj, 16, (-50 * (local_var(0) == 1)) + (-75 * (local_var(0) == 2)) + (-100 * (local_var(0) == 3)) + (win_payoff * -5));
						if (is_critical(LVar1) or is_success(LVar0) and (((18 * (local_var(0) == 1)) + (100 * (local_var(0) == 2)) + (200 * (local_var(0) == 3))) >= 18)) then begin
							win_payoff := 5;
							LVar1 := roll_vs_skill(dude_obj, 16, (-50 * (local_var(0) == 1)) + (-75 * (local_var(0) == 2)) + (-100 * (local_var(0) == 3)) + (win_payoff * -5));
							if (is_critical(LVar0) or is_success(LVar1) and (((18 * (local_var(0) == 1)) + (100 * (local_var(0) == 2)) + (200 * (local_var(0) == 3))) >= 100)) then begin
								win_payoff := 6;
								LVar0 := roll_vs_skill(dude_obj, 16, (-50 * (local_var(0) == 1)) + (-75 * (local_var(0) == 2)) + (-100 * (local_var(0) == 3)) + (win_payoff * -5));
								if (is_critical(LVar1) or is_success(LVar0) and (((18 * (local_var(0) == 1)) + (100 * (local_var(0) == 2)) + (200 * (local_var(0) == 3))) >= 100)) then begin
									win_payoff := 7;
									LVar1 := roll_vs_skill(dude_obj, 16, (-50 * (local_var(0) == 1)) + (-75 * (local_var(0) == 2)) + (-100 * (local_var(0) == 3)) + (win_payoff * -5));
									if (is_critical(LVar0) or is_success(LVar1) and (((18 * (local_var(0) == 1)) + (100 * (local_var(0) == 2)) + (200 * (local_var(0) == 3))) >= 200)) then begin
										win_payoff := 8;
									end
								end
							end
						end
					end
				end
			end
		end
		call Node002;
	end
	else begin
		debug_msg("\nPLAY BLOCKED");
		debug_msg("\n   slot_tube_size == " + local_var(3));
		debug_msg("\n   won_jackpot == " + local_var(1));
	end
end

procedure Node981
begin
	coin_mult := 1;
	call Node997;
end

procedure Node982
begin
	coin_mult := 2;
	call Node997;
end

procedure Node983
begin
	coin_mult := 3;
	call Node997;
end

procedure Node984
begin
	coin_mult := 4;
	call Node997;
end

procedure Node985
begin
	coin_mult := 5;
	call Node997;
end

